### ISSUE TITLE
[Feature Request] Allow disabling Leave/Join notifications

### ISSUE THREAD

**Issue by eyalroz** [telegramdesktop/tdesktop#10048]
### Is your feature request related to a problem?
I am in some groups/channels which have more Leave/Join events than actual messages. The messages are important to me, but the Leave/Join events - not so much or not at all. So I can either get a bunch of spam, or not be notified of important messages.

### Describe the solution you'd like
The notification enable/disable settings should be different for proper messages and for channel events (Leave/Join or all channel events). I can think of the following alternatives:

1. Replicate the existing settings, for Leave/Join notifications.
2. Create a gradation of notifications: Messages mentioning you; messages; messages and channel events. The preferences will include the a choice within this spectrum (different than whether you enable/disable notifications)
3. Change the default and simply stop notifying about Leave/Join events.

### Additional context
IIANM, in most IRC clients, notifications about messages don't trigger for channel Leave/Joins.

Also - thank you for this great messaging client. Down with Facebook and government spying etc.

**Comment by dimasm61** [comment]
A good idea.
I need possibility to switch off notifications for some channels and groups also. It distracts me greatly from important messages.
Yes, I seem to be able to turn off notifications in the Group info form, but the Telegram icon still changes after every events in a Group. As I said, this is distracting.
The existing "Notifications" option is not enough.

**Comment by eyalroz** [comment]
@Aokromes : Can you add the 'enhancement' label as well?

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by eyalroz** [comment]
@Aokromes : Can you explain what's the distinction between bugs which go here and bugs which go there? Especially considering how 18 days ago you did not make the decision to close...

**Comment by eyalroz** [comment]
Ok, I've filed a bugs.telegram.org issue, [here](https://bugs.telegram.org/c/2359).

**Comment by Aokromes** [comment]
> @Aokromes : Can you explain what's the distinction between bugs which go here and bugs which go there? Especially considering how 18 days ago you did not make the decision to close...

now they have opened that bug tracker to more people.

**Comment by jimdi** [comment]
> Ok, I've filed a bugs.telegram.org issue, [here](https://bugs.telegram.org/c/2359).
> 
> Everyone on this issue - please consider upvoting / "liking" that issue: @jimdi,  @22Nick22, @neesti, @navidmafi, @dimasm61 .

ok, i will build binary from source and test this version

**Comment by RememberTheAir** [comment]
> Can you explain what's the distinction between bugs which go here and bugs which go there?

bugs.telegram.org is the official platform where you can suggest new features (both app-specific, or that should be considered for every official app) and report bugs. It's directly managed by Telegram.

This issue tracker is just for bugs strictly related to tdesktop (for example: crashes, graphical issues with a DE, some videos not playing properly, and in general anything that should be fixed client-side by this app's maintainer) and improvements suggestions that don't need to be consistent with the rest of official clients environment. For example, new keyboard shortcuts, system integrations, and things like that. Stuff like raising the pinned messages limit or hiding blocked users' messages in groups **do not** belong here, since it's something that is supposed to work the same way on every Telegram official app and tdesktop developer can't just decide to change how these things work on this app alone. Also, this issue tracker is managed by the app dev + a couple of volunteers in no way related to Telegram. Anyway, bugs & suggestions that belong to this issue tracker can be opened on bugs.telegram.org anyway, since it's a general purpose platform and these kind of issues can be opened there too
