### ISSUE TITLE
Bot's will not delete

### ISSUE THREAD

**Issue by fritek373** [telegramdesktop/tdesktop#1006]
When I delete a bot in the Telegram Anroid app, it stays there in the Desktop client...

**Comment by telegramdesktop** [comment]
This is intended, in API there is no way to understand, did you "Delete a bot" or just cleared conversation, in any case on server you are just clearing history of this conversation and I get such event from server. So I choose to leave an empty conversation in the left column in case of that event, then to remove it from there (there will be the same bugreports about "just clearing history" otherwise, but in current case you can remove the conversation from desktop as well, yet there is no way to return it, if it was removed, when it should not be).
