### ISSUE TITLE
The font is unrecognized when trying to add attachment 

### ISSUE THREAD

**Issue by inouzuka** [telegramdesktop/tdesktop#10068]
Hello, 
I got issue when trying to choose file to upload in the desktop version. 
Currently I am using OS : Xubuntu 18.04.3

![Screenshot_2021-01-05_10-40-00](https://user-images.githubusercontent.com/11453851/103604029-93245600-4f42-11eb-9a55-b30734d76123.png)

Any idea what happened to it?

**Comment by ilya-fedin** [comment]
template was removed -> issue is invalid

**Comment by inouzuka** [comment]
any detail information where the template location is? 
I just fresh install the app via ubuntu software center

**Comment by ilya-fedin** [comment]
When you create a bug report, GitHub gives you an input field with the template that you should fill. You have removed the entire template and wrote your text instead of filling it.

**Comment by Mehrshad3** [comment]
### Steps to reproduce
1. 
2. 
3. 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by Mehrshad3** [comment]
\
### \### Steps to reproduce
1. 
2. 
3. 

### \### Expected behaviour
Tell us what should happen

### \### Actual behaviour
Tell us what happens instead

### \### Configuration
<b>\**Operating system:**</b>

<b>\**Version of Telegram Desktop:**</b>

<b>\**Installation source (Linux Only)**</b> - the official website / GitHub releases / flatpak / snap / distribution package:

<b>\*\*Used theme**</b>:

\<details>\<summary><details><summary><b>\<b>Logs\</b></b>:</summary>\</summary>
Insert log.txt here (if necessary)
</details>&lt/details&gt
