### ISSUE TITLE
[Question] Cannot access certain channels

### ISSUE THREAD

**Issue by joshua-612** [telegramdesktop/tdesktop#10120]
I am getting this channel cannot be displayed messege and there is no option in settings to enable sensitive content
Is this a server side thing or a client side thing?

**Comment by RememberTheAir** [comment]
It's server side. Some chats might be restricted because of copyright reasons (or because they share pornographic content) based on:
- your country of origin (which is based **I think** on your phone number country code and IP from when you connected when registering the account)
- how you installed the app (store (such as the Microsoft Store)/website/binary pulled from an official or third-party repository)

**Comment by joshua-612** [comment]
Thanks for the info, Is there any way to disable these restrictions without making a account with different phone number?

**Comment by RememberTheAir** [comment]
Disabling filtering from the privacy settings is the only thing you can do

**Comment by joshua-612** [comment]
![image](https://user-images.githubusercontent.com/40670164/104452242-b85f3700-55c8-11eb-99cf-a766501269b4.png)
There is no option to disable filtering in any of the official or third party apps I have used

**Comment by RememberTheAir** [comment]
You have to download the app from desktop.telegram.org, as the binary that you download from some stores don't have that option
