### ISSUE TITLE
[Feature request] Enable schedule poll in "Create" button in poll

### ISSUE THREAD

**Issue by Muaath5** [telegramdesktop/tdesktop#10157]
### Is your feature request related to a problem?
Yes, the problem is when I create a poll, I can't schedule poll message.
I want to have same menu in _**send**_ button (like image below):

![Menu](https://user-images.githubusercontent.com/60256639/104832145-fea1e800-589f-11eb-9947-68dec0223f3a.png)

**Because it's not avaliable when I want to schedule a poll:**

![Create poll windiw](https://user-images.githubusercontent.com/60256639/104832166-36109480-58a0-11eb-8700-c06750b5abad.png)

### Describe the solution you'd like
Add menu on `Create` button, that shows when I do right click, then I can schedule poll

### Describe alternatives you've considered
Telegram desktop has already alternative way to do this, when you go to schuedule messages, then _**Create Poll**_

**Comment by Ondra1230** [comment]
Cože?On 1/17/21 at 7:47 PM, ⁨مُعَاذ القَرْنِي⁩ wrote:
                
            
            
                
                    From: "مُعَاذ القَرْنِي" <notifications@github.com>Date: January 17, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: [telegramdesktop/tdesktop] Enable schedule poll in "Create" button in poll (#10157)
                
                
Is your feature request related to a problem?
Yes, the problem is when I create a poll, I can't schedule poll message.
I want to have same menu in send button (like image below):

Because it's not avaliable when I want to schedule a poll:

Describe the solution you'd like
Add menu on Create button, that shows when I do right click, then I can schedule poll
Describe alternatives you've considered
Telegram desktop has already alternative way to do this, when you go to schuedule messages, then Create Poll

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10157",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10157",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by 23rd** [comment]
You can't send a poll without sound, you can't schedule a poll and you even can't just send a poll until your question and poll options are empty.

**Comment by Muaath5** [comment]
## I can schedule a poll if I open `scheduled messages page -> three dots in top right -> Create poll` in the image below:
![Scheduled messages page Telegram desktop](https://user-images.githubusercontent.com/60256639/105069485-0ecde900-5a93-11eb-88db-de91f4d17ee1.png)

---

## And it worked successfully in image below:
![Scheduled poll](https://user-images.githubusercontent.com/60256639/105069811-813ec900-5a93-11eb-95c4-1d419dc3c1b7.png)

**Comment by 23rd** [comment]
I can do the same from conversation in channels or groups.
<details>


![image](https://user-images.githubusercontent.com/4051126/105070835-e8a94880-5a94-11eb-9380-324e8fffe572.png)
</details>

**Comment by Muaath5** [comment]
@23rd 
But not avaliable in private chats to bots!

**Comment by 23rd** [comment]
@Muaath5 No, it is still fine in chats with bots.

<details>

![image](https://user-images.githubusercontent.com/4051126/105071683-f8755c80-5a95-11eb-9ab5-67ce28106bcf.png)
</detalis>
