### ISSUE TITLE
Context Menu Appears on Wrong Display (Multiple Monitors)

### ISSUE THREAD

**Issue by kaserblade99** [telegramdesktop/tdesktop#10166]
### Steps to reproduce
1. Have multiple monitors attached (In my case 2 external monitors to laptop)
2. Right-click on the telegram app when placed in a monitor that's not the primary monitor (2nd or 3rd)

### Expected behaviour
Context menu pops up on the part of the app that I right clicked

### Actual behaviour
Context menu pops up on my primary monitor (not the monitor where I have telegram open)

### Configuration
**Operating system:** Windows 10 Pro 19041.746
AMD Ryzen 7 4800HS with Radeon Graphics
Nvidia GTX 1660Ti (Mobile)

**Version of Telegram Desktop:** 2.5.1

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**: Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
#7099

**Comment by Ondra1230** [comment]
Intéressant  sur 18/01/2021 le 09:31, Aokromes écrivit:
                
            
            
                
                    De: "Aokromes" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: Re: [telegramdesktop/tdesktop] Context Menu Appears on Wrong Display (Multiple Monitors) (#10166)
                
                
Closed #10166.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10166#event-4218743485",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10166#event-4218743485",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
