### ISSUE TITLE
[Feature Request] Linux installer as AppImage

### ISSUE THREAD

**Issue by devplan44** [telegramdesktop/tdesktop#10167]
I see that the Linux 64bit install is offered as tar.xz which requires old fashion make install.

### Describe the solution you'd like
I would like to be distributed in a more 21 century way - namely **AppImage**

### Describe alternatives you've considered
I considered snap and flatpack.

### Additional context
The cleanest app installs nowadays are portable and easily removable without leaving added junk behind.

**Comment by Ondra1230** [comment]
Linux or UNIX? same? sur 18/01/2021 le 14:12, devplan44 écrivit:
                
            
            
                
                    De: "devplan44" <notifications@github.com>Date: 18 janvier 2021à: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Objet: [telegramdesktop/tdesktop] [Feature Request] Linux installer as AppImage (#10167)
                
                
I see that the Linux 64bit install is offered as tar.xz which requires old fashion make install.
Describe the solution you'd like
I would like to be distributed in a more 21 century way - namely AppImage
Describe alternatives you've considered
I considered snap and flatpack.
Additional context
The cleanest app installs nowadays are portable and easily removable without leaving added junk behind.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10167",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10167",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-fedin** [comment]
> I see that the Linux 64bit install is offered as tar.xz which requires old fashion make install.

I don't understand what are you talking about... You have a .tar.xz with folder Telegram that you should unpack to your home folder and just run Telegram file inside this directory.

**Comment by opqriu** [comment]
It is an unofficial version, but the Telegram appimage & flatpak version is here.

https://apprepo.de/appimage/telegram
https://www.flathub.org/apps/details/org.telegram.desktop

**Comment by ilya-fedin** [comment]
Official static binary is effectively appimage

**Comment by devplan44** [comment]
> Official static binary is effectively appimage

Thank you.
