### ISSUE TITLE
[Question]  Build Telegram 1 fail tg_owt.lib(fir_filter_factory.cc.obj) : error LNK2019

### ISSUE THREAD

**Issue by jwqtest** [telegramdesktop/tdesktop#10170]
reference : https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-msvc.md
Open BuildPath\tdesktop\out\Telegram.sln in Visual Studio 2019 V16.5.0
Select Telegram project and press Build > Build Telegram (Debug and Release configurations)

...
38>  Creating library D:/TelegramBulid/tdesktop/out/Telegram/Debug/Telegram.lib and D:/TelegramBulid/tdesktop/out/Telegram/Debug/Telegram.exp
38>tg_owt.lib(fir_filter_factory.cc.obj) : error LNK2019: Unresolved external symbol "public: __thiscall webrtc::FIRFilterAVX2::FIRFilterAVX2(float const *,unsigned int,unsigned int)" (??0FIRFilterAVX2@webrtc@@QAE@PBMII@Z)，the symbol is referenced in  "class webrtc::FIRFilter * __cdecl webrtc::CreateFirFilter(float const *,unsigned int,unsigned int)" (?CreateFirFilter@webrtc@@YAPAVFIRFilter@1@PBMII@Z) 
38>D:\TelegramBulid\tdesktop\out\Debug\Telegram.exe : fatal error LNK1120: 1 Unresolved external command
38>Finished generating project “Telegram.vcxproj”-failed.
========== Build: success 37 ，fail 1==========

**Comment by ilya-fedin** [comment]
Check that you have tg_owt on the latest commit

**Comment by Ondra1230** [comment]
What is it?On 1/19/21 at 03:40, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 19, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Subscribed" <subscribed@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] [Question]  Build Telegram 1 fail tg_owt.lib(fir_filter_factory.cc.obj) : error LNK2019 (#10170)
                
                
Check that you have tg_owt on the latest commit

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10170#issuecomment-762723505",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10170#issuecomment-762723505",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ilya-fedin** [comment]
@Ondra1230 please don't respond to issues with your mail until you fix it

**Comment by Ondra1230** [comment]
I don't know what you're talking about, I don't have to write at all ..On 1/19/21 at 03:44, ilya-fedin wrote:
                
            
            
                
                    From: "ilya-fedin" <notifications@github.com>Date: January 19, 2021To: "telegramdesktop/tdesktop" <tdesktop@noreply.github.com>Cc: "Ondra1230" <Ondra123@mail.com>,"Mention" <mention@noreply.github.com>Subject: Re: [telegramdesktop/tdesktop] [Question]  Build Telegram 1 fail tg_owt.lib(fir_filter_factory.cc.obj) : error LNK2019 (#10170)
                
                
@Ondra1230 please don't respond to issues with your mail until you fix it

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/telegramdesktop/tdesktop/issues/10170#issuecomment-762725724",
"url": "https://github.com/telegramdesktop/tdesktop/issues/10170#issuecomment-762725724",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jwqtest** [comment]
@ilya-fedin 

> Check that you have tg_owt on the latest commit

D:\TelegramBulid\Libraries\tg_owt>git branch -av
* master                              a7c111b - update desktop capturer
  remotes/origin/HEAD                 -> origin/master
  remotes/origin/audio_level          6669990 Pass through outgoing audio data for level calculation.
  remotes/origin/before-01-01-2021    fa86fcc Enumerate all devices in ADM2 Windows audio backend.
  remotes/origin/desktop_capturer+arm a7c111b - update desktop capturer
  remotes/origin/libvpx               e1044a3 add support for packaged libvpx (enabled via TG_OWT_VPX_PACKAGED_BUILD)
  remotes/origin/master               a7c111b - update desktop capturer
  remotes/origin/update-01-01-2021    d91d618 - added support for macos arm

D:\TelegramBulid\Libraries\tg_owt>

**Comment by jwqtest** [comment]
> Check that you have tg_owt on the latest commit
 tg_owt on the latest commit
today, 
git clone --recursive https://github.com/desktop-app/tg_owt.git

**Comment by wxz879526** [comment]
I encounter the same problem,how to fixed it

**Comment by ilya-fedin** [comment]
`git reset --hard d91d618889cc743aafd809151449012de62e5327`

**Comment by jwqtest** [comment]
> `git reset --hard d91d618889cc743aafd809151449012de62e5327`

then

38>tg_owt.lib(auto_correlation.cc.obj) : error LNK2019: Unresolved external symbol  ___std_reverse_copy_trivially_copyable_4，the symbol is referenced in "float * __cdecl std::reverse_copy<float const *,float *>(float const *,float const *,float *)" (??$reverse_copy@PBMPAM@std@@YAPAMPBM0PAM@Z) 
38>D:\TelegramBulid\tdesktop\out\Debug\Telegram.exe : fatal error LNK1120: 1 Unresolved external command
38>Finished generating project “Telegram.vcxproj”-failed.
========== Build: success 37 ，fail 1==========

**Comment by jwqtest** [comment]
> `git reset --hard d91d618889cc743aafd809151449012de62e5327`

Thank you
Has been resolved
git reset --hard d91d618889cc743aafd809151449012de62e5327
