### ISSUE TITLE
[Question] A poll when people join my channel

### ISSUE THREAD

**Issue by AngryPhantom** [telegramdesktop/tdesktop#10244]
Hello!

I have a pretty simple question, but I can't find the answer on the Internet.

How can I create a poll **when people join** my channel? For example, I need to know how they found my channel. It should be a simple poll (or any other type of feedback) with predefined answers or the like.

Is it possible?

Sincerely yours, and thanks for this awesome messenger.

**Comment by RememberTheAir** [comment]
It's not possible to do that, because channels are a one-to-many broadcast where all the subscribers see the same exact content. You cannot inbox a new subscriber with a message/poll when they join. As a workaround, you can pin a poll in the channel and when you post something new, you can remind the subscribers to vote from the pinned message

**Comment by AngryPhantom** [comment]
@RememberTheAir  Ok, got it. Thank you!
