### ISSUE TITLE
[Feature Request] Make views of posts in channels count only once per a user

### ISSUE THREAD

**Issue by azat11** [telegramdesktop/tdesktop#10355]
### Is your feature request related to a problem?
Counter that counts each users views multiple times makes it impossible to tell how many unique users viewed the post. It's not like a post in a Telegram channel is a video on YouTube, views don't really need to be counted multiple times – posts are not videos.

### Describe the solution you'd like
Make views of posts in channels count only once per a user.

### Describe alternatives you've considered
No solution other than this. Except maybe add another metric – unique views.

### Additional context
I want to keep statictics clear, to clearly see the true reach of the posts.

**Comment by RememberTheAir** [comment]
This is out of the scope of this client, you should bring this on https://bugs.telegram.org

> Counter that counts each users views multiple times makes it impossible to tell how many unique users viewed the post

This is because views are not meant to tell you how many unique users viewed the post, they're meant to show how many times people decided to read or stumbled upon a certain post. You can ask for a new metric on the platform I linked above

**Comment by azat11** [comment]
@RememberTheAir Thank you.
