### ISSUE TITLE
Auto downloading images when auto download is off

### ISSUE THREAD

**Issue by yorodm** [telegramdesktop/tdesktop#10371]
### Steps to reproduce
1. Set media auto download off. 
2. Enter a channel where you were mentioned

### Expected behaviour
Media should not be downloaded

### Actual behaviour
Media is being downloaded ignoring previous settings

### Configuration
**Operating system:**
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.2.1
Codename:	Nibia

**Version of Telegram Desktop:**
2.5.8
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
 AUR (telegram-desktop-bin)
**Used theme**:

**Comment by Younes-L** [comment]
I have this same problem on Linux Mint, tdekstop 2.7.1 and older versions (from 2.5.9 onwards)

**Comment by jacob755** [comment]
telegram desktop 2.8.6 beta and must of 2.x version have same problem
since this issue is open and #16306 closed i prefer not to open another one, if it closed like the other one then i open new one.
automatic media download disabled for private chat and Channels and group
this working as it should work. and show blurred image. only in grouped item(several image in one post uploaded) if i open one of image, one before and one after that also start downloading.i think this is should be like that 
but for example if clicking **Channel info** button which open panel when clicking "photos"
image start downloading specially grouped item.
Expected behavior should be like older version not start downloading and just show  square thumbs image in opened panel in photos section

**Comment by Younes-L** [comment]
This issue is random and although I haven't noticed it since 3.3 I also changed distro and switched to a tdesktop fork and relogged and moved my media_cache path...  

From the quick test I did just now on tdesktop 3.4.1-based client (scrolling through groups & channels with unreads messages) it didn't autodownload any of the pictures which was my main complaint.

**Comment by john-preston** [comment]
I did fix them in some cases. Fill free to create a new issue if there'll be new clear steps to reproduce.

**Comment by Younes-L** [comment]
Thank you so much ❤️
