### ISSUE TITLE
Images/videos are not centered in Mac OS

### ISSUE THREAD

**Issue by psytechno604** [telegramdesktop/tdesktop#10383]
version 2.5.8
OS version 10.14.6 (18G103) Mac OS Mojave

using second monitor Samsung U28E590 (2560x1440)

when clicking on picture or video - it opens to the right bottom of the screen and only part of it is visible

like this: https://ibb.co/qn6cRQj

**Comment by ClockVapor** [comment]
I've found that, for me, this issue is caused by switching back and forth between my dock to connect to a monitor with a different resolution and using the built-in display on my MacBook Air. Something about switching resolutions causes Telegram to display media incorrectly like this.

My workaround is to quit and reopen Telegram after switching displays.

**Comment by ayozemr** [comment]
Seeing the same as ClockVapor

**Comment by ClockVapor** [comment]
Still an issue on macOS Monterey 12.0.1 and Telegram Desktop 3.4.3

**Comment by AoDev** [comment]
Same issue here. If Telegram is on the external monitor (Dell 4K monitor), it has the same behaviour that was reported by the first poster.

**Comment by AoDev** [comment]
This issue is not present for me anymore, on OSX Monterey, Telegram 8.9.234962 Stable
