### ISSUE TITLE
[Bug] Highlighting of links to local websites is broken in 0.8.55 

### ISSUE THREAD

**Issue by jogaraven** [telegramdesktop/tdesktop#1054]
example:
http://jira/secure/RapidBoard.jspa

**Comment by telegramdesktop** [comment]
I'm sorry, but from the last version links are parsed on server and client uses server-side links parsing. It is done for "shared links" section in Shared media, so that all the client apps have the same, synced with cloud, shared links list in conversation.

Perhaps some day additional links highlighting will be added in TDesktop-only, that won't go to shared links section, but right now only server-side links are used.
