### ISSUE TITLE
Scrolling an unfocused window should still mark messages read

### ISSUE THREAD

**Issue by kke** [telegramdesktop/tdesktop#10593]
### Steps to reproduce
1.  Have the telegram window visible but not in focus
2. Receive messages on Telegram
3. Scroll the unfocused telegram window using mouse wheel/gestures/whatever without focusing

### Expected behaviour
The new messages should be marked read as they are scrolled into view 

### Actual behaviour
Messages get marked read and the unread badge counts are updated only when the window is focused

### Configuration
Mac, latest beta.

**Comment by nuclight** [comment]
No, this should not be done so, because mouse cursor could be above another window, also while wheel scrolling, by mistake (mispositioning), that is, unintentional. And marking message reading cannot be undone, so this will break work for those who mispoint or even use this intentionally (e.g. I use scrolling of chat list by wheel without giving focus when part of window is overlapped, to see if may be I missed something or not).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/753

**Comment by DDR0** [comment]
> No, this should not be done so, because mouse cursor could be above another window, also while wheel scrolling, by mistake (mispositioning), that is, unintentional.

I know how to operate my computer, and when I scroll I mean it (or can quickly correct for it). I would like for my input to not be ignored in this case. What if I reply when the window is unfocussed? Should we not send the reply because I might have been aiming for a password field?

I bring up this example because it has happened to me, but I do think that it is my fault in that case for trying to log on before the screen had turned on. I've fixed it since. It's obviously useful, but also such a dumb use case that I don't think anyone would really argue it should be implemented. Philosophically, I think a lot of this boils down to how we use computers, and at the corners, we use them quite differently - especially on Linux, with it's myriad of graphical shells. It's a good thing, but certainly makes something like this issue a lot more complex.

>  use scrolling of chat list by wheel … to see if may be I missed something or not

I have a different use-case. :slightly_smiling_face: I don't care if I've missed stuff or not, because most of my chats look like this:
![Screenshot_20210428_105106](https://user-images.githubusercontent.com/862627/116450042-addf4b00-a80f-11eb-9699-1d72c1a067e0.png)
I know I've missed stuff. I've missed quite a lot of stuff. I had to. I have a life to live.

**Comment by kke** [comment]
@DDR0 

> No, this should not be done so, because mouse cursor could be above another window, also while wheel scrolling, by mistake (mispositioning), that is, unintentional.

Why would it scroll the telegram window if the mouse cursor was not on it and it does not have focus?

> And marking message reading cannot be undone, so this will break work for those who mispoint or even use this intentionally (e.g. I use scrolling of chat list by wheel without giving focus when part of window is overlapped, to see if may be I missed something or not).

In which case, you have noticed the message, which is what the counter is supposed to be counting.

In fact, this feature makes the counter confusing ==> Counter says 3, but there's nothing more to scroll to, where are the 3 new messages? Oh right, I already scrolled past them but now need to focus the window to confirm.

**Comment by kke** [comment]
@Aokromes this is not the same issue as #753 - this is about marking messages read when scrolling manually when not in focus, not auto-scroll.
