### ISSUE TITLE
Wrong diacritic shown in Telegram

### ISSUE THREAD

**Issue by ovidiub13** [telegramdesktop/tdesktop#1089]
On the desktop app, on Llinux, when typing the romanian diacritics "Ș" and "Ț", Telegram shows the incorect diacritics "Ş" and "Ţ".

The Romanian language uses the letters with a comma below. The "Ş" is a turkish letter and the "Ţ" doesn't exist in any language.

Refferences: 
- https://en.wikipedia.org/wiki/T-comma
- https://en.wikipedia.org/wiki/S-comma
- https://en.wikipedia.org/wiki/Romanian_alphabet#Comma-below_.28.C8.99_and_.C8.9B.29_versus_cedilla_.28.C5.9F_and_.C5.A3.29

No matter if I type the correct or the incorrect diacritic, Telegram always shows the incorrect diacritic.

**Comment by auchri** [comment]
See #23

**Comment by ovidiub13** [comment]
"telegramdesktop closed this on 17 Jun 2014"
That was closed a long time ago, there have been many updates since then. The issue persists now.
I'll look into the font, to see if the font has this issue.

**Comment by ovidiub13** [comment]
The email notificaiton said #23 Here I see #27. Previous comment was about #23.

**Comment by auchri** [comment]
Yes, typo :smile: 
I meant #27

**Comment by ovidiub13** [comment]
It seems to be the same issue having multiple symptoms.

**Comment by ralesk** [comment]
I just copy-pasted the issue text into my Telegram (also Linux) and I see S-comma, T-comma and then S-cedilla, T-cedilla...

I wonder if it's not maybe an issue with the keyboard layout being incorrect.  Compose Comma {S or T} in particular seems to create ş and ţ (cedilla versions) on my Fedora 21; not sure what the Romanian keyboard layouts do here, haven't tried.

**Comment by ovidiub13** [comment]
The keyboard layout is correct. Using the Romanian (Romanian) Layout. This issue is only happening in Telegram on Linux Desktop (Kubuntu). All other applications show the correct character.

**Comment by ovidiub13** [comment]
The issue still persists with the Material version. Please reopen.

**Comment by CociuDan** [comment]
![image](https://user-images.githubusercontent.com/23123693/102913640-5b67d980-447f-11eb-84a6-87ee820a46a2.png)
Seems like the issue is still there as 'ă' 'ț' and similar diacritics are displayed wrongly on Windows 10 (2004). Although I have the Romanian Language Pack

**Comment by ralesk** [comment]
That issue doesn't seem to be in Telegram (or not necessarily the way it seems), but in that you received decomposed letters (common on Mac, uncommon elsewhere — maybe the Mac Telegram does it, or Telegram generally doesn't care about it? I don't know).  This means that instead of the Latin Small Letter A With Breve you received the Latin Small Letter A, and a Combining Breve Accent.  Same with the t-comma, a t and a combining comma accent.

At that point it usually depends on the font and the text rendering engine to put the floating accents in the right place — it often doesn't really work well sadly.

I was able to send myself the sequence `ăț   ăț` and it resulted in a proper and a somewhat wonky rendering.

![image](https://user-images.githubusercontent.com/1564502/103104286-90626080-4626-11eb-8dad-3adb0c6426c7.png)

In charmap it looked as intended, but that's both a different font and not Qt and whatever else is in the way of a piece of text and the screen:

![image](https://user-images.githubusercontent.com/1564502/103104303-a2dc9a00-4626-11eb-8cda-c46860be0c3f.png)
