### ISSUE TITLE
Telegram Crashes when playing a Google Logo gif

### ISSUE THREAD

**Issue by WurdNerd** [telegramdesktop/tdesktop#1095]
The Culprit:
![google_logo](https://cloud.githubusercontent.com/assets/5887027/9892508/cc29aa46-5bcc-11e5-8c12-583a2d9de31f.gif)
The Issue:
[Screen Cpature](http://box.wurdnerd.pw/aEENM2.mp4)
IT seems to crash the Windows version when playing this gif, I'm not sure why, I can play other gifs just fine, even if they're bigger in size.

**Comment by auchri** [comment]
Seems to ba a memory leak:
![image](https://cloud.githubusercontent.com/assets/5092164/9892771/593c22ca-5c12-11e5-8c47-a91a35382a67.png)

**Comment by auchri** [comment]
![image](https://cloud.githubusercontent.com/assets/5092164/9892938/dfe5a8b8-5c13-11e5-85cb-395ad6f3d542.gif)

Telegram fills the memory and then it crashes

**Comment by auchri** [comment]
@WurdNerd wtf - Google Chrome crashes too with that gif!

**Comment by WurdNerd** [comment]
I haven't seen it crash Crhome or Android

**Comment by heejune** [comment]
The crash is somewhat related to the logo structure itself.

1. The Google logo animated gif contains 675 frames which are quite larger than usual.  So when the AnimatedGif::start() loads frames, it only read first few frames because the size limit exceeded MediaViewImageSizeLimit (Although MediaViewImageSizeLimit is defined as 100MB, the total size for 'per frame size * gif frames' easily goes over it)

2. Remaining frames which aren't loaded at start() method, will be loaded when AnimatedGif::animStep() called, though.

3. However, AnimatedGif::current will also consume huge memory while scaling the frames to appropriate size(by QImage) and it finally leads to OOM exception.

**Comment by telegramdesktop** [comment]
Thanks for this sample! I hope to improve and optimize that code in the future.

**Comment by telegramdesktop** [comment]
Please check out the new fixed update 0.9.17.

**Comment by dariuosh56** [comment]
hi

**Comment by XenHat** [comment]
This seems to be fixed now. I have reproduced that crash at time it was reported intially and Telegram appears to be handling that gif well now.
