### ISSUE TITLE
Iranian Calendar

### ISSUE THREAD

**Issue by neesti** [telegramdesktop/tdesktop#1155]
Hello.
Please support Iranian calendar (https://en.wikipedia.org/wiki/Iranian_calendars) into Telegram.
Thank you so much.

**Comment by Alireza-Mim** [comment]
@telegramdesktop  Is this issue accepted as an improvement? Or Considered as a feature?

**Comment by telegramdesktop** [comment]
@Alireza-Mim I did not fully understand what is expected to be done here, sorry. Some other date display?

**Comment by Alireza-Mim** [comment]
In some countries (specifically Iran and Afghanistan) a local Iranian calendar is employed officially instead of the Gregorian calendar.  For example today is 1394/07/27 in that calendar

The conversion between these calendars is simple and the algorithms exist since long time ago, it's just a matter of policy whether to change the displayed date in the UI and if it can be considered as an improvement.

**Comment by telegramdesktop** [comment]
@Alireza-Mim What about month names? We have strictly 12 language keys, which are translated in supported languages like they name in Gregorian and are used in UI.

**Comment by Alireza-Mim** [comment]
Month names are also localized. They are not exactly mapped to the Gregorian ones. 

Guess I should investigate this one deeper, as we still haven't added support for Persian language.

**Comment by neesti** [comment]
@Alireza-Mim سلام. فرصت کردید که در اینباره تحقیق عمیق‌تری بکنید؟ متشکرم.

**Comment by behrang** [comment]
I have a project for converting Gregorian calendar to Persian calendar. It is called Jalaali and is available here in different languages: [github.com/jalaali](https://github.com/jalaali).

Persian calendar, is a different calendar system, which also have 12 months but the do not map 1 to 1 to Gregorian calendar months. This is a different calendar system, and simply translating months will not work. You have to support a different calendar system, although conversion is easy and with that algorithm fast.

Currently we have JavaScript, Python, Elixir, Swift, PHP, Ruby, and Haskell implementations.

**Comment by afarsi** [comment]
There is two problem:
1-Translate name of 12 Georegian calendar's months. It should be implemented by translators in transifex.
2-We want telegram support multiple calendar systems, in additon of geroregian calendar. Because georegian calendar is not official and working calendar of many countries. Now, for example in Gmail, you can select another calendar system instead of georegian as your prefered calendar. For example, in Arabic countries, they are using Hijri calendar(Loonar Hijri Calendar) instead of Georegian calendar and in Iran and Afghanistan, official calendar is Solar Hijri(Jalali) calendar.
Now in windows 10's regional and languages settings, you can select another calendar as your prefered calendar.
This issue's problem is paragraph 2 not paragraph 1.

**Comment by stek29** [comment]
If only *#%$@%#$ like iGram didn't violate GPL..

**Comment by Aokromes** [comment]
Maybe #618 ?

https://i.imgur.com/8l0VQ0o.png

**Comment by afarsi** [comment]
@Aokromes, You'are right and your not!
Because in #618  discission is about Date Format, not diffrent calendar. Date format means you use diffrent date format for georegian calendar. for example 2017/9/15 or 17/09/15 or 9/15/2017 or 15/09/2017 and.... It would be fine if implemented.

But discussion in this bug is about using another(alternative) calendar instead of georegian calendar. As you mentoined in imgur.com link, windows supporting Iranian calendar also and Hijri calnder(Arabic calndar) also. The first(Blue) item in calendar type(In your screenshot) is subject of this 
I'm not sure if you can use windows Persian(Iranian) calendar by only using system date format or not? Because it's **not only a date format.** It's a fully different calendar.
 I know there is a library in .net framework and C# .net named PersianCalendar. For more info: https://msdn.microsoft.com/en-us/library/system.globalization.persiancalendar(v=vs.110).aspx
https://stackoverflow.com/questions/5811170/net-how-to-parse-a-persian-farsi-date-string-jalali-calendar-into-a-datetim

Really, you should do two different tasks:
1-Fix bug #618 for having a date format by selection of user(It will be usable for georegian calendar)
2-Fix bug #4182 (This bug is a part of #4182)

**Comment by stek29** [comment]
Closed in favor of #4182
