### ISSUE TITLE
Add "/me" support

### ISSUE THREAD

**Issue by DASPRiD** [telegramdesktop/tdesktop#1165]
It is a quite common feature among many chat clients to convert messages starting with the "/me" command. This originates from IRC, but is also found in other systems like for instance Skype or XMPP. Originally I wanted to provide a pull request for this, but the source code is quite confusing to me, so instead I just provide a mockup screenshot to demonstate how I imagined it.

When a user types for instance `/me does something`, it would appear like this for both the sender as well as the recipient:

![telegram-me-mockup](https://cloud.githubusercontent.com/assets/233300/10411188/7836fbe2-6f5d-11e5-8b9b-9e363c64ee7f.png)

From the sender's side, the UI change is minimal, as `/me` will simply replaced by their own name in bold (and optionally the entire line is kept in the username's color). For the recipient in a normal bi-user chat it would work the same, while on a group chat username which is normally printed at the top of every message would be omitted since it's redundant in this case.

**Comment by auchri** [comment]
I think this has to be implemented into the Telegram API?

**Comment by DASPRiD** [comment]
Not necessarily. It could just be sent as-is (like it currently does), and only handled per client. That way it would stay backward compatible.

**Comment by soren121** [comment]
Telegram Desktop is considered one of the official Telegram clients. I think it would be rather callous to implement new features and introduce fragmentation among official clients. This really should be brought to the attention of the Telegram API developers.

**Comment by DASPRiD** [comment]
@auchri @soren121 –  Is there a Github repository for the API or another way to bring this up?

**Comment by auchri** [comment]
@DASPRiD The api is not public, but you can suggest the new feature by the "Ask a question" feature in one of the official apps

**Comment by stek29** [comment]
Use `@bold *My user* does something`?
Or create bot which does it automatically.

**Comment by ZornTaov** [comment]
@stek29 I've tried that markdown, and having to see the "via @bold" at the top of each post is unnecessary for what's being asked for.  What was shown in the opening screenshot is exactly what most other chat clients do, and should be a very simple addition to functionality.

**Comment by Tynach** [comment]
@soren121 typed:
> This really should be brought to the attention of the Telegram API developers and implemented uniformly if at all.

Does this even matter at this point? On Telegram Desktop, a user can wrap text inside '\`'s to make the wrapped text monospaced, denoting code. A tdesktop user can also use three of them around a multi-line block of text to make a block of monospaced, preformatted text. The text looks correct on Android (and presumably all other platforms), but you can't actually make such posts from Android (and presumably all platforms other than desktop).

So we already have a situation where the desktop app provides functionality that other apps do not. And vice versa, such as being unable to see the ban list of a group you moderate on desktop, but you can on Android; and you also can't even configure who you let see when you were last online from the desktop client, only from Android/mobile (I don't have any Apple products).

Of course, then again, I'm of the strong opinion that you shouldn't try to emulate one platform on another platform, and I think Telegram's insistence on trying to make everything so extremely consistent is in fact detrimental to Telegram.

But the '/me' thing would fall in line with other little things that are different from tdesktop to other platforms' apps, such as the ability to type monospaced text. At the same time, it makes sense on another level: it's very difficult to type '/me' on mobile, and fairly easy to do so on a desktop computer. So if it were to be implemented anywhere first before elsewhere, it makes 100% sense to do so on tdesktop before Android/iOS.

**Comment by Tynach** [comment]
@auchri, do you think it'd be possible to implement in a way similar to how \`foo\` turns into `foo` on all clients? It may not be possible for other clients to immediately send '/me' posts this way, but can it at least be sent in a way that other clients will see tdesktop's '/me' posts correctly?

**Comment by Gollam** [comment]
I can only see some interference with the bot commands. A bot can implement a _/me_ command, am I right?

**Comment by ZornTaov** [comment]
@Gollam yes, a bot COULD implement a /me command, but that's not really what should be relied on.  /me is a command that is pretty well ingrained in almost every chatting platform with the only exception that I know now of being steam.  YES a bot could be made, but said bot would have to be known about  in a global sense like the Markdown Bot is with @bold.  However doing, say, "@bold *Zorn* waves" instead of "/me waves" to accomplish the same line is more work than should be needed, especially if you're stuck with the "via @bold" above the post.

**Comment by Gollam** [comment]
@ZornTaov I was not suggesting the creation of a bot for this functionality, and I am aware of the _/me_ command in general :) I was instead thinking about what happens if a bot also introduces a _/me_ command in a chat, and you write _/me_. What will happen then? Which command will run? To resolve this, bots may be forbid to implement a command named _/me_, to avoid interference, OR maybe the bot's _/me_ could take priority in this case.

**Comment by Tynach** [comment]
@Gollam, I feel the latter should be the case - the bot gets precedence. This will likely lead to a lot of people removing the functionality from their bot (as it was probably only included in the bot to make up for the lack of /me support to begin with), but it's one of those cases where they'll likely prefer the new support for the command anyway.

**Comment by antaeusdk** [comment]
+1

**Comment by DASPRiD** [comment]
It doesn't seem like there was any official activity on this ticket so far, right?

**Comment by stek29** [comment]
Why do you even need `/me`? Can someone please give me any **real** example?

**Comment by ZornTaov** [comment]
@stek29 /me has been a staple command in every single communication client I've come across  and is used as a way of role playing with the person or group of people you are talking with.  For myself and possibly others, using /me at the start of a post for an action is so ingrained into out habits that we'll keep using it even though the /me will do nothing to the post using the telegram client.  this leads to multiple posts that have /me at the start and it ruins the roleplay experience. as it breaks the immersion.

**Comment by stek29** [comment]
@ZornTaov Well, centuries ago humans were used to eating raw meat and living in caves.
That wasn't so good. But thanks innovations we now have ovens and houses.
Sometimes we should drop old unnecessary habits.

**Comment by ZornTaov** [comment]
@stek29 this wouldn't be a problem if it was a "move from one client to another and stop using the old one" kind of evolution that took place for humans.  INSTEAD it's a "still talking to different people on multiple different chat clients because that's the only way to talk to that particular person."  And since /me works on everything but one, that habit is going to stay.

**Comment by ptramsey** [comment]
I don't understand the resistance to this feature.  It seems simple to implement, and if the official client does so and people start using the feature from there, other clients will likely rapidly follow suit.  Slack supports it, Hangouts supports it, and telegram has a large userbase of people who would rapidly adopt it.  It's certainly no more frivolous than stickers and GIFs.

**Comment by stek29** [comment]
@ptramsey Telegram now != Telegram one-two years ago.
There are much more users who prefer "stickers and GIFs" to /me.
Also, Stickers and GIFs don't break bots.
They also don't require server/client to parse each message and check if it contains "/me", and change everything in message if it does.

**Comment by ptramsey** [comment]
I'd be curious to find out whether that's actually true w.r.t. relative importance of stickers/gifs vs. /me to users.  And, if this were implemented client-side only.... does the client not already parse each message looking for `@user` callouts?  I can't speak to the question of how easy it would be to do it without breaking bots, but I'd be curious to go find out if there's a way to build it so that the precedence of bot commands vs. the built-in /me makes sense.  I'll poke around this weekend :)

**Comment by stek29** [comment]
@ptramsey I highly doubt TDesktop would have anything like that implemented on client side only.

**Comment by gudvinr** [comment]
@stek29 oh, come on. That's not necessarily _should_ be done as `/me`. It can be long tap/RMB option on send key e.g.
Question is **more** about mention yourself doing something and not about exactly the same behavior.
And if use '/me' as command it can easily be disabled at least for bots or enabled only for groupchats since this is not very useful for single-user dialog.

**Comment by gentlecolts** [comment]
@stek29 /me is a trivial formatting option and there is no reason why it wouldn't be handled client side.  In fact it probably wouldn't even take long to write a simple browser plugin for the web client that replaces messages starting with /me with specifically formatted messages. Almost every chat client out there supports /me and there is no reason why telegram should ignore such a trivial feature, especially since it'd help new users migrate over.  Of all of the features on my telegram wishlist, this one is the one that continues to surprise me with its absence since it's such a trivial thing.  There is no reason it would break bots...any issue it'd cause with bots probably indicates that either the bot is implemented very poorly or that the way bot commands work is in need of revision

It's such a small thing to implement, but it'd really make a difference in user experience for those who are used to it while having no impact on those that dont use it

**Comment by cavac** [comment]
Just to take a look on the technical side of this discussion for a moment: Why would anything change for the bots? Wouldn't a bot just get a message that is starting with the string "/me "?

I can send that to a bot *now*. If it fails to parse the input correctly and does something stupid, it is *already* broken!

So, in effect what you are saying is, you don't want to add a useful feature because you want to "protect" broken software written by people who have not the slightest clue about basics like input validation?

**Comment by nuclight** [comment]
Come on, people, I see two different things confused and intermixed into one:

1) The need of action-describe in clients and possibly API
2) The problem of interference of "`/me`" command if done literally as-is with bots

Let's discuss them in order.

The first - need of action-describing thing. Yes, exact words are important, it's correct title is not "`/me` command" but rather "tool for describing action in 3rd person".

@stek29 you are terribly wrong here. It surely looks that you are neither psychologist nor linguist. The distinction between 1st / 2nd / 3rd person (that is, "**I am** `<verb>` / **you are** `<verb>` / **he is** `<verb>`") is fundamentally built-in into human languages, because this is the way human brains think  (and, as you may know, human brain did not changed significantly for ~40 thousands of years, and this is not going to happen in nearest centuries even if science will find a way to do).

You may have seen it in literature/books for hundredths of years: dialogues are distinct in form from describing what a hero is doing, in 3rd person. You wanted **real** example? Okay, I've many times seen a question in Telegram groupchats about who is doing what right now. And that's how it would look in IRC with actions:

```
11:00 <jane> hey people, what are you doing right now?
11:01 * john prepares to his exams
11:02 * peter drinks beer
11:03 * Myaw-Myaw бегает по потолку
11:04 * cat purrs
11:05 <jane> okay huys, who wants pizza?
11:06 <peter> I want!
11:06 * john too
```
Okay, example above was slightly imagined, so here is (a rough translation from Russian) a real phrase from nearest IRC channel:
```
Thu 19:09:26 <lavros> how badly matching of needed files is done in Git Large File Storage. This is full fuckup. Would be better if they done patterns as in .gitignore, but they've done some hueta.
Thu 19:09:57 * lavros spends second hour for trial-and-error
```
As you see, people really use, because it is natural. And come on, the `/me` command is now available even in World of Warcraft! It would be a real marketing benefit for Telegram over WhatApp/Viber/Facebook if it will support `/me`.

Next. I've chatted today with the inventor of original `/me` command in IRC, Carl "lynx" von Loesch (see https://groups.google.com/forum/#!msg/alt.irc/fWreRU1ECWM/B0IVwct7I5cJ for original announce in 1991). He told me that concept already existed before, in MUDs (multi-user text-only role playing games with server-bot) of 1980-s, just uncomfortable to use.

He also showed me an example of MUD, and guess what? They had "stickers and GIFs" back in 1980-s! Just that they were pure text ASCII art instead of real pictures :-) but 2nd and 3rd person language's grammar constructs were also used extensively (okay, you don't need 2nd person except when you talk with special RPG bot - but 3rd person you still need, and this entire issue is about 3rd person).

Also he told:

> By the way, the /me command was inspired from Shakespeare... «Me thinks the lady doth protest too much.» 

(remember what was said about literature/books above?..)

Also @stek29 you're certainly not fair speaking "users prefer stickers and GIFs to /me" - but hey! actually, they have _no choice_ because `/me` is not implemented, and users are _forced_ to use stickers and GIFs instead of `/me`. If you want to argue they don't know about `/me` - come on, even World of Warcraft has `/me`, surely they know!

And now second question. The bots, API and problems of `/me`.

You could draw several conclusions from above post to `alt.irc`. For example, that doesn't **have** to be exactly `/me` - Carl von Lynx now experiments with other chat systems, they've used a `+` char as a command prefix (instead of `/`) for a long time, for example.

Actually, on Android I would really prefer this action-tool _not_ as difficult to type `/me` (not only because of slash character, but need to switch keyboard language to English first - I usually chat in Russian - and then back) - but rather as, err... may be a button near smiles and stickers?.. That solves problem with bots completely - people need a tool, it doesn't need to be exactly `/me` or `+me` or whatever - just give us a tool.

Another option, as others already mentioned above, would be disable handling of `/me` for chats with bots (at least when presented with custom keyboard), though I think it's a hack.

From an API point of view, 1 (that is, _one_) bit in message flags is enough (you already have free bits in message `flags` field in schema, aren't you?) - and as older clients don't support this bit, they simply render message as usual message, just with a little strange wording for human - but other users in groupchat would (sooner or later) notice this and just tell those losers to update their app to render properly :)

This could be just-in-client handling (in IRC, CTCP is Client-to-Client Protocol, ACTION is it's part, other parts were used for e.g. file transfer - not relevant to us); as Telegram don't need real CTCP, it could be done not by `/me` string but by e.g. special Unicode symbol/smiley (what will older clients see). But it looks like an even worse hack to me.

The most important thing is - how this would be **displayed**. It surely must be clearly different in look from usual message (but probably not _very_ different). And it must describe user's action in 3rd person, as from side view.

Do we have something like that in present Telegram already? Yes! These are grayed messages about events happened, like:

`John Smith added Jane Doe` (to this groupchat)

or 

`January 19` (day changed)

...that is, actions in IRC were modelled after mesages about events ('* nick joined #chan'), too - and they differentiated later by colour of text. Thus, in Telegram those action should look not so-regular left-justified or right-justified message, but somewhat center-aligned looking in-between regular message and grey events. But this (design) part should be yet discussed, of course.

The main final point to progress is - `/me`-like actions **must** be implemented somehow.

**Comment by symlynX** [comment]
Heya! I'd guess Telegram would do itself good to satisfy the needs of its geek minority as they are very influential in the public opinion of Telegram's cryptographic safety etc etc. It's (unfortunately) been a winning strategy for both Google (fonts and scripts included in websites, this way enabling bulk tracking of users…) and Facebook (onion support, open sourcing cloud technology…).

In this case it is even really easy for Telegram: All you need to do is add an ACTION message type to the protocol (oh, these days it's just an API, how humble) and make all clients *display* it in a neat way. Then you can let desktop and indie implementations add /me or whatever they like (how those messages are generated does not need to be identical on all platforms as long as the encoding and display is consistent) while mobile phone app doesn't even provide a way to *generate* such messages.

Then you can observe how phone users react when they see action messages on their screens. Will they want to be able to make them, too? Or will they not care at all? If they don't care you can deprecate the message type again. Then you were right, it's just a geek minority thing. My experience is, you will probably be wrong and people will love it. Not the majority maybe, but a meaningful respectable minority. Just like there is a minority that hates emoji from the heart.

This bug report reminds me a bit of Ableton who refused to integrate MP3 support for years. Now a whole generation of remixers throws mp3 files into Ableton all the time, because you can't always have AIFF. A company can't always know what users want, and in this case it's even easy to just try it out.

Myself I stopped using Telegram since it cannot be accessed from Tor. I actually believe its secret chats are more trustworthy than Signal, simply because Telegram is in F-Droid – and the excuses for Signal not to be are lame and questionable.

**Comment by akaWolf** [comment]
Hello.
I'm sorry, but I was unable to see the official comments at this 1.5-year-old issue.
Are there such comments?

**Comment by john-preston** [comment]
@akaWolf There are no plans on adding such thing right now. Also, Telegram Desktop is trying to keep up with mobile apps in features so it will be considered here only if it will be added in the mobile apps first.

**Comment by Emulator000** [comment]
I think that this requested feature is a bit more "global", in fact, could be extended to all commands starting with /.

I'ts obvious that /commands is a command so, why show commands in public? Like in supergroups, groups etc? Commands should be private or seen only by admins.

Example:
Me: /command
Response: Error: command not found

This message "Error: command not found" or whatever else, is currently displayed to ALL member of the group. Imagine a command like /help, all users will see a lot of spam text to their client because all messages and commands are public.
A private response per user in supergroup or group is needed here.

If someone want a public command, should type something like !command and not /command and then, handle the reply to public or privately but still in the chat not contacting the bot privately.

This is directly attached to this feature, a bot can handle privately the "/me message" command and show to the public in whatever format.

**Comment by gentlecolts** [comment]
or instead they could just do what skype and basically every other chat program to ever exist does and have system messages be local only?

**Comment by mathiasverraes** [comment]
+1 for /me support. This is fundamental.

**Comment by grigoryvp** [comment]
As a long time IRC user I completely agree that it's a useful communication feature. And Skype supports it, too.

**Comment by bseishen** [comment]
+1 for this feature. I look a little bit special typing /me currently.

**Comment by pavel-odintsov** [comment]
Even HipChat supports it! Please add it! :)

**Comment by lastsky** [comment]
+1 for this feature! please implement this! even Skype support this.

**Comment by jchook** [comment]
Literally blown away that this is not implemented by THE chat solution of the future.

**Comment by gentlecolts** [comment]
@Lonami because it seems like a reasonably simple feature to add and people seem to want it.  It's a good, common shorthand for adding formatting that indicates having done an action, and as many people have noted in this thread, is quite useful for chatting.  IRC isn't even the only thing that supports it, Skype does too, for example, and it seems Discord also supports it, even if their implementation is just a basic shorthand for adding italics to the whole message.

**Comment by shirishag75** [comment]
just re-sharing the gist, although comment 2 and others have already shared the meat of it long time ago. 

https://www.livinginternet.com/r/ra_action.htm

**Comment by SmartManoj** [comment]
[Workaround](https://t.me/tds98)  using ahk and python

**Comment by mkahvi** [comment]
Steam was mentioned not having it, but they actually had it previously and they re-added it, probably due to popular demand.

It's kinda weird, but this is actually one of the bigger reasons why my friends refuse to use Telegram, because it's so necessary for fluent communication. We mostly communicate on desktops, not mobile, so.. I guess that's moot in face of the declared mobile focus.

**Comment by imukai** [comment]
The "telegram isn't IRC" might be accurate but it is also rediculous.  Every major chat platform since IRC has supported some sort of emotes because -- whether you do or not -- a good base of users like to roleplay.  If not roleplay it's handy to add expressiveness outside of putting things in asterisks or bolding it or whatever.  2019 -- add the support.

**Comment by akaWolf** [comment]
@imukai don't think we should use SW, authors of what seems don't care needs of people et all.

issue is 4 years old...

**Comment by RememberTheAir** [comment]
I only now figured out that typing "@me" will make tdesktop suggest you to mention yourself (if you don't have an username, it will mention your display name instead).

Not really what the OP is asking for:

> `/me` will simply replaced by their own name in bold (and optionally the entire line is kept in the username's color)

...but comes close

**Comment by trollfred** [comment]
it should be displayed the same way as skype does it, otherwise it's no fun at all

**Comment by trollfred** [comment]
It should be the displayed same way like it is now for messages like `Username created the group "Groupname"` or `Username updated group photo`

**Comment by fireton** [comment]
I moved my chat group from IRC and badly need this feature in Telegram. Please implement it. (cat_from_shrek.jpg)

:)

**Comment by EccoBlackfin** [comment]
Adding my vote for this issue.  It's really the only feature missing from Telegram, and needs to be implemented protocol-wide.

**Comment by nuclight** [comment]
According to TL scheme, this is doable for at least twenty layers already:

`messageActionCustomAction#fae69f56 message:string = MessageAction;`

@auchri so this is not API issue anymore
@johnpreston any ideas of when to wait implementation?

**Comment by nuclight** [comment]
According to TL scheme, this is doable for at least twenty layers already:

`messageActionCustomAction#fae69f56 message:string = MessageAction;`

@auchri so this is not API issue anymore
@john-preston any ideas of when to wait implementation?

**Comment by john-preston** [comment]
@nuclight Only the server side can create those messages for some events, no way to send such message by the client.

**Comment by Tynach** [comment]
@john-preston, perhaps the client could send a post to the server instructing the server in how the action message should look, and the server could then create them? Not exactly ideal, though... And it sounds kinda hacky.

Additionally, I feel like the messages *shouldn't* look the same as server messages - server-side actions *should not be spoofable*, in my opinion. Such issues are why Steam chat got rid of `/me` support in the past, before rewriting their entire chat system (at which point they added it back in).

Ideally, there'd be some sort of flag indicating whether the name should be styled as in-line with the body of the content (and if so, make it visible on their post regardless of whether the previous post is also theirs), or if the name should be separate from the post (and use the current behavior for whether or not to show the name).

I also think the color, font, styling, etc. and click-behavior of the name should be the same as it currently is.

**Comment by SmartManoj** [comment]
> I only now figured out that typing "@me" will make tdesktop suggest you to mention yourself (if you don't have an username, it will mention your display name instead).
> 
> Not really what the OP is asking for:
> 
> > `/me` will simply replaced by their own name in bold (and optionally the entire line is kept in the username's color)
> 
> ...but comes close

Isn't this enough ?

**Comment by trollfred** [comment]
@SmartManoj it doesn't come close at all. the point of this feature is to create messages which look exactly like system messages like `John Doe created the group "blahblah"` or `John Doe updated group photo`

**Comment by Tynach** [comment]
@trollfred, no, the idea is *not* to make messages that look exactly like system messages. The idea is to make messages which have your username exactly once, in-line with the rest of your message.

System messages should not be spoofable, this will lead to things like "/me has left the group" making people believe that a person *actually* left, when they didn't. Server messages should remain uniquely styled.

**Comment by nuclight** [comment]
> is to create messages which look exactly like system messages like
> `John Doe created the group "blahblah"` or `John Doe updated group
> photo`

Nope, it shouldn't look *exactly* like system messages - it should be
close to, but distinguishable. For example, many IRC clients, while
having system (e.g. join/leave) message looking textually same as
ACTION (/me) ones, still display it in different color (even in default
config when very little colors are used).

**Comment by karlgg** [comment]
> There are much more users who prefer "stickers and GIFs" to /me.

It's a bit silly to suggest things like "people prefer using something they **can use** over something they **aren't allowed to**." How can you have a preference for something that isn't possible?  Do people prefer to walk over flapping their arms and flying? I bet there's a couple of people around that might like that option. There aren't any physics stopping /me (except, maybe stubborn momentum).

Is it not "professional-sounding" enough?  Slack uses it, too. I type "/me will be back in a moment" constantly, and have as long as I've used Telegram, because I still use it in lots of other places where it works (including Steam, now).

I'm not sure why it's been an argument for four years, when this is a shrinking minority of "things that don't".  It would have taken little time to add it to Desktop and Mobile(s) and just be done with it. It's not a request for a wall of slash-commands, it's not a request to make the server spit out spoofed messages, it's a part of **conversation.** What Telegram is **for.** It's just a freakin' **/me.**

/me stops ranting.

In a more helpful tone, there are two or three standard responses, and any of them are appropriate.

/me does a thing:
- UserName does a thing.
- **UserName** does a thing.
- _does a thing._

No special colors, the same text as normal conversation. Literally removing /me and adding italics is what Discord does. If you edit your text later it's just italicized, but it's simpler to type than italicizing things manually.

**Comment by akaWolf** [comment]
I agree with @karlgg and also don't see any adequate reason to not add this functionality.

**Comment by trollfred** [comment]
> Slack uses it, too. I type "/me will be back in a moment"

Yep, slack implemented it but not the way it should look like, it just looks like a regular message just italic which does not make any sense, it's like person it talking about himself in third person in italic (bullshit implementation)

also @Tynach @nuclight guys I appreciate your concern, of course I didn't meant it to look REALLY EXACTLY like system messages, but they should like system messages IN GENERAL, thats the whole point of this feature. They just need to be a little bit different then real system messages. They can't look like a normal message from user like it is implemented in Slack. That is just kinda stupid and it doesn't make any sense to bother implementing it that way

**Comment by karlgg** [comment]
I wouldn't mind "looks different than the rest", but that's an option I wouldn't hang everything on. I don't think it "doesn't make sense" as normal text, because I see that in several places and it doesn't look jarring at all. The italics one is a little annoying in cases where it doesn't show the name with each message, but I would still prefer that to nothing. I'm more concerned about it not being done _at all._

**Comment by redtide** [comment]
I really don't see why not to implement such trivial thing like a simple /me command.

**Comment by akaWolf** [comment]
@redtide because Telegram is a proprietary solution. things are going into those direction which the Head decide to be the «right» one. no one care about minority of users and we are not able to change something because of Telegram's proprietary essense.

**Comment by danger89** [comment]
YEA /me !!!

**Comment by Tynach** [comment]
With the introduction of folders, there are no longer any reasons I have for using any other instant messaging service...

... Except for the lack of `/me` support. Granted, better ways of organizing large numbers of chats was a *much* higher priority, at least from my point of view - and as it was resolved first, apparently Telegram agreed on at least that point.

Group video conferencing is something I personally don't care about, but I could see more people caring about that than `/me`. If 'additions to protocol features' is a linear list with only one item being worked on or implemented at a time, I can understand that taking priority over `/me`.

But if there comes a day when Telegram has video conferencing, and a long time passes without `/me` support... Well, I guess I'll just have to complain louder at that point, because by then there'd be no other real reasons for me to use anything else.

I do think that `/me` support would be *much* easier to implement than video conferencing, though. So if the list of planned protocol feature extensions isn't being implemented one at a time, strictly in order of priority, then I would hope it'd be implemented first.

**Comment by dialex** [comment]
Well @Tynach, now Telegram supports video conferencing, so I think it's time we get our `/me` support :)

**Comment by yashpalgoyal1304** [comment]
> Well @Tynach, now Telegram supports video conferencing....

not group video "conferencing" though.

**Comment by Tynach** [comment]
@dialex, one can certainly hope! Though they've only implemented video *calls*, not video *conferencing*. A conference has a minimum of 3 participants, and you can't do 3-way (or more) video calls in Telegram yet.

I have at least one friend who uses Discord only because of the video conferencing feature, which he uses to play D&D with several other people online. Not something I do myself, but it's a very valid reason for wanting that feature, and I imagine many other people want such a feature as well.

They might (but might not) outnumber those of us who want `/me`, and among those who want *both*, I'm willing to bet they would weigh video conferencing (again - 3 or more people in a video call) higher than `/me` support.

It's worth noting that Matrix (at least in the Element, Mirage, and Nheko clients) *does* have proper `/me` support. Still, Matrix is very rough around the edges compared to Telegram, and it's harder to get people switched over to it. Telegram has a huge head start, and I'd really like to see `/me` support come to it as well.

**Comment by Tynach** [comment]
Since this is an API/server-side issue, I've submitted it to Telegram's new feature request platform here:  
https://bugs.telegram.org/c/944

I figure it's possible that maybe the right people will see it on there, that might not see it on here (given that this issue tracker is only for Telegram Desktop).

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by dialex** [comment]
Done: https://bugs.telegram.org/c/2360
People, let's give it a thumbs up :)

**Comment by yashpalgoyal1304** [comment]
it's not a nice way to go doing things u know. If a new tracker/platform is adopted, then mechanism should be made to automatically import the issues from the former tracker. As of now, it seems just a nice excuse. 

Anyways, i have given up trying to bring the issues in teams notice - the reason being things so complicated, arrogant replies, off topic chats, nobody caring about and so on and so forth. Enjoy wasting time on trying to file issues everywhere only to remain unnoticed.

**Comment by yashpalgoyal1304** [comment]
> such feature belongs to https://bugs.telegram.org/
> Aokromes closed this 9 hours ago

it's not a nice way to go doing things u know. If a new tracker/platform is adopted, then mechanism should be made to automatically import the issues from the former tracker. As of now, it seems just a nice excuse. 

Anyways, i have given up trying to bring the issues in teams notice - the reason being things so complicated, arrogant replies from team people, off topic chats being dominant rather than on topic discussions in the dedicated channels, nobody caring about and so on and so forth. Enjoy wasting people's time and forcing them to file issues everywhere, only to keep them engaged while still ignoring them.

**Comment by mirh** [comment]
This tracker is for the desktop app. 
That is for the platform/service. It doesn't seem hard.

**Comment by yashpalgoyal1304** [comment]
@mirh what doesnt seem hard??? huh? that tracker is new, this one is old. First this one was for services too. So, if they have decided to move to a new tracker, they should automatically import the issues from here over to there - which they are not. That's what i am saying. Why are they expecting the users to move over the issues huh??

**Comment by gentlecolts** [comment]
While the platform shift and sudden close is a little frustrating, you're not going to convince the devs to add this useful feature by being rude to them...that energy would be better spent supporting the ticket on the new platform:

https://bugs.telegram.org/c/944

**Comment by Aokromes** [comment]
> @mirh what doesnt seem hard??? huh? that tracker is new, this one is old. First this one was for services too. So, if they have decided to move to a new tracker, they should automatically import the issues from here over to there - which they are not. That's what i am saying. Why are they expecting the users to move over the issues huh??

only the platform wide tickets must be posted there, i don't closed the "api" ones before because there was no real alternative (ask a question meh), but they must had to be closed the same day they where marked "api" i don't closed them to stop people to make new tickets asking the same thing.
