### ISSUE TITLE
[Feature Request] Secret chat

### ISSUE THREAD

**Issue by Jeronimo17** [telegramdesktop/tdesktop#118]

**Comment by stormcloud-gnu** [comment]
Honestly, why is there still no implementation of secret chats in the desktop client?
Telegram advertises this feature as their big advantage over other messaging apps; 
they also advertise the existence of a desktop client, something whatsapp doesn't have.
But no secret chat in the desktop client?? This is NOT mentioned anywhere on the telegram page and i almost feel like being tricked....

**Comment by xur86x** [comment]
I will refrain from using Telegram until there are secret chats for the PC client.
I am looking for a secure alternative to Skype, but without secret chats Telegram is not able to become that.

**Comment by electricessence** [comment]
This is a dup of:
https://github.com/telegramdesktop/tdesktop/issues/5#issuecomment-69061631

**Comment by telegramdesktop** [comment]
Telegram is a mobile messaging app in the first place. Secret chats are hold only on one client device and can't be synced between them and they stay more secure remaining on the mobile. In my opinion different secret chats on different platforms will confuse users.

Desktop version is done to get full use of it's cloud-based infrastructure with instant sync between devices, including sync between mobile and desktop app. So the desktop app is more about work, with groups up to 200 members and documents of any file type up to 1.5 GB, than about secret chats. And that's why secret chats are not in the near plans for tdesktop.

**Comment by val108** [comment]
Dear Developers,

your app is used not only by glam girls with iphones. You deprive us of the opportunity to make contacts safe. Delete messages one by one each time? Are you kidding?

ADD SECRET CHATS FOR DESKTOP.

**Comment by edmundlaugasson** [comment]
This could be with message that if user will enable secret chat then it would not be cloud-based and synced. Certainly it would be good to see Telegram being most secure but [currently it seems that it is not true](https://www.eff.org/secure-messaging-scorecard)...
