### ISSUE TITLE
Support for new emojis?

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1196]
Are there any plans for adding support for new Emoji?

http://emojipedia.org/unicode-8.0/
![image](https://cloud.githubusercontent.com/assets/10401817/10558944/cf27b670-750d-11e5-99a8-23ede9c1f14e.png)

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov Apple first :) (in stable version of OS X).

**Comment by theus** [comment]
I suggested on Twitter to add option for Twitter Emojis. It's open-source like Telegram and the most beautiful emoji. :(

**Comment by PurpleMadness** [comment]
OS X now has the new emoji in stable 10.11.1. Time for an update? :)

**Comment by telegramdesktop** [comment]
@PurpleMadness Yes, it is time. But it is not that easy :) I hope to add them in one of the upcoming releases (not the nearest one).

**Comment by JuanPotato** [comment]
@telegramdesktop would you consider implementing the option to use other emojis? Like the twitter ones as mentioned before or emoji one?

**Comment by telegramdesktop** [comment]
@JuanPotato I'm not sure I will do that. It is really important that emoji are displayed in at most exact way in all the client apps, because you need to be perfectly sure what exactly the person you speak to will receive. You definitely know what he receives in case of words, in case of photos, videos, stickers. Emoji should be the same as well.

It is possible to implement some other emoji set in addition to the default one, but it is a low priority task, while supporting the same up-to-date set of emoji through all the client apps has definitely a higher priority.

**Comment by JuanPotato** [comment]
@telegramdesktop That makes sense. Thank you.

**Comment by sabret00the** [comment]
These are implemented on Android, hopefully we'll see them soon. My conversations now require to check Android just to see what the person means.

**Comment by auchri** [comment]
Added with v 0.9.15 stable

**Comment by DaFri-Nochiterov** [comment]
It's cool
