### ISSUE TITLE
Local passcode verification

### ISSUE THREAD

**Issue by c0der404** [telegramdesktop/tdesktop#1240]
Please, set local passcode verification like in Windows 10.
I mean that when I typing passcode app must be unlocked at once as soon as I entered the correct passcode.
Now I need to press "Enter" at the end of password input.

**Comment by telegramdesktop** [comment]
@c0der404 When I log in to Windows 10 I need to press Enter as well. And your idea means trying each passcode you enter, while you're typing it. It is not that good, because we want a local flood control to work — so that if someone takes your laptop he could just start guessing your password right inside the app.

**Comment by c0der404** [comment]
OK, got it. Thanks for explanation.
