### ISSUE TITLE
Blocked users' messages still appear in chat groups

### ISSUE THREAD

**Issue by foxmajik** [telegramdesktop/tdesktop#1281]
This issue references issue #1025 because that issue was marked invalid even though the issue is provably valid.

Messages from blocked users are not blocked in chats on the desktop client when that user is blocked using the desktop client.

If I block someone I still see messages in the chat from them on the desktop client.

This feature is crucial to avoiding text flooding and spamming.

See the attached screen shots:

<img width="536" alt="screenshot 2015-11-08 15 56 39" src="https://cloud.githubusercontent.com/assets/300165/11023570/946fcb50-8631-11e5-812f-111f899863f4.png">
<img width="633" alt="screenshot 2015-11-08 15 56 27" src="https://cloud.githubusercontent.com/assets/300165/11023571/9470c3e8-8631-11e5-973a-fae6e14e01aa.png">

**Comment by auchri** [comment]
@foxmajik This screenshots are not from Telegram Desktop.

**Comment by telegramdesktop** [comment]
If you block a user he can't send you private messages and invite you to groups. If you both participate in the same group you still will see messages from him (if not it will be very strange-looking, because you'll see some random part of the conversation that is going on in the group). This is the way server side works, client app has nothing to do with that.

**Comment by foxmajik** [comment]
@auchri Yes it is. Why are you so argumentative? I'm here to contribute to this project by reporting problems users complain about when I'm using the application, not to have a battle of wits with you.

**Comment by foxmajik** [comment]
Any update on this?

This bug still exists.

**Comment by john-preston** [comment]
@foxmajik This is the way server side and API works, there is nothing to fix from the Telegram Desktop side.

**Comment by foxmajik** [comment]
Disagree.

It is possible to implement client side filtering.

That's how filtering works in Microsoft Outlook.

Also there is a large body of users who disagree with you:

https://imgur.com/a/LUWF7

Your argument seems to be "don't implement the feature because somebody might not like it" which makes as much sense as not implementing filtering in Microsoft Outlook because somebody might not like it.

It makes more sense to make the feature available but not have it do anything by default.

**Comment by john-preston** [comment]
@foxmajik Client side filtering could be done, but it won't be consistent with other official applications (iOS / Android), so it is not planned here.

**Comment by foxmajik** [comment]
That's a conditional fallacy.

You are arguing that because other clients have not implemented filtering it would be impossible to implement filtering in _this_ client.

That implies that no client on any platform can implement any feature because no other clients have implemented it.

But since new features have been introduced since Telegram came into existence that is clearly untrue.

**Comment by john-preston** [comment]
@foxmajik No, thats not the case. Telegram Desktop is keeping it consistent with the major official mobile apps (iOS and Android), that have a major userbase and that present the new features first. After that they (not all, but most of them) appear in the Desktop app.

Also the Desktop app has some unique features, but they're not breaking consistency with those mobile apps, they're about something entirely different (like drag-n-drop of files or "Send to" menu integration on Windows).

**Comment by KamranMackey** [comment]
@foxmajik Filtering isn't being implemented. Now drop the subkect.

**Comment by KamranMackey** [comment]
@foxmajik Blocking users on Telegram only stops them from private messaging you, not block them entirely from viewing your messages and/or pinging you.

Also, filtering isn't going to be implemented. Now please drop the subject.

**Comment by ajanata** [comment]
I would also like to see this, or at least be given a pointer where to do this on the client side because it's annoying enough to me to make the change myself.

**Comment by thread13** [comment]
+1 on that. a bug or not a bug -- that would be a #1 must-have feature. ( will try to open a feature request on this. )

**Comment by Aminabzzz** [comment]
this screenshot isn't from windows client. In windows client the channels and groups list is UNHIDEABLE and many other things

**Comment by foxmajik** [comment]
Hi, just checking in since it's been a couple of years and this is still major missing functionality.

You seem to still be hung up over the fact that the screen shot I posted years ago wasn't from the desktop client.

I feel like you're trying to avoid to obvious and loud voice of your userbase demanding that you implement this feature by arguing that it isn't useful, avoiding the topic through whataboutism (google that word) and just shutting down any feature requests or bug reports where people are asking, demanding and begging you to implement it.

It's above and beyond obvious this feature is wanted because people keep putting in requests for it and you keep closing them.

See here, here and here:

https://github.com/telegramdesktop/tdesktop/issues/1025
https://github.com/telegramdesktop/tdesktop/issues/1281
https://github.com/telegramdesktop/tdesktop/issues/3772



In each request there was a mix of "I don't agree this is a useful feature" and "you posted the wrong screen shot" and "this needs to be fixed on the server" all in various forms of witty (snarky) retorts that are unfriendly and unnecessary.

You can keep shutting down the feature requests and bug reports but people are going to keep making them until you implement the feature, so I guess you get to choose where you want to do the work:

Do you want to spend all that effort being rude and evasive or do you want to spend it doing what you're asked to do by the people using your software?

**Comment by john-preston** [comment]
@foxmajik You just got it wrong, sorry. There is no sense in posting such issues here, because Telegram Desktop is part of the Telegram project and it doesn't introduce such major features on its own, without first being added to the major official applications, specifically iOS and Android apps.

No one here can implement that feature for you in the official desktop app. The links to Twitter and in-app support are just the places where you can request changes for the Telegram platform as a whole. Leaving them here, in Telegram Desktop issue tracker, has no point — no one, who can make that decision, reads anything from here ever, this issue tracker is for Telegram Desktop bugs only, that do not affect the way Telegram works as a whole.

**Comment by Aminabzzz** [comment]
Is the chats list hidable in desktop client? I don't see any buttons etc
for hiding the chats, bots and channels list. It is annoying me

**Comment by aphirst** [comment]
This drives me mad too. There's a prick who's in several groups I'm in. I get along with everyone else, but this guy makes constant personal attacks, yet no-one else can bring themselves to do anything about it. Being able to block/hide users within groups would be a very simple feature which would drastically increase the utility of this service.

**Comment by foxmajik** [comment]
@aphirst That's exactly my point.

I'm a human being and as much as I'd like to keep a stiff upper lip, there are toxic people who just keep at it and keep at it and keep at it.

**Comment by RememberTheAir** [comment]
Mmmmm, I honestly don't get why this issue is still open/not marked as API issue. @john-preston clarified why this can't be a thing on TDesktop:

> There is no sense in posting such issues here, because Telegram Desktop is part of the Telegram project and it doesn't introduce such major features on its own, without first being added to the major official applications, specifically iOS and Android apps.

I mean, hiding messages from some spicific users **must** be supported by the API and adding that locally, on a single client, wouldn't make much sense. Beside UX inconsistencies among clients, an hypotetic list of "hidden" users would disappear on logout and would be gone forever.

Features like this one should be reported to the in-app support or [via Twitter](https://twitter.com/telegram), but I'm quite sure many people already asked for this. But it does not seem to be in Telegram's plans :( although they are very cryptic about upcoming features so, who knows

**Comment by romanrm** [comment]
> I mean, hiding messages from some spicific users must be supported by the API 

For example hiding messages from specific users is not supported in the IRC protocol, each client implements its own ignore setup. And it worked fine for years, and still works now.  So no need to throw around bolded "must"s.

> hypotetic list of "hidden" users would disappear on logout and would be gone forever.

It would not, if it's saved locally on the device in client settings.

**Comment by RememberTheAir** [comment]
> For example hiding messages from specific users is not supported in the IRC protocol, each client implements its own ignore setup. And it worked fine for years, and still works now. So no need to throw around bolded "must"s.

Telegram's usage experience must be the same on all the official clients, such a major feature needs to be implemented at API-level first. No escape from that. It wouldn't make sense to add these features locally, at least on official clients. I wouldn't be able to hide the messages from a different device, and also other platforms' users wouldn't expect other clients to have features like this.  I can see it being implemented on some of the many cutom Android clients out there, or on a Telegram Desktop fork.

Telegram decides what will be implemented and what will not, and it's done at protocol level. TDesktop is not a third-party IRC client, is the third (or second?) most-used _official_ client, it can't just decide to add these things :)

**Comment by foxmajik** [comment]
> For example hiding messages from specific users is not supported in the IRC protocol, each client implements its own ignore setup

Yes, and ignore is well implemented in EVERY IRC client. It's considered essential functionality.

> Telegram team decides what will be implemented and what will not, and it's done at protocol level. 

And you interface directly with the Telegram team. We do not. So if your users are loudly and overwhelmingly asking you for this feature, you should to go the telegram team and go "oh hey guyz our users really want this can we haz plz."

You don't judge the features we want. You write code. Know your place.

**Comment by romanrm** [comment]
> You write code. Know your place.

Ouch, that last bit was uncalled for, that's not really how you talk to an open source project developers. :)

In any case we can always demand a full refund of $0 that we paid for the software. More practically speaking, there is the freedom of not using Telegram, or not using Telegram for multi-user chats.

Expressing your opinion or explaining a need is fine, but there is no place for demands or insults.

**Comment by john-preston** [comment]
@foxmajik "You don't judge the features we want. You write code. Know your place." This is magnificent! I'll take that to my Bio, not less. You made my day!

**Comment by stek29** [comment]
@foxmajik

> You don't judge the features we want. You write code. Know your place.

Golden. I wonder how many words starting with F would you get in other open-source projects you’d get after this words. In projects which can implement features like this one without changes in server side.
Also, I guess your comment only made it worse :)

**Comment by Lonami** [comment]
@foxmajik, it has been said several times. It's about keeping the UX consistent accross all major official applications out there (Android, iOS, and Desktop). Of course, people (like you) are free to fork the project and implement such a wanted feature. Maybe, if enough people *really* wanted this someone would be down for the challenge after all!

**Comment by ajanata** [comment]
> Of course, people (like you) are free to fork the project and implement such a wanted feature. Maybe, if enough people really wanted this someone would be down for the challenge after all!

And as I've stated before, if I could at least get a pointer into where in the code base to even start looking for where incoming messages are rendered into the group view, I'd do so myself.

**Comment by PandorasFox** [comment]
If you don't want to deal with someone in private, you can block them, or refuse to talk to them IRL.

You're still going to come across them in public - you can't really avoid that. That's a fact of life, and it's just how public spaces work.

This'll also impact how replies work (should Telegram just not show they're replying to someone? Should it just say "blocked message", similar to what it does for deleted messages? Should it just not show the reply?) and can impact perception on how conversations are going. (Also, how do you handle forwarded messages, etc).

What happens if an Admin has someone blocked - they should still see the user's messages so they can moderate stuff.

Telegram isn't IRC. IRC lacks replies/threading and has message immutability. You can't really compare the two.

Hard ignoring is a pretty bad thing, imho. The only feasible improvement that could be argued would be disallowing blocked users from replying to you in groups (which I still think is a bit bad - enforcing echo chambers through blocks is bad).

**Comment by romanrm** [comment]
> Should it just say "blocked message", similar to what it does for deleted messages? Should it just not show the reply?)

If you have to ask questions like this, it shows aren't aware of the accepted practices established over decades of multi-user messaging -- yes, primarily in IRC. And yes, an "ignore list" is not some unsolved problem on forefront of technology and science, it's a basic feature we have since, I dunno, if not "day one", then perhaps day two?

>  and can impact perception on how conversations are going.

THE HORROR. I can assure you 100.00% of people asking for this feature, are fully aware of the side effects it has, and could not care less about those.

Yes just not show it at all. Yes including any replies. Yes if the admin needs to see everything to moderate, then they don't have the luxury of using ignore. And most certainly we **can** compare TG groups to IRC, because they are both a mechanism for accomplishing the same thing, namely multi-user communication.

> Hard ignoring is a pretty bad thing, imho. The only feasible improvement that could be argued would be disallowing blocked users from replying to you in groups (which I still think is a bit bad - enforcing echo chambers through blocks is bad).

You don't get to decide for other people what is bad or good for them to do in privacy of their own homes. If I don't want to read a certain book, I will not read it, even if you insist otherwise. Just the same with not wanting to read a certain person -- so to say -- or more precisely, any messages they post anywhere, in public or privately. And not having those shown to me if I so desire, is just a basic convenience that the software program in use should be able to provide.

P.S. I do see the point mentioned earlier that ignore needs to be implemented server-side with Telegram, and not separately in every client. But please don't start with the line that "ignore is bad" as a concept, just because you don't need or "don't like" it.

**Comment by blha303** [comment]
If there's a group that want the ignore feature to work as they expect, fork a telegram client and add the feature yourself as you want it, or donate somewhere so they can consider it. Great thing about open source software is anyone can click the Fork button and make a new parallel release with some cool feature, happens on my projects sometimes and it's great. You're not going to convince developers on a free app to add a feature that needs huge upstream support to be done right without providing incentive, and "I think it should work this way" is not an incentive.

That being said, this thread is from 2015 and I'm sorry for contributing to the necro problem.

**Comment by RememberTheAir** [comment]
PSA, for those who don't want to see blocked users' messages, have a look at https://telegre.at/

It shows them in gray. They're not hidden, but it's better than nothing

@romanrm @foxmajik

**Comment by auchri** [comment]
@RememberTheAir Well, is the source code of this fork accessible?

**Comment by RememberTheAir** [comment]
@auchri nope :( I've seen it today for the first time and apparently these are the first releases, it still has some bugs here and there. But apparently it will be:tm:, the guy behind it  said "[it is not yet opensource](https://t.me/newschat/120658)"

**Comment by larslarsen** [comment]
Wow,  the devs are terrible people.  Good to know.

**Comment by addaitrs** [comment]
I 100% still cannot believe that this isn't an option in TG

If a user ignores a user, they'll know that they would be missing a part of future conversation. It's like an email client not having a block sender option in case they'll miss out on an email. Surely let the users decide what they want to ignore?

It's pretty simple concept and nothing that a user wouldn't understand, it's been happening on IRC for decades and many other platforms. TG users aren't without an IQ high enough to understand what ignoring a specific user/bot would achieve!
