### ISSUE TITLE
Stay online feature

### ISSUE THREAD

**Issue by zsavely** [telegramdesktop/tdesktop#1335]
Hello,

On previous versions of Telegram Desktop (really old) the behavior of the online status was simpler, in my opinion. A user was online every time the Telegram window was open (do not misinterpret with 'active'). Yes, that was not always right when you stayed online 'forever'. However, I think there should be a preference that could set the maximum 'active' time. Now it is a few seconds and for me it is quite annoying when I am online but in fact, I became offline because of inactivity.
So, what I am proposing:
* Checkbox for setting a user 'offline' status automatically.
* If checkbox is checked, set a maximum time of inactivity until you become offline.

It would be awesome if you implement this feature.

Thanks.

**Comment by zsavely** [comment]
By the way, this is how it is implemented in [https://telegram.org/dl/osx](Telegram for Mac OS).

**Comment by telegramdesktop** [comment]
@zsavely Well, that's bad :) Currently the synchronisation of the notifications sent to different devices is bound to the online status, e.g. if you stay online from one device (lets say desktop) and not from other device (lets say mobile) the notification is sent to the online device and is delayed for the offline device. In your case if you leave your computer with Telegram window open you'll receive mobile notifications with a huge delay (tens of seconds) because server will think that you're actually online on the desktop.

If the server state of "current active device" was something different than online status set by this device, then perhaps such solutions could be implemented (and you could stay online forever from some devices if you like), but it will require additional tracking of real activity from this device as well (for notifications). But currently there is only one entity -- the online status, it is designed to be _the_same_ as the "active" flag of the current device and so it can't be managed otherwise, because it will break activity-dependent logic in other places.
