### ISSUE TITLE
Crash when user interacts while tdesktop is opening system web browser

### ISSUE THREAD

**Issue by roytam1** [telegramdesktop/tdesktop#1340]
tdesktop-win32 version: 0.9.13 official binary

Zipped dump renamed as docx uploaded.
[Telegram-0.9.13-20151128-112224-3536-1436.dmp.docx](https://github.com/telegramdesktop/tdesktop/files/46226/Telegram-0.9.13-20151128-112224-3536-1436.dmp.docx)

windbg dump:

```
0:000> g
(dd0.59c): Access violation - code c0000005 (!!! second chance !!!)
eax=00000000 ebx=0012d9d4 ecx=06e31e50 edx=00000000 esi=06e31e50 edi=0012d9d4
eip=0060d82b esp=0012d654 ebp=0012d67c iopl=0         nv up ei pl zr na pe nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00000246
Telegram+0x20d82b:
0060d82b ff5068          call    dword ptr [eax+68h]  ds:0023:00000068=????????
0:000> !analyze -v
*******************************************************************************
*                                                                             *
*                        Exception Analysis                                   *
*                                                                             *
*******************************************************************************

*************************************************************************
***                                                                   ***
***                                                                   ***
***    Your debugger is not using the correct symbols                 ***
***                                                                   ***
***    In order for this command to work properly, your symbol path   ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: kernel32!pNlsUserInfo                         ***
***                                                                   ***
*************************************************************************
*************************************************************************
***                                                                   ***
***                                                                   ***
***    Your debugger is not using the correct symbols                 ***
***                                                                   ***
***    In order for this command to work properly, your symbol path   ***
***    must point to .pdb files that have full type information.      ***
***                                                                   ***
***    Certain .pdb files (such as the public OS symbols) do not      ***
***    contain the required information.  Contact the group that      ***
***    provided you with these symbols if you need this command to    ***
***    work.                                                          ***
***                                                                   ***
***    Type referenced: kernel32!pNlsUserInfo                         ***
***                                                                   ***
*************************************************************************

FAULTING_IP: 
Telegram+20d82b
0060d82b ff5068          call    dword ptr [eax+68h]

EXCEPTION_RECORD:  ffffffff -- (.exr 0xffffffffffffffff)
ExceptionAddress: 0060d82b (Telegram+0x0020d82b)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 00000000
   Parameter[1]: 00000068
Attempt to read from address 00000068

FAULTING_THREAD:  0000059c

DEFAULT_BUCKET_ID:  APPLICATION_FAULT

PROCESS_NAME:  Telegram.exe

ERROR_CODE: (NTSTATUS) 0xc0000005 - "0x%08lx"

READ_ADDRESS:  00000068 

BUGCHECK_STR:  ACCESS_VIOLATION

NTGLOBALFLAG:  0

APPLICATION_VERIFIER_FLAGS:  0

LAST_CONTROL_TRANSFER:  from 00aecaa1 to 0060d82b

STACK_TEXT:  
WARNING: Stack unwind information not available. Following frames may be wrong.
0012d67c 00aecaa1 0012d9d4 06e31e50 0012d9d4 Telegram+0x20d82b
0012d6ac 00812932 06e31e50 0012d9d4 06e31e50 Telegram!z_zlibVersion+0x1f8991
0012da30 00b74454 0012dd14 02e723e0 001617e8 Telegram!opus_get_version_string+0x643f2
0012da50 00b92898 00b0aeea 00b0aef8 0012dd14 Telegram!z_zlibVersion+0x280344
0012da54 00b0aeea 00b0aef8 0012dd14 02e723e0 Telegram!z_zlibVersion+0x29e788
0012da58 00b0aef8 0012dd14 02e723e0 0012dd14 Telegram!z_zlibVersion+0x216dda
0012da6c 00b0a7b0 02e723e0 0012dd14 0012dd14 Telegram!z_zlibVersion+0x216de8
0012da94 7c930222 001617e8 7c9301db 0016d514 Telegram!z_zlibVersion+0x2166a0
0012dadc 0085fe53 0016d55c 0012db5c 00000000 ntdll!RtlpAllocateFromHeapLookaside+0x42
0012db18 77d28dd9 00010470 00000215 00000000 Telegram!opus_get_version_string+0xb1913
00d3d5ef 819e75c0 080001ff f78f0f00 0f000001 USER32!RealDefWindowProcW+0x47
00d3d5ef 00000000 080001ff f78f0f00 0f000001 0x819e75c0


FOLLOWUP_IP: 
Telegram+20d82b
0060d82b ff5068          call    dword ptr [eax+68h]

SYMBOL_STACK_INDEX:  0

SYMBOL_NAME:  Telegram+20d82b

FOLLOWUP_NAME:  MachineOwner

MODULE_NAME: Telegram

IMAGE_NAME:  Telegram.exe

DEBUG_FLR_IMAGE_TIMESTAMP:  5654d5bc

STACK_COMMAND:  ~0s ; kb

BUCKET_ID:  ACCESS_VIOLATION_Telegram+20d82b

FAILURE_BUCKET_ID:  Telegram.exe!Unknown_c0000005_APPLICATION_FAULT

Followup: MachineOwner
---------


```

**Comment by mirhl** [comment]
Related to #731 I guess.

**Comment by heejune** [comment]
Although I couldn't see the dump in details due to lack of symbol file, but I see there's some hook module installed. The adjusted call stack shows the crash was related to the windows messaging so that it might have caused it. I recommend remove the third party hook dll and reproduce it.

0:000> .ecxr
eax=00000000 ebx=0012d9d4 ecx=06e31e50 edx=00000000 esi=06e31e50 edi=0012d9d4
eip=0060d82b esp=0012d654 ebp=0012d67c iopl=0         nv up ei pl zr na pe nc
cs=001b  ss=0023  ds=0023  es=0023  fs=003b  gs=0000             efl=00010246
Telegram+0x20d82b:
0060d82b ??              ???
0:000> kb
  *** Stack trace for last set context - .thread/.cxr resets it
ChildEBP RetAddr  Args to Child              
WARNING: Stack unwind information not available. Following frames may be wrong.
0012d650 0012d9d4 06e31e50 0012d9d4 00000078 Telegram+0x20d82b
0012d67c 00aecaa1 0012d9d4 06e31e50 0012d9d4 0x12d9d4
0012d680 0012d9d4 06e31e50 0012d9d4 0012d6e0 Telegram+0x6ecaa1
0012d684 06e31e50 0012d9d4 0012d6e0 0012d9d4 0x12d9d4
0012da94 7c930222 001617e8 7c9301db 0016d514 0x6e31e50
0012db18 77d28dd9 00010470 00000215 00000000 ntdll!RtlpAllocateFromHeapLookaside+0x42
0012db34 77d28d77 00010470 00000215 00000000 user32!RealDefWindowProcW+0x47
0012db7c 00d3e310 00010470 00000215 00000000 user32!DefWindowProcW+0x72
0012dc4c 77d1882a 77d28ea0 00000000 00d3e110 Telegram+0x93e310
0012dcd4 77d18b8c 00890fc7 00010426 00000401 user32!UserCallWinProcCheckWow+0x116
0012dcf8 00bf8156 0012dd70 0012dd80 00000000 user32!NtUserPostMessage+0xc
0012dcfc 0012dd70 0012dd80 00000000 00000000 Telegram+0x7f8156
0012dd00 0012dd80 00000000 00000000 00000000 0x12dd70
0012de0c 77d2b401 022e3a80 0012dedc 7ffdf000 0x12dd80
0012de40 77d2b372 00000000 53452b4e 0012dee0 user32!CallNextHookEx+0x46
0012de5c 77d18734 00010426 00000401 00000000 user32!DispatchHookW+0x31
0012de88 77d18816 00890020 00010426 00000401 user32!InternalCallWinProc+0x28
0012def0 77d189cd 00000000 00890020 00010426 user32!UserCallWinProcCheckWow+0x150
0012df50 77d18a10 0012fbdc 00000000 0012fc18 user32!DispatchMessageWorker+0x306
0012df60 0088fb15 0012fbdc 5345090a 0024c100 user32!DispatchMessageW+0xf
0012fc84 7c93005d 00000028 00000000 00150000 Telegram+0x48fb15
0012fdc0 7c92dc1a 7c92cfea 7c80a0e9 00000060 ntdll!RtlFreeHeap+0x647
0012fdd0 0012ff40 00f2e8c8 00000060 00f956b7 ntdll!NtSetEvent+0xc
0012fddc 00f956b7 01f8058c 010dd070 0024c100 0x12ff40
0012fde0 01f8058c 010dd070 0024c100 00f957a7 Telegram+0xb956b7
0012fde4 010dd070 0024c100 00f957a7 0012ff34 Telegram+0x1b8058c
0012fde8 0024c100 00f957a7 0012ff34 010375b8 Telegram+0xcdd070
0012fdec 00f957a7 0012ff34 010375b8 00000000 0x24c100
0012fdf0 0012ff34 010375b8 00000000 0012ff40 Telegram+0xb957a7
0012fdf4 010375b8 00000000 0012ff40 0066a379 0x12ff34
0012ff34 0102236b 00000014 0015e358 00f5e5d4 Telegram+0xc375b8
0012ffb0 00f34ad0 528afe32 00000000 0012fff0 Telegram+0xc2236b
0012ffe0 7c839b47 7c816040 00000000 00000000 Telegram+0xb34ad0
0012ffe4 7c81603f 00000000 00000000 00000000 kernel32!_SEH_epilog+0x18
0012ffe8 00000000 00000000 00000000 00f2f177 kernel32!BaseProcessStart+0x2b

0:000> lmvm UnlockerHook
start    end        module name
02b50000 02b55000   UnlockerHook   (deferred)             
    Image path: C:\Program Files\Unlocker\UnlockerHook.dll
    Image name: UnlockerHook.dll
    Timestamp:        Mon Jul 05 06:32:37 2010 (4C30FDF5)
    CheckSum:         00000000
    ImageSize:        00005000
    File version:     0.0.0.0
    Product version:  0.0.0.0
    File flags:       0 (Mask 0)
    File OS:          0 Unknown Base
    File type:        0.0 Unknown
    File date:        00000000.00000000
    Translations:     0000.04b0 0000.04e4 0409.04b0 0409.04e4

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by roytam1** [comment]
> this bug is still valid?

maybe not now.
