### ISSUE TITLE
Channel Link

### ISSUE THREAD

**Issue by Jav4dR** [telegramdesktop/tdesktop#1342]
hi Guys

Please Remove Private Channel Link only use Public Link for Best Manage Channels.

thanks so mach

**Comment by auchri** [comment]
what?

**Comment by Jav4dR** [comment]
Delete feature Private Link in Create or edit channel.

only Public Link for channel Because This is idea for Better  management abuse channel.

**Comment by DaFri-Nochiterov** [comment]
Nobody can get administrative permission on channel when join by link. 
If you don't want to anybody join in your channel - not share link to channel.
Generation of a link (but for what?) will take a lot of time. And you can in anytime revoke link, remove people, who join in your channel. 

Remove this feature because you don't like this - bad idea. I use this feature, and no one I, think.
