### ISSUE TITLE
Change icon in Windows 10 tray

### ISSUE THREAD

**Issue by theus** [telegramdesktop/tdesktop#1353]
Windows 10 has a beautiful icons patterns. They follow the same style. But, the general apps don't follow. 

![image](https://cloud.githubusercontent.com/assets/61322/11531169/a18cbb08-98d9-11e5-8aeb-7094a9e6c140.png)

**Comment by f242** [comment]
better able to switch between icons, i have two portaple apps with same icons and it's terrible!

**Comment by TiagoDanin** [comment]
+1 :+1:  Nice, i like the idea

**Comment by JuanPotato** [comment]
@f242 I agree with this, always allow the option

**Comment by DaFri-Nochiterov** [comment]
:+1: +1

**Comment by M132** [comment]
I agree, this issue affects Linux as well. Telegram is one of these apps that completely break consistent look of GNOME's and Unity's top bar by adding it's blue icon. IMHO it should only have colored new messages indicator, like Skype below.

![image](https://cloud.githubusercontent.com/assets/5361441/12958023/c1578b56-d02f-11e5-9989-10e0dca34803.png)

**Comment by sergioad** [comment]
Indeed, a symbolic icon (wich can become light or dark depending to the panel's color) could be amazing for Win10 Mac and Linux

**Comment by qprqpr** [comment]
+1

**Comment by Deilan** [comment]
Agree with @f242: it would be great to have a capability to assign an arbitrary icon. And this is actual not only for Windows 10, but for the previous versions also.

**Comment by stek29** [comment]
@sergioad macOS has symbolic icon already :)

**Comment by stek29** [comment]
#1199 should be changed to include windows 10 too

**Comment by Aokromes** [comment]
Maybe better #1908 ?

**Comment by Feichtmeier** [comment]
In linux we still do not have that monochrome icon
![bildschirmfoto von 2018-02-19 16-31-23](https://user-images.githubusercontent.com/15329494/36385252-57c8ef40-1592-11e8-9304-794011a54e90.png)

**Comment by Rnksts** [comment]
Since #1908 only offered a solution to Linux users, please consider re-opening this issue (@Aokromes). It would be nice to have the ability to use a custom icon or at least have the option to choose one that matches the default Windows style.

![05 00 22_k2wDmdH42B](https://user-images.githubusercontent.com/20311303/81035599-a1791a00-8e69-11ea-9e0d-dec9e3c6b3d7.png)

The Windows 10 May 2019 Update introduced a light theme, users of that theme might also be interested in having a more fitting icon.

![05 00 20_BS7cdWa2fV](https://user-images.githubusercontent.com/20311303/81035375-b0130180-8e68-11ea-92e4-10b08644aa34.png)
