### ISSUE TITLE
Some GIFs are displayed incorrectly

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1362]
![qqwe](https://cloud.githubusercontent.com/assets/10401817/11590271/9a8cd5a6-9ac1-11e5-8e7c-4e620477ecff.png)  ![qwe](https://cloud.githubusercontent.com/assets/10401817/11590273/9c790876-9ac1-11e5-8560-652bd4273b62.png) 

[Original GIF displayed](https://i.kinja-img.com/gawker-media/image/upload/b9yfge4uvdy2zv7rysr0.gif) fine in "Photos" and Chrome.

**Comment by telegramdesktop** [comment]
Thanks for your report! Looks like bad image reading somewhere in Qt :( I'll try to look into that on the next week.

**Comment by DaFri-Nochiterov** [comment]
Again this gif. But now it played incorrectly.

How original gif played: `*glasses fall* *deal with it text* *pause - 4sec* *repeat*`
How it's played in TDesktop: `*glasses fall* *deal with it text* *repeat* *pause - 3sec* *pause - 1sec*`

Open new issue or re-open this?

**Comment by auchri** [comment]
I don't know, it's the same in the android app ¯\_(ツ)_/¯

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov when _you_ send this gif it is played like a .gif in Telegram Desktop and should be displayed correctly. But if you send it from other device and receive it in Telegram Desktop (or you delete the initial file and re-download it from the cloud) then it is played differently (not correct, but the same on all the platforms now), because it is converted on the server from .gif to .mp4 now (and the conversion is done not very strict), so Telegram Desktop and all other apps play it that way. I can fix only the issues that are only about Telegram Desktop behaviour, not the server-side, sorry :(

**Comment by telegramdesktop** [comment]
@DaFri-Nochiterov I've fixed the issue when playing this gif when it was currently sent, in 0.9.18 it should play correctly. But the server converts it to .mp4 and it is received already in .mp4 (or downloaded from cloud if you relogin or simply delete or rename the original file), so it will be played not correctly -- like it is in .mp4 :(

**Comment by DaFri-Nochiterov** [comment]
@telegramdesktop
Anyway if I send this file from GIF panel it's played not correctly.

I think this GIF have some magic to play so and anyone should Deal With It ![image](https://cloud.githubusercontent.com/assets/10401817/12119465/fbfe8dfc-b399-11e5-9cf0-501fa9819826.png)

Thanks :)
