### ISSUE TITLE
Build instructions for qmake

### ISSUE THREAD

**Issue by Profpatsch** [telegramdesktop/tdesktop#1373]
Since all IDEs depend on qmake invocations, the obvious way to build with only qmake is missing from the build descriptions.

Explanations on which buttons to click don’t make mature developers happy. Even less so people who want to package the program.

**Comment by telegramdesktop** [comment]
@Profpatsch Thanks for your feedback! Unfortunately simplifying the build process and bringing it closer to the industry standards are not current priorities, too much work to be done with the app itself. I hope to improve them some day so that building of that project by a side developer from scratch will be much less painfull, but I can't give you any estimates and to be honest this won't be very soon.

**Comment by Profpatsch** [comment]
You have to be aware that this *will* hinder progress of the project, because this way

1) You won’t get packaged (which is how you get users)
2) You won’t get contributors (which is how you multiply the speed of development)

**Comment by auchri** [comment]
> You won’t get contributors

Why? This way it's easier to compile tdesktop
