### ISSUE TITLE
Cannot connect through http proxy with NTLM authentication

### ISSUE THREAD

**Issue by KindDragon** [telegramdesktop/tdesktop#1410]
Telegram cannot connect through http proxy with Microsoft NTLM authentication

**Comment by JPvRiel** [comment]
Agree, NTLM auth would be helpful, but is in fact mostly depreciated and many (properly secured) corporate proxies might require Kerberos.

Workarounds on Linux is creating a localhost peer proxy (because very many Linux apps can't do more than simple HTTP basic auth):
- If proxy supports NTLMv2, something like CNTLM acts as a proxy on your localhost, and then authenticates with the upstream proxy that requires windows authentication.
- If strictly Kerberos, this is even more challenging and perhaps Squid can help.

So far, in my experience, only browsers like Firefox and Chrome seem to handle NTLM proxy auth. All other Linux apps I've used don't.

**Comment by TollKha** [comment]
Telegram becomes useless in the corporate environment due to lack of Kerberos support. It's really sad. Kerberos is widely used and very few apps support it.

I can't use Telegram Windows client at work. That takes Skype several extra years of life, that disappoints me.

**Comment by john-preston** [comment]
@TollKha How can this be fixed? Maybe some links with ways to allow a Qt application to work there?

**Comment by TollKha** [comment]
Don't know if there is library/Qt feature that allows handling all proxies type including Kerberos.

I've found the example here: https://github.com/krb5/krb5/blob/master/src/appl/simple/client/sim_client.c .

And according to SO article here https://stackoverflow.com/questions/14706851/ntlmv2-authentication-in-qt , Qt5 can handle NTLMv2, at least. But we need to set up credentials. So there should be credential fields in Telegram connection settings.

**Comment by TollKha** [comment]
I've updated to 1.1.19 now and see username and pass fields. Unfortunately, I still can't connect through proxy.
