### ISSUE TITLE
Wrong command sent with bots in a group

### ISSUE THREAD

**Issue by matteocontrini** [telegramdesktop/tdesktop#1433]
When you add a bot in a group, and the bot sends you a message which contains a command like `/command`, this command gets highlighted. But when tapping the command, the client sends a message that looks like `/command@NameOfTheBot`, which is unexpected.

It should be `@NameOfTheBot /command` or just `/command`.

Thanks

**Comment by telegramdesktop** [comment]
@matteocontrini Currently commands for bots work that way on all client apps and bot developers are waiting a command message starting with slash, like /command or /command@bot, just /command is not good to use in groups, because there could be more than one bot.

**Comment by matteocontrini** [comment]
Ah, I see. But the Android client is sending just the command with no mention. And in the bots documentation there's no mention of that format...

**Comment by qgates** [comment]
@telegramdesktop behaviour for bot commands is inconsistent with the Android Telegram app, so this should be addressed. For consistency, tdesktop should provide the same UX when it comes to the display and handling of bot commands:

1. When only 1 bot is present in a group, the command list popup (after typing /) does not show @botname. If the command is selected, the command is pasted to the group without @botname.
2. When >1 bot is present in the group, the command list popup does not show @botname. Different bot commands in the popup are differentiated by the bot icon. If a command is selected, however, command@botname is pasted into the group.

Perhaps to be absolutely clear (at the risk of a slight inconsistency with Android), tdesktop can show command@botname in the command list popup when >1 bots are present in the group. Otherwise show (and paste) commands without @botname.

**Comment by stek29** [comment]
@qgates What a great idea! Lets check out whole chat participants list, then check all of them to count bots.
