### ISSUE TITLE
[fix] DONT RENAME SENT FILES

### ISSUE THREAD

**Issue by Schriftx** [telegramdesktop/tdesktop#1466]
Files downloaded from the chat on mobile are renamed. It's really annoying.

**Comment by auchri** [comment]
The android app renames the files.

**Comment by Schriftx** [comment]
Yeah, that's my problem.

**Comment by auchri** [comment]
Yeah, and that's not an issue of Telegram **Desktop**

**Comment by ttt111ttt** [comment]
it's more than a year passed and problem remaining :( this is terrible when saved file called "4_5888736888252006628.mp4", stupid Telegram :(
You lazy developers, please fix this, it's terribly annoying and piss me every time!!! SHAME ON YOU!!!

**Comment by Schriftx** [comment]
Although its the wrong thread for real, but u could use Plus Messenger on mobile, it has an option to keep original filename.

**Comment by ttt111ttt** [comment]
I use Telegram for work a lot and I can't use untrusted messengers.
Also I prefer to have program updated.

**Comment by john-preston** [comment]
@ttt111ttt This has nothing to do with Telegram Desktop, I'm sorry.

**Comment by stek29** [comment]
@ttt111ttt You can report this issue on Twitter or via in-app support.

**Comment by ttt111ttt** [comment]
It problem with renamed files is on Telegram Desktop v 1.1.7 !!! I am on Windows 7 !!!

**Comment by stek29** [comment]
@ttt111ttt Could you please explain it a bit more? From where did you get that file? Where was it saved?

**Comment by ttt111ttt** [comment]
Sent by my friend from Telegram Desktop. Saved on my computer. No matter, where I use Telegram, on Desktop or mobile (Android), files got renamed. Don't be stupid, you just install Telegram and send any file (mpg, avi, jpg, doesn't matter). Your questions are ridiculous, this thread is more, than a year old, everyone know this problem, just fix it, damn it.

**Comment by stek29** [comment]
@ttt111ttt Just damn it fork it and fix it on your own if you're stupid and can't explain why your TDesktop installation has this ridiculous behaviour.

**Comment by ttt111ttt** [comment]
FUCK YOU, IDIOTS. THIS IS WHY IT IS NOT WORKING! BECAUSE YOU AR MORONS AND TALKING RUDE, INSTEAD OF FIXING THINGS. FUCK YOU!

**Comment by john-preston** [comment]
@ttt111ttt Wow, wow, everyone.

If someone can't talk without offending each other you just go by and say nothing. This is the last warning.

About the issue: if it happens when you send files not ONLY from or to tdesktop, but the same way in web version or mobile apps (as you write "no matter where - on desktop or mobile") this almost certainly means that files are renamed by the server when they're transferred, not be the apps.

If this is the case - there is nothing I can do and this issue doesn't belong here, because they're renamed no matter what client app you write and you can't fix it in Telegram Desktop code.

This repository and discussions are only about things you can fix in Telegram Desktop code, because it is the only code I have access to :)
