### ISSUE TITLE
Debian stable - Wheezy support?

### ISSUE THREAD

**Issue by dmooray** [telegramdesktop/tdesktop#147]
Right now Telegram Desktop does not work on Debian stable. Trying to run the 64bit build on an updated Debian stable x86_64 machine and I'm getting

./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found (required by ./Telegram)

./Telegram: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./Telegram)

I'd love to help you fix this, let me know what details you need.

I'll try to build it from source too.

**Comment by philbert** [comment]
seems like libunity-dev is required for building it now?
unfortunatly its not available in debian repos or is it possible to disable it?

**Comment by madmuffin1** [comment]
I quickly took a look into it, and it seems the only reference to libunity is in `tdesktop/Telegram/SourceFiles/pspecific_linux.cpp`. Try commenting the lines 43, 168-175, 337, 437-448, 466, 594-601 and 802-812 out. I havent tested it myself, but this should do the trick.

**Comment by philbert** [comment]
worked, removed all unity related lines from pspecific_linux.cpp

**Comment by benbenolson** [comment]
The line numbers referenced above are no longer relevant (obviously), so anyone in the future that wants to remove the dependency on Unity can simply go through pspecific_linux.cpp, search for any instances of "Unity", and comment out each of those lines. I kept the "useUnityCount", etc., variables, but when it checks them ("if(useUnityCount)"), it does nothing because all of that code is commented out.
