### ISSUE TITLE
Crash on Telegram Mac OS for one specific contact

### ISSUE THREAD

**Issue by gozzilli** [telegramdesktop/tdesktop#1496]
Hi,

On my Telegram for Mac, every time I click on a specific contact -- and only on that contact -- the app crashes. 
Version 0.9.18, Mac OS 10.11 El Capitan. Let me know if you need any more info.

**Comment by telegramdesktop** [comment]
@gozzilli I need the crash log (Apple suggests to send it, but you can copy it to text file and upload it here).

**Comment by Diti** [comment]
I have the very same problem. It happened after trying to send multiple images in quick succession to a contact, by dragging and dropping them, and I cancelled one of them and the application keeps crashing since.

Upon trying to talk to my contact again, Telegram quickly attempts to show the conversation & images, but it crashes a few milliseconds later. I think it attempts to load a non-existing image, and crashes because the reference doesn’t exist any more (after all, I cancelled an image upload at the moment the crash occurred).

Crash log: [`telegram-contact-crash.txt`](https://github.com/telegramdesktop/tdesktop/files/312410/telegram-contact-crash.txt)

**Comment by john-preston** [comment]
@Diti This is a crash report for another OS X application. You can try Telegram Desktop from https://desktop.telegram.org :)

**Comment by Diti** [comment]
@john-preston: Uh-oh, sorry! ^^’ All this time, I have been using another Telegram app without even noticing it! No crash on Telegram Desktop indeed. Sorry!

**Comment by stek29** [comment]
@gozzilli is the issue still valid?

**Comment by gozzilli** [comment]
No, I don't see it any more.

**Comment by stek29** [comment]
Then you can close it
