### ISSUE TITLE
I can not paste unicode symbol as symbol

### ISSUE THREAD

**Issue by alltiptop** [telegramdesktop/tdesktop#1525]
Telegram auto convert unicode symbol to emoji image but i want paste only black text symbol (eg ☣). Not smile, emoji and other image. I just wont a TEXT SYMBOL.
May be make a option for change "old version" as <symbol_name> (as old messangers, e.g. icq) to Unicode symbol?

**Comment by telegramdesktop** [comment]
@alltiptop Emoji are (at least should be) displayed like iOS and OS X displays them. This means, that this symbol is displayed like this — it is just a font for those Unicode symbols, it is colored, not black. Your example looks like emoji on the iPhone.

**Comment by alltiptop** [comment]
If my system will display unicode as emoji, then telegram must display emoji. I don't use colorize font width emoji and telegram not must use not system fonts. I can to paste symbol as other system. Not apple choise. Not microsoft, google and other. Only my system, only my regulations.

And on Mac OS this option can be disallow. I doubt what telegram does the same.

**Comment by telegramdesktop** [comment]
@alltiptop The idea is to display it as "the same" as possible on all the platforms / devices / systems, so when you send something (symbols, emoji, whatever) you understand what will the recipient see.

**Comment by Tynach** [comment]
No idea if this will be seen, or even post properly (since this is closed). However, I want to add that several textual symbols are replaced by emojis, and thus do not render very well - and especially do not render the way they would on OS X or iOS.

These symbols are things like '™', '©', '®', and so on. Using an actual font, you will get a crisp, smooth rendering of the glyph. On Telegram, these are replaced by a somewhat blurry and often incorrectly placed image file (e.g. the '™' glyph is supposed to be slightly 'raised' and smaller from the rest of the text).

The symbols look a bit better on phones (with the high DPI displays), but they look horribly out of place on desktops. Maybe they look better on OS X due to OS X's default font rendering, but I'm willing to bet they don't by much - especially if the surrounding text uses subpixel antialiasing, while these emojis do not.
