### ISSUE TITLE
Strange text after cancel paste picture

### ISSUE THREAD

**Issue by DaFri-Nochiterov** [telegramdesktop/tdesktop#1582]
1. Copy picture in browser
2. Press CTRL+V
3. Click "Cancel"
4. We see something like this in message box:
```

%00C%00l%00e%00a%00r

```

(it's not always works)

**Comment by telegramdesktop** [comment]
Well, currently the logic is following: when something is pasted, that has mime type "image" in it, we suggest sending this image, if we cancel image sending, we paste mime type "text" from the same paste event to the input field. That was done because some data is copied to clipboard both in text and image format and we don't know which one the user wants us to handle.

It seems that some browsers along with the image place some strange text in the clipboard (but I've never seen that behaviour myself). Or there is some bug in my implementation of the suggested logic :)

**Comment by DaFri-Nochiterov** [comment]
Oh, OK.
Chrome copies something like `%01o...`.
Safari copies a url to the picture file.

If it's not a bug, I will close this issue =)
