### ISSUE TITLE
Error when viewing images saved from Telegram

### ISSUE THREAD

**Issue by MystBunny** [telegramdesktop/tdesktop#16072]
Whenever I save an image sent to me through Telegram, and later try to view it, I get this error
https://cp.sync.com/dl/a9d514eb0#ss6zvgb8-v38yyi6v-aavdig5w-2xewayeq

Only images from Telegram have been giving me this error, starting from a month to two months ago.

Running Windows 8.1, Telegram desktop version 2.7.1

**Comment by shekelboi** [comment]
If I understand it correctly, this occurs when you manually save an image (right click > save image as...)?

You can't open the image even when Telegram is close and you're using another picture browser than the default Windows app for it?

**Comment by MystBunny** [comment]
Yes when I save the image and later try to view it.

"photos" seems to open it, but "windows photo viewer", the default app, does not. It also seems so far that if someone sends me an image without compression, I can open it, just when they use the send photos "in a quick way" is when I have the issue.

**Comment by shekelboi** [comment]
Apparently, the bug is caused by the [ICC profile metadata of the image](https://superuser.com/a/1534245/1298068). So the issue seems to be on the side of Windows Photo Viewer. Telegram could consider stripping the metadata but depending on how common the issue is, maybe it's better to leave as it is, since the bug is not on their side.

**Comment by MystBunny** [comment]
I would prefer stripping the metadata of course. Plus it's only a recent issue.

**Comment by MystBunny** [comment]
bump?
