### ISSUE TITLE
Open Location in default Maps Application on Windows 10

### ISSUE THREAD

**Issue by NateMS** [telegramdesktop/tdesktop#1612]
It would be great for locations to open in the installed applocation instead opening google.com/maps in the browser.

**Comment by Brawl345** [comment]
aren't the locations just links to Google Maps? E.g. https://maps.google.com/maps?q=40.7128,-74.006&ll=40.7128,-74.006&z=17

**Comment by NateMS** [comment]
hmm yeah seems to be the case, though with the longitude and latitude in the link it should be possible to open the links in an application and pass the location

**Comment by telegramdesktop** [comment]
@NateMS A link to the info about launching that default maps app will be really appreciated.

**Comment by NateMS** [comment]
I found this: https://msdn.microsoft.com/en-us/library/windows/apps/mt228341.aspx

**Comment by telegramdesktop** [comment]
@NateMS Thanks, I'll look into that.

**Comment by NateMS** [comment]
If I read the documentation correctly, the link should lool like this:

bingmaps:?cp=40.726966~-74.006076&collection=point.40.726966_-74.006076_My%20Location

**Comment by TiagoDanin** [comment]
+1 :+1:

**Comment by auchri** [comment]
Added :)

**Comment by FireNero** [comment]
Is it possible to make this feature optional? Because I prefer to open google maps in a browser instead of Windows app.

**Comment by john-preston** [comment]
@FireNero You can right click and open the link.

**Comment by FireNero** [comment]
@john-preston Yes but I need to right click, copy a link, open browser and paste link instead of single left click. 
Anyway, if it isn't possible it isn't a big problem.

**Comment by gabrielsoldani** [comment]
+1 to make this optional. Windows Maps is very inconvenient.

**Comment by karai17** [comment]
i just ran into this feature and am very unhappy with this. when i click a Google map link, i expect to go to Google maps. hijacking this and forcing us into another service is absolutely unacceptable. if i wanted to use the Windows app, i would use Bing maps. i explicitly select Google and do not appreciate my choices being hijacked.

please disable this feature and let Google maps links go to Google maps. i suspect if Google got wind of this, there would be some legal issues that no one wants to deal with.

**Comment by john-preston** [comment]
@karai17 What do you mean by select google maps explicitly? Maps application should be used only for location links — not text google maps links, but the message location attachments. They do not have any preferred service for maps, because each platform uses its own system built in maps system (apple maps for iOS, google maps for Android, bing maps for Windows Phone).

**Comment by karai17** [comment]
i was linked a Google map and when i click it, it opens in Windows maps. if
i right clip to copy the link, it sends me correctly to Google maps.

**Comment by john-preston** [comment]
@karai17 Was it a text link or a small image of a google maps link?

**Comment by karai17** [comment]
the message itself is a map without text but is clearly marked as Google.

**Comment by john-preston** [comment]
@karai17 Well, that is a location attachment, not a google maps link.

It has only coordintates in it, two numbers. Each Telegram application uses what it likes to create those attachments (apple maps on iOS, google maps on Android, bing maps on Windows Phone, no way to send them in Telegram Desktop) and each application uses what it likes to display those attachments (apple maps on iOS, google maps on Android, bing maps on Windows Phone, google maps image on Telegram Desktop).

Also TDesktop adds a way to copy a google maps link with such coordinates (though, it is _not_ what a user sent you — this link is generated by TDesktop client side from the two coordinates someone have sent). Also TDesktop allows to open that coordinates in the OS-specific app (apple maps in macOS and microsoft maps in Windows) and opens the google maps link if there is no suitable app.

So there is no "hijacking and forcing into another service" in any way, as well as there is no "selecting Google and hijacking your choices".

**Comment by karai17** [comment]
ah! that makes sense, then. thank you for taking the time to explain this
to me, i was mistaken. sorry if i came off as harsh.

On Jan 10, 2017 6:47 AM, "John Preston" <notifications@github.com> wrote:

@karai17 <https://github.com/karai17> Well, that is a location attachment,
not a google maps link.

It has only coordintates in it, two numbers. Each Telegram application uses
what it likes to create those attachments (apple maps on iOS, google maps
on Android, bing maps on Windows Phone, no way to send them in Telegram
Desktop) and each application uses what it likes to display those
attachments (apple maps on iOS, google maps on Android, bing maps on
Windows Phone, google maps image on Telegram Desktop).

Also TDesktop adds a way to copy a google maps link with such coordinates
(though, it is *not* what a user sent you — this link is generated by
TDesktop client side from the two coordinates someone have sent). Also
TDesktop allows to open that coordinates in the OS-specific app (apple maps
in macOS and microsoft maps in Windows) and opens the google maps link if
there is no suitable app.

So there is no "hijacking and forcing into another service" in any way, as
well as there is no "selecting Google and hijacking your choices".

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/telegramdesktop/tdesktop/issues/1612#issuecomment-271544118>,
or mute the thread

**Comment by FireNero** [comment]
@john-preston thanks for the explanation. I guess many people don't like this behavior just because map preview is shown with Google logo. And when it is opened by Microsoft maps app it is really confusing without knowledge how it is working internally.

**Comment by karai17** [comment]
yeah, that exactly. it shows Google maps, it copies Google maps link, but
it opens in Bing maps. it definitely feels like a service hijack and i at
first suspected Microsoft of foul play before stumbling on this issue.

On Jan 10, 2017 10:53 AM, "Mykhailo Matviiv" <notifications@github.com>
wrote:

@john-preston <https://github.com/john-preston> thanks for the explanation.
I guess many people don't like this behavior just because map preview is
shown with Google logo. And when it is opened by Microsoft maps app it is
really confusing without knowledge how it is working internally.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/telegramdesktop/tdesktop/issues/1612#issuecomment-271595451>,
or mute the thread

**Comment by NateMS** [comment]
hmm yeah I guess if google released a google maps app or if MS somehow allowed one to set the maps website as default maps app, everyone would be happy.

But I guess in general it makes sense to use the system APIs for applications. (like he mentioned opening the respective app on each system)

**Comment by T3rminat0r** [comment]
Strongly agree to make this a setting or generally to allow the user to chose between opening the maps link directly or using the system-maps-app. (I strongly dislike that maps APP from MS, as it doesn't have any of my own bookmarks etc. etc.)

**Comment by beikeland** [comment]
Having looked at the various protocol handlers available to apps, it seems that changing the current url on the windows client to ms-drive-to: or ms-walk-to: would allow us to use both the native/default map app, and 3rd part map apps supporting google maps.

Using bingmaps: is forcing us to use the default windows map app as no other map apps seems to support this url handler, so its effectively more a lock-in than an protocol.

I would still much prefer to have the option to choose to have the location url to be a default http link for google maps on windows.

I tried adding a URLAssociations registry entry for bingmaps to chrome, and a navigator.registerProtocolHandler inside chrome; but I was forced to prefix bingmaps with web+ as its not whitelisted for use; so that failed. I guess I could try to write a custom .exe to accept the bingmaps: string and launch chrome with a gmaps url, but it seems like an extremely hard way to solve something that should be possible to fix in the default programs settings of windows - if a different protocol was used.

**Comment by khabraken** [comment]
I agree that bingmaps is a poor choice of protocol. On Windows 10, it doesnt seem possible to remove the app (at least not for the average user), nor is it possible to remap the protocol handler to a different app (as @beikeland describes). I hacked around in the registry and managed to remove the handler from the list in Control Panel, but somehow the OS still manages to start the Maps app.

It seems like the best option would be to switch to the geo protocol, which is [standardised](http://tools.ietf.org/html/rfc5870), and also [used on Android](https://developer.android.com/guide/appendix/g-app-intents.html) for quite some time.
geo is also a whitelisted protocol that websites can [register as handlers for via the browser](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler) (testable [here](http://rodrigopolo.com/tests/handler/?uri=%s)). This means users can have full control over it via their OS/browser (in contrast to bingmaps), and until such time as apps/websites register as handlers for it, the behaviour can fall back to opening a google maps URL (as it does currently, eg on older versions of Windows).

Otherwise, an "Open locations with Bing Maps" setting needs to be added in the Windows version, that users can opt out of (which will change the behaviour back to Open google maps URL). But this seems like a lot more development than simply changing the protocol (and still doesnt give users full flexibility).

**Comment by KoalaBear84** [comment]
This really sucks, this ticket made opening complete locations useless. It does open Bing/Windows Maps, but it shows the world is an ocean, which is not true.

**Comment by giou** [comment]
open this

**Comment by KoalaBear84** [comment]
That would be a good idea as it doesn't work at all

**Comment by internetcoffeephone** [comment]
This is still broken. Related to https://github.com/telegramdesktop/tdesktop/issues/3571, if neither bing maps nor the windows store app are installed, clicking on a map in telegram opens a useless dialog box with a checkbox that does nothing, and with an OK button that is permanently grayed out.

![bingmaps0](https://user-images.githubusercontent.com/5096835/54210903-a8fc9780-44e0-11e9-8176-0f120a851199.png)
![bingmaps1](https://user-images.githubusercontent.com/5096835/54210906-a9952e00-44e0-11e9-8037-6be8b0ff7993.png)

**Comment by bwims** [comment]
Suggestion:  How about right-click "Open link IN BROWSER" ?
