### ISSUE TITLE
[Feature Request] Account access by phone number and E-mail

### ISSUE THREAD

**Issue by VaGNaroK** [telegramdesktop/tdesktop#16369]
I have two accounts on the telegram, one with a phone number and another account on another number ... I recently had my cell phone stolen on one of the numbers and I can't access my second account because I no longer have that number, it's frustrating I losing access to an account with several important contacts and files because I no longer have the number to receive the sms message and have access to my account. 

 I would like in the future to add a method in addition to registering the number, registering the user's email, in case he lost the number to gain access to the account by email and thus be able to register another number.  Can you imagine how many users have not lost their accounts going through the same problems as me?  Please, we need this a lot.

 PS: if anyone knows how to recover an account without the phone number I would be very grateful if they helped me.

**Comment by RememberTheAir** [comment]
This is out of the scope of the desktop app, but you can upvote [this entry](https://bugs.telegram.org/c/858) on the official "bugs & suggestions" platform

> PS: if anyone knows how to recover an account without the phone number I would be very grateful if they helped me.

Unfortunately, no. You have to ask the phone number provider the access to your old phone number. If you can't access a phone number anymore and have a Telegram account registered using it, you should login to a backup device (another phone, tablet, or desktop os) so that session will receive the verification code in case you lose your main mobile phone
