### ISSUE TITLE
[Feature Request] Add a system theme that uses the current operating system colors

### ISSUE THREAD

**Issue by l0drex** [telegramdesktop/tdesktop#16414]
### Is your feature request related to a problem?
Telegrams theme support is great, but the problem with that is that it often does not look really native.

### Describe the solution you'd like
A system theme could be a solution. It would need to be dynamic, so that windows accent colors can be changed depending on the one selected and Linux themes would also work.

### Describe alternatives you've considered
There could also be something like official OS themes, like a Windows theme, macOS etc. However, that would mean that e.g. the windows accent color has to be guessed by using the default one. An official Linux theme would not be possible at all.

**Comment by ilya-fedin** [comment]
I don't think it worth the effort. That would need a lot, a lot of code to get style of controls on all systems and Linux toolkits and apply them to Telegram widgets somehow. Not to say that Linux has a lot of toolkits and Telegram would need to link to all of them and use their widgets, this seems something like impossible to me. GTK uses CSS, Qt uses C++ for themes (so precompiled static binary from official website can't use system Qt themes by any way since they're built with different Qt versions), other toolkits like EFL also using something their own.

It is better to have custom unified look'n'feel rather than trying to integrate with each system or that would be a developing nightmare...

**Comment by l0drex** [comment]
It came to my mind since Firefox and Chromium offer that functionality.
Forgive my ignorance, I thought this would be as easy as not using a custom theme and let Qt pick the default color palette instead (I'm only talking about colors, not actual style of buttons and sliders etc.).

**Comment by l0drex** [comment]
How about the alternative: Official themes for Windows and mac that would ship with the application and mimic the style of these systems? They would show up as "System" next to "Classic", "Day", etc.

**Comment by ilya-fedin** [comment]
This is still a lot of work, I imagine this can appear only as something implemented by interested people in a form of PR
