### ISSUE TITLE
Own messages are not aligned to the right in x64 client

### ISSUE THREAD

**Issue by azzimuth** [telegramdesktop/tdesktop#16436]
### Steps to reproduce
1. Install version 2.7.4 x64. 
2. Open any chat
3. Check your own messages

### Expected behaviour
The own chat message bubbles should be aligned to the right

### Actual behaviour
The own chat message bubbles are not aligned to the right as in the mobile app or x86 client.

### Configuration
**Operating system:**
Edition	Windows 10 Pro
Version	20H2
Installed on	‎2021-‎06-‎02
OS build	19042.1052
Serial number	5CD120T1M3
Experience	Windows Feature Experience Pack 120.2212.2020.0

**Version of Telegram Desktop:**
2.7.4 x64
**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
Default

![image](https://user-images.githubusercontent.com/1640148/121890058-38c1c980-cd1a-11eb-9243-42e3182352bb.png)
![image](https://user-images.githubusercontent.com/1640148/121890268-6f97df80-cd1a-11eb-8709-37fd5eba047a.png)

**Comment by Aokromes** [comment]
not a bug, disable adaptative layout.

**Comment by john-preston** [comment]
@azzimuth In case the window is large enough all messages are displayed in a single column, so that it is easier to read them one after another without having to jump to the left and to the right side of the screen.

If you like more the default way (used for small window sizes) even for large window sizes, you can go to Main Menu > Settings > Chat Settings and uncheck "Adaptive layout for wide screens" checkbox.

**Comment by azzimuth** [comment]
@Aokromes, @john-preston, thanks!
