### ISSUE TITLE
[Feature Request] Support Do Not Disturb on Ubuntu/Gnome

### ISSUE THREAD

**Issue by karanssh** [telegramdesktop/tdesktop#16473]
### Is your feature request related to a problem?
In ubuntu, when we turn on DND, we still get notification previews and notification sounds 

### Describe the solution you'd like
Expected behaviour: Telegram Desktop should respect DND option

### Describe alternatives you've considered
Alternative: Windows DND is supported, use that instead 
https://github.com/telegramdesktop/tdesktop/commit/2730ab1596b897c921e99d33242626f5aa2c01eb - relevant commit

**Comment by ilya-fedin** [comment]
There's none standardized public API to check DnD mode on Linux. There was an attempt to standardize it by a KDE developer, but GNOME developers prevented that attempt since they thing applications shouldn't be able to query that setting. That being said, you won't get support until GNOME developers change their mind.

tdesktop still uses that API (basically querying `Inhibited` property on `org.freedesktop.Notifications` interface), so you can switch to KDE and experience working DnD mode.
