### ISSUE TITLE
[Feature Request] Update the Microsoft Store version more frequently (always a lot of versions behind)

### ISSUE THREAD

**Issue by areiased** [telegramdesktop/tdesktop#16492]
### Is your feature request related to a problem?
Not exactly.
While this by itself does not represent any problem with the app itself, it makes the Microsoft Store users feel left behind and without many new features for months after we got them on mobile or macOS (The macOS App Store version gets updates everytime and on par with the mobile iOS app, not to mention it has a more modern and polished UI, but that's not being discussed here). We like the Microsoft Store version because it's faster to install on newly bought/formatted PCs, makes a cleaner install and uninstall, and feels more modern. Now with the newly announced Windows 11, the Store will have a complete redesign and Microsoft will push users to it much more - a.k.a: there will be a lot of new users using the Microsoft Store version.

### Describe the solution you'd like
Somehow try to submit new releases to the Microsoft Store more frequently. I'm not asking for a "day one" type of updates, but at least in a week's interval at maximum after the new versions come out on other platforms or to the manually installed desktop app.

### Describe alternatives you've considered
The manually installed desktop version (from the website) will always be an alternative, but in modern times of app stores and with Windows 11 pushing Microsoft Store really hard, this "alternative" is starting to feel like "the oldschool way" of doing it.

### Additional context
None.

**Comment by Younes-L** [comment]
> try to submit new releases to the Microsoft Store more frequently

the microsoft store belongs to microsoft, ultimately it's microsoft who decide which updates are shipped and when.

> The manually installed desktop version (from the website) will always be an alternative

the microsoft store is actually "the alternative" way to install tdesktop on windows. (in fact the microsoft store is not even listed as an official distribution channel, see telegram's website)
the recommended way to install tdesktop is to go to desktop.telegram.org and click the "get telegram for windows" button.

> the macOS App Store version gets updates everytime and on par with the mobile iOS app, not to mention it has a more modern and polished UI

the telegram client for macOS is not a "version" of tdesktop, it is a completely different app made by a different person. said app is only available for macOS, while tdesktop is made for macos/windows/linux and supports all three at the same time. A lot of extra work (and cross-platform limitations) are required to do that, otherwise it would be likely as "polished" as the macos native client.
of course no need to mention that telegram iOS is also a completely different app.

> We like the Microsoft Store version because [...] and feels more modern.

there's nothing more "modern" about the microsoft store version of tdesktop, it's virtually the exact same app as the manual install.

---

overall your issue description raises a lot of red flags , as such this might be the only reply you'll get.
A few words of advice : 
* cut the middleman, and you'll have fewer problems.
* some things are popular because they are good/best. some other things are popular because they are the default pick of most people. it's important to make the distinction between these two categories, the former is a direct result of choice, while the latter is a consequence of the absence of choice. always choose for yourself, instead of sticking to default configuration.
* change for the sake of change is a no-go in software (and not only software). no need to fix what's not broken, and terms such as "old-school", "legacy" , etc are martketing ploys designed to bypass critical thinking.

**Comment by p0358** [comment]
The only question here is whether they're submitted at the same time as to main update channel or no. If yes, then it's purely Microsoft taking the time to process/review and push the update. But we don't really know that

**Comment by ChlorideCull** [comment]
From my experience, they usually review updates in less than a day (even with enterprise permissions, which is supposed to warrant a deeper inspection). It's likely just that updates aren't pushed that often to Microsoft Store.

**Comment by areiased** [comment]
> From my experience, they usually review updates in less than a day (even with enterprise permissions, which is supposed to warrant a deeper inspection). It's likely just that updates aren't pushed that often to Microsoft Store.

this is what I think too, and thats why I created this post. Maybe tdesktop devs don't think they have a lot of users on the Microsoft Store so they don't pay too much attention to it... But everyone I know uses it. Because it's that thing "hey come use telegram on Windows it's pretty simple just go to the store and install it". And now with Windows 11 pushing the Store really hard, more users will choose the store as a way to install telegram.
Right now tdesktop on the Microsoft store is at version 2.7.2, while tdesktop manually installed is at 2.8.3. 
The Microsoft Store needs some more love

**Comment by areiased** [comment]
The Microsoft Store version is now fully updated and on par with the latest manual install, released just 1 day ago (wow!). Thank you tdesktop team! I will never ask for "day 1" updates, and no one should, it's perfect already if you guys just keep it fairly updated as you guys did now, so MS Store users can enjoy the latest Telegram features that make this app so incredible and better than any other competitors. Keep up the awesome work!

I don't think this github "issue" needs to be open anymore, so I will closed it.
