### ISSUE TITLE
How do you develop such large source continuously? [Question] 

### ISSUE THREAD

**Issue by mahdi-jfri** [telegramdesktop/tdesktop#16704]
I've been trying to work around developing some tiny features for learning purposes, but haven't been able to do anything. I haven't found any documentation and have trouble even navigating through classes(since I'm coding on linux and my IDE does not recognize definitions properly)

With all these things in mind, building the project takes ~10 minutes for me. So every bit of change takes too long to check.

I'm basically asking three things.
1. How do new people on telegram learn concepts of tdesktop?
2. Which IDE should I use for linux?
3. How to test my code without waiting so long?

**Comment by ilya-fedin** [comment]
> How do new people on telegram learn concepts of tdesktop?

There's no any public documentation on the code and there's usually no 'new people' in tdesktop. AFAIK @john-preston is the only paid developer of tdesktop and other contributions are usually from @23rd (I know nothing about him except of that he develops Forkgram), me or Linux maintainers that do small changes in order to be able to build tdesktop in their environments. Personally I started contributing due to the bad state of Linux platform code in the end of December 2019 and asked @john-preston for each thing I was needed to understand, via private messages on Telegram. AFAIK the code is open for security reviews rather than for community contributions, so don't except that this will be changed.

> Which IDE should I use for linux?

I think it's a matter of preference.

> How to test my code without waiting so long?

Full rebuilding of tdesktop takes around a hour for me, but full rebuild is not needed when you change something and want to test it, building after changing one .cpp files takes a minute or so.

**Comment by mahdi-jfri** [comment]
> I think it's a matter of preference.

I'm only asking that for code navigation part since CLion and vscode have failed me for this project.

**Comment by ilya-fedin** [comment]
Personally I use vscode, but I don't need such a feature

**Comment by mahdi-jfri** [comment]
Thanks!
