### ISSUE TITLE
Telegram Desktop sometimes takes forever to open

### ISSUE THREAD

**Issue by github-account1111** [telegramdesktop/tdesktop#16940]
### Steps to reproduce

No steps, just a load time bug.

### Expected behaviour

No lag.

### Actual behaviour

Sometimes TG Desktop takes forever to open. Just a blank window. I do not know what causes this, seems pretty random. Happens every few days.

Maybe #4576, #9305 and the various other issues reporting the exact same thing getting closed while the problem remains is the culprit.

### Operating system

Windows 10

### Version of Telegram Desktop

3.0.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
I'm sure those issues are unrelated.

#4576 was having slow startup time without showing window or even starting writing the app log.txt (so that something was delaying the launch even before my code started executing).

#9305 were Linux-only issues (I think with fonts detection, but I'm not sure now), so not relevant here too.

Can you provide log.txt of a slow launch? Will the delay be visible between some of the entries in the log?

**Comment by Ojd2000** [comment]
For me it always takes a lot of time to start, and then also to perform some operations.
I'm on Arch Linux and my download source is the AUR (the upstream is the official website).
I use `xdg-desktop-portal` and `xdg-desktop-portal-gtk` for desktop integration, and I discovered that, by uninstalling them, the problem gets solved (altough then I miss desktop integration), and I get these error messages, also mentioned in #9305:
```
error: : cannot open
error: : cannot open
error: : cannot open
```

**Comment by crisbal** [comment]
@Ojd2000 I am experiencing the exact same problem with the exact same setup
