### ISSUE TITLE
Context menus are off-screen on Wayland

### ISSUE THREAD

**Issue by escape0707** [telegramdesktop/tdesktop#16943]
### Steps to reproduce

1. Run Telegram with `env QT_QPA_PLATFORM=wayland telegram-desktop`
2. Maximize window
3. Right click in input panel / chat list / chat content panel near screen edge, or left click on chat detail button.

### Expected behaviour

Context menu show up inside screen like happened under XWayland.

### Actual behaviour

Context menu always show up on the right-lower side of click point, so it could go off screen.

### Operating system

ArchLinux, GNOME Wayland 40.4.0

### Version of Telegram Desktop

3.0.1

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
:thinking: I can't reproduce on KDE Wayland, maybe it's a GNOME bug?

**Comment by escape0707** [comment]
I just tried it out. On my KDE machine, it works as intended.

On my and my friend's GNOME machine, this is still happening. I think I should go to GNOME issue tracker to report it.

**Comment by escape0707** [comment]
@ilya-fedin This is actually a broader problem: 

https://github.com/WayfireWM/wayfire/issues/1129

https://bugreports.qt.io/browse/QTBUG-87303

It seems that only KDE Wayland has workarounds this in someway.

**Comment by ilya-fedin** [comment]
tdesktop checks screen bounds when showing menus: https://github.com/desktop-app/lib_ui/blob/master/ui/widgets/popup_menu.cpp#L764-L805

So it sounds for me that GNOME fakes screen bounds (what I would consider a bug in GNOME) when KDE doesn't.

**Comment by ilya-fedin** [comment]
Also, as far as I herad, this problem doesn't present on sway as well

**Comment by ilya-fedin** [comment]
I know that weston fakes window position for sure since I observed this behavior when testing Telegram on Wayland

**Comment by ilya-fedin** [comment]
Whenever I move the window, weston says it's at QRect(311,38 452x519)

**Comment by ilya-fedin** [comment]
> [WayfireWM/wayfire#1129](https://github.com/WayfireWM/wayfire/issues/1129)

> However, since the Qt issue remains open, I suppose that the issue is indeed in Qt.

:facepalm:
![изображение](https://user-images.githubusercontent.com/17829319/133358597-149edce2-06b6-41f5-b3a6-b70a5f1ffcbe.png)

**Comment by unrelentingtech** [comment]
Nothing "fakes window position" because there is *no* window position in the protocol *at all*. xdg-shell does not make applications aware of window position at all. (Who even said there's going to be *one* position, or that it must be in 2D space?) Popups are relative to the main surface. The toolkit is supposed to set `constraint_adjustment` to allow the compositor to move/resize/flip popups to prevent them from going off-screen. Qt indeed just doesn't do this, it is a Qt bug.

In the Qt bug report I said

> how is this tolerated by KDE? do they default the constraint_adjustment to non-zero in their compositor?

and indeed, this is true:

https://github.com/KDE/kwin/commit/8ef363cc210b12bba87bba78160ed55b9725e08d#diff-5425403b99ccea8dfc05a698d2ec3d51b684467a1bdd84a861df72caf4fe1acdR503-R508

Thanks KDE, keeping toolkit-specific hacks around for years instead of pushing toolkits to fix their bugs is exactly what we need :/

**Comment by escape0707** [comment]
Just want to shout out to you guys: thanks for all the effort put on maintaining these useful softwares, listening to users feed backs and troubleshooting with them! ♥️

**Comment by ilya-fedin** [comment]
> Nothing "fakes window position" because there is _no_ window position in the protocol _at all_.

I heard from other people in tdesktop issues that there is. You can't set position, but you can get it. Who should I believe?

**Comment by unrelentingtech** [comment]
Run `WAYLAND_DEBUG=1 telegram-desktop` and/or read the [xdg-shell protocol definition](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/xdg-shell/xdg-shell.xml) and see for yourself :) You won't find absolute positions anywhere. The only thing that can "fake" window position is *Qt* — it's not even intentionally faking, it probably just has an internal "position" field due to other platforms having one, and the value starts with 0,0 and it might be affected by resizes for whatever reason, but that internal value is really completely useless.

If you wanted to have a workaround, it seems that you can get access to the raw `xdg_popup` proxy as

```c++
QGuiApplication::platformNativeInterface()->nativeResourceForWindow("xdg_popup", popup_window))
```

but like… don't. Qt should be fixed, applications should not do anything.
