### ISSUE TITLE
Unread counter for posts from schedule

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#17079]
### Steps to reproduce

1. Schedule anything in channel
2. Wait until it posts
3. After it posts you will see two checkmarks like you already read this post
4. Open the channel to check this post
5. Restart Telegram client
6. This post now is looks like you didn't read it (with "1" unread counter)
7. When you schedule post from iOS client and when when it posts it does not looks like you already read it (with two checkmarks) it's have "1" unread counter so bug is only on Telegram Desktop.

### Expected behaviour

There is must be no "1" unread counter on posts that was posted from scheduled messages if I read it

### Actual behaviour

When I schedule anything to channels and it posts it's looks like that I already read it, but after restart I see "1" unread counter like I didn't read it

### Operating system

Windows 10

### Version of Telegram Desktop

3.1.7 Beta

### Installation source

Static binary from official website

**Comment by theelectricsoul** [comment]
I found this ticket after submitting my [own](https://github.com/telegramdesktop/tdesktop/issues/25071). 

I describe the impact of this bug a little more in detail. Conclusion is, that scheduled message cannot be leveraged as promised.

**Comment by theelectricsoul** [comment]
## Impact of this bug
Hinders basic communication.

### Probability of occurence

High, because the bug only shows when TG Desktop is running. Windows user will very likely not close TG.

### Affected scenarios

🔥Project management
🔥Customer communication
🔥All communication in general of course :)

### Conclusion
* Scheduled messages cannot be effectively used with TG Desktop. 
* Scheduled messages do not work as [advertised](https://telegram.org/blog/scheduled-reminders-themes) ;)*

**Comment by Neurotoxin001** [comment]
`+`

**Comment by Iowerth** [comment]
Still actually.

**Comment by theelectricsoul** [comment]
It is still a problem....

**Comment by Iowerth** [comment]
Thanks!
