### ISSUE TITLE
Icons and emojis are blurry

### ISSUE THREAD

**Issue by MohamadKh75** [telegramdesktop/tdesktop#17173]
### Steps to reproduce

1. Upgrade to 3.1.12 Beta
2. Here we go!

### Expected behaviour

To have clear and nice images, emojis, and structure!

### Actual behaviour

Everything is blurry:

Blurry images, icons, emojis, white lines, etc.

![x](https://user-images.githubusercontent.com/25561893/139701786-ae3171e5-0a54-45f3-ad19-3d08390835c9.jpg)

### Operating system

Ubuntu 20.04.3 LTS - KDE Plasma

### Version of Telegram Desktop

3.1.12 Beta

### Installation source

Static binary from official website

**Comment by s-light** [comment]
i have very similar problem.
but without the white lines.

just got the update to 3.1.13 beta
and for me the problem persists at least for emoji, stickers, profile pictures - 
seems that all graphics shows very pixelated -
the text seems ok to me:

![20211103__telegram_bug](https://user-images.githubusercontent.com/1340319/140024540-db868bb2-821d-4e11-ba05-0af54cdcabb5.png)

for me this changed two beta updates ago.
before this it was all clear and fine
(if version numbers incremented logicaly 3.1.11 beta should be the last good one)


### Operating system
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.4.0-90-generic
OS Type: 64-bit
Processors: 16 × Intel® Core™ i9-9980HK CPU @ 2.40GHz
Memory: 31,2 GiB of RAM
Display: 4K OLED
OS GlobalScale: 125%

### Version of Telegram Desktop
3.1.13 Beta

**Comment by ilya-fedin** [comment]
@s-light provide the log.txt please + the output of these commands: 
```
env | grep QT
xrdb -query
```

**Comment by MohamadKh75** [comment]
Fixed for me in 3.1.13 Beta

**Comment by bpierre** [comment]
Telegram 3.2 Beta with Arch Linux and Xorg here, same issue.

Telegram scale is at 125%.

```
$ env | grep QT
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_SCREEN_SCALE_FACTORS=1.25
```

```
$ xrdb -query
# (no output)
```

**Comment by s-light** [comment]
the `xrdb -query` result is very long.
so i removed about all *color* entries.
if you need the full output let me know and i edit it here

and how can i generate a log.txt?
i think i am missing something obvious here - but did not find any information on this..


```
$ env | grep QT
QT_ACCESSIBILITY=1
QT_SCREEN_SCALE_FACTORS=eDP-1=1.25;DP-1=1.25;DP-2=1.25;HDMI-1-0=1.25;
QT_AUTO_SCREEN_SCALE_FACTOR=0
```
```
$ xrdb -query
*Box.background:        #31363b
*Box.foreground:        #eff0f1
*Scale.activeBackground:        #31363b
*Scale.activeForeground:        #eff0f1
*Scale.background:      #31363b
*Scale.foreground:      #eff0f1
*Scale.highlightBackground:     #31363b
*Scale.highlightColor:  #eff0f1
*Scale.troughColor:     #31363b
*Scrollbar*Cursor:      left_ptr
*Scrollbar*background:  #31363b
*Scrollbar*cursorName:  left_ptr
*Scrollbar*height:      15
*Scrollbar*pushThumb:   false
*Scrollbar*shadowWidth: 2
*Scrollbar*width:       15
*ShapeStyle:    Rectangle
*SmeBSB*shadowWidth:    3
*background:    #31363b
*beNiceToColormap:      false
*borderColor:   black
*customization: -color
*foreground:    #eff0f1
Xcursor.size:   0
Xcursor.theme:  breeze_cursors
Xft.antialias:  1
Xft.dpi:        120
Xft.hinting:    1
Xft.hintstyle:  hintslight
Xft.rgba:       rgb
ml*XmCascadeButton.marginHeight:        2
ml*XmCascadeButton.marginWidth: 8
ml*XmForm*bottomOffset: 0
ml*XmForm*topOffset:    0
ml*XmForm*verticalSpacing:      0
ml*XmList*highlightThickness:   0
ml*XmPushButton.marginHeight:   1
ml*XmRowColumn*marginHeight:    1
ml*XmRowColumn*spacing: 0
ml*XmRowColumn.entryBorder:     0
ml*XmToggleButton.marginHeight: 1
ml*borderWidth: 0
ml*marginHeight:        2
ml*marginWidth: 3
ml.form.height: 550
ml.form.width:  650
xpdf.urlCommand:        kfmclient exec %s
```

**Comment by ilya-fedin** [comment]
looks like Qt doesn't round QT_SCREEN_SCALE_FACTORS :(
That's bad since tdesktop can't work with fractional values and Qt offers no way to avoid reading that variable...

**Comment by john-preston** [comment]
@ilya-fedin Patch it out!

**Comment by ilya-fedin** [comment]
@john-preston there's `-no-feature-highdpiscaling` build option in Qt, so no need for patching. But RIP for distro builds.

**Comment by land0r** [comment]
Also have blurry stickers, icons, profile photos.

Kubuntu 20.04, 
KDE Plasma 5.18.5
Qt version: 5.12.8

```
$ env | grep QT
QT_ACCESSIBILITY=1
QT_SCREEN_SCALE_FACTORS=eDP-1-1=1.5;HDMI-1-1=1.5;
QT_AUTO_SCREEN_SCALE_FACTOR=0
```

xrdb -query output:
[xrdb -query.txt](https://github.com/telegramdesktop/tdesktop/files/7471820/grepqt.txt)

Returning to the 3.1.1 version resolve the issue

**Comment by ilya-fedin** [comment]
No need in more reports, thanks

**Comment by dmitrygorbenko** [comment]
Thank you, and when can we expect the next update for the linux platform ?
Can we do something locally to fix this bug while waiting for the update ?
Thanks

**Comment by ilya-fedin** [comment]
> Thank you, and when can we expect the next update for the linux platform ?

Well, there doesn't seem to be a way to fix the issue fully. At least I don't know one. Any help is appreciated.

> Can we do something locally to fix this bug while waiting for the update ?

Disable fractional scaling in KDE settings.

**Comment by goganchic** [comment]
> Well, there doesn't seem to be a way to fix the issue fully. At least I don't know one. Any help with fixing is appreciated.

Everything works fine in 3.1.1 but breaks in 3.2. Why don't return behavior from 3.1.1?

**Comment by ilya-fedin** [comment]
Behavior is changed due to Qt update (5.15 -> 6.2).

**Comment by goganchic** [comment]
Is it possible to resolve this issue before major Qt update?

**Comment by ilya-fedin** [comment]
I don't quite understand your question. Can you refolmulate?

**Comment by goganchic** [comment]
Sorry, my fault.

For me as a user the behavior looks like this:

1. snap makes an automatic update (it's [impossible to disable](https://forum.snapcraft.io/t/disabling-automatic-refresh-for-snap-from-store/707/10))
2. icons looks broken

If I'm not mistaken you say that it's a bug of Qt 6, not the telegram-desktop. It's OK, new libraries sometimes have some bugs. But telegram-desktop 3.1.1 worked fine and there were no such bugs.

You have said:
> Disable fractional scaling in KDE settings.

It's not an option for the laptop users with 1080p screen <= 14" because all the elements of the interface will be too small and it will be very hard to use other apps.

I try to understand the purpose for updating from Qt 5.15 to 6.2. On the one hand It does not look like the security update. On the other hand it breaks the user experience for some of us. Would you please provide a bit more info about it? Is it better to get rid of snap version and use the Linux static build?

**Comment by ilya-fedin** [comment]
> If I'm not mistaken you say that it's a bug of Qt 6, not the telegram-desktop.

I'm not sure it's a Qt bug. The problem is Qt 6 doesn't allow to disable its scaling (Qt 5 allows) and tdesktop is incompatible with Qt's fractional scaling. It's still possible to say Qt that it should round scale factor (and tdesktop seem to look mostly ok with rounded one), but rounding is not applied when scale factor is told to Qt by variables like QT_SCALE_FACTOR/QT_SCREEN_SCALE_FACTORS. There's private undocumented API in Qt that allows to prevent Qt from applying the value from QT_SCALE_FACTOR (that is read in both Qt 5/6 even when Qt's scaling is disabled) and tdesktop successfully uses it, but there's no equal API for QT_SCREEN_SCALE_FACTORS. The documentation doesn't say whether HighDpiScaleFactorRoundingPolicy should be applied to these variables or not, so apparently we can't call it a bug. It seems these variables for debugging purposes mostly, but KDE uses them to set scale factor for applications. :cry:

> It's not an option for the laptop users with 1080p screen <= 14" because all the elements of the interface will be too small and it will be very hard to use other apps.

Well, I was asked about workaround, I told the one I know. Whether use it or not is your decision.

> I try to understand the purpose for updating from Qt 5.15 to 6.2.

Well, to use the latest version of the library. It's not realistic to stick with 5.15 forever and the amount of backported only increases.

> Would you please provide a bit more info about it?

Which do you want to know?

> Is it better to get rid of snap version and use the Linux static build?

Generally it's better since it's the main distribution channel and it's maintained directly by @john-preston. But it won't help with this issue.

**Comment by bpierre** [comment]
My understanding was that [this PR](https://github.com/telegramdesktop/tdesktop/pull/17186) was fixing the issue, is it not the case? If not, does it mean that Telegram is going to stay in this state on Linux from now on, or are other solutions being investigated? Thanks :pray:

**Comment by ilya-fedin** [comment]
There was a fix even before this issue was opened (#17170). It fixed the issue for users who have system-defined DPI translating into fractional scaling. But this doesn't help people who have fractional scaling based on Qt's environment variables. The PR you linked will disable Qt's scaling in build time, so the issue should disappear from official builds completely. Still, third-party builds (e.g. distro packages) will have the issue and I have no idea how to fix the issue for them.

**Comment by bpierre** [comment]
Oh I understand now, thank you. Now my problem is that I am using the official binaries, and the fix seems to be included in [the latest version](https://github.com/telegramdesktop/tdesktop/commits/v3.2.1) which I am using, but the issue is still here. Should I open a separate issue?

**Comment by ilya-fedin** [comment]
As you can see, 3.2.1 doesn't contain 81327ede7bcd829f6f2158096a97253b615c675a

**Comment by bpierre** [comment]
Oooh my mistake sorry, I mixed up https://github.com/telegramdesktop/tdesktop/pull/17170 and https://github.com/telegramdesktop/tdesktop/pull/17186. Looking forward for the next release then, thanks for the amazing work on Telegram! :pray:

**Comment by john-preston** [comment]
Please check the 3.2.2 version from https://desktop.telegram.org or when it becomes available as a snap update.

**Comment by bpierre** [comment]
I confirm the problem is now fixed, thank you!

**Comment by s-light** [comment]
i also just got the update in.
now on 3.2.2 it is fixed!

**Comment by dmitrygorbenko** [comment]
thank you for the update !

**Comment by vimpostor** [comment]
> tdesktop is incompatible with Qt's fractional scaling

What is the reason that tdesktop is incompatible with Qt's fractional scaling in the first place and how hard would it be to fix it properly inside tdesktop's codebase?

**Comment by ilya-fedin** [comment]
> What is the reason that tdesktop is incompatible with Qt's fractional scaling in the first place

Because device pixel ratio is assumed to be an int, I guess. @john-preston implemented support not more than needed for correct rendering on mac (where it was impossible to prevent Qt's integer scaling). I remember he once said that when tdesktop was created, Qt's scaling was very unstable, so he invented his own solution.

> how hard would it be to fix it properly inside tdesktop's codebase?

Well, I have no idea, it's a question for @john-preston. Apparently, that would rewriting all the widgets in tdesktop with the assumption that device pixel ratio could be fractional.
