### ISSUE TITLE
Unable to unpack update

### ISSUE THREAD

**Issue by 0xNima** [telegramdesktop/tdesktop#17248]
Hi. `UnpackUpdate` function fails because of `#ifndef TDESKTOP_DISABLE_AUTOUPDATE` line. So I've removed `TDESKTOP_DISABLE_AUTOUPDATE` from Visual Studio Preproccessor Definitions but visual studio can't include `<LzmaLib.h>`. I've added include directory of `lzma` to the compiler include directories but solution build fails with error `unresolved external symbol _LzmaUncompress@24`.
The `UnpackUpdate` function was working before when there wasn't `#ifndef TDESKTOP_DISABLE_AUTOUPDATE` line, and I didn't have to do any additional steps. What is changed now?

**Comment by 0xNima** [comment]
I added the `Lzmalib.lib` to the linker and unpacked the update file successfully. But I'm still confused O_o why before `lzma` included automatically?

**Comment by john-preston** [comment]
Unofficial builds are not supposed to unpack updates, because it will overwrite the unofficial builds with official updates.

There is a CMake variable `DESKTOP_APP_DISABLE_AUTOUPDATE`. You can pass `-D DESKTOP_APP_DISABLE_AUTOUPDATE=ON` to the `configure` invocation, that way it'll link all required dependencies.
