### ISSUE TITLE
Windows 11 Design Language

### ISSUE THREAD

**Issue by vivaanmathur** [telegramdesktop/tdesktop#17250]
### Is your feature request related to a problem?

Telegram Desktop should be compatible with the design language of Windows 11. It looks a bit off on the new OS.

### Describe the solution you'd like

Windows 11 comes with a bunch of UI improvements and an entirely new design language. Please use the new UI enhancements in the app.

Telegram Desktop should support the design language of Windows, just like the Telegram for macOS (App store app) has native macOS design and Telegram for iOS has native iOS design.

**WinUI3** is compatible with existing desktop applications: [https://docs.microsoft.com/en-us/windows/apps/winui/](https://docs.microsoft.com/en-us/windows/apps/winui/)

**Mica** is a dynamic material that tints the background of windows based dynamically on your desktop wallpaper and theme: [https://docs.microsoft.com/en-us/windows/apps/design/style/mica](https://docs.microsoft.com/en-us/windows/apps/design/style/mica)

**Acrylic** is a translucent material that adds depth to the window; [https://docs.microsoft.com/en-us/windows/apps/design/style/acrylic](https://docs.microsoft.com/en-us/windows/apps/design/style/acrylic)

Please add Fluent Design and WinUI3 to the Telegram Desktop app, or create a separate app with WinUI3 just like there are two macOS apps.

Design principles of Windows 11: [https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/design-principles](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/design-principles)

The app should be packaged as MSIX instead of EXE.
**MSIX** is more reliable than EXE (which is outdated now) and offers a better installation experience and updates.

### Describe alternatives you've considered

Doing all of this is not difficult, you just need to use the Windows App SDK which can be easily added to existing projects also.

[https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/)

### Additional context

 I have added this to the Telegram Bugs & Suggestions platform too: https://bugs.telegram.org/c/11289

**Comment by vivaanmathur** [comment]
#16626

**Comment by john-preston** [comment]
> Doing all of this is not difficult

I'm not sure you're right. Right now Telegram Desktop doesn't use any Windows API for UI at all, it is built with Qt, a cross platform toolkit that implements all of the UI painting and input management and handles the resulting image of the window to the OS. There is no way you can include some Windows-specific UI elements or tweaks into it easily, none of the new WinUI 3 features.

WinUI 3 is compatible with existing native Windows desktop apps, not with cross platform Qt apps.

Comparing Telegram Desktop to Telegram for macOS here is incorrect, because Telegram for macOS is indeed a native macOS app,while Telegram Desktop has a single code base and design for all desktop platforms (Windows, macOS and Linux), so it is as native on macOS as it is on Windows.

Perhaps you could ask for some UI tweaks for Unigram, which is across as it gets to a native Windows app for Telegram. Asking for a separate native Windows app here is incorrect as well, it would be a completely separate project, like Unigram is. Maybe bugs.telegram.org is a right place for such request.

**Comment by john-preston** [comment]
I'm not sure how exactly msix is better.

**Comment by vivaanmathur** [comment]
I get your point. So basically, the Telegram Desktop application is designed with Qt instead of native Windows APIs, which is why it won't be as seamless to add WinUI3 here. 

> Perhaps you could ask for some UI tweaks for Unigram, which is across as it gets to a native Windows app for Telegram. 

I don't think that is possible. Unigram is a UWP app, and WinUI3 is for desktop applications. WinUI3 might be added to UWP next year.

> I'm not sure how exactly msix is better.

Windows is going through a transition period from 'programs' to 'apps', and MSIX creates a container for each app, so installations are more reliable. Uninstalling an MSIX app doesn't keep traces left on the system. The update mechanism is much better on MSIX.

It seems like you probably use .appx files for the Microsoft Store. MSIX is pretty similar to it in functionality and combines the features of AppX and older .exe files. When you download Telegram from the website, it still downloads the older .exe files which do not have these.

**Comment by john-preston** [comment]
Yup, sorry.

Unigram developer recently built it as a desktop (non-UWP) app as well, maybe he has plans to do so further. You can ask.

How is update mechanics better? With the "setup.exe" approach I can build the autoupdate inside the app and it works seamlessly for the user being installed on the nearest relaunch. I have to prepare setup-s anyway, I don't have plans to drop Windows 7 / 8 / 8.1 support yet. Also there is a portable version being deployed which doesn't play well with msix as far as I understand.

**Comment by readonly24** [comment]
At least it would be nice to have the accent color in the title bar while Telegram Desktop has the focus.

**Comment by vivaanmathur** [comment]
You can already do that. You just need to enable this option.
![image](https://user-images.githubusercontent.com/42546935/147358082-f46c7177-6390-4ac7-af3d-203f079cd0d5.png)

**Comment by readonly24** [comment]
This option is already enabled, but the title bar color is ignored in Win 11, it works in Win 10.

**Comment by vivaanmathur** [comment]
Well, this issue should be extended to 'Integration with more native Windows / Windows11 features'.
1. Windows Share option: Telegram has an option 'Place Telegram in Send to Menu'. The functionality already exists in Telegram Desktop, so placing it in the Share menu would be easier I guess?
2. Fluent Design, Rounded Corners/Bubbles, and the native Windows feel. 

There are many more, which are mostly impossible with Qt. 
I am closing this issue because it all depends on Telegram's management to create a separate native app for Windows, or just clone Unigram and port it to WinUI3. (Funny how WhatsApp, which has been the worst in user experience is working on Mac Catalyst and native WinUI apps)

**Comment by john-preston** [comment]
@vivaanmathur 1. Unfortunately, absolutely not. Place in "Sent to" menu is done by creating a special shortcut in a special folder - and that's that. Integration with the modern Share menu is done using a modern Windows APIs, available through complex COM wrappers in C++/WinRT library. Some of them may be just used, while others require a complex registration in the system using a sparse package, which can't be done for portable applications and hard to do even for installed Win32 apps. So this still requires research on how and in what cases the Share menu integration could work.

2. Rounded corners are already there? Some things are just about design, others are indeed impossible in Qt apps. But for now tdesktop design is influenced mostly by Google Material, because it is the most recognized cross-platform design approach (almost everyone uses Google services on the web).

Fully Windows design should indeed be proposed for Windows-only Telegram app, which Unigram is. There is a contest for its redesign according to Windows 11 guidelines going on right now:

https://t.me/contest/287

I'm not sure Mac Catalyst app is needed for Telegram, because it has a great native macOS application written in Swift. Unigram is the closest we have to native Windows application right now, leaving TDesktop in between with Windows / macOS / Linux support at once.
