### ISSUE TITLE
[Question] How does "local password" feature work?

### ISSUE THREAD

**Issue by TruncatedDinosour** [telegramdesktop/tdesktop#17375]
Hello, I have an unofficial telegram client in development and I can't think of a good way to implement local passwords, like that you could add a local password to your client locally, so I though I'd do it like in telegram-desktop, so how hoes telegram desktop's client's implementation work, because I am quite confused by the code

Thanks for the answers in advance

**Comment by GUOguocai88** [comment]
但是我的電腦🖥️已經鎖起來了，我忘記密碼了


---Original---
From: ***@***.***&gt;
Date: Fri, Dec 10, 2021 13:29 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [telegramdesktop/tdesktop] [Question] How does &quot;local password&quot;feature work? (Issue #17375)




 
Hello, I have an unofficial telegram client in development and I can't think of a good way to implement local passwords, like that you could add a local password to your client locally, so I though I'd do it like in telegram-desktop, so how hoes telegram desktop's client's implementation work, because I am quite confused by the code
 
Thanks for the answers in advance
 
&mdash;

**Comment by TruncatedDinosour** [comment]
> 但是我的電腦desktop_computer已經鎖起來了，我忘記密碼了
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Fri, Dec 10, 2021 13:29 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [telegramdesktop/tdesktop] [Question] How does &quot;local password&quot;feature work? (Issue #17375) Hello, I have an unofficial telegram client in development and I can't think of a good way to implement local passwords, like that you could add a local password to your client locally, so I though I'd do it like in telegram-desktop, so how hoes telegram desktop's client's implementation work, because I am quite confused by the code Thanks for the answers in advance &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Translation by google translate: "But my desktop_computer is locked, I forgot my password"

I did not forget my password, I just want to know how it works so I could implement it myself

**Comment by john-preston** [comment]
You need to save authorization keys on the disk.

So you can take the local passcode, derive an encryption key from this passcode and use this key to encrypt the authorization keys before saving. So when you start the app you can't decrypt the keys (and start using the API) without providing a correct local passcode for that. You can also save some hash (like SHA256) of the original keys along so that you can check whether you've decrypted the correct keys or just garbage because of an incorrect passcode.

**Comment by TruncatedDinosour** [comment]
> 



> You need to save authorization keys on the disk.
> 
> So you can take the local passcode, derive an encryption key from this passcode and use this key to encrypt the authorization keys before saving. So when you start the app you can't decrypt the keys (and start using the API) without providing a correct local passcode for that. You can also save some hash (like SHA256) of the original keys along so that you can check whether you've decrypted the correct keys or just garbage because of an incorrect passcode.

Thanks!

**Comment by GUOguocai88** [comment]
就是这样我的电脑才会锁住呀。


---Original---
From: ***@***.***&gt;
Date: Fri, Dec 10, 2021 18:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [telegramdesktop/tdesktop] [Question] How does &quot;local password&quot;feature work? (Issue #17375)




    
You need to save authorization keys on the disk.
 
So you can take the local passcode, derive an encryption key from this passcode and use this key to encrypt the authorization keys before saving. So when you start the app you can't decrypt the keys (and start using the API) without providing a correct local passcode for that. You can also save some hash (like SHA256) of the original keys along so that you can check whether you've decrypted the correct keys or just garbage because of an incorrect passcode.
  
Thanks!
 
&mdash;
