### ISSUE TITLE
[Feature Request] Let Administrators replace the default reactions message for the ones we want.

### ISSUE THREAD

**Issue by ZeroCool22** [telegramdesktop/tdesktop#17473]
### Is your feature request related to a problem?

No.

### Describe the solution you'd like

Let Administrators **replace the default reactions** for the ones we want.

![Replace Reactions TG](https://user-images.githubusercontent.com/13344308/147822734-a365cda2-92cd-4a79-8d44-8ae9b523886a.jpg)

### Describe alternatives you've considered

.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by ZeroCool22** [comment]
> such feature belongs to https://bugs.telegram.org/

Og really?

And what about this:

https://github.com/telegramdesktop/tdesktop/issues/17469

**Comment by PeterNjeim** [comment]
> And what about this:
> 
> #17469

First of all, I'm not sure why you clicked thumbs down on Aokromes message. This is not related to the desktop app, it's related to Telegram itself. Imagine you change an emoji on the desktop client to a different one. What will people on Android and iOS see? What about other desktop users? They'll still see the regular Telegram emoji, not the one you chose, as that would only be client-side. You would need to ask Telegram to add more emoji support. You should've clicked thumbs up as they gave you useful information on how to proceed with your feature request :)

The other issue you mentioned can indeed be added to the desktop client. Notice how that issue doesn't have the "api issue" label. Although the issue is worded quite badly. What the user really wants is to remove the side panel and have a different way of selecting folders, possibly a tabbed interface like on Android.

Happy new year!
