### ISSUE TITLE
Bad UX for sticker's reaction position

### ISSUE THREAD

**Issue by masreplay** [telegramdesktop/tdesktop#17488]
### Steps to reproduce

1. Send sticker in telegram desktop
2. Sticker's reactions are now centered in the middle Unlike other types of messages
3. Only happen with the First user message (Me) my side sticker
![Screenshot 2021-12-31 181954](https://user-images.githubusercontent.com/55885230/147849092-9dde7fc9-6c0f-4dad-8c60-7f80d13325ff.png)
 

### Expected behaviour

Put reactions on the side of the message like another type of messages

### Actual behaviour

Sticker's reactions are centered

### Operating system

Windows 11

### Version of Telegram Desktop

Version 3.4.1 x64 and Version 3.4.2 x64

### Installation source

Microsoft Store

**Comment by Aokromes** [comment]
plz update to 3.4.2

**Comment by masreplay** [comment]
@Aokromes my sticker's reactions are still centered!

**Comment by Aokromes** [comment]
strange, for me the version from webpage shows on side....

**Comment by masreplay** [comment]
@john-preston

**Comment by john-preston** [comment]
Current position is intended. In the first version I tried to put it similar to bubble messages, but it was sometimes covering the "time, signature, edited-badge, views-count, replies-count, pinned-icon" label, sometimes not easy to find in some random place, so now it is displayed always to the left of this info label mentioned above (with the message time).

Maybe it'll be changed later, but right now it was the desicion.

**Comment by bviktor** [comment]
Hi,

I don't care much for the position, but I truly HATE the fact that I have to scroll every friggin' time for the ":D" reaction. Even though there's PLENTY of space to show all the reactions. It's a completely unnecessary extra step I need to take every time.

<img width="152" alt="image" src="https://user-images.githubusercontent.com/5798552/148404901-a2b7353e-94cd-4275-a502-9f93c49935e9.png">

Why don't show all by default?

In any case, that's prolly the reason why most messengers implement this horizontally, not vertically.

![image](https://user-images.githubusercontent.com/5798552/148405345-6e11dc29-cb74-47b9-b69b-19bd306454cf.png)

Vertical space might be dependent on the message's posistion, while horizontal is not.

It'd also help if you showed the reaction overlay right upon hovering, instead of having this 1 second delay. You might consider it more intrusive, but Messenger alleviates this by making it grey-ish transparent. It works pretty well imo:

![image](https://user-images.githubusercontent.com/5798552/148405642-6c8bc553-f0b7-4557-9d95-a0e490d4f70d.png)

Thanks in advance. Reactions are still much appreciated, I've been waiting on this for years, really.

**Comment by RememberTheAir** [comment]
@bviktor if you right-click on a message, reactions will be displayed horizontally with a button to expand the list so you don't have to scroll. It is also possible to disable the "hover" reaction menu from the settings -> chat settings

**Comment by bviktor** [comment]
Yes, I know that, that was not the point. I only right click when I want to bring up the context menu, as it's been the established practice for the past 3 decades.
