### ISSUE TITLE
Legacy Tray options menu

### ISSUE THREAD

**Issue by abhinav-adtechs** [telegramdesktop/tdesktop#1752]
tdesktop for debian 64-bit build's option menu has characters which are not in human readable characters and need fixing.

**Comment by zeorin** [comment]
+1. In my case I'm running Debian Stretch. I've also got another computer running Ubuntu 15.10 that does not have this problem.

**Comment by zeorin** [comment]
I've done a little more research, and I have a suspicion that the application depends on the `appmenu-qt5` package, which is not available for install in Debian Stretch (testing) at this time, because it depends on another package which is not available in the repos yet.

The issue currently still persists on with Telegram Desktop version 0.9.40. My Ubuntu laptop still doesn't have this issue, but then again the `appmenu-qt5` package is installed on that laptop.

**Comment by zeorin** [comment]
I don't have this issue any more. Likely it was a Debian problem. @abhinav-adtechs, do you still have this issue?

**Comment by abhinav-adtechs** [comment]
Recently I switched to OS X, so, I really can't comment on this. 
But thank you for the follow-up. Cheers.
