### ISSUE TITLE
Use Windows Internet Proxy settings

### ISSUE THREAD

**Issue by esteveblanch** [telegramdesktop/tdesktop#178]
The proxy settings on windows, does not work properly on different networks, for example, on one that needs a proxy, and another that does not.
The "Auto" option, does not work on this scenario, and I need to change the proxy settings when I change to different networks.
I think the best approach is to use the windows internet settings, or an option to use a proxy pac script.

**Comment by Brom2** [comment]
There are proxy settings but not the setting to use system's proxy. The other participants asked for the windows proxy settings but there are global proxy settings in some linux distributions, too. I'd be nice if both are supported.
It would also be an improvement if the proxy hostname  and port inserted in "custom http-proxy" is saved when I go back to "Auto" so that I can switch between the options without re-entering hostname and port.

**Comment by gnanaswaroop** [comment]
I'd love this feature too. Was this removed in the latest version of TG desktop ?

**Comment by auchri** [comment]
Telegram tries already to use the system proxy settings (http://doc.qt.io/qt-5.5/qnetworkproxyfactory.html#setUseSystemConfiguration). So it's not working for you, it's an issue with Qt :confused:

**Comment by gnanaswaroop** [comment]
I am 100% sure that it doesn't use the proxy settings.. I am on windows 7 btw..

**Comment by danielandross** [comment]
I am sure this does not work, either. 
Am 05.09.2015 04:00 schrieb Swaroop <notifications@github.com>:I am 100% sure that it doesn't use the proxy settings.. I am on windows 7 btw..

**Comment by CtrInt** [comment]
This is definitely a bug

**Comment by CtrInt** [comment]
I've verified as this seems to work in windows 10 64 but it doesn't in windows 7 64.
