### ISSUE TITLE
how to convert super group to normal group ?

### ISSUE THREAD

**Issue by shotgunner** [telegramdesktop/tdesktop#1792]
I recently upgrade my group into super group but seems that it has no clear history in options. is it possible to downgrade it to normal group ? or is there any option for clearing the history in a super group ?

thanks in advance :)

**Comment by shotgunner** [comment]
Any suggestion ?

**Comment by john-preston** [comment]
@shotgunner No, there is no way to convert it back (when you converted it should've been specifically mentioned — this action cannot be undone).

Clear history option has no sense for the supergroups (it would have absolutely different meaning), because the messages are stored only once for all the participants and the clearing of the history would delete the messages for all the participants, not only for you (like in regular groups).

**Comment by mintux** [comment]
> Clear history option has no sense for the supergroups
it's your opinion 
im not admin and im client of a supergroup but i have to see damn contents of everyone and there is no delete message or clear history
i hope telegram just make something not break something was true 
i have no idea why telegram destroy this best feature that each user can delete some message for himself (not for everyone)

**Comment by piedoom** [comment]
Just FYI, on android, if you make another person an admin, it converts to a supergroup without prompting you at all. Super annoying and idk how to go back to normal

**Comment by john-preston** [comment]
@piedoom No way to convert back. And it is supposed to be not needed to.

**Comment by piedoom** [comment]
performing a one-way action without prompting the user is very bad ux

**Comment by john-preston** [comment]
@piedoom The idea is for the distinction of groups / supergroups to be now more like an implementation detail than something that should bother the user.
