### ISSUE TITLE
Privacy setting: Last seen

### ISSUE THREAD

**Issue by Umriyaev** [telegramdesktop/tdesktop#1809]
This is basically feature request. I noticed that if you set that no one can see your last seen time using privacy settings, app shows 2 different last seen statuses:
1) last seen recently
2) last seen long time ago

It lets other users to predict my last active time, however, by setting that no one can see my last seen status, I want that they can't assume whether I was online or not.

It would be better if client wouldn't show anything in such cases. If I disable to share my last seen status, others shouldn't be able to predict my last seen time. Best way to do it is to not show last seen status for users, who disabled it via privacy settings.

**Comment by john-preston** [comment]
@Umriyaev This has nothing to do with Telegram Desktop, sorry. The Telegram cloud is designed to work that way. I could ve show similar strings in all the cases (recently, month, long time), but it is pointless, because the server is still providing this information and all the official apps display it correctly.

**Comment by stek29** [comment]
@Umriyaev Try asking Telegram Support about it
