### ISSUE TITLE
group administrator can not remove unknown member

### ISSUE THREAD

**Issue by omoridi** [telegramdesktop/tdesktop#1817]
Hi,
If some user left the telegram, admin can not remove he/she from group. 
the user last seen long time ago.
after remove, telegram do not remove and do not show any message.

**Comment by john-preston** [comment]
@omoridi Is it possible to remove them in https://web.telegram.org?

**Comment by DaFri-Nochiterov** [comment]
I heard this: "You can't remove deleted user from your group, you only can wait for some time (~1 week) and this user should disappear"

**Comment by haevalencia** [comment]
@john-preston @DaFri-Nochiterov That does not happen, actually can not delete these "ghost" users. The same on Android. In support they told me that only can be done directly with iOS Telegram 😓. I have seen some users disappear, but after a long, long time.

**Comment by john-preston** [comment]
@haevalencia Is it possible to remove them in https://web.telegram.org?

**Comment by haevalencia** [comment]
@john-preston 
It's not possible. Luckily I could find a user with these caractarísticas since Telegram web only shows the last 50 users connected to the group. I tried it in Chrome and Firefox on Windows 10.

![web](https://cloud.githubusercontent.com/assets/17348259/14059627/a51b3410-f325-11e5-9faf-323cf85e32d8.png)

`Method: channels.kickFromChannel
Url: N/A
Result: {"_":"rpc_error","error_code":400,"error_message":"USER_ID_INVALID"}
Stack: u@https://web.telegram.org/js/app.js:29:4521
https://web.telegram.org/js/app.js:29:5814
l@https://web.telegram.org/js/app.js:13:12015
https://web.telegram.org/js/app.js:13:12187
$digest@https://web.telegram.org/js/app.js:13:18028
$apply@https://web.telegram.org/js/app.js:13:19879
https://web.telegram.org/js/app.js:13:27217
a@https://web.telegram.org/js/app.js:12:3100
https://web.telegram.org/js/app.js:12:4550
n@https://web.telegram.org/js/app.js:3:16925`

**Comment by diazbastian** [comment]
@john-preston I've tried using TDesktop and Webogram and may delete users with deleted accounts. I think it was a bug server side.

Cheers

**Comment by stek29** [comment]
@diazbastian may or may not?

@auchri <kbd>api issue</kbd>? :)

**Comment by diazbastian** [comment]
@stek29 Currently is possible to expel users with deleted accounts.

Tested: 
Telegram Desktop 0.9.47 alpha and webogram stable

**Comment by haevalencia** [comment]
Yeah, in Webogram does not throw any errors :+1:

**Comment by Aokromes** [comment]
This ticket can be closed, telegram desktop now can kick deleted accounts.
