### ISSUE TITLE
[Improvement] Show full tweet text.

### ISSUE THREAD

**Issue by LuckyTea** [telegramdesktop/tdesktop#1912]
140 characters is not so much to cut the text in the preview tweet. Can telegram show full tweet text when i post link in chat?

### Configuration
**Operating system: Windows 10
**Version of Telegram Desktop: 0.9.42

**Comment by john-preston** [comment]
@LuckyTea This 140 characters can be 70 lines of text :)

**Comment by LuckyTea** [comment]
Fair enough. My bad but anyway.
Are you afraid that people will abuse tweets with ASCII art or 4 lines on is a standard guideline, and you do not want the perception of users?
Anyway thanks for the reply.

**Comment by john-preston** [comment]
@LuckyTea Currently all texts in webpage previews with an image at the right side are cut to four lines (+ title, to be just like the image) because text rendering does not support floating of the text around the image. And if you leave it in a small column (without floating around the image) it won't look nice.
