### ISSUE TITLE
Groups with no admin

### ISSUE THREAD

**Issue by parsipixel** [telegramdesktop/tdesktop#1916]
### Steps to reproduce
1. Create a group
2. Add members
3. Leave the group
### Expected behaviour

Maybe the first member after admin in the group should be the next admin
Or admin can not leave the group without assigning the next admin
### Actual behaviour

In this situation no one is admin of the group :|
### Configuration

**Operating system:**
IOS

**Version of Telegram Desktop:**
0.9.42
### Logs

Insert logs here (if necessary)

You can type "debugmode" in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type "debugmode" in settings again to disable logs.

**Comment by stek29** [comment]
Wait, did you mix up Actual and Expected behaviours?

**Comment by parsipixel** [comment]
Edited*

**Comment by Aokromes** [comment]
´Well, in fact, someone can invite back old admin and he will recover admin :)

**Comment by mirh** [comment]
I don't think this has anything to do with desktop client per se. 
You should probably contact in-app support.

**Comment by KinIcy** [comment]
Currently happening to me. The admin from the group has leave and now there is no admin and nobody can reinvite him.

Telegram Desktop 0.9.59
![image](https://cloud.githubusercontent.com/assets/10891866/17267778/2a0ef70a-55d8-11e6-80bc-213ad19f2d0e.png)

**Comment by stek29** [comment]
But how is it related to TDesktop? It's server-side issue.

**Comment by stek29** [comment]
Telegram is against any transfers of ownership: for bots, channels, groups, etc.
It's because they don't want them to be selled.

**Comment by mahyar-abdoli** [comment]
So if the admin deletes his account after leaving the group and creates new account even if you can add him back I think he wont be the admin any more.

**Comment by stek29** [comment]
> deletes 
> creates **new** account 
> won't be admitted

Of course, because those are absolutely different accounts.

**Comment by jarhill0** [comment]
It's disappointing that there seems to be no way for any user to gain admin status if the one and only admin leaves. This issue is of course not related directly to Telegram Desktop, but, because the server code is not open source (and it should be, but that's another matter), this is the most appropriate place to discuss.

When the only admin leaves a group, it leaves the rest of the group stuck in a zombie chat, because they can all still message as before, but none of them can add or kick people. 

In the case that the only admin leaves the group, ownership should absolutely be passed off to the next-longest member.

**Comment by stek29** [comment]
@jarhill0 what if admin returns shortly after that? what if next-longest member kicks everybody and deletes all messages?

**Comment by jarhill0** [comment]
@stek29 

> what if admin returns shortly after that?

The way it is currently, it is impossible for the admin to return.

- Nobody becomes admin when the admin leaves, so nobody in the chat can re-add the admin
- The admin doesn't have the ability to re-add themselves without a join link, which they don't always have. 

> what if next-longest member kicks everybody and deletes all messages?

If the next longest member kicks everybody, that's too bad. But *someone* having control is better than nobody having control.

An alternative to solve the problem of the next-longest member abusing their power would be to allow the creator or only admin of a group to re-join their own group no matter what. Unfortunately, this is currently only possible if they saved a join link.

---

Ultimately, the problem I care most about is the situation where a group can end up as an "orphan," with no admin and no way for anyone to become an admin. If there were some solution implemented that allowed someone to "adopt" one of these orphan groups, I would consider the issue solved.

**Comment by stek29** [comment]
@jarhill0 btw, most of the time when users complain about orphan groups Telegram just recommends them just to move to new group.

But I agree with your thoughts about lacking any way to bring admin back to group.

**Comment by ryukinix** [comment]
Interested on that behavior. I was earlier the creator of https://telegram.me/uapda, but I deleted my account for personal reasons and when I go back to group I can't have even be a normal-admin with ban/add/maintaining powers. It would be almost ok cannot be a creator again, but why other admins that I nominated cannot pass admin to me? This doesn't makes sense for me. Only creators can share admin-powers with others? At least this on super-groups should be allowed:

1. When a creator account is gone, the older admin now have more powers than before, as creating more admins.

That way I, the creator of group, can get back at least a minimum of power to maintaining the group. 

This is quite sad and annoying, mainly because is a old group, with really SO MAANY messages and so hard to move out to a new group ignoring all the stuff.

Looking for a solution since 2017...

**Comment by auchri** [comment]
@ryukinix Did you contact the Telegram support?

**Comment by ryukinix** [comment]
@auchri as @jarhill0 I tried, but there is not such any useful thing that they can do for us :(

**Comment by stek29** [comment]
Neither can TDesktop

**Comment by format37** [comment]
it cold be convinient to native vote for new admin

**Comment by Aokromes** [comment]
this doesn't belongs here, ask twiteer telegram
