### ISSUE TITLE
Can't select more than 100 messages.

### ISSUE THREAD

**Issue by LeoDJ** [telegramdesktop/tdesktop#2045]
### Steps to reproduce
1. Open any chat
2. try to select more than 100 messages

### Expected behaviour
More than 100 Messages should be selectable

### Actual behaviour
The first message up until the 100th message get selected (chronologically). The following messages won't be selected.

### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
0.9.49
### Logs
No logs necessary.

### Comment
I didn't find an issue already on this topic. So I hope this is not a duplicate.
I'm not even sure if this is a real issue at all. I was just bummed to find out that I couldn't forward more than 100 messages. (I wanted to forward a lengthy conversation to a friend and I think I remember I could select more than 100 messages in the past)
If the limit has to stay due to stability reasons, maybe bump it up to 1000 or so.

**Comment by Vilmodao** [comment]
It's still here. 
V 0.10.11

**Comment by john-preston** [comment]
Well, there is a server-side limit for one-time forward or delete messages (it is 100 or a bit more), so it makes sense to make the same limit in the app. This is intended.

**Comment by ropinheiro** [comment]
Sorry, but I really need this... if there is a limit in the server, just code some cycle in the app to send 1 command for each 100. At least for the DELETE one, that is the one I need. I want to clear some group conversations for privacy reasons from time to time without needing to delete the entire group and create another one.

**Comment by stek29** [comment]
@ropinheiro use "Clear history" option.

**Comment by auchri** [comment]
Why do you want to delete those messages?

**Comment by ropinheiro** [comment]
The group is a place where Deaf people write about sensitive personal topics. I'm in charge of regularly deleting the conversations to give everyone some relief that it doesn't persist forever.

**Comment by auchri** [comment]
You know that messages are only deleted for you and they are still visible for other members?

**Comment by ropinheiro** [comment]
When it's a supergroup, all messages I delete are also removed for all members. I verified that...

**Comment by stek29** [comment]
@ropinheiro because you can't delete messages in supergroups (except your own messages) unless you're an admin.

**Comment by ropinheiro** [comment]
@stek29 I'm the admin of that supergroup.

**Comment by stek29** [comment]
@ropinheiro anyway, API doesn't support this kind of thing (mass deletion of messages in channels/supergroups) because it may be dangerous (what if someone hacks your account and cleares whole chat in a couple of seconds?)
And even if TDesktop tried to delete messages in cycle, it would get FLOOD_WAIT really soon.

I'd suggest you to make something around tg-cli.

**Comment by ropinheiro** [comment]
Well, I understand your concerns, but there are easy workarounds. I have just cleared the entire chat, 100 messages a time, by repeating it manually 30 to 40 times until all messages got cleared. I took some 5 minutes to do that for about 2 months of intense chatting. Now, I think that if some hacker really wants to clear the whole chat, taking 5 minutes to do it manually instead of a couple of seconds would not stop him/her to accomplish the objective. Moreover, FLOOD_WAIT can also be avoided by adding 5 seconds of pause between commands (the time I took manually selecting 100 messages, pressing delete and ENTER - and the application didn't stop me from deleting everything, so I assume that pause is enough for a coded script too). Again, not rocket science or great inconvenience for a lightly motivated hacker. Just waste of time for real users, I think :)

**Comment by stek29** [comment]
@ropinheiro 
> I understand your concerns

That's not mine concerns, that's Telegram's concerns.

> FLOOD_WAIT can also be avoided by adding 5 seconds of pause between commands

All those things will make code more complex and may result in mistakes.
I think it would be better to allow selection with shift+click, so it would be easier to select multiple messages.

**Comment by ropinheiro** [comment]
> I think it would be better to allow selection with shift+click, so it would be easier to select multiple messages.

Currently, I can (from the laptop, not mobile devices) click somewhere in the chat, then "drag" upwards or downwards, causing the chat to scroll while selecting multiple messages. It will take up to 5 seconds to scroll enough to select the maximum number of 100 messages (if there are images in the middle of the selection, less messages will be selected due to the constant pace of the scroll and the fact that an image usually takes the space of N messages. Same for long multi-line messages that count as one).

More useful would be a shortcut like CTRL+A to automatically select 100 messages starting backwards from the currently selected message, thus skipping the boring scrolling action, so that we could do quicker "select, CTRL+A, delete, ENTER" iterations.

But that would probably collide with the FLOOD_WAIT, as now the commands will be sent with a faster pace.

**Comment by radrow** [comment]
Ok, but what if I would like to copy these messages out of telegram? Exporting data is too heavy operation for this and takes a lot of time. Maybe it would be better to lock forwarding/deleting up to 100 messages, but leave just the selection to be unlimited?

**Comment by ropinheiro** [comment]
There is still no easy workaround? :) I found one, but it rather silly: I just create a new group once each 3 or 4 months, then move everyone to the new group, deleting the former (thus causing all messages to be deleted at once). Almost two years after I reported this, it is still a need.
Answering @radrow, what if CTRL+A selecting the maximum of 100 messages, then another "A" (making the sequence CTRL+A+A) to select everything? Anything that could make this easier for admins...

**Comment by ropinheiro** [comment]
I also noticed that there is an option to export chat history that seems to fit @radrow  needs, so...

**Comment by catsuryuu** [comment]
I would like to have a possibility to just copy (Ctrl+C) some large fragment of a conversation. I used to do this very often when I was using Messenger before Telegram. In Telegram this action is quite frustrating...
I suggest to let the selection be larger than 100 messages and just disable/hide the `FORWARD` and `DELETE` buttons (and `Forward Selected` and `Delete Selected` from the context menu) in this case.
What do you think about this idea?
