### ISSUE TITLE
Why doesn't Telegram let every system handle emojis?

### ISSUE THREAD

**Issue by DarthJahus** [telegramdesktop/tdesktop#2111]
Each platform has its own emojis and Telegram is trying to use its own set, making them more coherent with the design.
Why doesn't it just let that be handled by the host?

**Comment by stek29** [comment]
Each? Even Linux? Even Windows 7?

**Comment by z3ntu** [comment]
I am pretty sure, that Telegram tries to use one single emoji set (-> Apple's) because of the fact, that many emojis look very different / have a different meaning on different platforms (see http://motherboard.vice.com/read/what-the-emoji-youre-sending-actually-look-like-to-your-friends for example). I also personally prefer the Google (Noto Color) Emojis, but apparently Telegram decided for the Apple emoji.

**Comment by stek29** [comment]
@z3ntu Because first Telegram app was iOS app maybe?

**Comment by Sushubh** [comment]
Windows 10 has beautiful emojis. Android has their own emoji set. Telegram usage of their own emoji is kind of annoying because what you type using your keyboard is not what you see inside the Telegram chat app. I personally hate the emoji set used by Telegram and based on previous bug reports related to emojis that have been closed by the developers, I do not think this behavior is going to change. I would love to see Telegram using the emoji set of the platform on which it is running and only use their own set on platforms where native support is not available.

**Comment by z3ntu** [comment]
@Sushubh you should read my comment why they probably will never do that. And tbh I find the Windows 10 set really ugly but just my opinion.
And the "telegram set" is from Apple/iOS.

**Comment by AndydeCleyre** [comment]
I agree with the original report here, but if it does have to be hard-set across the board, I would vote for [EmojiOne](http://emojione.com/).

**Comment by Sushubh** [comment]
Righto. EmojiOne is being used by a lot of platforms. XenForo 2 is using them. Discord is using them. If maintaining uniformity is the goal, it is a pretty solid alternative to Apple's emojis. Posted this as this thread is now marked as a discussion! Noticed today that the desktop app does not support the emojis added in the latest build of Android. I get a black and white version instead of the ones shown in the app.

**Comment by julianxhokaxhiu** [comment]
What was the outcome of this discussion? It looks like to me in a dead-end. Still as of today I get also black and white emojis on Linux, although I did set EmojiOne as the my system-wide emoji font ( which works really well ).

Can you bring an option in the interface to either use fully the system fonts or either yours? This would at least make happy whoever complains about this. Then when you will come up internally with a decision you can update the client to use that one.

But providing an option here won't hurt no one. It's just a win-win feature. I hope you can really consider this.

**Comment by Sushubh** [comment]
This also kind of becomes an issue with new emojis being added at a much faster rate. i do not think telegram has added support for the latest that were added in android p for example. 🥴 Works fine on Android app but shows up as block on the Windows app. I am not sure how it works on Telegram Android as it appears as stock android emoji unlike the older ones. I wonder if Telegram is using EmojiCompat?

**Comment by danesusername** [comment]
You can argue that using the Apple emoji makes it more consistent across Telegram users, but I'm more concerned about consistency within my own devices. I hate that when I open up Telegram I see a different emoji set from the rest of my phone. Why can't this just be an option for the user to decide?

**Comment by AndydeCleyre** [comment]
@danesusername I wholeheartedly agree with this sentiment broadly, and it is the crux of a bunch of issues on this tracker. 

Last I heard, the primary developer was still largely against consistent UI/UX from the users' perspective, prioritizing consistent UI from the developer's. I do hope this approach is reconsidered eventually.

**Comment by null-von-sushi** [comment]
Not in the scope of this issue, but it's a shame that someone (who knows what they're doing, which I am sorry to say isn't me) doesn't just fork the project and patch it to use system stuff. I mean, it's open source at least.
That said, I obviously think having a decent project upstream in the first place is better then X amount of forks to change something...

**Comment by sammoth** [comment]
You can choose emoji sets now

**Comment by Sushubh** [comment]
not on the android app though. but i guess does not apply here coz this page is focused on the desktop app. would have liked the emoji picker on all official apps for uniformity. also it does not support system emoji. you can pick from three third party emoji sets.

**Comment by JakeSays** [comment]
Personally, I much prefer consistency across devices instead of having to deal with different emoji sets. I use telegram on windows, linux, android and ios. Having that consistency is much appreciated.

**Comment by julianxhokaxhiu** [comment]
I'm not sure if this was implemented incidentally or not, but custom Emoji set support is now available mainstream on the client since a while. Please don't comment this issue anymore.

@auchri please lock this if you can. Thank you in advance.

**Comment by DarthJahus** [comment]
I don't think it should be locked. As you said, @julianxhokaxhiu, Custom Emoji has been implemented. But on Windows 10, for example, it's still not possible to use the native emojis. Or at least, they should add the Win10 emojis to the available sets. It would be a correct workaround for this specific request.
