### ISSUE TITLE
[feature request] voice recording

### ISSUE THREAD

**Issue by White-Oak** [telegramdesktop/tdesktop#22]
It's my favourite feature of pocket Telegram, my friends and I always use it for sending short voice reports/messages. Will it be implemented in desktop app?

**Comment by claudioschell** [comment]
Please add Voice Message on Desktop

**Comment by mbnoimi** [comment]
+1

**Comment by Mindstormer619** [comment]
This has not had any attention in a while. Is it still in the works?

**Comment by White-Oak** [comment]
Well, yeah, almost a year has passed. Though I'm still curious.

**Comment by ppparadox** [comment]
+1

**Comment by phplego** [comment]
+1

**Comment by SanKro** [comment]
you can use cutegram -> http://aseman.co/en/products/cutegram/ its a much better client and has voicememo support for the desktop :)

**Comment by mbnoimi** [comment]
@SanKro cutegram seems promising but unfortunately it doesn't support Windows (I'm using Windows portable distro of Telegram)

**Comment by 24252411** [comment]
I ALREADY CANCEL MY TELEGRAM ACCOUNT A FEW DAYS AGO , ESPECIALLY WHEN I NOTICE  THAT I WAS RECEIVING , MANY MAILS OF PEOPLE Y DONT HAVE IDEA WHO IS , OR WHAT KIND OF PEOPLE IS , I REPEAT FO 7 TIMES Y CANCEL MY ACCOUNT INMEDIATELY .IF I RECEIVE ANOTHER THING FROM YOU ., I WILLBE FORCEW TO GO TO THE POLICE.TANK YOU

**Comment by 24252411** [comment]
REPEAT I CANCEL INMEDIATELY MY PERSONAL AND FREE ACCOUNT WITH YOU AND I ALREADY CANCEL A FEW DAYS AGO MY ACCOUNT IN TELEGRAM .THIS IS THE 8 TIME I REPEAT THIS , I CAN DO IT BECUSE WAS A FREE AND ONLY I WAS THE OWNER .
THANK YOU
gaira.bohorquez@gmail.com

**Comment by Katzen-Gott** [comment]
@24252411 1st of all, please stop SHOUTING. 2nd, try this recipe: https://telegram.org/faq#q-how-do-i-delete-my-account . 3rd, if previous doesn't help, try contacting Telegram Support: https://telegram.org/faq#telegram-support .
I hope this helps you. And please remember that tdesktop and Telegram are different projects and don't mix them up.
I'd also like to notice, that I can't see how Telegram or TDesktop might make you receive spam, because I can't remember a place where any of these would ask you for your email.

**Comment by Mindstormer619** [comment]
@Katzen-Gott Idiots abound.

**Comment by Katzen-Gott** [comment]
@White-Oak It was added in v0.19.8. Cold you please close the issue? (there is a button below the comment box)

**Comment by Mindstormer619** [comment]
@Katzen-Gott Er, no. I am running v0.8.17 (latest stable) and there is no such update yet.

**Comment by auchri** [comment]
its a developer version :)

**Comment by Mindstormer619** [comment]
Ah, I suppose it can be closed after it trickles down to the stable. It might not be in the next stable version for all we know.

**Comment by auchri** [comment]
The stable version with the voice messages is already released (0.8.20)

**Comment by brunobsouzac** [comment]
How the same subject, I'll leave what I wrote in another post.

The new update 0.8.21 released the voice message, but it would be more convenient for those using the desktop a shortcut key to tighten and talk instead of using the mouse.

Something like Ctrl + Space (and a warning users about the function)

And finally, radio voice messages with auto play, so we would listen in real time as a Voxer / Zello / Radio. The Telegram iOS already have this option but it is not released to the Android or WP. To disable this feature if you want, an exposed button on the chat would be ideal.

It would be perfect for Desktop, iOS, Android and WP.

**Comment by auchri** [comment]
@brunobsouzac It's maybe a nice idea, but its better to open a new issue for this enhancements.

**Comment by brunobsouzac** [comment]
@auchri My English is very bad, my apologies.

But what I did is I'd better create a new issue and put this idea?

![1](https://cloud.githubusercontent.com/assets/12419098/7947958/e6c54db0-0956-11e5-88da-9b8c03404139.png)

**Comment by auchri** [comment]
Yes create a new issue with your idea would be fine :)

This issue should be closed tho @White-Oak

**Comment by brunobsouzac** [comment]
@auchri great

**Comment by White-Oak** [comment]
Yeah, finally! 1 year of waiting worths it.

Thanks devs.
