### ISSUE TITLE
Received audios does not play. I click to play but he instantly stops. Works after restart.

### ISSUE THREAD

**Issue by igorlemosvicente** [telegramdesktop/tdesktop#2238]
### Steps to reproduce

I do not know.
### Expected behaviour

I click play in the audio and he play.
### Actual behaviour

He don't play. He instantly stops.

**Version of Telegram Desktop:**
Telegram for Linux 0.9.56

**Comment by john-preston** [comment]
@igorlemosvicente Are there any errors in log.txt?

**Comment by zumoshi** [comment]
I have a similar issue , I wanted to post a new issue but I found this one.
basically, it happens when the audio device that telegram is bound to gets disabled/disconnected.

**Steps to reproduce**:
open telegram
go to Control panel -> hardware and sound -> sound
right click on default device and select disable
right click on it again and select enable

**expected behavior**:
telegram re-evaluate its playback device on failure and gets bound to default device or display a meaningful error if no such device exists

**actual behavior**:
does nothing.


win8.1 x64 , telegram 0.9.56

---

to be more precise about why I encounter this a lot, it is because I have two devices (wireless headphone and speakers) and to force programs to use the other one if they were running before I switched the default device I disable the default device. (or unplug the wireless headphone while it was default)
other programs start using the second (now default) device but telegram doesn't play anything until restarted. 

the only line in log.txt that i think might be relevant is this one:

    [2016.07.21 20:50:15] Getting difference! no updates timer: 0, remains: -1

**Comment by zumoshi** [comment]
still waiting for an answer? was there something else I should've included in my report ?

**Comment by zumoshi** [comment]
@auchri the problem still exists on telegram v0.10.1
can you please update the labels on this issue, I believe the current label prevents it to be seen by the developer. or at least tell me that you don't intend to fix it ... it's been almost a month, I don't expect a fix right away but at least an acknowledgment of the bug would be nice.

thanks in advance.

**Comment by john-preston** [comment]
@zumoshi Well, the original issue is about the Linux play problem, while yours is about not updating the audio device while running on Windows, so the label and the issue itself don't belong to your problem.

Your issue is known in the OpenAL library that is used in tdesktop, this library doesn't have a way to keep up to the changing default output device :( perhaps a different library should be considered, but I don't know which.

**Comment by stek29** [comment]
@john-preston what about libsound.io? 

Also, this happens on OS X too sometimes, but I'm not sure how to reproduce it...

**Comment by pleabargain** [comment]
I can confirm that the desktop v. of telegram 0.10.1 audio playback does NOT work on Ubuntu 16.04. The Android v. of telegram DOES play the same audio files correctly.

here's the video
https://youtu.be/2dyuII788_g

**Comment by LuKePicci** [comment]
It's very easy to reproduce this issue. Just start tdesktop and make sure audio works as expected, than connect an external audio playback device (USB/Bluetooth headset, HDMI monitor, remote desktop audio etc...) and audio playback starts failing. App restart is needed to get it working again.

**Comment by Germano0** [comment]
Confirming on Fedora 24

**Comment by Dalboz** [comment]
This issue still exists on telegram 5.1.1 (166797) Stable running on Mac OS 10.11.
Comments?

**Comment by john-preston** [comment]
@Dalboz 5.1.1 is not Telegram Desktop. Please try Telegram Desktop from https://desktop.telegram.org
