### ISSUE TITLE
[Enhancement] Notify on reply even if the group notification are switched off

### ISSUE THREAD

**Issue by dmarrazzo** [telegramdesktop/tdesktop#2329]
# Steps to reproduce
- User1 switch off the group notification
- User1 send a message to the silent group
- User2 use reply feature to reply to the message sent by User1
- User1 has no evidence about the reply to his initial message
# Expected behaviour

User1 should receive a notification and the telegram icon should have a badge with incoming message.
_Optionally 1: to define a different sound for reply
Optionally 2: to use a different color for the icon badge when a reply message is present (yellow?)_
# Actual behaviour

User1 has no evidence about the reply message

**Comment by stek29** [comment]
Issue name is a bit confusing.
TDesktop already notifies on reply and mention.
But badge color isn't changed.

**Comment by dmarrazzo** [comment]
@stek29 in my experience, you are notified for mentions but not for replies.
The title of the issue was misleading. Using different colours is a "nice to have" feature.

**Comment by stek29** [comment]
Closing as invalid, since notifications from muted chats do arrive for replies (**not forwards**).
Feel free to open a new issue for badge counter, if you don't want us to fix the issue.

<details><summary>And it looks like you don't</summary>
![image](https://user-images.githubusercontent.com/11808223/29931219-415bcc82-8e79-11e7-9501-2137c28b06a7.png)
</details>
