### ISSUE TITLE
Не убирается кнопка "Прокомментировать" на канале

### ISSUE THREAD

**Issue by machinsoft** [telegramdesktop/tdesktop#23932]
### Действия по воспроизведению

1. Создайте канал
2. Добавьте к каналу чат
3. Напишите пост
4. Удалите пост в чате

### Ожидаемое поведение

После удаление поста в чате, кнопка "Прокомментировать"  на канале должна исчезнуть

### Фактическое поведение

Кнопка "Прокомментировать" не исчезает и ее нельзя нажать.

![img](https://i.ibb.co/nQ2q4tb/1.png)

### Операционная система

windws 10/ android

### Версия Telegram для рабочего стола

v 3.4.8 19.01.22

### Источник установки

Static binary from official website

**Comment by Aokromes** [comment]
english plz, this tracker is english only.

**Comment by machinsoft** [comment]
> english plz, this tracker is english only.

Use the google translator

**Comment by FrayxRulez** [comment]
> > english plz, this tracker is english only.
> 
> Use the google translator

no u

**Comment by stek29** [comment]
> > > english plz, this tracker is english only.
> > 
> > 
> > Use the google translator
> 
> no u

no u

**Comment by bymaer** [comment]
> > > > english plz, this tracker is english only.
> > > 
> > > 
> > > Use the google translator
> > 
> > 
> > no u
> 
> no u
![266-2668327_image-yellow-reverse-card-uno-hd-png-download](https://user-images.githubusercontent.com/37290594/152568158-fb20bad7-077a-49f7-bbd3-18b63fa789b2.png)

1. Create a channel
2. Add a chat to a channel
3. Write a post
4. Delete a post in a chat

**Expected Behavior**
After the post in chat is deleted, the "Comment" button on the channel should disappear

**Actual Behavior**
The "Comment" button does not disappear and cannot be clicked.

**Comment by 23rd** [comment]
Can't reproduce. You can upvote [this one](https://bugs.telegram.org/c/3798) if you want.
