### ISSUE TITLE
Top 1px of system title bar (Windows) fully transparent since version 3.4.6 or 3.4.7 beta

### ISSUE THREAD

**Issue by adrianghc** [telegramdesktop/tdesktop#23931]
### Steps to reproduce

Set the title bar style to system-native on Windows.

### Expected behaviour

The title bar should look like a native title bar normally should on Windows.

### Actual behaviour

Since version 3.4.6 beta, the top 1 pixel of the title bar is not filled in with color and is instead fully transparent.

![image](https://user-images.githubusercontent.com/11506007/150199194-8cd00c0b-20fe-4468-85b8-996266491bd4.png)

![image](https://user-images.githubusercontent.com/11506007/150199394-700f40bf-211e-4829-bb0a-0601940c53ac.png)

![image](https://user-images.githubusercontent.com/11506007/150200092-0647d928-bee1-4c97-a91e-49aea928b396.png)

![image](https://user-images.githubusercontent.com/11506007/150200188-06e03640-c3ae-4340-84de-81f9bc886fee.png)

### Operating system

Windows 11 22000.466

### Version of Telegram Desktop

Version 3.4.7 beta (however, I noticed this after an update that showed me the changelog for 3.4.6 beta, which makes me think I might have skipped a version.)

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
@adrianghc This shouldn't be possible :)

What is your Windows interface scale?..

**Comment by adrianghc** [comment]
> @adrianghc This shouldn't be possible :)
> 
> What is your Windows interface scale?..

125%

**Comment by PeterNjeim** [comment]
I'm having a slightly different but certainly related problem. I'm at 100% scaling, but the top pixel doesn't work to click the close, minimize, and maximize buttons. This is explained in more detail in #23933

**Comment by john-preston** [comment]
@PeterNjeim Does it look like that in this case?

![image](https://user-images.githubusercontent.com/17900494/150301106-90404043-7386-4987-a1e8-f76f5db58ad2.png)

I've added a 1px padding to the controls in windowed mode, because Windows visually cuts 1px out of the window so the buttons were looking clipped without that. (you can see the semi-transparent top line that belongs to the window, but Windows doesn't paint it, painting the shadow instead)

If I snap the window to the right side, so it visually takes all the space, then the button works in the corner:

![image](https://user-images.githubusercontent.com/17900494/150301351-3fbf151e-503e-49e7-9a57-6ac6f0f1a618.png)

**Comment by john-preston** [comment]
@adrianghc I'm not sure it is "since 3.4.6 beta". I've tried to download 3.4.3 stable and enable the native system frame:

![image](https://user-images.githubusercontent.com/17900494/150304536-704942bc-4640-46c5-bdb3-9d733182e944.png)

Also I took the first version that introduced a system window frame (2.1.18) from July 2020 and guess what:

![image](https://user-images.githubusercontent.com/17900494/150305114-1e18b388-beff-48a4-bbea-babb83d9bef9.png)

So this either was from the start or it was introduced in some Windows 11 update :(

**Comment by john-preston** [comment]
@adrianghc ok, look at the Windows Command Prompt:

![image](https://user-images.githubusercontent.com/17900494/150305381-351e198a-9692-4f1b-a8a3-54be780448c3.png)

Sorry, this is Microsoft doing its thing ¯\_(ツ)_/¯

**Comment by adrianghc** [comment]
So why couldn't it have been introduced between 3.4.3 and 3.4.6? It worked for me then and it doesn't work for me now. It broke after updating Telegram, not after updating Windows.

**Comment by john-preston** [comment]
@adrianghc Look at my screenshots please. Even the system command prompt window behaves this way and also all the versions of Telegram Desktop that had a system frame option.

But you can switch to the non-native one, it is as good now =) And doesn't have this problem.

**Comment by adrianghc** [comment]
@john-preston At first glance the title bars in your screenshots looked fine to me, probably due to them using light instead of dark mode. Now I see what you mean. I just restarted my PC for unrelated reasons and the title bar looks right now. This suggests it may not be a problem that happens 100% of the time. It may also indeed suggest that it's a Windows issue and that I simply might have missed it before. I just don't think I would have done that for several months, to be honest. I'll see if I can reproduce the issue again and also with other programs (I use Windows Terminal instead of the old one so I never noticed it there).

**Comment by john-preston** [comment]
@adrianghc Maybe it happens when you switch windows scale without signing out and back in?.. But anyway TDesktop has nothing to do with it, because at the moment TDesktop has this problem (that I happened to reproduce) all versions have it at once and also some other non-TDesktop windows as well.

**Comment by john-preston** [comment]
@adrianghc In my case I switched the scale from 200% to 125% and got the issue. Perhaps if I restart the computer after that it won't be there.

**Comment by adrianghc** [comment]
@john-preston Curiously 125% and 200% are also the scaling factors that I use, though I use the 200% only rarely (when I undock my laptop). I think you're right, this is probably a bug when you switch from 200% to 125% (perhaps others too). Now why I never noticed it before, I don't know. Not to say it's impossible I could have missed it, but I do use Telegram very much. Perhaps just a combination of it possibly not happening 100% of the time, me not switching scaling often and me not always being as observant as I was when I noticed this. ^^

**Comment by PeterNjeim** [comment]
It looks like this: 
![image](https://user-images.githubusercontent.com/26418974/150301823-01d0772e-320f-496e-bdd2-f9e00f0238de.png)

Snapping does make it work, but I can't do that since it doesn't preserve the position when I close and open it (which I do frequently), as Windows handles snapped windows very oddly. What I do is resize the window by dragging the bottom right corner of Telegram to the bottom of the desktop (to the taskbar), and wiggle it left and right repeatedly until the window becomes the full height of the desktop, but without actually triggering the actual snap. Then I make the window the minumum width, and use mouse keys to drag it perfectly to the right edge of my screen. This way, it preserves its location. 

https://user-images.githubusercontent.com/26418974/150313617-8300e110-cfa4-4e7a-8255-729ec2d98d7e.mp4 

Since this issue is closed now (since it was related to the non-integer scaling), I think I will reopen my previous issue, as it is directly caused by the new snapping support update, and this never happened on earlier versions of Telegram, where the buttons aren't pressable on the top pixel.
