### ISSUE TITLE
Please give the option to turn off link preview. This is very annoying when typing/editing a message with domain-like strings.

### ISSUE THREAD

**Issue by uFire** [telegramdesktop/tdesktop#23946]
### Is your feature request related to a problem?

While typing/editing messages containing domains or even something visually similar to, I have to click that "x" all the time. This is very annoying and inconvenient.

### Describe the solution you'd like

Just add a switch to both desktop and mobile apps to have us an ability to turn that feature off on specified device. Or at least make it appearing only once per message write/edit session, so there will be no need to click "x" all the time while typing a long message with multiple "anything.anything" combinations.

### Describe alternatives you've considered

No alternative other than clicking, clicking and clicking that "x" all the time.

**Comment by RememberTheAir** [comment]
> Or at least make it appearing only once per message write/edit session

This is how it should work - unless you edit (or add) a link while typing a new message/edit an existing one. If you don't edit existing urls, the link preview should not be fetched again

By the way, this is a cross-platform request (since behavior and options should be consistent on every platform) - you can upvote [this card](https://bugs.telegram.org/c/3195) on the official bugs/suggestions platform(found it in #687)

**Comment by uFire** [comment]
@RememberTheAir thanks, I have it upvoted.

As for the behavior, you are right, maybe I was a bit wrong. But anyway, it's pretty annoying. And yes, it happens when editing the same post. I have a template containing multiple URLs in "Saved Messages" and several times a day I have to edit each link and then forward it to some contact, and this simple task has become a real struggle with the telegram URL fetcher. :)

Why not just give users the option to turn it off, after all, there have been a lot of requests for this simple feature over the past few years.
