### ISSUE TITLE
Hard to resize video PIP window in wayland

### ISSUE THREAD

**Issue by brauliobo** [telegramdesktop/tdesktop#23956]
### Steps to reproduce

1. Open a video
2. Set it to PIP

### Expected behaviour

In X11, the resize keeps the aspect ratio and it is easy to land in the resize area

### Actual behaviour

In wayland it is almost impossible to find the resize area. Also the aspect ratio isn't kept

### Operating system

Archlinux, KDE Wayland, kernel 5.16.2

### Version of Telegram Desktop

3.4.8

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, aspect ratio couldn't be kept due to the lack of appropriate APIs in Wayland protocol (no way to set window position). I can't reproduce another part of your report though - resize area is the same in X11 and Wayland. I'm testing on Weston though since cursor on KDE Wayland works really weird with libvirt/KVM: I can't find where to resize any window of any application, actual cursor position seem to be not where VM displays it and while finding the resize area, it changes like crazy.
