### ISSUE TITLE
Invalid number of viewers with reactions

### ISSUE THREAD

**Issue by Pakulichev** [telegramdesktop/tdesktop#24063]
### Steps to reproduce

1. Send any message in small group chat
2. Wait for some views by other users (at least 2 views)
3. Wait for emoji reaction from another user (first view with reaction, second view without reaction)
4. Set your own reaction on your message (one reaction from you, one reaction from another user and one more view from another user without reaction; generally, 3 views and 2 reactions)
5. View number of views and reactions

### Expected behaviour

You should see text "2/3 Reacted" and 3 viewers on right side panel

### Actual behaviour

You will see text "2/2 Reacted" and 3 viewers on right side panel

![photo_2022-02-12_02-29-40](https://user-images.githubusercontent.com/48885290/153673616-ab8fa5b7-907d-4d25-8275-5faf0b5a204a.jpg)

### Operating system

Windows 10

### Version of Telegram Desktop

3.5.1 x64

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
But yourself isn't counted and isn't shown in viewers list 🤔  The android app works the same.

**Comment by Pakulichev** [comment]
It's strange, but the sender is not taken into account in the total number of views, but his reaction is taken into account, and thus another viewer is lost in the total number 🤔

In theory, either the reaction of the author of the message should not be counted, or it should be added to the final number. Accordingly, there should be either "1/2 reactions" or "2/3 reactions"

**Comment by hessam-kk** [comment]
The problem, which also happens in android, is caused because of that the counter placed on the message bobble, gets updates rarely. here, after clicking on the counter to view accounts that reaction to a message, it queries to the server and gets a fresh update of reaction list; so it cause a contrast with the on-bobble counter and reactions full list.

**Comment by hessam-kk** [comment]
The problem, which also happens in android, is caused because of that the counter placed on the message bobble, gets updates rarely. here, after clicking on the counter to view accounts that reaction to a message, it queries to the server and gets a fresh update of reaction list; so it cause a contrast with the on-bobble counter and reactions full list.
