### ISSUE TITLE
Telegram 3.6 ugly icons [Question] 

### ISSUE THREAD

**Issue by fcore117** [telegramdesktop/tdesktop#24174]
Before 3.6 icons was much more pleasing and more professional looking monochrome.

**Comment by Snugface** [comment]
Absolutely despicable icons, I agree. I know you guys work hard. But please. Those icons just do not need to be here.
They look like a horrendous mess of colors. They are so unnecessarily colorful. Like a kid's book.
They don't fit with the theme at all. And make for an eye-gouging experience.
Not to mention that it is now MORE DIFFICULT to find the menu items one needs! Because those icons draw too much attention to themselves!
<details>
<summary>New icons image</summary>
<img src="https://user-images.githubusercontent.com/17455618/157985260-f5ae6f08-fae2-45fc-bf25-458b28755d17.png"></img>
</details>

Love what you did with the chat folder icons, though. Very nice greyed-out effect for the ones that are inactive.
<details>
<summary>Folder icons image</summary>
<img src="https://user-images.githubusercontent.com/17455618/157985018-7537b80c-ef43-4cfa-ba22-224e36bf5506.png"></img>
</details>

If you really like the icons you've added and you feel like Telegram Desktop needs them - please, make old icons an option. That can be enabled somewhere from the settings.
Telegram is such a rarely clean and _pleasant_ to use application. Please, try to keep it this way for those who value it.

**Comment by fcore117** [comment]
New icons have very hard effect on eyes too that i cannot directly explain. I call for urgent reversal to professional monochrome clear icons.

**Comment by Snugface** [comment]
So from the looks of #24176 this might actually be a bug. And not a feature.
Apparently, these icons are customarily used on MacOS systems. To each his own.
But please bring us back our non-Mac icons!

**Comment by john-preston** [comment]
This is intended, sorry. Has nothing to do with macOS.

Colors can be themed in custom themes to any others.

**Comment by fcore117** [comment]
Then please point out theme change as i do not find that option on my Windows version. Seems again another feature that is made backwards 😞

If anyone knows how to change icons on client then please post here, thanks.

**Comment by DenebTM** [comment]
Jesus Christ this looks horrible, completely out of tune with the rest of the app and the mobile version too. The hell kind of response is "This is intended, sorry"?

**Comment by fcore117** [comment]
> My apologies but this looks horrible, completely out of tune with the rest of the app and the mobile version too. The hell kind of response is "This is intended, sorry"?

Please bring this issue to other channels like Reddit and elsewhere as here it seems to be quite useless to ask. I hope more people notice this soon everywhere.

**Comment by Aokromes** [comment]
> > My apologies but this looks horrible, completely out of tune with the rest of the app and the mobile version too. The hell kind of response is "This is intended, sorry"?
> 
> Please bring this issue to other channels like Reddit and elsewhere as here it seems to be quite useless to ask. I hope more people notice this soon everywhere.

it's not a bug, there is nothing to be fixed, like preston said, icons can be themed.

**Comment by john-preston** [comment]
@Aokromes Icons can't be themed, but icon colors can, you can make them all the same colors if you want.

**Comment by vimpostor** [comment]
> The hell kind of response is "This is intended, sorry"?

Don't blame the devs, Preston is just implementing whatever design he got from the design team. Blame the design team for trying to mix iOS design with Material design.
Did this new icon design mockup come from a new Telegram Design team intern/trainee? It is really unusual to see such bad and inconsistent UI from Telegram, as Telegram was a prime and rare example of good opensource UI/UX.

Maybe the Design team just got lazy and didn't want to create separate designs for iOS and Desktop anymore, but I think that is a terrible decision, especially since Telegram has now an inconsistent mixed Design.

@john-preston Is there any way to report this to the Design team?

**Comment by john-preston** [comment]
@vimpostor Inconsistent is my problem maybe, not everything was yet implemented.. But I doubt that you'll be happier if you don't like changes that were already made 😅

**Comment by vimpostor** [comment]
I dislike the iOS design entirely, yes. I guess I could try out creating a tdesktop theme that is the default + icon colors changed back to monochrome.

If it looks any good, I will share it here but my guess is that it still will look weird.

**Comment by Snugface** [comment]
> @john-preston Is there any way to report this to the Design team?

This is a very valid question. I'd like to ask that this issue remain open, until there is some sorta solution. There will be more people over the coming days who are not happy about these icons. Rightly so.

It's not a bug, that's good. But we'd like to find a way to resolve this. Instead of simply accepting that Telegram menus now look like a clown car and closing this issue.
John Preston, please, tell us all where can this be reported. Because you seem to also not be particularly thrilled about these icons. Why don't we try to at least let the design team that this is how we feel.

I always found myself powerless when some platform, like YouTube, would push a yet another "improved" design out there.
If you can, please help me and others before and after not to feel this way about Telegram and to be able to voice our discontent.

**Comment by Younes-L** [comment]
@Snugface @vimpostor the best place to make noise about this is probably [twitter](https://twitter.com), since the design team are immune to logical arguments, while telegram rely on good publicity :))
we could tag telegram in a thread where we list all the reasons why the new design is inferior in usability (not for telegram to see them, but for everybody else on twitter)

another place is [suggestions.telegram.org](https://suggestions.telegram.org) , it might be less effective as only telegram will see it, on the other hand more telegram users could upvote a card there compared to how many would retweet a tweet.
example : 
* https://bugs.telegram.org/c/15425
* https://bugs.telegram.org/c/15482

**Comment by fcore117** [comment]
@Younes-L i agree, they try to make Telegram to "Christmas tree" but actually should keep quite clean and add actual practical features. Telegram is only IM app left that is fast and comfy compared to every other Electron/Node.js horror.

**Comment by Snugface** [comment]
@Younes-L a most invaluable observation from your edit.
> These frequent and dubious redesigns make tdesktop look completely unprofessional and all they accomplish is alienate and **disturb the workflow** of long time (loyal) users.

Unfortunately, this issue is still closed. And people can't even easily find it in here. As a direct result of this your links to bugs.telegram.org will also go unnoticed by most. I commented under the [new version reddit post](https://www.reddit.com/r/Telegram/comments/tbn3fb/download_manager_new_attachment_menu_live/), but it seems to have gained zero traction, too.

Telegram is the only IM that I find to be clean and easy-to-use, too. UX was always superior to that of Whatsapp, Viber and many others.

@john-preston please, re-open this issue. It's important. And it's not resolved, either. Even if it was just a "question", it now contains some basic guidelines and resources that can actually help interested individuals to make a difference.

**Comment by Aokromes** [comment]
> @Younes-L a most invaluable observation from your edit.
> 
> > These frequent and dubious redesigns make tdesktop look completely unprofessional and all they accomplish is alienate and **disturb the workflow** of long time (loyal) users.
> 
> Unfortunately, this issue is still closed. And people can't even easily find it in here. As a direct result of this your links to bugs.telegram.org will also go unnoticed by most. I commented under the [new version reddit post](https://www.reddit.com/r/Telegram/comments/tbn3fb/download_manager_new_attachment_menu_live/), but it seems to have gained zero traction, too.
> 
> Telegram is the only IM that I find to be clean and easy-to-use, too. UX was always superior to that of Whatsapp, Viber and many others.
> 
> @john-preston please, re-open this issue. It's important. And it's not resolved, either. Even if it was just a "question", it now contains some basic guidelines and resources that can actually help interested individuals to make a difference.

where captain dictates (durov) mariner works (preston)

**Comment by Snugface** [comment]
@Aokromes I seem to understand that design team(or even Pavel Durov himself) approved of the new icon designs. And that resulted in Preston, you, and other maintainers/developers/collaborators complying and integrating them.
But we still can object to them and make our voices heard by gaining more traction, with this issue. Or new issues on Telegram's own tracker.

Or do you mean to say that you, guys, can not/will not join us?

**Comment by Aokromes** [comment]
> @Aokromes I seem to understand that design team(or even Pavel Durov himself) approved of the new icon designs. And that resulted in Preston, you, and other maintainers/developers/collaborators complying and integrating them. But we still can object to them and make our voices heard by gaining more traction, with this issue. Or issues on Telegram's own tracker.
> 
> Or do you mean to say that you, guys, can not/will not join us?

posting here won't help to revert the icons to old version or changing to other version, like preston said, if you don't like colored icons you can change them of colour back to bw with a custom theme.

**Comment by john-preston** [comment]
> Because you seem to also not be particularly thrilled about these icons.

Tbh the icons are fine for me. Yes, this is the same as design changes, happening on YouTube and all other large platforms. They just happen.

I'm sure the only way to get something similar to the old icons is in a fork (there are several forks of tdesktop, like Kotatogram), where icons can be done differently or an option added. If you use custom graphics + changed palette values there is no need to change anything in the code, only colors in the palette and .pngs in the resources. But it's not going to happen in the official build.

> Or do you mean to say that you, guys, can not/will not join us?

I will not, I like the new design. And even if I didn't I wouldn't think it's a big deal. But you can open an issue on suggestions.telegram.org to see (and make them seen by somebody who is not me) the upvotes, I guess. If a lot enough people wants this I guess some fork can add an option. Maybe I can add an experimental setting, but without graphics changing, just the colors.

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/158115510-25b9cf28-1f4c-4ba8-b294-5c65409d4ec7.png)

=)

**Comment by Snugface** [comment]
@Aokromes @john-preston Thanks for all the effort, guys. Especially for having taken the time to explain & suggest how to fix this. Despite you actually not thinking that it needs fixing. That's pretty important.
As I've commented under #24186, I'd already changed the colors; as you two have suggested. It mitigates the issue.
But I still wish we could have grown this. You know, like they do with petitions on change.org.

But I gotcha. Will probably go over to suggestions.telegram.org or issues.telegram.org with this.

Thanks again! All of you.

**Comment by fcore117** [comment]
Good to know that option is coming, professional look is way to go for lot of people who just need pure and distraction free robust communication platform. Thanks @Aokromes @john-preston

**Comment by fcore117** [comment]
Any idea when it will land as a option? thanks.

**Comment by c0re100** [comment]
> Any idea when(what version) it will land as a option? thanks.

Enable install beta version >> Experimental settings >> mono icons

**Comment by fcore117** [comment]
Thanks, way way better and easy to react and i hope it will be forever. Pavel Durov should keep it mind that Telegram is used by a lot by persons who prefer clean and non-flashy experience as communication is priority without using any of flashy unneeded features.
