### ISSUE TITLE
A deleted chat still appears in the list

### ISSUE THREAD

**Issue by christianmtr** [telegramdesktop/tdesktop#24292]
### Steps to reproduce

I made this steps, maybe there is another way to reproduce this.

1. Login in desktop app (macOS) using QR code.
2. Select a contact to start a new chat.
3. Delete that chat for both.
4. Change account.
5. Back to new logged in account.
6. The chat still appears in the list.

### Expected behaviour

That the deleted chat is no longer shown in any client.

### Actual behaviour

I logged in in another desktop app (windows) and the chat appears there also. i tried to delete many times that chat in both clients but when I go to that account the chat still there.
In my phone, that chat is not displayed.

When I start a new chat with that contact in phone, in the desktop apps the chat is displayed but the old conversation is also shown (in my phone is all ok).

### Operating system

Windows, MacOS

### Version of Telegram Desktop

3.6.1

### Installation source

Static binary from official website

**Comment by malaguer** [comment]
I have the same problem in Telegram Desktop (v4.0.2, Windos 10 OS) with official Telegram Channel always appearing when I start the program. The channel is always there whenever I restart the program, no matter how many times I remove it. It is quite annoying.

This issue only happens in Desktop version. On the phone everything works fine.

**Comment by plm203** [comment]
I do have the same issue. I can delete the "resilient" chat in both the web client and the iOS TG app, but on my MacOS high sierra the chat keeps reappearing everytime i launch the app.

Please give us some ideas of things to try. Do not close the issue if you have made no attempt to solve the problem.

**Comment by ntcuong777** [comment]
As of March 16th, this bug still exists on the latest stable release. I'm also expecting that the deleted private/group chats are removed on all clients. Additionally, I can still search for the name of the deleted private/group chats.

Currently, I'm using the Telegram Desktop for MacOS downloaded on the official website. The Telegram app for iOS also experiences the same unexpected behavior.

**Comment by akrotov** [comment]
Same bug for Windows client. Windows 10. Funny that telegram, which claims to be a safe and private messenger ignores such critical security issue for years.

**Comment by eyad4education** [comment]
> Same bug for Windows client. Windows 10. Funny that telegram, which claims to be a safe and private messenger ignores such critical security issue for almost a year.

Not only funny but also annoying

**Comment by akrotov** [comment]
> > Same bug for Windows client. Windows 10. Funny that telegram, which claims to be a safe and private messenger ignores such critical security issue for almost a year.
> 
> Not only funny but also annoying

Sure. It is actually no funny at all. Only God knows how many were arrested killed and tortured due to this bug in various dangerous places of our world due do this bug.

**Comment by kilem02** [comment]
As of April 6th, 2023, this bug still exists on the latest stable release.I can't delete a chat,FFFFFFFFk!

**Comment by kilem02** [comment]
oh bro,i use "switch to Z version" and press F5，then go delete the chat。
Successfully deleted chat.

**Comment by plm203** [comment]
Thank you kilem, i already tried that and it didn't work. But i'm going to try an n+1st time.

**Comment by foxnoodles** [comment]
LOL You guys are a joke of a messenger. This bug is still here. 2 year old chat pops up everytime I link a new device

**Comment by mass4cr3** [comment]
The bug is still there and it's really creepy. A few days ago I signed up on Telegram and received an unwanted message from a user. I blocked the user and deleted the message (both for me and for him). This message is still present and undeletable in version A of telegram web. If I'm on the K version, the message is not there... However, if I install the Telegram desktop application on Windows 10 (via the Microsoft Store or desktop.telegram.org), once open the application the message reappears. Maybe it's time to fix this sync problem between Telegram Web A and K, don't you think?

**Comment by kilem02** [comment]
> Thank you kilem, i already tried that and it didn't work. But i'm going to try an n+1st time.

I am so so so so sorry. o(╥﹏╥)o

**Comment by alorma** [comment]
A +1 user with the same bug

**Comment by dearpanan** [comment]
the  same bug. windows 11.

**Comment by akrotov** [comment]
> The bug is still there and it's really creepy. A few days ago I signed up on Telegram and received an unwanted message from a user. I blocked the user and deleted the message (both for me and for him). This message is still present and undeletable in version A of telegram web. If I'm on the K version, the message is not there... However, if I install the Telegram desktop application on Windows 10 (via the Microsoft Store or desktop.telegram.org), once open the application the message reappears. Maybe it's time to fix this sync problem between Telegram Web A and K, don't you think?

It means that this is not just a bug of Desktop client, this is a huge security whole. It means that telegram dosen't deletes messages at all (well I was sure that they still keeping them on server), but futhermore - it sends all deleted messages to client applications, and only client application really applied the filtering. That's why the bug is not exists on Android but appears on Mac and Windows PC. Mac and Windows clients has bug in filtering of such messages. But it also means, that alternative 3rd party telegram client is able to show any deleted messages and conversations, including deleted by 3rd parties. Solid security whole of "most secure messager". I can image what is going on in the source code, if poor architecture is seen even without code review, and taking into account that bugs are not fixed for years. 

Looks like it is a time for new Telegram. Same features but implemented by senior developers, Not by band of juniours.

**Comment by akrotov** [comment]
How then deleted chat reappears after fresh reinstallation of Telegram, as users reported above (I haven't tried such case)? Something is pushing deleted message to client, there are no other options. Server or client on another side. But if Android app dosen't have this issue (and it dosen't), then it filters such messages. It was just an assumption, but I still don't have another logical explanation of this bug.

**Comment by john-preston** [comment]
@akrotov The deletion may have a bug, that deletes the messages locally without making a correct delete request to the server. If the app caches the messages in a database, like android, it won't show them even if they're on the server, because it won't request them until you re-login. TDesktop downloads them from server each launch, so it shows what server has. If server received and processed a delete messages request it won't return them anymore, no client side filtering on any apps.

**Comment by foxnoodles** [comment]
>TDesktop downloads them from server each launch, so it shows what server has. If server received and processed a delete messages request it won't return them anymore, no client side filtering on any apps.

I disagree, as the deleted message also appears on iOS client along with Desktop one. I'm a living proof of that. There's a message from a deleted account which I can't delete it comes back each time I relaunch an app both iOS and Desktop.

**Comment by john-preston** [comment]
@foxnoodles That means the request may not be handled by the server, but if you see a message after launching TDesktop that means it wasn't deleted on the server (the delete request didn't work), there is still no client side filtering of deleted messages, no such place in source code where server says "here is a message with some text, but it is deleted, so don't show it, please".

If you can this specific message case we can try looking at DebugLogs of TDesktop session with a deletion attempt and see if a request goes to the server, what the server responds and what it sends on the next TDesktop launch. DebugLogs contain all the network data, all requests and responses, so I usually try not asking for them, but in this case I don't have any other ideas.

If you're interested in helping debugging that in this way please contact me at https://t.me/preston, I'll write how to enable the logs, how to collect them and I'll ask you to send them to me.

**Comment by john-preston** [comment]
@foxnoodles OK, one done, there was a server side bug that didn't delete a chat if it has only a single message with id = 1 (first message ever for this user).

Anyone else? @akrotov @dearpanan @alorma @mass4cr3 @plm203 @ntcuong777

**Comment by plm203** [comment]
Thank you very much John. This seems to match my case as i had a single message with that correspondent, though i could delete the message. But not the chat, which still opens everytime i open TG. I am still using the latest MacOS desktop version. Will your fix apply in the next release of TG or is it supposed to work already ? Because the problem is still present, unchanged, for my account.

**Comment by plm203** [comment]
Hi everyone, i've just received the notice of automatic closing. I had left a response, as you can see above, and i don't know why the bot says otherwise. However i have just checked my TG and now the old chat i wanted to delete has finally disappeared, so for me the problem is solved. I guess that is thanks to John, so thank you John.

**Comment by plm203** [comment]
@foxnoodles thank you. I would have done anything i would have been asked. No one asked me my logs, and i have no idea where to get them, and had no idea they could be useful.

**Comment by foxnoodles** [comment]
> @foxnoodles thank you. I would have done anything i would have been asked. No one asked me my logs; i have no idea where to get them, and had no idea they could be useful.

The dev literally asked and tagged you and others who complained about the bu in the comment above.
