### ISSUE TITLE
Desktop click video (or sound on video) and TG opens full screen

### ISSUE THREAD

**Issue by infonut** [telegramdesktop/tdesktop#24309]
### Steps to reproduce

Click video (or sound on video) and opens full screen

### Expected behaviour

Just play the video

### Actual behaviour

Opens full screen

### Operating system

Windows 10 

### Version of Telegram Desktop

Don't know how to find this - you can tell me ☺

### Installation source

Static binary from official website

### Logs

```shell
Hi,
I have seen this mentioned numerous times but have not found a solution nor even a response.
It is like a stone in my shoe - I am growing more and more irritated. As far as I remember, a few months (?) back, TG did not do this.
Can you please, please fix this bug so TG desktop - both app and web - will play a video in the log stream vs opening to full screen? I feel like I am being put in jail. I REALLY want to listen to the video but it is like being slammed in the face - can't do anything else on the whole computer. 
Who has time for that?!?!?!
I am not saying this idly. I don't want to leave TG, but I am going to if this is not fixed. It's just so basic and SO irritating. I can't stand it any more. Better to not see it than to see it and not be able to play it b.c I don't have time to sit like a zombie in front of my screen and just listen to a video. 

If nothing else, could someone please respond?

thank you.
```

**Comment by ilya-fedin** [comment]
#1710

**Comment by infonut** [comment]
Well. So nice that this was closed when that link goes back to 2016 and the issues has never been fixed! Seems to me that it needs to be opened again. Seriously. Why has this never been addressed in all these years? Makes TG useless.

**Comment by ilya-fedin** [comment]
1. This is not a bug, so word 'fix' is not applicable
2. Since this is an intentional design decision made by Telegram's designers, this won't be changed until Telegram's designers will invent a new design for the media viewer (and that will happen only at their will apparently)
3. You can send your design mockups at https://t.me/designers, Telegram's designers don't read GitHub (so all complains here will be seen only by other users).
4. You can't open issues when there's already an opened issue, if you open yet another issue about this, it will be closed as a duplicate, too.
5. If you disagree with something, you can always create a fork that will be controlled only by you. And maybe provide a PoC as a PR then.

**Comment by infonut** [comment]
That information helps a lot. Thanks so much for taking the time to reply and to explain.
Appreciate it!
Sure wish they would fix it! Did not know they do not read Git Hub - thanks for letting me know.
Lisa
________________________________
