### ISSUE TITLE
Linux - links are not opened with the default browser, again

### ISSUE THREAD

**Issue by azazar** [telegramdesktop/tdesktop#24466]
### Steps to reproduce

I have multiple Chrome, Firefox and Brave installed. Brave is default.

### Expected behaviour

Links should open in Brave.

### Actual behaviour

Firefox loads instead of Brave.

### Operating system

Ubuntu 22.04 LTS

### Version of Telegram Desktop

3.7.1

### Installation source

Static binary from official website

### Logs

```shell
$ xdg-settings get default-web-browser
brave-browser.desktop
```

**Comment by azazar** [comment]
It seems that Telegram uses `gio`'s mechanism. It should not be used, because it ignores user settings. But it's not a bug

**Comment by ilya-fedin** [comment]
GIO implements the XDG specification, so it uses user settings (as long as your DE conforms to the XDG specification)

**Comment by azazar** [comment]
I've seen that `xdg-open` and `gio open` open different browsers

**Comment by ilya-fedin** [comment]
Well, xdg-open is a very bugged shell script that launches DE's binaries (while gio represents functions of glib library) rather than implementing XDG specs on its own. And these binaries aren't always XDG-compatible in fact. For example, xfce doesn't fully conforms XDG, it has its own EXO system instead. And when you select your default browser in Xfce settings, it modifies EXO configs instead of XDG ones.

**Comment by azazar** [comment]
And as a result, Telegram ignores user settings.

**Comment by ilya-fedin** [comment]
Blame Xfce for implementing own MIME system instead of using XDG specs

**Comment by azazar** [comment]
I do. But it's how it is. Without a workaround, Telegram is not able to open links properly.

**Comment by ilya-fedin** [comment]
That's what happens when you choose a non-conforming desktop
