### ISSUE TITLE
File download fails when "Ask for download path for each file" is enabled on Ubuntu 22.04

### ISSUE THREAD

**Issue by earendil02** [telegramdesktop/tdesktop#24491]
### Steps to reproduce

1. Activate "Ask for download path for each file" in Settings>Advanced>Data and storage
2. Try to download a file sent in a chat

### Expected behaviour

Opens a classic window dialog for folder (path) selection, select destination and save file.

### Actual behaviour

Opens the window dialog but an error popup on top saying
_The folder contents could not be displayed
Operation was cancelled
OK_
clicking "OK" closes the error popup and allows folder browsing and save destination selection, but at the end, after clicking on "Save", the file is not saved.
Sometimes after dismissing the error saving succeeds, could not find a pattern for success though.

### Operating system

Ubuntu 22.04 with Gnome 42.0

### Version of Telegram Desktop

3.7.4 beta

### Installation source

Static binary from official website

**Comment by emmmhx** [comment]
@earendil02 did you manage to find a workaround for this issue? Maybe some custom telegram clients lack this issue?

**Comment by earendil02** [comment]
No workaround found yet, however I strongly suspect that the problem is related to gnome 42, because since updating gnome I had problems downloading files also from chrome...

**Comment by emmmhx** [comment]
@earendil02 have you tried downgrading gnome?

**Comment by earendil02** [comment]
Yeah, I also upgraded to Ubuntu 22.04 that comes with Gnome 42.
I haven't found reported issues on this, but I'm not sure my search was exhaustive.

**Comment by emmmhx** [comment]
Would be great if someone could post/find an existing issue on this on Ubuntu bug tracker.

**Comment by filippobistaffa** [comment]
Is the `telegram-desktop` package in Ubuntu's repository affected as well?

**Comment by emmmhx** [comment]
@filippobistaffa yes. Moreover, gnome based desktop environments are affected. I experience the same issue on KDE as well.

**Comment by emmmhx** [comment]
No idea why this issue is not mentioned anywhere.

**Comment by zenaan** [comment]
Because this bug only appears in Ubuntu 22.04, this bug might be unrelated but I'm not sure:

[snap] cannot save file under $HOME
https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1766192

but in that bug, I see the following comment also: "Nikolaj, that's a separate issue. Snaps are not allowed to read files in dot folders under $HOME."

This is another older bug:

org.gtk.setting.file-chooser.location-mode setting is not respected and is reset to path-bar
https://bugs.launchpad.net/ubuntu/+source/meta-gnome3/+bug/1830979

Possibly related - perhaps snap do some sort of "local share" thing? :+1: 

[snap] Files on local network shares are not opened / written
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1971168

Possibly useful to create an Ubuntu bug and link here?

**Comment by zenaan** [comment]
> No idea why this issue is not mentioned anywhere.

It's mentioned here. This is its bug report.

**Comment by zenaan** [comment]
This bug makes working with Telegram on the desktop (I use it for work in a team with a few people) quite problematic - I have to manually type in the name of a file every time when saving, which is error prone of course, AND I don't know the filename because Telegram puts an ellipsis in most filenames (because they are 'too long')!

POSSIBLY useful data for someone to find the cause of this bug:

Because of this bug, I asked my team members to paste the actual filename into each file posted, so that I can at least see what the filename is meant to be;

So I naturally __Select__ and then __Copy__ the filename, and then click in Telegram to save the file, THEN I try to __Paste__ the filename I just copied, into Telegram's "file save" dialog...

...and for me it is __then__ that I get the dreaded error message:

__"The folder contents could not be displayed"__
__"Operation not supported"__

... which leaves my only solution to Manually type in the filename!  Very very frustrating...

**Comment by zenaan** [comment]
This bug makes working with Telegram on the desktop (I use it for work in a team with a few people) quite problematic - I have to manually type in the name of a file every time when saving, which is error prone of course, AND I don't know the filename because Telegram puts an ellipsis in most filenames (because they are 'too long')!

POSSIBLY useful data for someone to find the cause of this bug:

Because of this bug, I asked my team members to paste the actual filename into the post of each file posted (or above or below), so that I can at least see what the filename is meant to be, so that I can at least paste or type it in;

Step 1, I click on a file to save it.

As per this bug, the __Name__ field in the file save dialog is blank/empty!

So next, Step 2, just prior to clicking on a file to save it, I naturally first __Select__ and then __Copy__ the filename that my team mate pasted into their post, and __then__ click in Telegram to save the file.

Once again, the filename save dialog has an __empty__ Name field.

So, Step 3, NOW I try to __Paste__ the filename I just copied, into Telegram's "file save" dialog...

...and for me it is then that I get the dreaded error message:

__"The folder contents could not be displayed"__
__"Operation not supported"__

... which leaves my only solution to Manually type in the filename! Very very frustrating...

**Comment by ilya-fedin** [comment]
Has something change in 4.0? Custom file dialog implementation was removed and QFileDialog is always used now.

**Comment by zenaan** [comment]
On Thursday, June 23, 2022, ilya-fedin ***@***.***> wrote:
> Has something change in 4.0? Custom file dialog implementation was removed and QFileDialog is always used now.

I just checked it, same problem for me - full system update, latest
Telegram Snap - snap info telegram-desktop shows version 4.0.0 .

**Comment by ilya-fedin** [comment]
Sad to hear, looks like gtk folks are trying to sabotage Qt again...

**Comment by ilya-fedin** [comment]
Have anyone found what component of the gtk stack broke compatibility with Qt?

**Comment by emmmhx** [comment]
> Has something changed in 4.0? Custom file dialog implementation was removed and QFileDialog is always used now.

I can confirm the issue still remains for me on Manjaro Linux.

**Comment by ilya-fedin** [comment]
Looks like it's xdg-desktop-portal-gnome
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/29
https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/44
Looking at the issues, it's weird they don't fix them as checking whether the file path specified by Qt exists should take 2-3 lines with glib (one to create a GFile instance, one for actual check and one to destruct GFile instance if g_autoptr is not used), so my suspect is they specially not fixing them to make Qt apps work worse than gtk ones in their environment.

**Comment by ilya-fedin** [comment]
There's also seem to be a bug in xdg-desktop-portal API documentation, so I filed https://github.com/flatpak/xdg-desktop-portal/issues/818.

But in my experience they usually ignore issues, so if you folks won't complain in GNOME bugtracker, nothing would move I guess.

**Comment by zenaan** [comment]
> But in my experience they usually ignore issues, so if you folks won't complain in GNOME bugtracker, nothing would move I guess.

So is there a Gnome bug we can pile into?

I'm not technical enough to understand the above, and I don't know
where to report the bug.

But if someone creates the bug report on Gnome, then I am happy to
pile on with "bug same for me, happy to test" etc...

Regards,
Zenaan

**Comment by ilya-fedin** [comment]
> So is there a Gnome bug we can pile into?

Have you seen the before-last mesage? :thinking:

**Comment by ilya-fedin** [comment]
Are there any changes in 4.2?

**Comment by forkirara** [comment]
Yes. Now it works. 
Thanks :)
