### ISSUE TITLE
I found the answer thanks

### ISSUE THREAD

**Issue by tgcallsproject** [telegramdesktop/tdesktop#24527]
I found the answer thanks

**Comment by Aokromes** [comment]
if it's server side, it belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@Aokromes I'm not sure.

**Comment by tgtglove** [comment]
@john-preston 

compiled my test software with telegram calls via InstanceImplLegacy.cpp
and it not work anymore

there are guesses about
"real cause is the absence of some server-side endpoints which existed previously"

I think the legacy implementation will no longer help us
especially since telegram team seemed to want to delete it in February

before everything was on **endpoints**
now on **rtcservers**
they are completely different structures.
old instances worked only with the first, new ones - only with the second

perhaps someone knows whether it is possible to ask the telegram team to enable all endpoints through which libtvoip worked on the server side?

**Comment by Aokromes** [comment]
if it's server side it belongs to bugs.telegram.org

**Comment by tgtglove** [comment]
> if it's server side it belongs to https://bugs.telegram.org

maybe you know someone personally from the telegram team who does the server part?
