### ISSUE TITLE
100% CPU Load for no reason

### ISSUE THREAD

**Issue by VitalyyBezuglyj** [telegramdesktop/tdesktop#24555]
### Steps to reproduce

1. Start these bot @JPG2PDFBot
2. Send it couple of png images in one message
3. It reply that queue is full and ask to try later
4. Done! 
It is enough to repeat once, deleting the bot, messages, restarting and reinstalling the application does not affect the result.

After several iterations of turning the application on and off, it stops loading the CPU, but when you try to send a new file to an arbitrary chat - it activates again

### Expected behaviour

Typical cpu usage - 1-2%

### Actual behaviour

![image](https://user-images.githubusercontent.com/36605305/170872004-8b9f3452-730d-45c9-921a-bfb6e0dcbe8e.png)
![image](https://user-images.githubusercontent.com/36605305/170872035-f6eea333-88c7-4d63-987f-8f523a29afcc.png)

### Operating system

Fedora 36 Workstation, Gnome 42.1

### Version of Telegram Desktop

3.7.3

### Installation source

Flatpak

**Comment by m911t** [comment]
also happens with the telegram-desktop of the rpmfusion repo. Opening the emoji/gif/sticker menu triggers this bug, but only maxes 1 core for me. scrolling down on either of the menus starts maxing out the other cores. 
this also happens when viewing a channel or group or dm that has a video.
also, this prevents closing telegram, and requires to kill it via a system monitor.

**Comment by ilya-fedin** [comment]
@m911t rpmfusion bug is unrelated to this

**Comment by rederik1986** [comment]
I also observe a bug that described @m911t . On all my computers.
installed from rpmfusion
fedora 36 KDE

**Comment by ilya-fedin** [comment]
Please stop discussing bugs you encounter in third party builds. Either switch to official build or go to your distro bugtracker,
