### ISSUE TITLE
[Question] tdesktop v.4.0

### ISSUE THREAD

**Issue by diabolick72** [telegramdesktop/tdesktop#24735]
How can I go back to version 4.0
After updating to 4.0.2 if I forward my own message saved on saved messages I cannot modify it as it is forwarded by myself.
I need to keep the old txt and create a new updated one.

**Comment by diabolick72** [comment]
It does not happen if I open and do the same thing from web-telegram

**Comment by john-preston** [comment]
Can you describe in details, what should I do and what happens and what should happen?

**Comment by diabolick72** [comment]
> Can you describe in details, what should I do and what happens and what should happen?


If you enter a text on the cloud telegram (saved messages) and then always forward the same post on saved messages to update, this is not possible.
I need to have a historian.

**Comment by mb6ockatf** [comment]
I have checked myself - it works pretty OK. It may be something wrong at your side. Try reinstalling the app
Although, you can get previous releases at the [releases button](https://github.com/telegramdesktop/tdesktop/releases)

**Comment by diabolick72** [comment]
> Ho controllato io stesso - funziona abbastanza bene. Potrebbe esserci qualcosa che non va al tuo fianco. Prova a reinstallare l'app Anche se puoi ottenere le versioni precedenti tramite il [pulsante delle versioni](https://github.com/telegramdesktop/tdesktop/releases)


Thanks for your tests.
I tried several times to always install the same problem.
Now I solved it by installing v.4.0 and blocking updates.

**Comment by CrAcK75** [comment]
Same issue, on web telegram I can modify one of my forwarded message but on telegram desktop I cannot. My actual Telegram desktop is v. 4.0.2

**Comment by oplexz** [comment]
Can reproduce on Telegram Desktop 4.0.2.

The issue is that whenever you save your own messages, they appear as if they were sent by someone else. Not really sure what the intended behavior is, but it *does* differ from Telegram iOS and Telegram Android.

Some screenshots to elaborate:

![image](https://user-images.githubusercontent.com/12859907/178446650-dadb15c1-cd6a-43c7-b87f-182a5c28a4e1.png)

![image](https://user-images.githubusercontent.com/12859907/178446912-3dc94186-ef40-4bb1-9211-32bcf39c2d62.png)
