### ISSUE TITLE
[Question] please reduce the insane size application 

### ISSUE THREAD

**Issue by redno2** [telegramdesktop/tdesktop#24864]
Hi,
could you maybe reduce your snap size package, as it use an insane amount of 1GB (with it dependency core22)..

```
$ sudo du -sh /snap/core22/
230M    /snap/core22/
$ sudo du -sh /snap/telegram-desktop/
926M    /snap/telegram-desktop/





commands:
  - telegram-desktop
snap-id:      jpdoHqMd90M39DdH2JSZbeQxipqHtwLo
tracking:     latest/stable
refresh-date: today at 14:55 CEST
channels:
  latest/stable:    4.0.2                     2022-06-25 (4024) 361MB -
  latest/candidate: ↑                                                 
  latest/beta:      ↑                                                 
  latest/edge:      4.0.3-beta-183-gbe133fce7 2022-08-01 (4072) 361MB -
installed:          4.0.2                                (4024) 361MB -



```

**Comment by ilya-fedin** [comment]
I'm not sure what could be done here as the most part is libraries (255M), then localizations follow (217M), then executables (116M) and various data (84M). This all is necessary since snaps don't have access to the host system, it's literally a system in the system. If you don't have enough space, snap was a wrong choice to install tdesktop. Feel free to choose another installation method at http://desktop.telegram.org. You most likely want the static binary downloaded with the big blue button: it gets updates first, way smaller than any other installation method on the page (it's the only method that can use data & libraries from your host system) and the recommended installation method.
