### ISSUE TITLE
Constant CPU usage when idle because of the little premium emojies animations on right-side of input box

### ISSUE THREAD

**Issue by wiz0u** [telegramdesktop/tdesktop#24863]
### Steps to reproduce

1. Open Telegram
2. Select a chat where there is no GIF or animated stickers showing
3. Watch Task Manager showing constant ~25% CPU usage on my 6-years old laptop

### Expected behaviour

My laptop should not start to heat and make fan noise just when I'm idle in Telegram Desktop.
Task Manager or Process Explorer should show <1% CPU when there is nothing special to animate in the chat.

### Actual behaviour

Task Manager or Process Explorer display a constant ~25% CPU usage even when there is nothing special to animate inside the chat.
I'm pretty sure this is due to the constant animation of the little premium emojies that are shown on the right side of the input box, in the Emoji pane. In previous version of Telegram Desktop, it used <1% CPU on my laptop when idle.

If Telegram window is not focused, then those little emojies don't animate and CPU is back to <1%

![image_2022-08-02_23-06-24](https://user-images.githubusercontent.com/11647984/182474507-7e8be162-01e3-4862-a4c8-658a608ef0b8.png)
Edit: There might have been some fix to this issue since I captured the screenshot, because now the usage is around 10% rather than 25%... better already (but still not very good for the planet to consume 10% CPU when idle)

I'd recommend an advanced option somewhere to disable the animation of these little emojies, when they're shown on the right of input box.

### Operating system

Windows 10

### Version of Telegram Desktop

4.0.3 beta

### Installation source

Static binary from official website

**Comment by GUO-CAI** [comment]
可以


&nbsp;


ment
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月3日(星期三) 凌晨5:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [telegramdesktop/tdesktop] Constant CPU usage when idle because of the little premium emojies animations on right-side of input box (Issue #24863)






繁殖的步骤

开放电报

选择一个没有 GIF 或动画贴纸显示的聊天

观看任务管理器显示恒定的~ 25 %的 CPU 使用率在我的 6 岁的笔记本电脑

预期行为

当我在 Telegram Desktop 中闲着时，我的笔记本电脑不应该开始发热并发出风扇噪音。
任务管理器或进程浏览器应该显示< 1 %的 CPU 时，没有什么特别的动画在聊天。

实际行为

任务管理器或进程资源管理器显示一个恒定的 25 % CPU 使用率，即使没有什么特别的动画里面的聊天。
我敢肯定，这是由于不断的动画小溢价表情显示在右边的输入框中，在表情面板。在以前版本的 Telegram Desktop 中，空闲时在我的笔记本电脑上使用< 1 %的 CPU 。

如果 Telegram 窗口没有聚焦，那么这些小表情就不能动画， CPU 恢复到《 1 %


编辑：有可能已经有一些修复这个问题，因为我捕获的截图，因为现在的使用率是 10 %左右，而不是 25 %...已经好了（但仍然不是很好的星球消耗 10 %的 CPU 时空闲）

我推荐一个高级选项来禁用这些小表情的动画，当它们显示在输入框的右边。

操作系统

视窗 10

电报桌面版

4.0.3 beta

安装源

来自官方网站的静态二进制

日志

无回应

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这封邮件是因为您订阅了这个帖子。留言 ID ***@***.***与&gt;

**Comment by wiz0u** [comment]
version 4.1.1 now uses ~1.5% CPU when idle with the animated little emojies, which is much more reasonable.
