### ISSUE TITLE
Add Toast notifications for W8.1

### ISSUE THREAD

**Issue by Marocco2** [telegramdesktop/tdesktop#249]
https://code.msdn.microsoft.com/windowsdesktop/Sending-toast-notifications-71e230a2#content
This might help. :)

**Comment by brynthomas** [comment]
I know I would love to have Telegram be even more of a good Windows citizen, and use features like this which play nicely with notifications in desktop/metro/full screen games. Especially with Windows 10 and the upcoming Notification Center.

I looked at what was required to implement this, and the one thing that made me hesitate was a requirement that the app has an entry in the Start Menu. I don't know if that's a given when using Telegram.

Would like to know though if this would at least be considered by the Telegram team, because if it was acceptable, I would be fine with implementing it.

**Comment by Marocco2** [comment]
Telegram is already on Start Menu, so there is no problem :)

**Comment by brynthomas** [comment]
I know it's generally on the Start Menu, but I get the feeling that it's not a dependency they would want to force. Mostly because they have the portable version of Telegram which isn't installed into the Start Menu, and they also like to bundle everything into the single Telegram EXE. That shows me something of a desire for a single contained thing without external dependencies, but that's just reading tea leaves.

Presumably one could build it so that it checks if it's installed properly in the Start Menu on Windows 8.1+ and then use Toasts, and otherwise fallback to the existing system. Would still want to hear any concerns from @telegramdesktop before implementing this.

**Comment by sergioad** [comment]
Also adding native Linux notiffications can be nice too :smile: I think the Linux and Windws versions should have the SAME look and feel because on Linux Qt is native; also I agree with the needing of a native notiffications support for Windows and Linux because I think this could be a nice deal

**Comment by brynthomas** [comment]
I'm not sure what you mean regarding the same look and feel vs native notifications? Should the apps keep the same custom Qt notification style in order to preserve consistency across Windows/Linux, or should they use a style that matches whatever platform it's being run on?

I'm all for similarity where necessary to keep the codebase as consistent as possible across all three support platforms, but I really think that applications need to respect the uniqueness that exists in the behaviours of each of the platforms and be consistent with other applications that run on the same platform. Personally feel that it's important that on Windows it behaves like a Windows app, and plays nicely with the expectations that Windows users have as far as the way apps works. Part of the reason I moved away from Google Hangouts is that their Chrome-based client that runs on Windows feels and behaves nothing like my other Windows apps.

**Comment by Marocco2** [comment]
@brynthomas Did you see my link? The sample doesn't need to install nothing. Just 10 lines of code. I would like to add them by myself, but I don't know how telegram app is built.

**Comment by brynthomas** [comment]
@Marocco2 I did look at how it worked and ran it. Check your Start Menu after you run it, it adds an entry into the Start Menu (called "Desktop Toasts App") if it doesn't already exist which might not be what the Telegram people would want.

**Comment by Marocco2** [comment]
How can people be annoyed by a link? It requires just a link to start menu, nothing else. Maybe Telegram should add an option to use native notification, shouldn't it?
________________________________
Da: Bryn Thomas<mailto:notifications@github.com>
Inviato: ‎09/‎01/‎2015 14:23
A: telegramdesktop/tdesktop<mailto:tdesktop@noreply.github.com>
Cc: Marocco2<mailto:marocco2@live.it>
Oggetto: Re: [tdesktop] Add Toast notifications for W8.1 (#249)

@Marocco2 I did look at how it worked and ran it. Check your Start Menu after you run it, it adds an entry into the Start Menu (called "Desktop Toasts App") if it doesn't already exist which might not be what the Telegram people would want.

---

**Comment by brynthomas** [comment]
@Marocco2 I'm fully onboard with the idea of including it. I really would prefer if it used this built in notification system of Windows. It's only going to get more important in Windows 10, as seen in the preview.

It's just that the implementation of it has complications like this which means it has to be a bit smarter about how it works. i.e. might have to check if it's been installed (which would have the link) vs being run as the portable version which wouldn't. 

The @telegramdesktop people may have a limit as to how much platform specific code they want to include, and each of these complications adds lines of code, so wouldn't want to do anything on it without hearing their thoughts.

**Comment by GitMoDu** [comment]
Mucking the user experience to preserve common development code has not been historically sound. Different platforms and OS have different requirements and expectations. Sure, a modern chromeless QT app may look and feel in place in almost any modern OS, but handling OS specific stuff like notifications and installations will always be better if you adhere to OS guidelines.

Regarding the specifics, I've tried the Windows 10 Preview and it already converts legacy notifications into modern notifications, so you'd only delaying the inevitable by keep a common code for notifications.

Common core and OS specifics, that's what I'm getting at.

**Comment by Marocco2** [comment]
@andré Finally I've found a guy who has my opinion about developing apps on different platforms. +9000 :D :D :D
________________________________
Da: André<mailto:notifications@github.com>
Inviato: ‎09/‎01/‎2015 19:04
A: telegramdesktop/tdesktop<mailto:tdesktop@noreply.github.com>
Cc: Marocco2<mailto:marocco2@live.it>
Oggetto: Re: [tdesktop] Add Toast notifications for W8.1 (#249)

Mucking the user experience to preserve common development code has not been historically sound. Different platforms and OS have different requirements and expectations. Sure, a modern chromeless QT app may look and feel in place in almost any modern OS, but handling OS specific stuff like notifications and installations will always be better if you adhere to OS guidelines.

Regarding the specifics, I've tried the Windows 10 Preview and it already converts legacy notifications into modern notifications, so you'd only delaying the inevitable by keep a common code for notifications.

Common core and OS specifics, that's what I'm getting at.

---

**Comment by sergioad** [comment]
only have said that I think both the Windows and Linux versions must have native notiffications @brynthomas

**Comment by sergioad** [comment]
about the apparience the Linux versión does not has tray icon not the beautyfull client side decorations

**Comment by GitMoDu** [comment]
@sergioad Then we agree about the stuff that should be native :)

**Comment by sergioad** [comment]
Yes, on Linux Telegram desktop has not icon tray, has not CSDs (Client Side Decorations / the window controls and titlebar on the same main toolbar) and because of that has the uggly Server Side Decorations (the normal titlebar)

**Comment by Snnlk** [comment]
I for one would very much like this as well.

**Comment by gtirloni** [comment]
If you add toast notifications, please add a way to make just the first one show to avoid flooding the screen with one notification after another. Usually when people start messaging you, they want your attention to the conversation, not to every message (since the point they're trying to communicate could be multiple messages, specially with people that like to put one emoticon in a separate line -- very annoying). In summary, please don't make it annoying :)

**Comment by sergioad** [comment]
maybe one per 1/5 minutes?

**Comment by stefanmaric** [comment]
Windows 10 brought a notification tray: http://www.theverge.com/2015/7/28/9057735/microsoft-windows-10-music-video-hype-sweat-beef

An extra reason to add native notifications, to all platforms. (see #91)

Cheers.

**Comment by Marocco2** [comment]
WIN! New 0.8.49 update supports Windows Notifications!!!
