### ISSUE TITLE
Members cannot be added or removed when owner leaves a gorup

### ISSUE THREAD

**Issue by deper29** [telegramdesktop/tdesktop#2495]
### Steps to reproduce
1. Create a group chat with several members
2. Have the creator of the group chat leave the group
3. Members of the group cannot add or remove anyone, which makes the group stagnant. 

### Expected behaviour
Original creator of the group should be forced to transfer ownership when leaving, or at least have the option of transferring ownership while in the group chat.

### Actual behaviour
Group chat remains "ownerless" and a new chat must be created to add new people. Chat history is then lost.

### Configuration
All

**Version of Telegram Desktop:**
0.10.11
### Logs
Insert logs here (if necessary)

You can type `debugmode` in settings and then see ~/.TelegramDesktop/DebugLogs/log_...txt for log files.
Type `debugmode` in settings again to disable logs.

**Comment by Aokromes** [comment]
#1916

**Comment by stek29** [comment]
@auchri one more bug with you? XD

**Comment by KoichiSenada** [comment]
So what happened to this bug?
How to pass the ownership of a chat group or a channel before leaving it?

**Comment by auchri** [comment]
@KoichiSenada will be fixed in the next versions:

![image](https://user-images.githubusercontent.com/5092164/27627811-61869992-5bed-11e7-966d-7af3498417ff.png)

**Comment by KoichiSenada** [comment]
@auchri , that is just awesome!
Will it be possible for the other admins to change the private/public status of the group/channel and to change their public links, too?

I am asking that because I have already spent my 5 public links limit and so I wish to share it with the other admins of my channels and groups, since I was initially just assisting them while they were not skilled enough.
