### ISSUE TITLE
Markdown in Telegram

### ISSUE THREAD

**Issue by dostonnabotov** [telegramdesktop/tdesktop#25023]
### Is your feature request related to a problem?

Sometimes, when I write a message or post something, I want the heading or subheading that stands out from the rest of the content or use a different font family. Also, we still don't have an option to create an ordered/unordered list or add color to the text. Although we have some of the options (bold, italic, or mono), still there are not enough, I think. 

### Describe the solution you'd like

I would love to see the use of Markdown in Telegram as well. It would be cool if you could have headings, different colored text, code blocks and etc. I hope to see this new feature being added in the next newer versions.

### Describe alternatives you've considered

Or alternative option would be switching the text to normal default telegram text or markdown text. I mean, adding a toggle to switch between two options (default and markdown) would be great.

**Comment by thisisthelongestusernameyouhaveeverseen** [comment]
Use Telegraph instead.

**Comment by RememberTheAir** [comment]
Markdown parsing should be handled on all clients _and_ by the server too, since telegram handles formatting by passing to the client a list of text chunks (offset - length) to display in a certain way. I think you should bring this to https://suggestions.telegram.org since it's out of the scope of a single client (there's probably an existing issue about that)
