### ISSUE TITLE
"Delete for myself only" as owner of the group

### ISSUE THREAD

**Issue by bettimms** [telegramdesktop/tdesktop#25090]
### Is your feature request related to a problem?

Can't delete my media posts only for myself as owner of the group.

### Describe the solution you'd like

Make it possible to delete my own comments & media without deleting for other members of the group. I tend to remove videos and photos that I'm not interested anymore in order to free up my space on the phone. As group owner, I'm not able to delete for myself only. This seems related to supergroups, and the switch to supergroup has been done automatically without any prior warning for the consequences. 

### Describe alternatives you've considered

It doesn't seem big deal to make this possible; on my opinion it's a good thing it's missing compared to other alternatives like WhatsApp & Viber.

**Comment by RememberTheAir** [comment]
It's not because you're the owner of the group, it's because the group is a supergroup (more details [here](https://telegra.ph/groups-08-26)). In supergroups, it's no possible for anyone to delete messages just for theirselves

> in order to free up my space on the phone

This issue is not about tdesktop, it's something that belongs to https://suggestions.telegram.org because it should be consistent across all apps. Btw, you can set the android app (assuming you're using android) to free up medias you haven't accessed in a specific amount of time (3 days/one week/one month). You can always re-download them when you visit the message again. From iOS you can even set the max size the media cache shouldn't cross
