### ISSUE TITLE
[Question] View all contacts stored in Telegram

### ISSUE THREAD

**Issue by mahmoodn** [telegramdesktop/tdesktop#25115]
I see some "X joined telegram" messages but such contacts are very old and at the moment that I see such telegram message, that contact is no longer in my phone. How can I check which phone contacts are still existing in my telegram account? I have to say that I don't see them in the telegram contact list. In other word, there was no contact for X in my telegram account yesterday, but today I see that X joined telegram... 
Any comment about hat?

**Comment by RememberTheAir** [comment]
There is no way for an app to request the list of phone numbers in their server-synced contacts list that haven't joined telegram yet. However, from the mobile apps, you can erase your synced contacts from settings -> Privacy & Security -> Delete Synced Contacts. This will erase all your Telegram contacts (with/without phone numbers), but if your mobile app has access to your phone contacts, those contacts will be synced again and your contacts list will be populated again, but just with the contacts currently stored in your phone (regardless of whatever contacts list you're storing them with, eg. google account, SIM card, etesync, an exchange account, etc.)

Btw, since the api doesn't support what you're asking for, you should bring this issue to https://suggestions.telegram.org
