### ISSUE TITLE
[Question] Bubble rounding bad

### ISSUE THREAD

**Issue by Kolsky** [telegramdesktop/tdesktop#25317]
pls revert

**Comment by NinoM4ster** [comment]
duplicate of #2526.

also @Aokromes GitHub now has the option to close issues as "Not planned", to indicate a duplicate issue (such as this one).

![image](https://user-images.githubusercontent.com/8485761/201267030-31e53f65-c106-4f5b-9e11-1b0575a8bb50.png)

otherwise it shows it as "completed", which could be misleading.

![image](https://user-images.githubusercontent.com/8485761/201267243-5c777da3-f5de-42de-9b83-8dfd67891aac.png)
