### ISSUE TITLE
Telegram desktop crush due to switch between accounts

### ISSUE THREAD

**Issue by dmitrii92** [telegramdesktop/tdesktop#25409]
### Steps to reproduce

1. You should have several accounts on telegram desktop
2. Switch between them

### Expected behaviour

It should be normal!

### Actual behaviour

![Telegram_Crush](https://user-images.githubusercontent.com/17344213/203334031-7bab1ee9-7961-44f8-b832-1f69398a28ab.PNG)

### Operating system

Windows 8.1

### Version of Telegram Desktop

v 4.3.1

### Installation source

Static binary from official website

**Comment by kogeki** [comment]
Same thing for me. I tried to reinstall and it wiped my accounts and now I can't find them. Nice.

**Comment by pakskiy** [comment]
Hello! The same error happens to me too! Win10 x64 release 4.3.2

**Comment by H3ool** [comment]
Hello! After updating to Win10 x64 release 4.3.2, I also see the same bug.

![image](https://user-images.githubusercontent.com/12871727/203425430-836a4f32-f542-40b3-8848-407bffd3b656.png)

**Comment by azimutFTW** [comment]
Same problem (Win 11, TG 4.3.2)

**Comment by Vladisvalov** [comment]
Same problem (Win10 x64)

**Comment by Aokromes** [comment]
there is no need of bump the issue.

**Comment by denis-hrebeniuk** [comment]
Same problem (Windows 11 x64)

**Comment by tunerok** [comment]
Same. Nice upd
![image](https://user-images.githubusercontent.com/20516589/203543649-053d29fc-66a9-4bae-9331-b71ee397b9ac.png)

If you touched the rescaling mechanism, then report it in the changes. It doesn't look like anything to do with pretty spoller animations.
![image](https://user-images.githubusercontent.com/20516589/203543869-02343f63-75fb-4cc0-ae07-ea49b488a807.png)

The problem is visible even in the tray
![image](https://user-images.githubusercontent.com/20516589/203543751-6a43502a-d85a-45ab-a4a1-558017f8da2c.png)

**Comment by dmitrii92** [comment]
Works well in new version 4.3.3
