### ISSUE TITLE
App crashes and breaks Wayland connection after opening a webview on Linux

### ISSUE THREAD

**Issue by rmnscnce** [telegramdesktop/tdesktop#25487]
### Steps to reproduce

1. Go to Telegram Premium
2. Try to pay the invoice
3. Select a payment method that will spawn a webview instance window
4. Bug reproduced.

### Expected behaviour

The webview should successfully appear and not crash the application.

### Actual behaviour

The application crashed and breaks its connection with the Wayland socket (other apps are just fine, probably due to Flatpak's sandboxing).

![image](https://user-images.githubusercontent.com/31619874/205123237-4f130de6-4e26-4efa-b67e-0a86bd5217bf.png)

![image](https://user-images.githubusercontent.com/31619874/205123272-adf3446e-8fc8-4047-95de-c7659fd8fc66.png)

![image](https://user-images.githubusercontent.com/31619874/205121178-4bf5433b-3e5f-4cbe-8f28-a04b2624c225.png)

(This persists until the Wayland compositor gets restarted)

### Operating system

Fedora Linux 37.20221130.0 (Silverblue)

### Version of Telegram Desktop

4.3.4

### Installation source

Flatpak

### Logs

Upon attempting to open the webview:
```
<...trimmed...>

qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:23:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
qt.qml.context: qrc:/qt-project.org/imports/QtWayland/Compositor/qmlfiles/WaylandCursorItem.qml:25:9 Parameter "surface" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
```

Upon attempting to open the application after it crashed:
```
F: /run/user/1000/.flatpak/org.telegram.desktop/xdg-run/wayland-0 is not a symlink to "../../flatpak/wayland-0" as expected: readlinkat: Invalid argument
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
Failed to create wl_display (Connection refused)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

```

**Comment by ilya-fedin** [comment]
This is https://github.com/flatpak/flatpak/issues/5167
You can switch to the official binary from https://desktop.telegram.org

**Comment by smcv** [comment]
Is this the correct tracker for issues specific to the Flatpak packaging of tdesktop, and not just the upstream version? I see https://github.com/flathub/org.telegram.desktop has issue-reporting disabled.

On flatpak/flatpak#5167, @ilya-fedin wrote:
> tdesktop uses QtWaylandCompositor to create a nested compositor for web bots, the library checks lock files to find a free socket name

Regardless of whether this is solved by something like flatpak/flatpak#5195 or not, it would be safer to create special-purpose compositors with a namespaced name so that they don't accidentally get used by normal applications. If you're running an X11 desktop environment, you presumably don't want ordinary GTK or Qt applications to see your special-purpose nested compositor create `$XDG_RUNTIME_DIR/wayland-0`, think "oh good, Wayland is available!" and start displaying on your special-purpose nested compositor instead of on the global X11 display...

[Gamescope](https://github.com/Plagman/gamescope) is an example of a special-purpose compositor used to run games (its Wayland compositor intentionally doesn't have ordinary desktop-oriented interfaces, only the minimum that's required to run a full-screen Xwayland), and it uses `$XDG_RUNTIME_DIR/gamescope-%d` (where `%d` is some integer) instead of `$XDG_RUNTIME_DIR/wayland-0`. I think that would be a good model to follow if you're creating a similarly special-purpose compositor. In particular, please don't create `$XDG_RUNTIME_DIR/wayland-0`, because that's the socket that libwayland-client will use if `WAYLAND_DISPLAY` is not set.

(This might not be possible without a feature addition to QtWaylandCompositor, I don't know.)

**Comment by ilya-fedin** [comment]
It seems neither QtWaylandCompositor nor wayland-server has API for this. There's wl_display_add_socket_auto that is used by QtWaylandCompostior to find the first free socket name, but the API has no way to specify custom prefix.

**Comment by NgoHuy** [comment]
I confirm this bug is reproduced on Archlinux with PKGBUILD, telegram crashed while trying to load the webview. Only happenned when using wayland - included sway and KDE as I tested.

**Comment by ilya-fedin** [comment]
@NgoHuy I believe you have other issue then, this issue is flatpak-specific
