### ISSUE TITLE
Telegram [snap] still crashes when try to share a screen on Wayland

### ISSUE THREAD

**Issue by EndrII** [telegramdesktop/tdesktop#25525]
### Steps to reproduce

    run telegram (from snap-store) on wayland
    share screen

### Expected behaviour

Telegram should be share a screen without issues.

### Actual behaviour

Telegram crashes when try share screen on wayland

### Operating system

ubuntu 22.10

```
Linux X570-GAMING-X 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

### Version of Telegram Desktop

4.4.1

### Installation source

Snap

### Logs

```shell
amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
If they do, bad things may happen!
[E] pw.loop [loop.c:86 pw_loop_new()] 0x7f5a93b58ef0: can't make support.system handle: No such file or directory
Segmentation fault (core dumped)
```

**Comment by EndrII** [comment]
About distro 
```
Linux X570-GAMING-X 5.19.0-26-generic #27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by ilya-fedin** [comment]
We sadly still can't examine the crash as snap still doesn't provide infrastructure for debug symbols, so you should switch out of snap if you want screen sharing on Wayland

**Comment by EndrII** [comment]
Hm, you can add to the snap package gdb and run 
snap --shell telegram-desktop 
After crash, you can run gdb with your telegram-desktop and check your crash stack dump manual..

**Comment by ilya-fedin** [comment]
no, the problem is not in gdb, but in the fact there's no way to get debug symbols after Telegram is built. E.g. with official binary, debug symbols are separated from the binary, people send crash reports with the integrated crash reporter and the developer looks them with the debug symbols he obtained after building the binary. With flatpak, the user should install `.Debug` package and then run gdb manually. Snap doesn't provide anything like, you can run gdb. but traces without debug symbols are useless.

**Comment by EndrII** [comment]
@popey hi, do you have any ideas how to debug snaps in this case?

**Comment by popey** [comment]
@EndrII I no longer work on snaps, sorry.
Perhaps @kenvandine can find someone.
