### ISSUE TITLE
Inexplicable pop-up windows in macos

### ISSUE THREAD

**Issue by kekeimiku** [telegramdesktop/tdesktop#25531]
### Steps to reproduce

1. open telegram, close the window.
2. Click on the upper left corner, about this machine, more information, close the window.
3. telegram appears on the screen.

### Expected behaviour

Nothing happened.

### Actual behaviour

telegram appears.

### Operating system

macOS m2 13.0.1

### Version of Telegram Desktop

4.3.4

### Installation source

Mac App Store

**Comment by john-preston** [comment]
It was discussed before. On app activation we show the main window so that when you Cmd+Tab to Telegram from another app it would show the window, otherwise it looks buggy.

I don't know an API way to detect was the app activated by Cmd+Tab or by closing another app and auto-activating this one. If there is one, I can leave window activating only for Cmd+Tab. For now it works the way it works :(
