### ISSUE TITLE
Date of the message is displayed in Russian even if I have English language

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#25578]
### Steps to reproduce

1. Set up English language in Telegram
2. Set up Russian language in Windows
3. Messages dates (when you mouseover it) will be in Russian

![image](https://user-images.githubusercontent.com/39812401/208293383-92e60030-55ea-407f-b134-1c4a1b8ec5cf.png)

### Expected behaviour

The date of the message must be in the language that is set in Telegram

### Actual behaviour

Message date in the language that is set in Windows

### Operating system

Windows 10

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
It's the intended behavior

**Comment by Neurotoxin001** [comment]
> It's the intended behavior

But why…

**Comment by ilya-fedin** [comment]
tdesktop asks time string from QLocale that uses system APIs. That way all the locale-dependent nuances are respected (i.e. no bugreports 12-hour time vs 24-hour and other way less known nuances from Persian people and etc) and the user can configure the format with system settings (e.g. you can add seconds to the short format via Windows settings, this won't be possible if tdesktop will create QLocale from its language rather than using the system one).
