### ISSUE TITLE
Feature request: Unread chats on top

### ISSUE THREAD

**Issue by mboronin** [telegramdesktop/tdesktop#2557]
Why don't you guys add a possibility to show chats with unread messages on top of all others. This will be really useful

**Comment by stek29** [comment]
#1067 related.

**Comment by stemar94** [comment]
What will be useful for you might not be useful for others. If the chat has unread messages it may have a reason and then I don't want to have them always on top. I guess you want them to be on top in order to be reminded of reading them. But if you intend to read your messages in a timely manner there is no need to force unread messages to be on top, since they will be near top anyway.

**Comment by mboronin** [comment]
@stemar94 It can be implemented in the way so you can turn the feature on and off

**Comment by crocodilys** [comment]
+1 for ability to sort messages according unread/read status

**Comment by a-zazell** [comment]
+1!

**Comment by stek29** [comment]
@a-zazell @crocodilys use GitHub reactions please.

**Comment by ruv** [comment]
Also it will be useful if chats with unread messages and **enabled notifications** are shown before other chats with unread messages. Sometimes it is pretty hard to find such chat among others.

**Comment by stek29** [comment]
@ruv Try typing "workmode" while in settings 😉

**Comment by ruv** [comment]
If somebody is interested: "workmode" option allows just to [hide muted chats](https://t.me/geekschannel/647) in one click. Very helpful.
@stek29, thank you for this hint!

**Comment by stek29** [comment]
#2440 duplicate, but this one has more reactions...

**Comment by lalejand** [comment]
> @stemar94 It can be implemented in the way so you can turn the feature on and off

This feature would be very useful for me. Sometimes I receive messages from not urgent chats, so I don't read them when they arrive, but I don't want to forget them. Then they get pushed down by other messages in other chats. When they are out of the chat list in the left column, I often forget them.
That's why de option to group unread chats on top of the list would be useful.
Alternatively, some graphic indication that there are unread chats out of sight, like Mattermost does, can be useful.
