### ISSUE TITLE
TG mixes up channels with groups and won't let me comment

### ISSUE THREAD

**Issue by ILoveSkilledCoders** [telegramdesktop/tdesktop#25617]
### Steps to reproduce

I go into a channel I'm already a member of.
I go to the comment section to say something & TG tells me I can't join the group even though it's a channel, not a group AND I'm already a member.

This has happened at least 3 times in different groups in the last 6+ months.

Here's a video - https://mega.nz/file/V01gHKTL#HQdWavTn15QAAAql9VnO-NcGV6CSIHt74zTrgXDrItY

### Expected behaviour

I should be able to comment

### Actual behaviour

 Won't let me comment even though I'm a member. And it should say I can't comment in the channel (not group) & why.

### Operating system

Win 7

### Version of Telegram Desktop

4.4.1

### Installation source

Static binary from official website

**Comment by john-preston** [comment]
Comments in channels are done through special groups, that are created separately and "linked" to the channels. After that each post from the channel is forwarded to this "linked" group (named "Discussion group") and all replies to this forward are comments to this post.

By the video you provided it looks like you were banned in the group that is "linked" to that channel. That way you can see the channel posts but when you try opening the comments (that are really "threads of replies in a group") you're not let in, because you're banned.

**Comment by john-preston** [comment]
Here is how this group managed in the channel settings:

![image](https://user-images.githubusercontent.com/17900494/210226207-dd66e148-0ead-4512-aa04-3fcd509e41cc.png)

**Comment by ILoveSkilledCoders** [comment]
> Comments in channels are done through special groups, that are created separately and "linked" to the channels. After that each post from the channel is forwarded to this "linked" group (named "Discussion group") and all replies to this forward are comments to this post.
> 
> By the video you provided it looks like you were banned in the group that is "linked" to that channel. That way you can see the channel posts but when you try opening the comments (that are really "threads of replies in a group") you're not let in, because you're banned.

Yes I know how it works as I have channels like that too, but I don't think I'm banned. 

I've had this happen in 3 different groups & there's no reason for me to have been banned.

It's also happened with someone else I was talking to.

I'll PM you on TG.

Thanks

**Comment by john-preston** [comment]
We can know for sure what is the server response when you try to apply to this group if you share log.txt after the failed attempt to join.
