### ISSUE TITLE
Background picture is set to tiles instead of strech after every update

### ISSUE THREAD

**Issue by Kolobamanacas** [telegramdesktop/tdesktop#25666]
### Steps to reproduce

1. Install the latest version of Telegram Desktop for Windows.

2. Go to Menu > Settings > Chat Settings > Chat Background > Choose From Library > select fir tree as shown in picture below > click Apply > Close > close Settings window.

![2023-01-03_00-00-01](https://user-images.githubusercontent.com/20444060/210280776-49327c3e-7c47-4346-9e21-782ba624466f.png)

3. Wait for any Telegram Desktop update and update it.

4. Close Telegram Desktop.

5. Open Telegram Desktop.

### Expected behaviour

The background image stays the same: stretched to the whole space:

![2023-01-03_00-04-10](https://user-images.githubusercontent.com/20444060/210280939-7f42543a-efa2-4234-bec0-3b1733dee283.png)

### Actual behaviour

The background images changes to tile mode:

![2023-01-02_20-49-51](https://user-images.githubusercontent.com/20444060/210280745-f0cb655e-45be-4120-8a12-1ec6419d4faf.png)

### Operating system

Microsoft Windows 11 Home x64 22H2 (OS Build 22621.963) (Windows Feature Experience Pack 1000.22638.1000.0)

### Version of Telegram Desktop

4.5.1 x64 (but the bug was there since the very beginning)

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
#16468

**Comment by john-preston** [comment]
Unfortunately, this doesn't happen on a fresh install. If I follow the steps, take version 4.5.0, log in, set this background, update it to 4.5.1 -> it stays not tiled. Please correct me if I'm wrong. You can try a fresh portable version from https://github.com/telegramdesktop/tdesktop/releases page.

So this is something remembered in your installation from some old version :( You can clean your installation completely (logout and delete "tdata" folder near Telegram.exe) in case you can log in back. Or I can add some logs to the tile background property reading / writing for the future versions, but I'm afraid it won't be enough to make once, because the codepaths to update data from all ever made old versions are very complex.

**Comment by john-preston** [comment]
WAAIT 🤣

It reproduced on the second launch. I'm looking into it.

**Comment by Kolobamanacas** [comment]
I've been struggling with this issue for years and just a day after I've created the issue, it's already fixed! Why did I wait for so long! :))) Thanks a lot! I confirm it is solved in v4.5.3.
