### ISSUE TITLE
[Feature Request] Replace binary packages or Snap with AppImage

### ISSUE THREAD

**Issue by khalil-i-o** [telegramdesktop/tdesktop#25675]
### Is your feature request related to a problem?

For linux, there are many distributions; to solve different bugs, it is very complicated. In Ubuntu, there is a big difference between the options in X.Org and Wayland (for example: no problems with [screen sharing](https://github.com/telegramdesktop/tdesktop/issues/25674) or [text selection](https://github.com/telegramdesktop/tdesktop/issues/25673)), being the same operating system with different window manager.

### Describe the solution you'd like

Replace or add the installation alternative as Appimage, since it is an executable that integrates all the dependencies.

### Describe alternatives you've considered

Give the same development management for Ubuntu in Wayland as in X.Org.

**Comment by ilya-fedin** [comment]
Can you provide a proof of better AppImage's integration? I believe AppImage format is no better than static binary, but worse given that it requires fuse and library stripping is not happenning (so you get hundreds of megabytes inside a squashfs image instead of a 100 MB binary).

**Comment by ilya-fedin** [comment]
> They are easily integrated and both the interface and functions are solved internally.

tdesktop's binary integrates no harder than AppImages and I would say even easier (without installing third party programs like AppImageLauncher).

> If there is a webrtc or Gnome update, the executable works unchanged despite this.

I'm not quite sure what this means. The only difference between static binary and AppImage is that bundled dependencies are linked statically in first case while being a part of suqashfs in the second case. This has no difference for system updates, but has a difference for consumed size and application startup speed (static binary in the winning position).

> The change Ubuntu made in version 22.04 (changing the environment to Wayland), did not affect the functions or the interface at all.

VLC is still using Xwayland, Inkscape is based on gtk (that has way better support for Wayland and GNOME than Qt), StandardNotes is based on Electron (so uses Xwayland and partially gtk), Audacity is based on wxWidgets that is based on gtk. This is definitely not due to AppImage.

> However, it is a suggestion, the developers will see if it is better or worse

I'm the person doing most of the Linux-specific work in tdesktop

> but the idea of making the application less dependent could lead to better results

Well, tdesktop's static binary is already independent on system libraries as far as it could be possible, any further library bundling will lead to worse system integration, here are all the system dependencies tdesktop has currently:
```
libgtk-3.so.0
libgio-2.0.so.0
libgobject-2.0.so.0
libfontconfig.so.1
libfreetype.so.6
libEGL.so.1
libGL.so.1
libwayland-egl.so.1
libwayland-cursor.so.0
libwayland-client.so.0
libxcb.so.1
libX11.so.6
libX11-xcb.so.1
libglib-2.0.so.0
libdl.so.2
libm.so.6
libpthread.so.0
libc.so.6
ld-linux-x86-64.so.2
```
Bundling libgtk-3 will lead to gtk Qt uses for system integration (like icon theme, file dialogs) work incorrectly (as gtk heavily uses plugins and its theming engine had multiple API breaks), bundling libGL or libEGL will result in impossibility to use system OpenGL drivers. Bundling everything else will result in gtk to crash (as it will mix system copies of those libraries with bundled ones used by Qt). Bundling libc and its parts (libdl, libm, libpthread, ld-linux) will lead to impossibility of using any shared libraries.
