### ISSUE TITLE
Can't see video of interlocutor

### ISSUE THREAD

**Issue by ForesterDev** [telegramdesktop/tdesktop#25692]
### Steps to reproduce

1. Dial Video call
2. The interlocutor answers from a smartphone
3. You don't see him, although the camera is on

### Expected behaviour

You must see it. There is no problem if both people use the desktop

### Actual behaviour

You see yourself, but you do not see the interlocutor

### Operating system

Windows 10 Pro

### Version of Telegram Desktop

4.5.2 x64

### Installation source

Static binary from official website

**Comment by MetalDroid** [comment]
Hello, I leave here what I wrote in the TDesktop group with what I know about this bug:

There is a strange #bug in TDesktop related to video calls

I've been trying to reproduce the problem for a few days, but I can't.

The problem is that when making video calls, the video of the other person is not shown on the screen, it is not shown in black either, it is simply shown as if it were an audio-only call.

The only clues I've been able to find to that error may be related to the lock code.

Before upgrading to new versions, I enabled the lock code. So after update, no video call worked fine. Your own video is sent to the other person, but the other user's video is not shown (as described above).

What I did was disable the lock code, restart TDesktop, and enable the lock code again. 

That's how it was magically fixed. But the error is really there somewhere.

I hope this can help to fix the error or other people can fix it like I did.

PS: TDesktop for Linux

**Comment by MetalDroid** [comment]
@ForesterDev 

Please, can you tell us if you had the lock code enabled?

**Comment by DeanMills89** [comment]
I've never had the lock code on and I have the same problem

**Comment by Aokromes** [comment]
works for me client pcs:
windows 10, windows 11, telegram desktop 4.5.2
android 12 phone, telegram android 9.3.3.

**Comment by Aokromes** [comment]
test
https://github.com/telegramdesktop/tdesktop/commit/08fa6a981578034a078b20eb6775521288fc129a

**Comment by DeanMills89** [comment]
It's working now for me

**Comment by huntertran** [comment]
with version 4.5.3, it's working now
