### ISSUE TITLE
Telegram doesn't scale in fractional scaling

### ISSUE THREAD

**Issue by howdev** [telegramdesktop/tdesktop#25698]
### Steps to reproduce

1. run Ubuntu 22.10
2. install telegram from Telegram website
3. set GNOME fractional scaling to 150%
4. QT_AUTO_SCREEN_SCALE_FACTOR=1
5. logout, login
6. run telegram

### Expected behaviour

Telegram scales to 150% same as other apps do.

### Actual behaviour

Telegram does not follow desktop scaling, uses its own scaling instead at 200% but text and UI is still small. I need to set Telegram to 250% UI is bigger but text still small. UI size to text is not in right proportion.

KeepassXC also uses Qt5 scales properly by itself.

### Operating system

Ubuntu 22.10 GNOME 43

### Version of Telegram Desktop

4.5.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Fractional scaling on Wayland is working by rendering all the applications at the higher integer scaling (1.5x = 2x) and raster downscaling buffer images to the fractional scale factor. So it's 200% from tdesktop PoV. Setting QT_AUTO_SCREEN_SCALE_FACTOR has no sense because:
1. It's not used by Qt 6
2. Qt's High-DPI scaling is disabled in official builds
3. Qt's High-DPI scaling is no-op on Wayland anyway (at least in auto mode) as it's only for platforms operating in device-dependent pixels while Wayland operates in device-independent pixels, just like macOS.

**Comment by howdev** [comment]
I forgot to mention it is not wayland. It is running Xorg

**Comment by ilya-fedin** [comment]
I have no idea how this works on X11 as it's an Ubuntu-specific thing, but I suspect it's similar as gtk doesn't support rendering at fractional scales

**Comment by howdev** [comment]
Ubuntu X11 Nvidia uses GPU scaling together with Gtk scaling, so most of the Qt apps don't scale. KDE scaling has the same problem that only Qt apps scale and not Gtk apps. I was using Zorin, and Telegram was the same.

I tried Wayland session of Ubuntu, Telegram produce same result as in X11. Telegram own default scaling is unusually smaller than other apps. It is a problem that you cannot change the font size in the Linux version. If you increase the Telegram scale the UI is big but text small, not in proportion.

**Comment by ilya-fedin** [comment]
> If you increase the Telegram scale the UI is big but text small, not in proportion.

I don't see such behavior
