### ISSUE TITLE
hindi fonts not looking good after update

### ISSUE THREAD

**Issue by jitusaini9929** [telegramdesktop/tdesktop#25910]
### Steps to reproduce

![image](https://user-images.githubusercontent.com/103476094/219909908-a7d0dbe1-53f7-4bf8-b754-00f7fddcccdb.png)

### Expected behaviour

please chnage fonts

### Actual behaviour

fonts change after updating app 

### Operating system

window 11

### Version of Telegram Desktop

64.4.6.3

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Do you know the name of the expected font?

**Comment by YohaneWW** [comment]
> Do you know the name of the expected font? Do you know the name of the font actually used now?

The issue is not only here, it was font rendering issue of Windows, please assign `Freetype` font engine in qt, it may help.

I can modify `qt.conf` in other app to let qt to use Freetype, they looks like this:
![photo_2023-02-21_12-11-29](https://user-images.githubusercontent.com/20187175/220246080-90a40fc3-413e-4d0d-b0f3-0126970f3382.jpg)

https://doc.qt.io/qt-5/qt-conf.html
```
[Platforms]
WindowsArguments = fontengine=freetype
```

Please check that, thanks.
