### ISSUE TITLE
Why is a spell-checking backend mandatory?

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#25921]
### Steps to reproduce

1. Install Gentoo
2. `emerge -qv =net-im/telegram-desktop-4.6.2::gentoo`

### Expected behaviour

The package should install.

### Actual behaviour

```
!!! The ebuild selected to satisfy "net-im/telegram-desktop" has unmet requirements.
- net-im/telegram-desktop-4.6.2::gentoo USE="X dbus fonts (jemalloc) -enchant -hunspell (-qt6) -qt6-imageformats -screencast -wayland" ABI_X86="(64)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    exactly-one-of ( enchant hunspell )

  The above constraints are a subset of the following complete expression:
    exactly-one-of ( enchant hunspell ) qt6-imageformats? ( qt6 )
```

I'm not sure if Telegram Desktop itself has a requirement like this, but it's evident that the Gentoo ebuild does. Please clarify.

### Operating system

Gentoo Linux

### Version of Telegram Desktop

4.6.2

### Installation source

Other (unofficial) source

**Comment by john-preston** [comment]
lib_spellcheck must be built starting with one of the late releases because it holds some common code working with languages.

So for the latest versions to be built on Linux hunspell is required. Downstream build scripts should be fixed with taking this into account.

**Comment by grepwood** [comment]
I see. What can contributors or devs do, to remove this requirement?

**Comment by ilya-fedin** [comment]
@grepwood why would you ever need to disable this? If you have any problem installing hunspell, tdesktop provides a bundled copy.

**Comment by grepwood** [comment]
@ilya-fedin I don't write official letters over Telegram. All I do there is goof off with my buddies, write mis-spelled copypastas, etc. The only communication tool which I use for official communication, that requires correct spelling to present myself as a responsible and serious individual, is Thunderbird. That is not to say that because my use case is such and such, other use cases are invalid. I do not wish to infringe on other people who want to have a spellchecker. I just want the option to remain without one at the binary linker level if that's okay.

**Comment by ilya-fedin** [comment]
@grepwood there's a lot of other dependencies without any switch, hunspell is one of the lightest dependencies and there was a switch only due to macOS not supporting spellchecking in the lowest supported OS version at the time. I bet you won't create this issue if there were no such option from the start.

**Comment by grepwood** [comment]
@ilya-fedin okay, but I'm not developing ebuilds right now, and I'm not the maintainer of tdesktop in Gentoo. That's nice to know there are other switches and perhaps that person should know about it, but that is unrelated to this issue. What's the rationale to enforce the presence of a spellchecker?

**Comment by john-preston** [comment]
Talking about the UI level, if this is required, you can disable spellcheck in Settings and not see it. 

Talking about the build level, I don't think this should be supported, it would complicate code and build scripts significantly for no reason.

It is not "enforcing the presence of a spellchecker", it is removing clutter from code and maintenance burden in terms of many if() branches in CMake code / many #if / #ifdef branches in C++ code for unbundling one particular dependency and making it optional.

Some other user may come and ask to make a switch to make OpenAL optional, because he doesn't need sound in TDesktop, the same for Lottie, for FFmpeg, for WebRTC. But this complicates code and makes maintenance harder for no benefit to the project.

**Comment by ilya-fedin** [comment]
@grepwood you probably misundertood what I said, it's the other way around.

> there's a lot of other dependencies without any switch

In other words, there are no other switches for other dependencies generally, there are switches only when there's a strong need of them, like the aforementioned lack of the APIs in older versions of macOS what is not a problem anymore.

**Comment by grepwood** [comment]
So if I submitted a patch to facilitate exactly what I want tdesktop to do, that's just not gonna cut it? Cause I need a spellchecker like I need a stick in the eye to be honest.

**Comment by ilya-fedin** [comment]
That's right, disabling visible features build-time is not pleasant in tdesktop
