### ISSUE TITLE
Last selected conversation gets deselected when closing the main window

### ISSUE THREAD

**Issue by kathampy** [telegramdesktop/tdesktop#2594]
When I close the main window and restore it from the dock / system tray on both macOS and Windows, it deselects the last active conversation. I now have to click on the person I was talking to last every single time! I suspect this is a feature, not a bug, but it's degrading my experience heavily.

**Comment by smaragdus** [comment]
This annoying behaviour when restoring Telegram to tray and the oval chat boxes (_Improved design for chats_.)- square boxes look far better- I do not want my conversations to look like comics, forced me to go back to version **0.9.56**.
I hope that what **kathampy** described above is a bug, not a feature, because it is horrible.

**Comment by stek29** [comment]
#2541.
I heard that search may be useful sometimes. Maybe you should even try using it next time.

**Comment by stemar94** [comment]
The fact that so many people independently assume the new "feature" is a bug and keep creating issues should be proof enough to revert it or make it configurable.
I heard that listening to the users may be useful sometimes. Maybe you should even try doing it next time.

**Comment by stek29** [comment]
@stemar94 I'd possibly do it if I was part of @telegramdesktop or was related to it in any way (except watching it).

**Comment by stemar94** [comment]
Yeah I also tried to locate this change in one of the latest commits, but couldn't find it. Maybe I should try again and then build my own version.
