### ISSUE TITLE
Client doesn't honor disabled autoupdate nor proxy settings after a crash

### ISSUE THREAD

**Issue by patheticcockroach** [telegramdesktop/tdesktop#26078]
### Steps to reproduce

- Have a SOCKS5 proxy configured
- Have auto-updates disabled
- Somehow manage to crash or "not close properly" the client
- Start the client again

Unfortunately, I don't know how to reproduce it reliably, it only happens when you get the tiny window, when starting the client, that says something like "Last time Telegram Desktop was not closed properly" and has a button to skip. I don't have a screenshot as I rushed to click "canceled" when I saw it downloading the update - alas too late, I have fiber... Pretty sure it's the [crash_report_window.cpp](https://github.com/telegramdesktop/tdesktop/blob/4247fd0c0f86f0cd07cdbd1bc85ec7fea9399722/Telegram/SourceFiles/core/crash_report_window.cpp) thing though.

When you get that window, it tries to connect directly to Telegram's servers without using the configured SOCKS5 proxy, and if you let the connection through, it will actually download an updated client (if any) even though updates are disabled.

Note that due to the nature of the bug, it's impossible for me to fully reproduce it with the very latest version, as then obviously auto-update won't do anything as there is nothing to update.

### Expected behaviour

Don't connect without using the configured proxy
Don't download an update

### Actual behaviour

Connects without using the configured proxy
Automatically updates

### Operating system

Windows 10

### Version of Telegram Desktop

4.6.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, it shouldn't follow the settings as it's constructed to not to share any code to avoid a crash while presenting the reporter.

**Comment by john-preston** [comment]
@patheticcockroach It is working like it's supposed to. It can be discussed whether this OK or not, but it is made explicitly.

Crash Reporting / After Crash Handling is working outside of local settings reading, including proxy settings and autoupdate, to minimize probability of crashing inside this Crash Reporting / After Crash Handling part of code.

So in normal working flow it should not crash, but if it crashes it forcefully checks for an autoupdate, because crashes sometimes are triggered instantly after the app is launched and it is possible that a fix is available with the updated version.

**Comment by patheticcockroach** [comment]
So, security vulnerability by design. I see.

**Comment by john-preston** [comment]
@patheticcockroach Why is it a security vulnerability?

**Comment by patheticcockroach** [comment]
Why use a proxy? 🤷

**Comment by john-preston** [comment]
@patheticcockroach I still don't understand why is this a security vulnerability. Proxy may be used because there is no direct access to Telegram in this network.
