### ISSUE TITLE
Show common groups/channels in profile

### ISSUE THREAD

**Issue by cihanyakar** [telegramdesktop/tdesktop#2613]
In contact info panel can show mutual groups and channels.

Since latest Telegram for Android (official client) update you can see "Groups in common" menu in people profiles.

![image](https://cloud.githubusercontent.com/assets/2780044/20134233/c065b830-a67b-11e6-99aa-9d4cf00c95c8.png)

**Comment by auchri** [comment]
Great.

**Comment by Kondra007** [comment]
@auchri Well, I don't get your sarcasm. Since latest Telegram for Android (official client) update you can see "Groups in common" menu in people profiles.
So this is more enchancement rather "invalid", IMO

![image](https://cloud.githubusercontent.com/assets/2780044/20134233/c065b830-a67b-11e6-99aa-9d4cf00c95c8.png)

**Comment by auchri** [comment]
@Kondra007 thanks for the explanation.

@cihanyakar should next time use the template and provide a better description.

**Comment by cihanyakar** [comment]
@auchri  Next time I will be more attentive.
