### ISSUE TITLE
Images are being pasted as a huge text

### ISSUE THREAD

**Issue by yurikoles** [telegramdesktop/tdesktop#26188]
### Steps to reproduce

I have option “Send large photos” enabled, it seems to be relevant, since it was a large image.

1. Copy some image to a clipboard from a Google Chrome context menu.
2. Paste it to Telegram Desktop.

### Expected behaviour

Image should be pasted.

### Actual behaviour

Sometimes, a huge volume of text is being pasted, and the app lags, just like in #26185. I faced this a few times, but one time I accidentally hit enter during app hang. So the app sent this large paste via smaller chunks, effectively creating a SPAM attack.

Moreover, I saw only a few first messages and didn't understand the frustration of other chat members until I restarted the app and saw this history nightmare they have faced.

### Operating system

Windows 11 22H2 Beta 22624.1610 

### Version of Telegram Desktop

4.7.1

### Installation source

Static binary from official website

### Logs
I restarted the app after the previous issue, so I see only a new log now.

**Comment by Aokromes** [comment]
not telegram desktop bug. reproducible with notepad too.

**Comment by yurikoles** [comment]
> not telegram desktop bug. reproducible with notepad too.

Ok, given that pasted-image-becomes-text bug is a third-party one, as you said. There is still another issue, `tdesktop` silently sends large text as a SPAM attack without any confirmation, and it appears in the history of the sender _only after restart_ of the app. Is this a known bug, or I should create a new ticket for it?

**Comment by john-preston** [comment]
@yurikoles Can you provide an example? An url where there is such image that I can paste and get a huge amount of text?

**Comment by yurikoles** [comment]
I'm trying to reproduce, with no luck so far, I'm mostly sure last time it happened with this image https://prnt.sc/wyVnayFXqxXt and other cases were with this site too. I mostly did image copies from this site, nowadays.

**Comment by VetaLioSTV** [comment]
@john-preston i can confirm this, since i'm facing it always. Very old bug i guess 😢 .

Example : [Url](https://allegro.pl/oferta/lusterko-prawe-bmw-e46-silbergrau-5pin-lift-euro-13244855206) with images , so when you want to save it to Telegram, for some photos ( i think it has reference to resolution(?) of image) it loads too slow, i even can see "micro" freezes (like a heavy stuff is going on main thread which blocks UI) and as results its not uploads photo, but for some reason a source link.

Links with images(from source url provided ^) which are not uploaded and threated as link - [this](![image](https://user-images.githubusercontent.com/15155286/233709675-8772216a-fdc8-4ff4-99fa-c10b83a188b5.png)), [this](https://a.allegroimg.com/original/11fac7/54d1c21b4ec2b5994cefd26782e4/Lusterko-prawe-BMW-E46-SILBERGRAU-5PIN-LIFT-euro) and [this](![image](https://user-images.githubusercontent.com/15155286/233710034-57a40427-6db4-4aa0-b4bf-aebde09758f5.png)) 

It has weird behavior, on 80%-95% cases first image will go with success and will appear form with sending images, but next images you want to paste unfortunately are threated as text links with micro freeze\lag (its kinda exception thrown and as result  pasted source link where it tried to upload into client?)

**Comment by yurikoles** [comment]
I haven't used Windows for a while, so I don't know if this bug is still there. And I never saw it on macOS.
