### ISSUE TITLE
Linux - links are not opened with the default broswer

### ISSUE THREAD

**Issue by cippaciong** [telegramdesktop/tdesktop#262]
Hello I'm running tdesktop 0.6.8 on my Linux machine and I have a problem with the browser. While all applications (graphical o cli) open links with Firefox which is my default browser, tdesktop open them with Midori, another browser I installed which is not the default one.
A friend of mine have the same problem but in his case links are opened with dwb (I don't think Midori is installed on his system).

**Comment by nchowning** [comment]
I am experiencing the same issue. I am running i3 w/ no desktop environment. My default browser is firefox set via the BROWSER environment variable:

% echo $BROWSER
firefox

On one of my computers, Telegram links will open in qutebrowser and on another they open in chromium.

**Comment by cippaciong** [comment]
@nchowning In the end I found out how to solve this problem, you just have to set your `xdg-open` default browser as explained here https://wiki.archlinux.org/index.php/xdg-open#Set_the_default_browser

**Comment by nchowning** [comment]
That fixed it for me. Thank so much cippacciong!

**Comment by Arcaena** [comment]
I've been having this problem recently. I've got my defaults set but once firefox is installed, links open in firefox by default (even though `xdg-open` opens the link in chromium properly)

**Comment by jeronimozc** [comment]
Hey! I'm having the same issue as @PandorasFox on Ubuntu 16.04 with tdesktop 1.2.14. Firefox just goes ahead and opens links on telegram, even if Chromium is my default browser.

**Comment by PandorasFox** [comment]
It ended up being a (weird) issue with some defaults I had set, buried, somewhere. I think the env var `$BROWSER` also mattered, maybe? It's been a while, but I fixed my setups and they behave properly now.

**Comment by jakub-olczyk** [comment]
Since I had the same problem and looking for a solution I was pointed here, yet the above-mentioned solutions didn't work for my setup. I'd like to leave mine fix for others in similar situation.

(For context, `gio open` and `xdg-open` had different behaviour for some reason on i3wm + CentOS 7.8 I use). 

I have solved the problem for me by following the guide here: https://unix.stackexchange.com/questions/386321/how-to-set-the-default-web-browser-used-to-open-urls-under-i3/572176#572176

And here's the gist of it for posteriority if the link ends up dead for some reason (Bash specific solution):
```
cat > /usr/share/applications/defaults.list <<__END__
text/html=firefox.desktop;
text/xml=firefox.desktop;
application/xhtml_xml=firefox.desktop;
image/webp=firefox.desktop;
x-scheme-handler/http=firefox.desktop;
x-scheme-handler/https=firefox.desktop;
x-scheme-handler/ftp=firefox.desktop;
__END__
```
Just remember to use one of the desktop files located here `/usr/share/applications/` .
I hope that leaving this solution here may be useful for somebody (and I hope never to rediscover it in the future :crossed_fingers: )

**Comment by 13werwolf13** [comment]
end of 2020 and we are still there

**Comment by enomado** [comment]
Looks like regression from last update

**Comment by filmmakerto** [comment]
i'm having the same problem with `pdf` files, they open in `gimp` even though i have `xreader` set as my default pdf application in `~/.config/mimeapps.list` as well as `/usr/share/applications/defaults.list`. links work fine though, they open up in the browser i have set as default. anyone else have the same problem?

**Comment by mrjimenez** [comment]
> Looks like telegram uses new way to determine default browser.
> 
> ```
> $ xdg-mime default browser.desktop x-scheme-handler/http
> $ xdg-mime default browser.desktop x-scheme-handler/https   
> ```
> 
> works for me

Just to make things a bit clearer, substitute `browser.desktop` by the appropriate .desktop file that should be present in `/usr/share/applications/`, e.g. `firefox.desktop` or `google-chrome.desktop`
