### ISSUE TITLE
Audio quality control

### ISSUE THREAD

**Issue by DiedByDisgust** [telegramdesktop/tdesktop#26307]
### Is your feature request related to a problem?

since(months ago, maybe couple years) audio quality upgraded, in Cuba works poorly because of the bad quality of the internet connection, it takes sometimes minutes to send or receive an audio message of few seconds, while in a primitive app as whatsapp that uses audios of less quality this is not a problem. is in my knowledge that this matter affects thousand of my fellow countryman, and i can guess the same for any other place with similar conditions. 

### Describe the solution you'd like

i believe that users with bad and poor internet connection quality, will be benefited of an option to chose reduce audio quality in order to optimize traffic.

### Describe alternatives you've considered

to use whatsapp, is the main answer to this problem for most Cuban that face it. I repeat, not a problem when using whatsapp with their few kibibytes per audio.

### Additional context

i'm posting this here at telegram desktop github, but it is a general suggestion, telegram widely. If i need to take this suggest to somewhere or someone else, please point me in the right direction. This has been a problem for too long now.

**Comment by Ciancy28** [comment]
Actually, this isn't a "telegram wide" issue, and has nothing to do with tdesktop.
The problem is with the Android client, which has for some reason switched from 24 kbps vbr (which is the same of tdesktop, iOS and even whatsapp) to 153 kbps cbr, which is extremely high and wasteful, considering that the makers of the codec (Opus) [suggest 128 kbps vbr as "fully transparent" for fullband stereo music.  ](https://wiki.xiph.org/Opus_Recommended_Settings)  
you should upvote this bugreport: https://bugs.telegram.org/c/20785
