### ISSUE TITLE
pinned message order order is not currect

### ISSUE THREAD

**Issue by AkramiPro** [telegramdesktop/tdesktop#26320]
### Steps to reproduce

pin more than 2 message 

### Expected behaviour

when click on pinned message it shoud show message in currect order 

### Actual behaviour

in the left of the pinned nessage bar the status of the current message is not currect
for ex: i am on 2 th message buy it show that i am on 1 th message
![image](https://github.com/telegramdesktop/tdesktop/assets/54323929/cf8105f8-9a15-48e8-a8a7-c651d1f9b138)

### Operating system

win 10 64bit

### Version of Telegram Desktop

4.8.1

**Comment by john-preston** [comment]
The bar shows the next message, the one you'll jump to if you click on the bar. When you open the chat at the bottom it shows there the last message, because if you click on the bar you jump to the last message. After that it shows the previous one, because if you click on the bar it'll show you the previous one. So, this is intended.
