### ISSUE TITLE
Telegram Icon is not shown in the panel

### ISSUE THREAD

**Issue by Gameranand** [telegramdesktop/tdesktop#2638]
I am not sure if it can be reproduced at all. After OS updation it just started.

Telegram system tray icon should be visible

Telegram System tray icon is not visible, instead a blank space is there. 
![image](https://cloud.githubusercontent.com/assets/11816991/20300820/dedf18cc-ab46-11e6-91a7-233837d04202.png)

Linux Mint LMDE 2 Cinnamon Edition

Version of Telegram - 0.10.9

**Comment by Aokromes** [comment]
#2092 generic bug?

**Comment by Gameranand** [comment]
No I don't think so. See the space on the right of Redshift Icon. A place is left blank, in that place Blue or yellow icon should be there but it isn't.

In this Issue you mentioned, space is not left either, that issue I ca reproduce by disabling the Systray icon from Telegram settings.

**Comment by Gameranand** [comment]
dbus-launch ~/.softwares/Telegram/Telegram start & disown

This command worked for me. Hopefully it might work for others as well.

Still no direct option but at least its working for me now.

**Comment by Translator5** [comment]
^ confirmed -> Linux Mint 18.1; Cinnamon 3.2.7+serana; Telegram Client 0.10.20

**Comment by maxkl** [comment]
I have the same problem.

I am on Arch Linux with Cinnamon 3.2.8. My version of Telegram Desktop is 1.0.5.

- If I start telegram with `XDG_CURRENT_DESKTOP` set to `gnome`, I do get a tray icon. In the log file, there is a line `Using appindicator tray icon.`.
- If I start telegram with `XDG_CURRENT_DESKTOP` unchanged (by default, it's set to `X-Cinnamon`), I do **not** get a tray icon, just an empty space. In the log file, there is a line `Using Qt tray icon.`.

I have come to the conclusion that the bug is caused by Qt, as libappindicator does apparently work.
The hack with `XDG_CURRENT_DESKTOP` works because of [line 381 in /Telegram/SourceFiles/platform/linux/main_window_linux.cpp](https://github.com/telegramdesktop/tdesktop/blob/28899a642b98e2bba77a172be83a6cc487c56759/Telegram/SourceFiles/platform/linux/main_window_linux.cpp#L381).

The command suggested by @Gameranand does also work for me. However, it changes the style of the tray context menu.

Maybe Telegram Desktop is using an outdated version of Qt? Or has there been a breaking change in a recent version of Qt?

**Comment by Translator5** [comment]
@maxkl Actually I think, you are probably right with outdated versions of Qt, but this issue is not only for Telegram. Ts3 and Steam do have issues with Cinnamon also.^

**Comment by maxkl** [comment]
Thank you, it works for me now!

**Comment by maxkl** [comment]
Well, it's not working anymore.
The workaround I described before also doesn't work with `XDG_CURRENT_DESKTOP=gnome`. However, it does work if I set `XDG_CURRENT_DESKTOP` to `unity`.
I don't exaclty know since which version this has changed, but it was recently.

**Comment by th-slopes** [comment]
Hi, maybe it's a little late but, I was having a similar behavior on my system and I got fix that increasing the delay time in the initialization of the Telegram. Looks like it work because the icon only appears when all others items of the cinnamon interface was fully charged.

**Comment by assarbad** [comment]
> Hi, maybe it's a little late but, I was having a similar behavior on my system and I got fix that increasing the delay time in the initialization of the Telegram. Looks like it work because the icon only appears when all others items of the cinnamon interface was fully charged.

Then it should work as long as it's not automatically started (or as you mention: delayed) during startup. Unfortunately didn't work for me on Ubuntu 20.04 with Cinnamon.

`XDG_CURRENT_DESKTOP=unity` also didn't work and neither did the `dbus-launch` method, **but `XDG_CURRENT_DESKTOP=Unity` (uppercase U) did work.
