### ISSUE TITLE
"Use native window" feature is broken on Linux

### ISSUE THREAD

**Issue by zilti** [telegramdesktop/tdesktop#26564]
### Steps to reproduce

1. Open Telegram settings on desktop
2. Try to find the option to turn on native window borders
3. Fail to find the option and research online
4. Find out it is supposed to auto-detect if native borders are supported, but the feature is broken

### Expected behaviour

I get the option to enable native window borders

### Actual behaviour

The option is missing here (KDE Plasma, and apparently also Sway)

### Operating system

openSUSE Tumbleweed, KDE Plasma 5.27.6

### Version of Telegram Desktop

4.8.4

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
As it was said in the issue template, only official builds are supported. If you can't report with checking the issue on official build, you should report the issue to whoever made the build.

**Comment by zilti** [comment]
Well, then I guess you can shove it. I don't feel the need to go out of my way to track down an obviously existing bug even further for some toxic maintainer online.

**Comment by ilya-fedin** [comment]
The problem is that no one has time & will to check on dozens of custom builds from various distros and repositories especially given that all of them patch for their policies (e.g. Debian is known to crop out a lot of features). It's also a standard practice that users report to people who made build to them and they then report further having their investigation part done, confirming it's not their fault and providing the relevant information to upstream.
