### ISSUE TITLE
Limits to exclude chats

### ISSUE THREAD

**Issue by Crushtests** [telegramdesktop/tdesktop#26713]
### Steps to reproduce

click on a chat
try to remove it from folder.

### Expected behaviour

I have a lot of chats, so I am cataloging them by folders. some chats became inactive, so I remove them. And now I can't do that, because it tells me that I have limits to EXCLUDE chats. I understand limits of chats in the folder - not more thatn 100/200, but to exclude - why? I can just delete the wrole folder and recreate it again with chats I need, but why?

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/20880689/4bf6dda3-7d0a-4316-a995-24ecd5e7ed94)

### Operating system

Windows 11

### Version of Telegram Desktop

Latest 4.9.2x64

### Installation source

Static binary from official website

**Comment by Crushtests** [comment]
Works the same from mobile app as well. shows me the same error.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by john-preston** [comment]
@Crushtests Because you added a chat category to the folder (like Groups, or Channels) and then started adding exceptions (some specific chats or channels), there is a limit on the exceptions list. If this was a folder with only specific chats being added there in the first place, not the whole categories, you could've removed them from the folder one by one without a limit, until the folder is empty.

**Comment by Crushtests** [comment]
entered the folder settings. really. this is stupid. I removed chat from the folder by clicling on "add to the folder" and choosing the same folder. I didn't knew that this chat will be added to excluded list.
Well, this is literally a mistake, because the folder I am using doesn't have any automatically added chats. I manually add and remove them.

**Comment by enowayter** [comment]
what's the solution for this?

**Comment by Crushtests** [comment]
> what's the solution for this?

Just open chat settings, where you see the list of the chats and options to add them. And there is a list of excluded chats.
And remove them.
Actually this logic works if I really added to the folder group of chats, like channels, e.g. I have 1000 channels and I can exclude not more than 100/200 of them. But I manually added chats there. So in this case, instead of just remove the chat, I also exclude them.

**Comment by john-preston** [comment]
@Crushtests @enowayter In the latest versions adding to exclusion list should be done only if otherwise (without adding to exclusion list) the chat will appear in the folder (by the category selector, like Groups or Contacts or Channels).

So if you manually add a chat from context menu to a folder and then manually remove the same chat from the folder it shouldn't be added to exclusions list and this problem shouldn't arise.

**Comment by Crushtests** [comment]
> @Crushtests @enowayter In the latest versions adding to exclusion list should be done only if otherwise (without adding to exclusion list) the chat will appear in the folder (by the category selector, like Groups or Contacts or Channels).
> 
> So if you manually add a chat from context menu to a folder and then manually remove the same chat from the folder it shouldn't be added to exclusions list and this problem shouldn't arise.

Just cgecked. Indeed. perfect then :-)
