### ISSUE TITLE
Strange bug with playing big m4a file

### ISSUE THREAD

**Issue by palandovalex** [telegramdesktop/tdesktop#26834]
### Steps to reproduce

Send someone this m4a file:

https://disk.yandex.ru/d/pmIIW4ULKF0z0Q

Play this file inside telegram-desctop. 

### Expected behaviour

It should goes untill compliete and then go to other file.

### Actual behaviour

When it will goes to 35:58 - it goes to start of file, and gets into an endless loop of file playback from the beginning to the point 35:58

### Operating system

Linux Mint 21.2 Victoria

### Version of Telegram Desktop

4.9.9

### Installation source

Snap

**Comment by ilya-fedin** [comment]
I think there was a similar report before and the problem is that your system asks tdesktop to stop playing via the MPRIS API. You can prevent tdesktop from accessing D-Bus as a workaround (by e.g. setting DBUS_SESSION_BUS_ADDRESS environment variables to some garbage value). A proper fix could be done only by the component that does that request and so you should report this somewhere to your system.
