### ISSUE TITLE
Restore proper color of the reply

### ISSUE THREAD

**Issue by maxoku** [telegramdesktop/tdesktop#26987]
### Is your feature request related to a problem?

After the new update the replies are purple, against the theme color and can't be changed. That's just rude.

### Describe the solution you'd like

If that's suppose to be a premium function then don't use a fixed color for everyone, just let it follow the theme color like was before.

### Describe alternatives you've considered

Or just allow everyone to change it, not only those that are paying.

**Comment by Aokromes** [comment]
platform wide bugs / requests belongs to https://bugs.telegram.org/

**Comment by maxoku** [comment]
Rude, can't report anything cuz it's being closed. With every update telegram is becoming more annoying and we have no right to complain. It's a valid issue, if you broke something then take responsibility.

**Comment by john-preston** [comment]
@maxoku No sense in keeping open issues here for something, that isn't decided here and can't be changed here.

You have "right to complain" on https://suggestions.telegram.org.

Here is the issue tracker for bugs (behavior not intended by the developer, me), so that I can track them.

Also some TDesktop-specific suggestions can be posted and discussed here, that are not related to the way platform operates as a whole (in all official apps, like iOS / Android).

Everything related to Telegram as a whole should be posted and discussed on the platform on telegram.org.
