### ISSUE TITLE
Text embedded in web page previews cannot be selected

### ISSUE THREAD

**Issue by bb010g** [telegramdesktop/tdesktop#27016]
### Steps to reproduce

1. Send a message with a web page as its media, e.g. `https://youtu.be/dQw4w9WgXcQ`.
2. Attempt to select any of the message's web page view's text.

### Expected behaviour

By clicking & dragging, text can be selected. Perhaps the alt modifier key must be held during this process to prevent opening the link (a convention followed by Firefox, Chrome, and TDesktop itself for message body text).

### Actual behaviour

Clicking anywhere on the web page view's text opens the link. Dragging from anywhere on the web page view's text starts a drag action for the link target, as if dragging from the body's link. Holding alt changes neither of these behaviors.

Dragging from the body's text into the web page view's text selects both the body's text and the web page view's text, as in TDesktop before v4.11.0. Dragging from this selection, on the web page view's text, drags the selection content, as if dragging from the selection on the body's text. Holding alt does not change this behavior.

### Operating system

Windows 11 Pro 22H2 (x86_64)

### Version of Telegram Desktop

v4.11.1

### Installation source

Static binary from official website

### Extra information

I suspect this was introduced through a combination of <https://github.com/telegramdesktop/tdesktop/commit/f8d5a8a203f96bf0f10db5098e4ee9bddac89a41#diff-e9718579cda095d4fd006f5ae0e1ae39c08c3dc0b7b3d7343b0f67654e88e629R718-R720> and <https://github.com/telegramdesktop/tdesktop/commit/3a84c6afdd891e80b02b90b35a492517e293a994#diff-e9718579cda095d4fd006f5ae0e1ae39c08c3dc0b7b3d7343b0f67654e88e629L718>.

**Comment by Aokromes** [comment]
fixed on https://github.com/telegramdesktop/tdesktop/releases/tag/v4.11.2

**Comment by bb010g** [comment]
This was fixed by <https://github.com/telegramdesktop/tdesktop/commit/728ed02a1cf3400091b37a72659bdb046e793e85>, specifically. Thank you!

**Comment by enchained** [comment]
After the fix it feels much clunkier compared to how it was before all the changes. Now you can not double click to select a word or triple click for a paragraph. Now you have to be very careful to not accidentally click anywhere during the text selection, since it will lead to the link opening. The whole link area also highlights when you select the text, which I find distracting. 

It feels like Telegram rolled out a lot of features recently without a proper accessibility testing (I'm talking about the original mobile implementation - you still can't even select the text there)

**Comment by john-preston** [comment]
@enchained Well, the new links preview implementation wasn't supposed to have the text selection at all, I've just added it on top.
