### ISSUE TITLE
[Feature request] Display exact timestamp in messages

### ISSUE THREAD

**Issue by fbnlsr** [telegramdesktop/tdesktop#2705]
It would be useful if messages could display the exact timestamp, precise to the second, when a message has been sent/receive.

At this day, the message is only precise to the minute.

**Comment by mongolrgata** [comment]
But now you can hover timestamp box to popup datetime in full format.

**Comment by fbnlsr** [comment]
It still won't show the time to the second. At least not on Telegram client on MacOS.

**Comment by john-preston** [comment]
@fbnlsr It depends on your system full date-time format.

**Comment by fbnlsr** [comment]
That means that the UX is non-consistent depending on the OS a user is using, which is counter-intuitive. I think it should be changed to something that is the same across all platforms.

**Comment by stek29** [comment]
@fbnlsr so you think that app should force one time format for everyone independent on their system settings?

**Comment by fbnlsr** [comment]
@stek29 In that case I believe so, as it would provide a platform-agnostic and consistent user experience.

**Comment by stek29** [comment]
@fbnlsr the app forces 12 hour format on Linux and has DD.MM.YY format hardcoded in some places, and you could easily find a lot of users who dislike it.
While you're the first one asking for forced unconfigurable date format.

P.S. https://support.apple.com/kb/PH18435

**Comment by eyalroz** [comment]
Repeating a point from the dupe bug: I'm hoping there could be a configurable option to switch between verbose, full timestamps and simpler, HH:MM only timestamps.

**Comment by Aokromes** [comment]
#618 ?

**Comment by eyalroz** [comment]
@Aokromes : That one is completely independent of this one - I would hate to see the two  artificially linked.

**Comment by Aokromes** [comment]
Well, for me it looks very related, the choice of way to show the timestamp :)

**Comment by SmartManoj** [comment]
In windows
By changing the short time format to "h:mm:ss tt" will show seconds 
![image](https://user-images.githubusercontent.com/7231077/47617169-8dbd5c80-daea-11e8-845e-e7c9d5fed883.png)

[Source](https://smartmanoj.blogspot.com/2018/10/telegram-desktop-show-seconds.html)

**Comment by SanderBouwhuis** [comment]
> 
> 
> @fbnlsr It depends on your system full date-time format.

Yessssssssssss. Actually, it depends on the system's SHORT time format. By default it's HH:mm. Simply changing it to HH:mm:ss will fix the problem.

Thanks fbnlsr!

**Comment by Littleprince18** [comment]
How does Telegram timestamp an image do you know if the timestamp is created at the point the message is sent or is it when it is received to the device or is it when it is downloaded?

**Comment by SmartManoj** [comment]
@Littleprince18  timestamp is created when the message is received in server

**Comment by Littleprince18** [comment]
Thanks, so that does not mean that you have to have clicked download for that timestamp to have tagged? For example if i havecauto download on and a bunch of images sace to my gallery then all the timestamps will be when they reached my server and not when retrieved by my gallery. 
Also do you know if dev on group chat differs from a one on one chat with respect to the way that messages are downloaded. What i am wondering is if i am in a massive group chat with users in different global locations and I have not been active in a group for a while but then I click back into the group will the cascade of messages start from the top of everything I have missed or will it start from tbe bottom. And if I'm in a one to one chat will that be different or the same
Thanks

Sent from Yahoo Mail on Android 
 
  On Wed, 28 Aug 2019 at 13:08, SmartManoj<notifications@github.com> wrote:   
@Littleprince18 timestamp is created when the message is received in server

**Comment by Littleprince18** [comment]
Also is the timestamp the same for iphone and android? If i transfer all my apps from an iphone to an android phone including telegram would the timestamp in the back end of an image still be created when my servwr received that download, or is the coding different.

**Comment by Littleprince18** [comment]
Also does anyone know if the configuration of grouo chats versus one to one chats differs on telegram and how so? Im doing something really important which is why my questions are so specific but also im not a technical whizz so i just need some help thanks

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1920
