### ISSUE TITLE
Monochrome icon settings are not displayed in Windows 10 build 17763

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [telegramdesktop/tdesktop#27056]
### Steps to reproduce

Despite [matching the version check code](https://github.com/telegramdesktop/tdesktop/commit/cd0f58fa658941c5bd1cd1e8596c81ab220db9d1) and [Qt 6.5 support](https://doc.qt.io/qt-6.5/windows.html) the icon settings do not appear.

### Expected behaviour

A toggle switch should be shown.

### Actual behaviour

see top

### Operating system

Windows 10 LTSC 1809 (17763.4974)

### Version of Telegram Desktop

4.11.5

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
tdesktop code uses Qt 5.15 on Windows. Although that part of the code is not related top option, it's related to application night mode detection as builds with Qt 6.5+ use Qt API.

**Comment by ilya-fedin** [comment]
As you can see, having build 17763 is not enough, the registry key query must also success. It may be that the version check is incorrect and your Windows version doesn't support the registry key. There's nothing you can do except of updating Windows then.

**Comment by ilya-fedin** [comment]
According to this wiki page, you need build 18282 or newer
https://en.m.wikipedia.org/wiki/Windows_10,_version_1903

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
@ilya-fedin I don't think so because I solved this problem after adding that registry key. Probably the code should have blocked only auto-enablement, but not access to setting.

**Comment by ilya-fedin** [comment]
Windows 10 1809 doesn't have the feature so reading the key on it is wrong. Setting this key to 1 will lead to black icon on black taskbar rather than the system switching to light theme.

**Comment by blankCubicle** [comment]
@ilya-fedin Why disable the monochrome icon entirely for earlier Windows versions? Dark taskbar is supported in these, it is the only option, it could just display the white icon without issue if the user enables the setting, LTSC 1809 (17763) users can still benefit. The registry check only needs to be done on v18282 and up to display the black icon if the taskbar is light/white. It could fall back to white icon if the key doesn't exist.

**Comment by ilya-fedin** [comment]
> Dark taskbar is supported in these

The feature in question is light taskbar, not dark taskbar. Before light taskbar there were no way to check taskbar background (I'm not aware about any way at least) and without a way to check taskbar background it's unreliable.

**Comment by ilya-fedin** [comment]
> it could just display the white icon without issue if the user enables the setting, LTSC 1809 (17763) users can still benefit.

1809 has only AppsUseLightTheme which is irrelevant for the use-case. Application dark mode has nothing to do to the system appearance, you will still have dark taskbar in light mode and get dark icon on dark taskbar.

**Comment by blankCubicle** [comment]
> 1809 has only AppsUseLightTheme which is irrelevant for the use-case. Application dark mode has nothing to do to the system appearance, you will still have dark taskbar in light mode and get dark icon on dark taskbar.

Sorry, when I said "if the user enables the setting" I was referring to Telegram's monochrome icon setting, not the Windows' app theme mode.

The problem is that you can't get the white icon for your dark taskbar. Since the monochrome icon setting is missing, you're forced to use the blue icon when the white icon would do just fine.

I'm saying the registry check is unnecessary for 17763, the taskbar will always be dark, so allow us to use the white tray icon.

**Comment by ilya-fedin** [comment]
Sorry but it's not possible to implement monochrome icon without knowing what background will be under it or you take a risk of having icon color the same as the background which is no-go for an official client. If you know API for older Windows versions then feel free to help but otherwise you have to accept you have to upgrade your OS for new features.
