### ISSUE TITLE
Pios bookworm 64bit Raspb Pi5 arm64 error SNAP arm64 telegram-Desktop not start

### ISSUE THREAD

**Issue by tigernero79** [telegramdesktop/tdesktop#27128]
### Steps to reproduce

Install snap telegram-Desktop arm64

Start the error

### Expected behaviour

Start telegram

### Actual behaviour

when I launch the telegram-Desktop arm64 snap after installing it on my 64-bit Raspberry Pi5 with Debian 12-based Pios bookworms I get the error:

`<jemalloc>: Unsupported system page size ../glib/gprintf.c:349: failed to allocate memory`

how can I solve it?

### Operating system

PiOS Bookworm 64bit

### Version of Telegram Desktop

4.11.x

### Installation source

Snap

**Comment by ilya-fedin** [comment]
Looks like you need to ask jemalloc project to support your hardware
https://github.com/jemalloc/jemalloc

**Comment by tigernero79** [comment]
I read the link but I don't understand I don't know how to program I installed the snap but it just doesn't start. yes can you fix it with new snap arm64 release?

**Comment by ilya-fedin** [comment]
no, the depency of tdesktop I linked doesn't support your hardware. You have to ask the developers of that library to support your hardware providing the error line you provided here. You can report back the issue you will create at their repo and I subscribe to it.

**Comment by tigernero79** [comment]
in the last post I was criticized for what I wrote they reported that compilation options would be up to you to implement in the snap application so that it starts on pi5 arm64 os 64 bit so I will wait here for news if you release an update that includes this fix. Thank you

**Comment by ilya-fedin** [comment]
Compilation option won't be added, it will change the target to your hardware while make worse for other hardware. As was discussed at the jemalloc tracker, jemalloc should first gain dynamic target size support so it automatically detects it and can work on any hardware. Right now it's a choice between different kinds of hardware, not making it universal, so I don't see any sense to do the change.

They also said this is not a high priority from their side, so unless you want to use your open source rights and help them with implementing that, this apparently won't happen in the near future.

**Comment by tigernero79** [comment]
so you're telling me regardless of what jemalloc said that you should have implemented, according to him.

but are you telling me that official telegram-desktop snap which is compatible with arm64 architecture will not run soon on a pi5 with arm64 architecture? I don't understand the problem and how to solve it but it's absurd given that the previous arm64 model runs? what changed from pi4 to pi5? both arm64 why doesn't it start? I'm not technical but I think that in the snap you have to specify that on some arm64 architectures the snap will not start

which seems absurd to me, I repeat

**Comment by ilya-fedin** [comment]
The only officially supported architecture is amd64. Everything else is community maintained.

**Comment by ilya-fedin** [comment]
> what changed from pi4 to pi5? both arm64 why doesn't it start?

As far as I understand it's something about the OS or hardware. But honestly this is not very much clearer to me than to you.

**Comment by vielmetti** [comment]
What has changed in the Pi 5 is that 16K page sizes are now the default. This is the same configuration as Asahi Linux on Apple Silicon.

jemalloc will work with 16K pages if it is compiled with support for them, but it defaults to 4K pages.

It is possible to boot a Pi 5 with 4K page sizes, which Is documented on the Pi. "The Raspberry Pi 5 firmware defaults to loading kernel_2712.img because this image contains optimisations specific to Raspberry Pi 5 (e.g. 16K page-size). If this file is not present then the common 64-bit kernel (kernel8.img) will be loaded instead." If nothing is going to be fixed in the snap, then @tigernero79 you can try booting the 4K kernel to see if that gets around your problem here.

I have a longer description of the issue here - as dealing with jemalloc is a common problem on Pi5 setups.

https://vielmetti.typepad.com/logbook/2023/11/16k-page-size-compatibility-for-pi5-software.html

The common upstream issue is https://github.com/jemalloc/jemalloc/issues/467 .

**Comment by ilya-fedin** [comment]
The only adequate way forward is probably to replace jemalloc with scudo but I'm bot sure whether such change is wanted given that arm is not officially supported.
