### ISSUE TITLE
Scrolling is broken through ELAN touchpad

### ISSUE THREAD

**Issue by PEKTOP** [telegramdesktop/tdesktop#2726]
I try to scrolling through the touchpad (place two fingers on the touchpad and slide vertically) list of contacts orconversation on my lenovo z50 laptop but it doesn't work.

### Steps to reproduce
1. Just use Telegram Desktop
2. Try to scrolling through the touchpad

### Expected behaviour
Scrolling

### Actual behaviour
Not scrolling

### Configuration
Operating system: Windows 10 Home Version 1607 Build 14393.576

Telegram Desktop: 0.10.20

**Updated:** It was observed after start VirtualBox (that use QT too) everytime.

**Comment by stek29** [comment]
> Expected: Scrolling 
> Actual: Scrolling 

I guess you made a typo :)

**Comment by behnamazimi** [comment]
I have this issue too!
Lenovo Z510 Windows 10 x64

**Comment by PEKTOP** [comment]
Sorry. I made typo of course.
Expected behaviour: scrolling; actual: not scrolling.

**Comment by noiob** [comment]
Do you mean vertical? Since they're vertical lists, horizontally scrolling shouldn't do anything.

Scrolling is also broken on Linux (Debian stable, XFCE), where the app does not honor the scroll direction set in the XFCE settings but scrolls in the opposite direction for some reason.

**Comment by PEKTOP** [comment]
Sorry. I done vertically slide.
Also, I have more information about this problem: Scrolling broke after start VirtualBox (that use QT too). 
Have ideas?

p.s: just very seldom reboot my laptop

**Comment by mariohuq** [comment]
I have too!
Lenovo G50-45
Windows 10 Pro N 1703 build 15063.540

**Comment by JackieMium** [comment]
Windows 10 1709 OS Build 16299.192. Telegram 1.2.6, vertical two finger scroll not working.
However, it works under Debian Linux, Xfce4 desktop environment.

**Comment by grayideas** [comment]
I have this problem too..
Lenovo Z5070 - Windows 10 Enterprise x64
The scrolling sometime works.. but in usual suddenly stops working in no reason..
Is a way to solve this bug?

**Comment by fortunereject** [comment]
What's the manufacturer of your touchpad? I've found simlar issue on my Lenovo Ideapad 100 with ELAN drivers. After hours of deep-googling I finally located and solved this scrolling bug. 

I posted the fix [here](https://answers.microsoft.com/ru-ru/windows/forum/windows_10-hardware-winpc/%D0%BD%D0%B5/3bc9564a-85c8-405b-bb10-7c64bec650a1) (Russian).

Brief explanation: ELAN drivers have custom app profiles feature, in case an app needs some custom gesture behaviour. These profiles are located in [[\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Elantech\APOptimize\] registry path. In case of Telegram, ELAN driver somehow raises wrong mouse events. More on this [here on Mozilla bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=593372), [here](https://bug593372.bmoattachments.org/attachment.cgi?id=511627) and [here](https://bug593372.bmoattachments.org/attachment.cgi?id=511608) in code comments.

My registry fix for this is [here](https://drive.google.com/open?id=1PZ5RfkcyGMumEOme--LMSuXdKvRM5xwl), I just copy-pasted Google Chrome custom profile. Now it works like a charm. 

This problem is totally not on Telegram side, but Telegram team can create some hacks to bypass this driver bug.

Hope it helps.

**Comment by JackieMium** [comment]
@fortunereject  Could you please provide more information about what you did? 
I think we're probably facing the same problem as my touchpad is ELAN too. But I used you reg file and scroll still won't work in Telegram. Thanks!

**Comment by fortunereject** [comment]
@JackieMium did you reboot your laptop?

**Comment by JackieMium** [comment]
@fortunereject Great! Thanks for the tip. It is working after a reboot!

**Comment by RuvimPinka** [comment]
In ELAN driver version 22.4.22.2 (on Windows 10), APOptimize key is located in the Class branch.

The corresponding regfile is following:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e96f-e325-11ce-bfc1-08002be10318}\0000\APOptimize\Telegram]
"Text"="Telegram"
"Class"="Qt5152QWindowIcon"
"FocusText"=""
"FocusClass"=""
"FileName"="Telegram.exe"
"FileVersion"=""
"Option"=hex:01,00,00,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,00,00,00,00
"Scroll"=hex:01,01,01,01,b9,9b,7d,5f,41,32,28,1e,a0,84,6c,58,48,3c,34,30,01,02,\
  05,07,0a,11,23,4b,02,5b,02,02,5b,02
"Zoom"=hex:58,28,18,10,0c,08,02,02,58,28,18,10,0c,08,02,02,01,02,05,07,0a,11,\
  4b,4b
```


Don't forget to reboot after applying these changes to have the effect.

**Comment by ruv** [comment]
In ELAN driver version 22.4.22.2 (on Windows 10), APOptimize key is located in the Class branch.

The corresponding regfile is following:

````
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Class\{4d36e96f-e325-11ce-bfc1-08002be10318}\0000\APOptimize\Telegram]
"Text"="Telegram"
"Class"="Qt5152QWindowIcon"
"FocusText"=""
"FocusClass"=""
"FileName"="Telegram.exe"
"FileVersion"=""
"Option"=hex:01,00,00,00,00,00,00,00,00,00,01,00,00,00,00,00,00,00,00,00,00,00
"Scroll"=hex:01,01,01,01,b9,9b,7d,5f,41,32,28,1e,a0,84,6c,58,48,3c,34,30,01,02,\
  05,07,0a,11,23,4b,02,5b,02,02,5b,02
"Zoom"=hex:58,28,18,10,0c,08,02,02,58,28,18,10,0c,08,02,02,01,02,05,07,0a,11,\
  4b,4b

````
Don't forget to reboot after applying these changes to have the effect.
