### ISSUE TITLE
using mtproto_proxy  in desktop version

### ISSUE THREAD

**Issue by rezaei** [telegramdesktop/tdesktop#27359]
### Steps to reproduce

I want to using mtproto proxy in desktop version 
but it says to me download the latest version , 
after download latest version , again show me that error 
![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/38a0e70d-5df4-47cb-be01-af1a0b71cb00)

![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/7be1478b-c627-4608-af58-e2f12e121014)

### Expected behaviour

i want to use mtproto proxies in desktop version 

### Actual behaviour

![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/e00c0bbb-e96f-4b78-a5b4-40b3becec900)

### Operating system

windows 10

### Version of Telegram Desktop

4.14.4  x64

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
Telegram desktop supports mtproto since a lot of years ago, can you link the proxy you are trying to use?

**Comment by usergitalberto** [comment]
I commented follow message a month ago in the android version, unfortunately without response:

In some links dedicated to add a new proxy isn't possibile to use due to an error message:

"Your Forkgram Desktop version doesn't support this proxy type or the proxy link is invalid. Please update Forkgram Desktop to the latest version."

Below is an example link:

https://t.me/proxy?server=cloudflare.com.nokia.com.co.uk.do_yo.want_to.clash_with.this.www.microsoft.com.there_is_no.place_like.localhost.www.bing.com.count_with_me.cyou.net.now_sudo.rm.again_to_fight.everyone.i_am.the_internet.colam-bonaza.sbs.&port=4550&secret=AAAAAAAAAAAAAAAAAAAAAGQ=

I hope it can help

**Comment by rezaei** [comment]
https://github.com/telegramdesktop/tdesktop/pulls

> Telegram desktop supports mtproto since a lot of years ago, can you link the proxy you are trying to use?

it seems after update to new patch  . this problem have been solved 
![image](https://github.com/telegramdesktop/tdesktop/assets/2250985/b0e398b4-aa54-402c-a103-ba2fa071abb7)
