### ISSUE TITLE
Webview Crash in Ubuntu when I tried to open Devtool.

### ISSUE THREAD

**Issue by MrBns** [telegramdesktop/tdesktop#27427]
### Steps to reproduce

I  was developing an wallet as TMA (telegram mini app).  as a developer we all must to debug our program in actual using environment. So found the debugging way in official telegram page [here](https://core.telegram.org/bots/webapps#debug-mode-for-mini-apps).  As a linux user I followed instruction.  But when I open open Webview Devtool and inspect something, It does always Crash the Webview without any error message..  
I don't have any idea how can I get error report or details message. 

**I also want to mention** that Webview Devtool is soo bad compared to Tauri Devtool.. Why tauri ? because Tauri also using native Webview to render application.. it shouldn't be different. Please  try to focus on this section. Linux. 

### Expected behaviour

When I run webview devtool it should be working fine with debugging process. 

### Actual behaviour

Telegram webview get Crashed when I open devtool and do some very basic debugging task like running console, selecting element. 

### Operating system

ubuntu (23.10)  - GNOME desktop environment.

### Version of Telegram Desktop

4.14.9

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Yeah, webview on Linux is not stable.. The reason is insane stakeholders of wayland-protocols refusing to provide native window embedding and the QtWaylandCompositor library is full of bugs with crashes.

**Comment by MrBns** [comment]
> Yeah, webview on Linux is not stable.. The reason is insane stakeholders of wayland-protocols refusing to provide native window embedding and the QtWaylandCompositor library is full of bugs with crashes.

So we cannot deliver a bug less TMA to the Linux user ? Btw I am not on Wayland..

**Comment by ilya-fedin** [comment]
> So we cannot deliver a bug less TMA to the Linux user ?

Without a help of someone more experienced, no. tdesktop lacks Linux contributors.

> Btw I am not on Wayland..

The Wayland backend is forced on GNOME beacuse the native X11 backend doesn't display anything at all on GNOME and user helped with forwarding the bug to GNOME developers.

**Comment by ilya-fedin** [comment]
As far as I'm aware, it works somewhat reliably only on KDE X11.

**Comment by MrBns** [comment]
> Yeah, webview on Linux is not stable... The reason is insane stakeholders of wayland-protocols refusing to provide native window embedding and the QtWaylandCompositor library is full of bugs with crashes.

Also I don't know which kind of WebView Tauri is using for linux. it works fine..  My point is is Why we cannot use a good stable webview  for telegram miniapp ?  is this just because of `QtWaylandCompositor`  ?

**Comment by ilya-fedin** [comment]
> Also I don't know which kind of WebView Tauri is using for linux. it works fine..

If their README is right they use the same library: webkitgtk. The difference with the crashes is due to the fact tauri provide webkit in a top-level while tdesktop embeds it into Qt-based UI interface. In order to do that, a nested compositor has to be spawn with QtWaylandCompositor which is very buggy.

> My point is is Why we cannot use a good stable webview for telegram miniapp ?

What is 'good stable webview'? I'm happy to make it more stable, but I don't see a way to do that.

> is this just because of `QtWaylandCompositor` ?

Yeah, most bugs are due to the fact of embedding gtk to qt. This doesn't always go through QtWaylandCompositor (if you're using X11 without GNOME then it should go through native stuff used by QWidget::createWindowContainer + QWindow::fromWinId) but it's always more or less bugged.

On Windows and macOS, native window embedding works without bugs, apparently because those OS have good underlying protocol without the hell of compatibility between different WM implementations and are likely more important to Qt due to their big market share.
