### ISSUE TITLE
Weird notification windows in version 4.15.3 (Ubuntu 20.04 Unity DE)

### ISSUE THREAD

**Issue by vkapas** [telegramdesktop/tdesktop#27807]
### Steps to reproduce

1. Upgrade Telegram from version 4.15 to 4.16.8.
2. The «Use native notifications» option is enabled in Settings.
3. Telegram started using a weird notification method.

### Expected behaviour

I've expected standard Ubuntu-style notification, which Telegram used up to version 4.15.
![2](https://github.com/telegramdesktop/tdesktop/assets/12103655/1aaf4863-a97b-455a-b8c3-16225f7e5b2e)

### Actual behaviour

Notifications appear in wildly weird windows in the center of the screen.
![1](https://github.com/telegramdesktop/tdesktop/assets/12103655/d8c2d0b0-a0eb-4f99-a724-b2b5dae93215)

### Operating system

Ubuntu 20.04, Unuty DE 7.5.1

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
> Other (unofficial) source

Which source? Can you reproduce with official static binary?

**Comment by vkapas** [comment]
Telegram is installed from the http://ppa.launchpad.net/atareao/telegram/ubuntu repository.

I've just tested Telegram binary version 4.16.8 — notifications look exactly the same.
![3](https://github.com/telegramdesktop/tdesktop/assets/12103655/9439d729-4805-4e7c-bbb5-030be8df9137)

**Comment by ilya-fedin** [comment]
Are you sure it's a Telegram regression, not a system one? Can you reproduce if you download and try version 4.15 here from releases?

**Comment by ilya-fedin** [comment]
Indeed, 4.15.3 has migrated to a different glib C++ wrapper so notification code was kind of rewritten. I don't think we can revert to where we were, though, so maybe that's something you have to live with (or update your system to a newer Ubuntu version). You can try to enable GNotification switch in experimental settings, though, which enables notification implementation from glib (rather than tdesktop's implementation over raw dbus).

**Comment by vkapas** [comment]
Thanks for the explanation. Unfortunately, GNotification option does not change anything.

By the way, Ubuntu Unity is [a part of Ubuntu ecosystem](https://ubuntu.com/desktop/flavours) again. And Ubuntu 20.04 release will be supported for at least [one more year](https://ubuntu.com/about/release-cycle).

**Comment by ilya-fedin** [comment]
> By the way, Ubuntu Unity is [a part of Ubuntu ecosystem](https://ubuntu.com/desktop/flavours) again. And Ubuntu 20.04 release will be supported for at least [one more year](https://ubuntu.com/about/release-cycle).

Regardless of its support by Ubuntu, the choice is either between making it good for you or making it good for users of newer distros. I believe the latter is better.

**Comment by ilya-fedin** [comment]
@vkapas can you report this to the Ubuntu Unity team? I can reproduce this even with 22.04 and that's not ok as GNotification will likely become the default long term (where no control of underlying implementation is present). If Unity reacts in such a bad way to the most common notification implementations nowadays then it has no future. I believe the bug is on their side, as tdesktop doing nothing prohibited by the API documentation yet the DE reacts in a bad way to such minor yet allowed change in API usage.

**Comment by ilya-fedin** [comment]
This is fixed for now but this doesn't mean you shouldn't report to Unity: once tdesktop will switch to GNotification and remove the custom implementation, this wouldn't be possible to fix on tdesktop side so it's in your interest to ensure Unity works correctly with GNotification, to be able to use native notifications by the time the switch happens.
