### ISSUE TITLE
[flatpak] allow for client side theming

### ISSUE THREAD

**Issue by carlocastoldi** [telegramdesktop/tdesktop#27827]
### Is your feature request related to a problem?

Up until a few months ago you could just install https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations (or https://github.com/FedoraQt/QAdwaitaDecorations) and have Telegram's window decorations using Adwaita theming.

Now it's no longer possible. I suspect because flatpak Qt themes attach to org.kde.Platform instead of org.freedesktop.Platform. Do you reckon it is still doable?

_No response_

**Comment by ilya-fedin** [comment]
> Up until a few months ago you could just install https://github.com/flathub/org.kde.WaylandDecoration.QAdwaitaDecorations (or https://github.com/FedoraQt/QAdwaitaDecorations) and have Telegram's window decorations using Adwaita theming.

Perhaps something is wrong with your time perception, it's not possible since three years ago: https://github.com/flathub/org.telegram.desktop/commit/b2fb06ce581aac683dccfb59158b1c3181e32c98

> Do you reckon it is still doable?

I don't think you really need it - tdesktop has its own design and titlebar, just don't enable the Qt one in settings.
