### ISSUE TITLE
Animated stickers can overheat the CPU

### ISSUE THREAD

**Issue by grepwood** [telegramdesktop/tdesktop#27837]
### Steps to reproduce

1. Install Telegram 4.16.8 from `rpmfusion-free-updates` on Fedora 39
2. Have the sticker selection on the right hand side
3. Open a conversation and slide the sticker selection such that there's gonna be a lot of animated stickers visible
4. Hover your mouse over to the stickers to force Telegram to play all their animations

### Expected behaviour

Displaying many animated stickers on Telegram should have no dramatic impact on the CPU temperature.

### Actual behaviour

On Ryzen 5700X, the temperature goes up to 96C, then the temperature increase stops and some stickers may experience lag when playing their animation.
On Ryzen 7900, this is a reliable way to crash the system.

### Operating system

Fedora Linux 39 KDE

### Version of Telegram Desktop

4.16.8

### Installation source

Other (unofficial) source

**Comment by ilya-fedin** [comment]
Perhaps this means you have bad cooling? tdesktop draws on CPU so CPU load is expected

**Comment by grepwood** [comment]
@Aokromes it's not completed. You're not helping.
@ilya-fedin this is on NoFan CR-80EH so you can expect the system to idle at 54-63C, this is perfectly normal in such a circumstance. On another system with the same cooler, but one which uses Ryzen 2700 on Gentoo (and thus Telegram Desktop from Portage), this issue does not exist. What codec is used to animate the stickers?

**Comment by ilya-fedin** [comment]
> Maybe, just maybe, the animation of stickers can be offloaded to OpenGL? 

Only if you would write an implementation. No one else has time/motivation for this. But offloading only stickers wouldn't really help as lots of time is likely to be spent in Qt while compositing CPU and GPU driven parts of the UI. Qt copies content of entire window right now when compositing and that's likely why it's worse than your browser. To solve that, one has to rewrite entire tdesktop to QtQuick. I'm doubt anyone would do that, there are already web clients wrapped in Electron which are such modern GPU-drive clients.

**Comment by ilya-fedin** [comment]
>  it's not completed. You're not helping.

It's completed. If you want a GPU-driven client, switch to web clients. No one will rewrite tdesktop.

**Comment by ilya-fedin** [comment]
> Could you tell me please which part of the code does this?

Well, the problem is entire codebase, as it's written in QtWidgets which is CPU-based. All the wdigets in https://github.com/desktop-app/lib_ui and tdesktop itself have to be rewritten from QPainter to OpenGL. The stickers themselves are decoded with https://github.com/Samsung/rlottie and wrapped into QImages with https://github.com/desktop-app/lib_lottie but porting only them to OpenGL is unlikely to provide any improvement as the problem is with compositing the window by Qt rather than decoding the stickers.

> Is this a new behavior in Qt6?

Yeah, since Qt 6.4, when they ported QtWidgets compositing from direct OpenGL to RHI.

> Poor RAM.

Seem to be ok for most of people... And apparently better than poor CPU.
