### ISSUE TITLE
Khmer font too small

### ISSUE THREAD

**Issue by elit69** [telegramdesktop/tdesktop#27917]
### Steps to reproduce

ref https://github.com/telegramdesktop/tdesktop/issues/25839

Chat Settings => Theme settings => Font family => Default or System font

![image](https://github.com/telegramdesktop/tdesktop/assets/4709476/ed955e0d-772f-400b-88f0-887e8142f615)

### Expected behaviour

Size should be the same as English.

### Actual behaviour

Khmer font is small again after I restart PC. Then I found out that Telegram desktop was updated.

### Operating system

window 10

### Version of Telegram Desktop

5.0.1 x64

### Installation source

Microsoft Store

**Comment by ilya-fedin** [comment]
Hm, I don't have Windows 10 but seem to be ok on Windows 11:
![](https://github.com/telegramdesktop/tdesktop/assets/17829319/ef270288-b02e-4b67-a662-077351757d36)

If you can tell which font should be used for Khmer, I can add it to Qt's fallback list with a patch. Otherwise you can select the font you like manually in settings.

**Comment by panpov** [comment]
So I recently reinstalled Windows 11 and I'm having the same issue. I installed the Windows Language Pack for Khmer but it hasn't done anything. I believe the font that should be used for Khmer is Khmer UI, since it's the one that came with the Windows Language Pack.

I've manually changed the font in settings, but that makes the English characters look unpleasant. Is there a way to change only the Khmer font? Many thanks.
