### ISSUE TITLE
Pinned message send notification even when supergroup notification is disabled

### ISSUE THREAD

**Issue by halaei** [telegramdesktop/tdesktop#2791]
### Steps to reproduce
1. Disable notifications for a supergroup.
2. Let the admin of supergroup pins a message with notification.

### Expected behaviour
No notification!

### Actual behaviour
A disturbing notification! 
**Version of Telegram Desktop**: Latest

**Comment by john-preston** [comment]
@halaei It is a feature.. This is a thing controlled by the sender (pinner). If he enables notifications for the pinned message it gets to everyone like the way personal replies and mentions have notifications in the muted groups.

**Comment by halaei** [comment]
Ok then. It sounded bad to me.

**Comment by timschwartz** [comment]
Just want to say I hate this stupid fucking "feature".

When I mute a group I expect it to be muted. I do not like being woken up in the middle of the night because some idiot decided to pin some random useless thing.

**Comment by coolslon** [comment]
It makes all sound options useless if you are in 10-20 big groups, because every hour you get random and useless pinned message notification. Also big groups quite often have many admins, so it takes a lot of time to block everyone. When I mute notifications, it's mean I don't want to hear anything.

If this is a feature, then please add an additional option "Pinned message notifications".

**Comment by valerioegidi** [comment]
I agree that this "feature" is just "bad design". A muted group should be muted.

BUT, since we have to deal with this situation, i quote what @john-preston said in another issue thread like this:
You get the notification because its a notification from the admin that pinned the message. So, you can "simulate a fix" disabling notification from that specific admin that like to flag the "notify all the users" checkbox. Its not the perfect solution since you may still want to get notification from that user, but i'm getting used to it

**Comment by NightMachinary** [comment]
This is terrible design, which only works for people with insane IQs and saintly souls. There is a definite need for “Mute pinned messages” options per group, whose default value is also settable globally.

**Comment by Aokromes** [comment]
this very likely needs to be api side.
