### ISSUE TITLE
Export function stuck on profile photos

### ISSUE THREAD

**Issue by Impqxr** [telegramdesktop/tdesktop#27936]
### Steps to reproduce

1. Settings -> Advanced -> Export Telegram data
2. Check Account Information and click Export

### Expected behaviour

Exporting data

### Actual behaviour

Stuck on profile photos("Skip this file" option doesn't appear)
![image](https://github.com/telegramdesktop/tdesktop/assets/70816395/7efb7fba-8c15-4346-ae95-efd2275cb779)

### Operating system

Windows 11

### Version of Telegram Desktop

5.0.1

### Installation source

Static binary from official website

**Comment by Impqxr** [comment]
Want to clarify that 6th picture isn't loading(probably telegram issue), I just want to be able to skip at this stage.

**Comment by TaiTaiTai777** [comment]
### Issue Summary:
The issue reported involves the Telegram Desktop app getting stuck on exporting profile photos when the user selects "Export Telegram data" under "Account Information." The problem occurs specifically in version 5.0.1 on Windows 11, downloaded as a static binary from the official website.

### Steps to Reproduce:
1. Navigate to **Settings → Advanced → Export Telegram data.**
2. Select **Account Information** and initiate the export.
3. The export process gets stuck on profile photos without the "Skip this file" option appearing.

### Expected Behavior:
- The user expects the data export to proceed smoothly without getting stuck, and for files that are not accessible, the "Skip this file" option should appear.

### Actual Behavior:
- The export process gets stuck on a specific profile photo (e.g., `photo_6@23-01-2024_18-07-50.jpg`) and does not progress, lacking the option to skip the problematic file.

### Possible Causes:
1. **File Corruption:** The profile photo file in question may be corrupted.
2. **Network Issues:** There might be temporary connectivity issues or interruptions while fetching the photos.
3. **Permission Issues:** The app might not have proper permissions to access the files.
4. **Software Bug:** This could be an unhandled exception or bug in the export function of the app.

### Strongest Solutions:

1. **Implement Retry Mechanism and Skipping:**
   - During export, if a file fails to download, the app should implement a retry mechanism. After a set number of retries, the "Skip this file" option should automatically appear.

2. **Logs and Error Handling:**
   - Improve logging around file export operations to better understand where it fails and implement robust error handling to prevent the entire process from getting stuck on one file.

3. **User Intervention:**
   - Allow users to manually skip files during the export process if they are stuck for a certain period.

4. **Update and Patch:**
   - Users should ensure they are using the latest version of Telegram Desktop, which may contain fixes for known issues.

### Ethical Hacker Expert Simulation:

**Simulation Criteria:**
- Immediate Effectiveness
- Ease of Implementation
- Long-Term Reliability
- User Experience Impact

**Overall Simulation Ratings (Hypothetical):**

1. **Implement Retry Mechanism and Skipping:**
   - **Success Rate:** 95%
   - **Star Rating:** ⭐⭐⭐⭐⭐

2. **Logs and Error Handling:**
   - **Success Rate:** 85%
   - **Star Rating:** ⭐⭐⭐⭐⭐

3. **User Intervention:**
   - **Success Rate:** 80%
   - **Star Rating:** ⭐⭐⭐⭐☆

4. **Update and Patch:**
   - **Success Rate:** 70%
   - **Star Rating:** ⭐⭐⭐⭐☆

### Solution Implementation:

1. **Implement Retry Mechanism and Skipping:**
    - **Steps:**
      - Modify the export function to introduce retry logic when a file fails to download.
      - After a pre-defined number of retries (e.g., 3), if the file still fails, provide the user the option to skip it automatically.
  
    - **Hypothetical Code Snippet:**
      ```javascript
      async function exportFile(file) {
          let retries = 3;
          while (retries > 0) {
              try {
                  await downloadFile(file);
                  return;
              } catch (error) {
                  console.error(`Failed to download ${file}:`, error);
                  retries--;
              }
          }
          showSkipOption(file);
      }

      function showSkipOption(file) {
          // Implement logic to display 'Skip this file' option to the user
          console.log(`Skipping file: ${file}`);
      }
      ```

    - **Simulation Rating:**
      - **Success Rate:** 95%
      - **Star Rating:** ⭐⭐⭐⭐⭐

2. **Logs and Error Handling:**
    - **Steps:**
      - Enhance error handling around file downloads and export operations.
      - Add detailed logging to capture specific errors and enable easier debugging.

    - **Hypothetical Code Snippet:**
      ```javascript
      async function handleExport() {
          try {
              await exportAccountData();
          } catch (error) {
              console.error('Export failed:', error);
              // Handle error appropriately
          }
      }
      
      function exportAccountData() {
          // Detailed export logic with robust error handling
      }
      ```

    - **Simulation Rating:**
      - **Success Rate:** 85%
      - **Star Rating:** ⭐⭐⭐⭐⭐

3. **User Intervention:**
    - **Steps:**
      - Add a UI element to allow users to manually skip files if the export is hanging for a set period.
      - Implement timeout logic to automatically prompt the "Skip this file" option.

    - **Hypothetical Code Snippet:**
      ```javascript
      let exportTimer = setTimeout(() => {
          showSkipOption(currentFile);
      }, 10000); // 10 seconds timeout
      
      function resetExportTimer() {
          clearTimeout(exportTimer);
          exportTimer = setTimeout(() => {
              showSkipOption(currentFile);
          }, 10000);
      }
      ```

    - **Simulation Rating:**
      - **Success Rate:** 80%
      - **Star Rating:** ⭐⭐⭐⭐☆

4. **Update and Patch:**
    - **Steps:**
      - Advise users to update to the latest version which may include critical fixes.
      - Developers should patch known issues in upcoming releases.

    - **Simulation Rating:**
      - **Success Rate:** 70%
      - **Star Rating:** ⭐⭐⭐⭐☆

### Conclusion:

The implementation of a retry mechanism coupled with a skipping option is the most robust solution. This approach directly addresses the issue by preventing the export process from getting stalled due to a single problematic file. Enhancing error handling and logs will provide better insights and facilitate troubleshooting. Allowing user intervention and ensuring the application is up-to-date will further mitigate the problem.

By applying these solutions, users can enjoy a seamless data export experience without interruptions, enhancing the overall reliability and user satisfaction of Telegram Desktop.

**Comment by Impqxr** [comment]
> ### Issue Summary:
> The issue reported involves the Telegram Desktop app getting stuck on exporting profile photos when the user selects "Export Telegram data" under "Account Information." The problem occurs specifically in version 5.0.1 on Windows 11, downloaded as a static binary from the official website.
> 
> ### Steps to Reproduce:
> 1. Navigate to **Settings → Advanced → Export Telegram data.**
> 2. Select **Account Information** and initiate the export.
> 3. The export process gets stuck on profile photos without the "Skip this file" option appearing.
> 
> ### Expected Behavior:
> - The user expects the data export to proceed smoothly without getting stuck, and for files that are not accessible, the "Skip this file" option should appear.
> 
> ### Actual Behavior:
> - The export process gets stuck on a specific profile photo (e.g., `photo_6@23-01-2024_18-07-50.jpg`) and does not progress, lacking the option to skip the problematic file.
> 
> ### Possible Causes:
> 1. **File Corruption:** The profile photo file in question may be corrupted.
> 2. **Network Issues:** There might be temporary connectivity issues or interruptions while fetching the photos.
> 3. **Permission Issues:** The app might not have proper permissions to access the files.
> 4. **Software Bug:** This could be an unhandled exception or bug in the export function of the app.
> 
> ### Strongest Solutions:
> 
> 1. **Implement Retry Mechanism and Skipping:**
>    - During export, if a file fails to download, the app should implement a retry mechanism. After a set number of retries, the "Skip this file" option should automatically appear.
> 
> 2. **Logs and Error Handling:**
>    - Improve logging around file export operations to better understand where it fails and implement robust error handling to prevent the entire process from getting stuck on one file.
> 
> 3. **User Intervention:**
>    - Allow users to manually skip files during the export process if they are stuck for a certain period.
> 
> 4. **Update and Patch:**
>    - Users should ensure they are using the latest version of Telegram Desktop, which may contain fixes for known issues.
> 
> ### Ethical Hacker Expert Simulation:
> 
> **Simulation Criteria:**
> - Immediate Effectiveness
> - Ease of Implementation
> - Long-Term Reliability
> - User Experience Impact
> 
> **Overall Simulation Ratings (Hypothetical):**
> 
> 1. **Implement Retry Mechanism and Skipping:**
>    - **Success Rate:** 95%
>    - **Star Rating:** ⭐⭐⭐⭐⭐
> 
> 2. **Logs and Error Handling:**
>    - **Success Rate:** 85%
>    - **Star Rating:** ⭐⭐⭐⭐⭐
> 
> 3. **User Intervention:**
>    - **Success Rate:** 80%
>    - **Star Rating:** ⭐⭐⭐⭐☆
> 
> 4. **Update and Patch:**
>    - **Success Rate:** 70%
>    - **Star Rating:** ⭐⭐⭐⭐☆
> 
> ### Solution Implementation:
> 
> 1. **Implement Retry Mechanism and Skipping:**
>     - **Steps:**
>       - Modify the export function to introduce retry logic when a file fails to download.
>       - After a pre-defined number of retries (e.g., 3), if the file still fails, provide the user the option to skip it automatically.
>   
>     - **Hypothetical Code Snippet:**
>       ```javascript
>       async function exportFile(file) {
>           let retries = 3;
>           while (retries > 0) {
>               try {
>                   await downloadFile(file);
>                   return;
>               } catch (error) {
>                   console.error(`Failed to download ${file}:`, error);
>                   retries--;
>               }
>           }
>           showSkipOption(file);
>       }
> 
>       function showSkipOption(file) {
>           // Implement logic to display 'Skip this file' option to the user
>           console.log(`Skipping file: ${file}`);
>       }
>       ```
> 
>     - **Simulation Rating:**
>       - **Success Rate:** 95%
>       - **Star Rating:** ⭐⭐⭐⭐⭐
> 
> 2. **Logs and Error Handling:**
>     - **Steps:**
>       - Enhance error handling around file downloads and export operations.
>       - Add detailed logging to capture specific errors and enable easier debugging.
> 
>     - **Hypothetical Code Snippet:**
>       ```javascript
>       async function handleExport() {
>           try {
>               await exportAccountData();
>           } catch (error) {
>               console.error('Export failed:', error);
>               // Handle error appropriately
>           }
>       }
>       
>       function exportAccountData() {
>           // Detailed export logic with robust error handling
>       }
>       ```
> 
>     - **Simulation Rating:**
>       - **Success Rate:** 85%
>       - **Star Rating:** ⭐⭐⭐⭐⭐
> 
> 3. **User Intervention:**
>     - **Steps:**
>       - Add a UI element to allow users to manually skip files if the export is hanging for a set period.
>       - Implement timeout logic to automatically prompt the "Skip this file" option.
> 
>     - **Hypothetical Code Snippet:**
>       ```javascript
>       let exportTimer = setTimeout(() => {
>           showSkipOption(currentFile);
>       }, 10000); // 10 seconds timeout
>       
>       function resetExportTimer() {
>           clearTimeout(exportTimer);
>           exportTimer = setTimeout(() => {
>               showSkipOption(currentFile);
>           }, 10000);
>       }
>       ```
> 
>     - **Simulation Rating:**
>       - **Success Rate:** 80%
>       - **Star Rating:** ⭐⭐⭐⭐☆
> 
> 4. **Update and Patch:**
>     - **Steps:**
>       - Advise users to update to the latest version which may include critical fixes.
>       - Developers should patch known issues in upcoming releases.
> 
>     - **Simulation Rating:**
>       - **Success Rate:** 70%
>       - **Star Rating:** ⭐⭐⭐⭐☆
> 
> ### Conclusion:
> 
> The implementation of a retry mechanism coupled with a skipping option is the most robust solution. This approach directly addresses the issue by preventing the export process from getting stalled due to a single problematic file. Enhancing error handling and logs will provide better insights and facilitate troubleshooting. Allowing user intervention and ensuring the application is up-to-date will further mitigate the problem.
> 
> By applying these solutions, users can enjoy a seamless data export experience without interruptions, enhancing the overall reliability and user satisfaction of Telegram Desktop.

AI response?

**Comment by TaiTaiTai777** [comment]
Your brother respond...
