### ISSUE TITLE
Option to switch back from that new "material design".

### ISSUE THREAD

**Issue by Skytale** [telegramdesktop/tdesktop#2795]
### Steps to reproduce
1. Install new alpha
2. 
3. 

### Expected behaviour
Old good blue titlebar with LARGE close button.

### Actual behaviour
New "material" design is a UI degradation.
You guys are forcing every desktop user to stare into bright white panel and use these microscopic tiny icons in the right top corner to close TD window _every time_, multiple times a day.

### Configuration
Win10

**Version of Telegram Desktop:**
Last one, from Jan10.
Can you also add a version number  to the "setting rollout" at the left side, so users actually could see some USEFUL information, instead of pretty blue square, the only designation of which is seems to "take space"?

**Comment by auchri** [comment]
Duplicate #2752

**Comment by andreymal** [comment]
@auchri you're ignored my question. Can you show us some poll, in which the majority have chosen the new design?

Maybe @john-preston too

**Comment by auchri** [comment]
I've got other thinks to do as discussing with you about things that are not likely to change in the near future

**Comment by andreymal** [comment]
@auchri Now we know that the developers don't care about the views of users. But you should know that it is irresponsible.

**Comment by Zero3** [comment]
@auchri @john-preston I'm sorry to see the rude approach by @andreymal on this issue.

I'm saddened to see that you closed this issue and the #2752 one though. It appears like there is a significant number of people that dislike the new design and have some quite valid concerns about it. I think it would be great if we could have a constructive discussion about it, and help improve on the issues with the new design. In the end, I think we all just want the best Telegram Desktop possible :+1:.

Like some of the other contributors, I also feel that the new design is a step back both visually and usability-wise compared to the design we used to have. I realize that design is a quite subjective matter, so perhaps we could focus on the few core issues mentioned in #2752 and find a compromise that most would feel happy about? :).

Either way, thanks for your work on Telegram Desktop. I use it every day!

**Comment by john-preston** [comment]
@Zero3 Well, the only real issue there is the title bar size. Small letters is a strange report, because nothing was changed regarding the font size. The colors can be customized by themes now.

Title bar size could be an issue, but I think it is not that bad, macOS had it not large for years. Perhaps there will be a way to use OS-specific window title / resize areas in the future, starting from Windows 10 for example.

**Comment by AlexMedia** [comment]
@john-preston I'm sorry, but there are more issues than the size of the title bar. The recent changes to the application's user interface now make Telegram Desktop look out of place on my platform (Windows 10), which is something which can't be fixed with some colours alone. 

See it like this: you have bought a new house and you have just finished decorating your living room exactly to your liking. You opted to go for a modern scandinavian look, so you figured out a matching colour scheme, got yourself a nice carpet, some modern furniture that combined nicely, you bought a modern flatscreen tv, and so on.

![image](https://cloud.githubusercontent.com/assets/948700/22129329/929f6cf4-dea5-11e6-8a02-5e1ea2f1abd3.png)

A few weeks after you've moved into your new place your birthday comes around, a family member comes to visit and brings along a gift. They give you this beautiful table:

![image](https://cloud.githubusercontent.com/assets/948700/22129269/376f980e-dea5-11e6-94c8-4c54405b7823.png)

As your family member suspected that the colour "black" might not be to your liking they also give you some sanding paper and a few paint tubes. As it's a dearly beloved family member, you have no choice but to accept the gift and give it a place in your home.

Initially, you try to place it next to the window, but it doesn't fit there. It's too tall to fit underneath the tv.  You end up placing it besides the sofa, but it's not really useful there either. It's too thin to reach when you're sitting on the sofa, and it looks odd when you compare it to the table standing on the other side. In the end, you're forced to look at something that you didn't ask for, for which you have no practical use, and that you can't get rid of without upsetting someone. 

This is (a slightly overdramatised version of) the consequence of the recent change to Telegram Desktop. Hence, I would like to see an option added to completely disable theming and drawing of window chrome. Let the OS handle it, please!

**Comment by john-preston** [comment]
@AlexMedia But your request has nothing to do with "switching back from that new material design" (apart from the size of the title bar), because the previous version also was custom, had no title, was not respecting your color theme and had underscore minimize control icon. At least now with themes you can have it close to your color style, before you couldn't. So I think this issue is not the right place %)

**Comment by AlexMedia** [comment]
You are correct, the previous version of Telegram Desktop also rendered its own window chrome. And it always bothered me, but it was more tolerable than it has become since the recent change. "Back then", some more effort was made to have the application at least blend in with its surroundings (title bar size, button spacing, look of the icons) and I could see some justification for having the custom UI because of how the space on the left hand side was used for application links.

With the recent update, the area is no longer used for anything useful at all so I would much prefer to see the look of that area reverted to the default OS look and feel. I don't care about themes, I care about consistency in the look of my OS.

**Comment by Zero3** [comment]
@john-preston Thanks for getting back!

I agree that the title bar is the most prominent issue with the new design. Here is a quick example from my Windows 7 desktop (with 125% DPI scaling in Windows):

![image](https://cloud.githubusercontent.com/assets/82504/22184437/c2a014f2-e0d1-11e6-958d-05d160c0d8e7.png)

I personally also find the new buttons to be too small and easy to miss, besides their lack of visual separation. I'm annoyed by them on a daily basis while using Telegram Desktop, and I never had an issue with the old ones.

Anyway, I noticed that there is now a popular issue about this at https://github.com/telegramdesktop/tdesktop/issues/2818, which has not been closed like the other issues. So I guess we can move this discussion there instead :).

**Comment by smaragdus** [comment]
The new material design, the hamburger menu and the horrendous title bar are too much for me. I can see that the developers will not listen to the users' request for an option to switch back to the old design so I have a simple workaround- dumping Telegram for good in favour of LINE/Tox clients.
