### ISSUE TITLE
Enchancement: get rid of material

### ISSUE THREAD

**Issue by MightySeal** [telegramdesktop/tdesktop#2805]
would be really nice to have an option to turn of all that material stuff — ripple effects, round avatars, etc. At least with themes.

**Comment by bertmsk** [comment]
Almost each Telegram release is giving me heavy frustration. Material design is good for mobile clients but not desktops. 
I dont see any reasons in design's unification with mobile clients.
And please - don't use #Windows10 design guidlines. It's ugly just by default since Microsoft was never can into UI & UX

**Comment by fluidpanda** [comment]
Anyway Google's interface is really strange step on Windows platform, maybe it's good for example on Chrome books where the whole interface is build around material design paradigm. At least add an option or a command line switch to opt out.

Basic interface in versions prior to 1.0.0 is way more suitable for windows because it looks like normal windows interface, not like an android app strangely appeared in Windows.

**Comment by bertmsk** [comment]
I think it's because of missing a QA department of Telegram at all. Typical use-cases, basic user's behavior, his expirience etc - all is missing or just ignored

**Comment by MasterGroosha** [comment]
Duplicate #2752

**Comment by fluidpanda** [comment]
Wow, nice. Really powerful move, lets close every issue criticising something you doing wrong. Of course design guidelines is written by some dumb folks, who have absolutely no idea about consistency of ui, ux and other useful stuff. Maybe some symbian ui elements in your windows desktop app? Take a try, really.

**Comment by andreymal** [comment]
@auchri closing of all these issues is not a solution. The new design is still very bad.

**Comment by auchri** [comment]
In your opinion maybe. Most of the users like it.

**Comment by MasterGroosha** [comment]
@fluidpanda First of all, that's impossible to make everyone happy.  
Second, according to [Telegram Support Initiative manual](https://core.telegram.org/tsi/feature_philosophy#q-so-who-decides) users _may_ influence decisions, however the devs and Pavel Durov have the last word.

**Comment by andreymal** [comment]
@auchri then you can show us some poll, in which the majority have chosen the new design?

**Comment by john-preston** [comment]
All the world use Google products on desktop. Material guidelines are nice and they're consistent with the largest mobile OS. Google Chrome moves to material, all Google web products move to material (like Docs, Gmail and others), they serve hundreds of millions of users each day on Windows and other desktop platforms.

In our opinion it is the most beautiful, consistent and modern approach to the design in desktop software. As you can see above the request is even not to use Windows 10 guidelines as well, so it looks like there is no other option anyway.

We receive a lot of positive feedback, which supports or point of view.

**Comment by andreymal** [comment]
@john-preston I hate all Material Design, including Chrome and Android, this is my negative feedback :)

**Comment by john-preston** [comment]
Sorry to hear it. But there is no way to please everyone, you know that. We follow the ideas that we think are right and watch on the opinions across the web to see if we understand what we're doing. And in this terms the redesign was clearly a success, we receive a lot of messages supporting it.

So there is nothing we can offer to some users, who dislike it - we can't keep up completely different design approaches within one app and even if we could it would be wrong, there should be a consistent approach to the things we do. If you take into account that Android has absolute majority of market share in all the countries together, rising up to 85% in some of them, you can understand, that the right approach is to be consistent with Android and desktop design that it inspires.

**Comment by andreymal** [comment]
@john-preston  You're lying. There is a way to please everyone — just add design settings. Why do not you want to make this? Many good applications (especially issued in the 2000s) have a lot of settings interface allows you to customize everything to your taste. I especially like Blender, Psi+ and Miranda. I doubt that making such applications in the 2010s it became impossible.

P.S.1. Android also has settings to disable some Material effects.

P.S.2. Android is so popular is because they simply do not have phones with other free OS. Do not confuse cause and effect. I hate Android, but I have to use it, because it has no alternatives (iOS and Windows Phone are non-free; Ubuntu Phone, Sailfish and other Linux-based OS are unavailable for most devices).

**Comment by john-preston** [comment]
@andreymal I'm not :) I said "we can't and even if we could — we won't keep up completely different design approaches within one app", not that it is impossible.

The situation is — I'm building the software as I and the rest of the team sees as the right way to do it. Someone has different approach (like Miranda, never heard of the other two your examples), so if you like it more, you're free to use it instead. Also this app is open source so you're free to build your own customized version of it and use it as well. Also you can find some other guys, who share your opinion and they could build some other version of Telegram Desktop based on this code or on Miranda or whatever.

As you clearly see, there is no way to please everyone — Miranda doesn't please you (or at least me) as the substitute for Telegram Desktop. Ubuntu Phone doesn't please you because it simply doesn't work on your phone.

Anyway, this discussion goes nowhere, so I guess it can be stopped.

**Comment by andreymal** [comment]
"we can't and even if we could — we won't keep up completely different design approaches within one app" — well, make second official app :D

Other unofficial apps like Miranda or fork of official app are bad just because are unofficial :) But apparently this is the only way to continue to use Telegram, if you deliberately broke the official app and not ashamed of it.
