### ISSUE TITLE
Context menu half display

### ISSUE THREAD

**Issue by oodzchen** [telegramdesktop/tdesktop#28113]
### Steps to reproduce

1. Login to the telegram and open a channel or conversation
2. Right click on a message bubble

### Expected behaviour

Show the entire context menu.

### Actual behaviour

Only partial context menu display, and there's layout error.
![Screenshot_20240702_170318](https://github.com/telegramdesktop/tdesktop/assets/9650699/ec0cb656-108c-4d50-82de-fcaa372c950b)

### Operating system

Debian 12 with KDE Plasma

### Version of Telegram Desktop

5.2.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
This means your DE has a bugged implementation of damage tracking with fractional-scale-v1 protocol. I don't think disabling fractional scale support or partial damage support just because old distros have bugs is a good idea so I think you should either switch to a distro with latest Plasma or report the bug to kwin package of your distro bugtracker.
