### ISSUE TITLE
Window size gets smaller and smaller each time you open the app

### ISSUE THREAD

**Issue by MadAnt0** [telegramdesktop/tdesktop#28264]
### Steps to reproduce

1. Minimize the app to tray
2. Open it again
3. After repeating the first two steps for a couple of times, you'll see the window gets smaller each time.

Video of the bug:

[Screencast_20240811_141151.webm](https://github.com/user-attachments/assets/505a6084-8103-4163-b429-6fe4614367ae)

### Expected behaviour

Window size should not change upon opening, closing the app.

### Actual behaviour

Window size changes by opening the app via system tray.

### Operating system

Fedora Linux 40 (KDE Plasma), Wayland

### Version of Telegram Desktop

5.3.2

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
Can't reproduce

**Comment by SeedPuller** [comment]
> Here's what I see: https://github.com/user-attachments/assets/70dd52f5-fe7a-4ddd-be0f-2bf340633b29

Are you using a different monitor? I just check it again and it only happens on my second monitor.

My monitor specs:
1. Built-in Screen: 1920x1080, scaled to 125%, 60Hz
2. Secondary Screen: 2560x1440, no scaling, 144Hz

Please let me know if you think any other information might help.

Thanks.

**Comment by ilya-fedin** [comment]
I have only a built-in laptop display

**Comment by ilya-fedin** [comment]
> I just check it again and it only happens on my second monitor.

This sentence confuses me. As far as I know, there's no way application can restore the position on Wayland and the compositor always opens the window in the center of the primary screen. So it just couldn't happen.

**Comment by SeedPuller** [comment]
Sorry my message was unclear.
By "secondary screen" I meant "external screen".

So basically what happens here is that whenever my primary screen is set to my external screen, the bug I described above happens. The bug doesn't happen when my built-in screen is set to be the primary screen.

**Comment by ilya-fedin** [comment]
What if you rearrange the screens? Can you make it so that it gets reproducible on the built-in one (even if it would enlarge rather than shrinking)?

**Comment by SeedPuller** [comment]
I did rearrange and was able to reproduce it on both monitors (enlarging rather than shrinking).

I realized it has something to do with the scaling. As I said before, the builtin monitor was scaled to 125% and external monitor was 100%.

I realized when I change the scaling factor for builtin monitor to 100%, the problem doesn't occur anymore. When I scale up the external monitor MORE THAN the builtin monitor (i.e. builtin monitor 100%, external monitor 120%), window enlarges.

I was able to reproduce the same behavior on the builtin monitor but with different scaling numbers: builtin monitor 70% and external monitor 100%. (Wasn't able to reproduce it there with builtin scaled to 100% and external scaled to 120%).

So from what I see, it seems that if the scaling factor of external monitor is less than builtin monitor, window shrinks and if the scaling factor of external monitor is more than builtin monitor, window enlarges.

Let me know if you need me to test other things.

**Comment by ilya-fedin** [comment]
That's not what I asked. I asked you to change the effect by rearranging (changing the monitor order), not by changing monitor settings.

The problem is I still can't reproduce. I tried to create a virtual monitor but still no enlarging or shrinking despite I have different scaling on it. Either the problem needs some specific monitor arrangement or I don't know.
