### ISSUE TITLE
Chat layout

### ISSUE THREAD

**Issue by shikhov** [telegramdesktop/tdesktop#2836]
New material design is not bad, but this small detail... It makes me cry(

![2017-01-13_160146](https://cloud.githubusercontent.com/assets/9966764/21928256/9184c23c-d9ab-11e6-8874-e0c31ed86e79.png)

**Comment by bertmsk** [comment]
Avatars at the bottom? Sorry but "a lot of positive feedback" makes impossible to fix it.

**Comment by john-preston** [comment]
@bertmsk This is consistent with both iOS and Android apps.

**Comment by shikhov** [comment]
> This is consistent with both iOS and Android apps.
Yes, it mutiplies sadness by 3 :(

**Comment by andreymal** [comment]
@john-preston and this is very bad. This is one of the reasons why I hate the new design.

**Comment by luckydonald** [comment]
@john-preston, no, that's not true.
It is **not** consistent with **iOS** (couldn't check Android):
iOS has the profile picture at the top, because it adds the profile picture at **every message**.
And the native **Mac OS** app has it **on top** too.

## Prove
#### Mac OS
![image](https://cloud.githubusercontent.com/assets/2737108/21956759/1389fffe-da88-11e6-8053-7b2d3dc30859.png)

**Comment by stek29** [comment]
@luckydonald  it's consistent with Android.
