### ISSUE TITLE
Request on some improvements for v.1.0 message style

### ISSUE THREAD

**Issue by srazi** [telegramdesktop/tdesktop#2844]
The part in red circle seems ugly for messages that have inline keyboard:

![1](https://cloud.githubusercontent.com/assets/1328454/21938132/41d71f40-d9cf-11e6-80f2-2b5e3fc664fb.png)

Indeed I suggest modifying it like the following image:

![2](https://cloud.githubusercontent.com/assets/1328454/21938138/49c6dc2c-d9cf-11e6-943b-7f1122de9104.jpg)

**Comment by john-preston** [comment]
Perhaps just the tail should be removed. Because if you stop rounding those corners, you'll have to stop rounding all the others as well, except the bottom left and bottom right of the lowest button row.

**Comment by Lazek** [comment]
This element used in official client for iOS, changes not need (may be?)

**Comment by srazi** [comment]
@Lazek I think other official clients also should consider this issue and at least remove that tail or move it to the lowest button row.

**Comment by fluidpanda** [comment]
I really like that this tail appears in version 1.0, because now chats are complete. You could surely see the end of your multi level text, for example: message one, message two, and last message. And you've this funny tail.

@srazi you said it should be moved to the lowest button row, but now it in the lowest message you've send or received. I think this is correct behavior.

**Comment by john-preston** [comment]
@fluidpanda It's just not needed for the messages with the bot inline keyboard buttons. It's not that frequent anyway.

**Comment by fluidpanda** [comment]
@john-preston I see, so will you remove that tail only for these rare cases of inline keyboard buttons?

**Comment by john-preston** [comment]
@fluidpanda Yes.

**Comment by srazi** [comment]
It has been fixed in recent versions.
