### ISSUE TITLE
Why there's not a beta channel for Tdesktop?

### ISSUE THREAD

**Issue by CarlosLopezES** [telegramdesktop/tdesktop#28546]
### Is your feature request related to a problem?

On the last few weeks, we have faced some obvious issues on some updates, like the empty spaces on the chat boxes or the media preview on app launch on Windows. Those are not rare bugs, but obvious bugs for everyone.

### Describe the solution you'd like

I think should be, maybe, a beta channel for those who wants always the very last update, and one stable channel with the latest Telegram features (like the Android APK from official website), but give us some stability.

Thanks a lot.

### Describe alternatives you've considered

NA

**Comment by Aokromes** [comment]
there is, simply enable beta.

**Comment by CarlosLopezES** [comment]
> there is, simply enable beta on settings.

I appreciate the response, but that was not the intention of the post.

The idea is that the stable channel should be stable, and with daily updates and multiple bugs, it looks more like the beta channel than stable.

Thanks

**Comment by Aokromes** [comment]
you asked why there is no, but there is.
no individual can test every telegram desktop feature alone.
if multitrillon companies like apple and microsoft pushes bugs to non-beta channels, you must live with the fact everyone else can have same issues.

**Comment by CarlosLopezES** [comment]
Of course, I don't mean to, it's normal to have bugs in the software. And of course, all the effort that is put into the application is welcome.

My idea is that, perhaps, the stable channel is too ‘beta’ at the moment, and that maybe it is not necessary to update it several times a week. That would reduce the number of bugs that the end user receives.

Of course it's just an opinion :)

**Comment by Aokromes** [comment]
also, you say about separate channels for beta, android and ios uses totally different places, yet some bugs enters production.

**Comment by john-preston** [comment]
@CarlosLopezES some of those were intended as bugfixes actually in an already released version. But you're right that beta testing could be done better.

The problem is that this project is mono-branch really. And the versions sequence is always linear, both beta and stable version. It works for the simplest thing of "new feature, new feature, beta version, beta version, stable version, bug fix stable version, bug fix stable version, new feature, new feature, etc", but once "new feature, bug fix, new feature" get to the code in arbitrary code some features end up in a "bug fix stable version" that were not really well-tested.

"Ship fast break things" should be tweaked down a bit.
