### ISSUE TITLE
JXL encoding support on client side, disable image compression for personal chat

### ISSUE THREAD

**Issue by kupitmanzv** [telegramdesktop/tdesktop#28684]
### Is your feature request related to a problem?

partially. Telegram is currently inconvenient for exchanging images and videos, especially from mobile devices.

### Describe the solution you'd like

Client-Server-Client side JXL. Client-1 encode, Server transfer to, Client-2 decode+encode to png or save in .jxl
By default send uncompressed or lossless compressed images in personal chats, add traffic saving mode for force compression.
Ideally complete replacement of jpg with jxl for lossless compression, or avif for force traffic saving.

### Describe alternatives you've considered

don't see alternatives

### Additional context

1. Regarding the first, since Telegram initially added the JXL decoder, and on the desktop it even works without additional settings, based on this you can add an encoder in lossless mode on the client side.
In addition to optimizing the traffic of TG servers, you can add a setting for saving in .jxl by a second client, which will give an impetus to support the format.

2. Remove image compression in personal chats/notes, this only spoils the images without much savings (most of the traffic comes from channels, or am I wrong?), at the same time, expand lossless images to full size (as is done with compressed ones), and add they have a postscript "lossless" or something like that in the upper corners. This is as funny as possible when a greedy discord with subscriptions for $10, and with file size restrictions, does not compress images/videos, but telegrams do. 

Thanks.

**Comment by kupitmanzv** [comment]
Why closed? All of this can be add on client side -_-

**Comment by kupitmanzv** [comment]
Only CLIENT-1 preprocess image to jxl (NOT A SERVER), ONLY CLIENT-2 download and convert file to png or view on jxl on client side, i don't see when need to use API. What about disable lossy for personal? What's the reason for closing theme, any work there was no work done, no normal responses

**Comment by ilya-fedin** [comment]
> Why closed?

Please re-read:

> It's not possible, the Photo message type accepts only jpegs. Support has to be added on server first



> All of this can be add on client side -_-

You can't change the API client side.

**Comment by kupitmanzv** [comment]
You can't add preprocess? or change to lossless by default? What wrong

**Comment by kupitmanzv** [comment]
1) I mean add lossless by default (without choice, add choice "internet saving" like option in settings) and expand it to full size, there wasn't even an answer to that.
2) I mean compress jpg/png to lossless jxl when share (choice to use JXL in settings), in a future add to API for using JXL anywhere by default, but now only for testing add on client. That not about lossy jpeg, that not about API for now.
I hope we understand each other, please open issue

**Comment by john-preston** [comment]
The only thing that can be done in the app is (and I think this is what you are talking about?):

- when sending .jpg/.png files (like files, documents - not like photos) allow to auto-recompress them in lossless .jxl and send the result instead of the original file.

This can be done, but there is no such plan here right now. Forks can add such option, it's not very hard.

But it's hard to integrate such thing in an easy-to-understand manner, because there is already a "compress" checkbox for the case when you send .png-s, and introducing one more, different "compress" check will confuse everyone.

Compressing sent image files (that are not compressed to .jpg for "photo"-sending in API terms) by default to jxl won't be a good idea either because originally (and in all Telegram apps across the ecosystem) sending something as a "document" (or as a "file") considered "sending 'as is', without messing up the file", it's used to send exactly the bytes you have to transfer the exact file to the recipient. So auto-recompressing will confuse users because they're used to Telegram working the way it does.

For example, I use .png format for icons inside TDesktop itself. So I chat with my designer and he sends me icons for the next feature I implement, right inside our chat, as files. And I save them to disk and use them. If TDesktop starts auto-recompressing the sent .png-s to jxl - I won't be able to use them straight away, I'll need to recompress all of them back to .png on my end, which would be bad.

You can say that I should use .jxl for the icons - but this is just an example of how many power users can be really unhappy with such change to defaults.

**Comment by kupitmanzv** [comment]
You understood correctly, I meant to add to this option (compatibility: save/display in png/jpg, and efficiency: in jxl), mostly the problem arises in the display (on android, for example, you need to open the gallery, although telegram and supports the file, but the gallery does not), you can background transcode to a compatible format. But this is good, it can be left for later and as you say used in forks.

The second thing I am interested in is the normal display of images sent without compression, in the same open form as with compression, and in the best case to remove compression for private messages at all

**Comment by ilya-fedin** [comment]
> The second thing I am interested in is the normal display of images sent without compression, in the same open form as with compression, and in the best case to remove compression for private messages at all

I'm very doubt this is something client-side dev could decide

**Comment by kupitmanzv** [comment]
So about the second one, can't be added a setting to open images sent as a document in full size?
