### ISSUE TITLE
Allow narrow main window with visible narrow chats list

### ISSUE THREAD

**Issue by S-ed** [telegramdesktop/tdesktop#2893]
### Expected behaviour
When shrinking down main window do not hide list with minified chats.

### Actual behaviour
When Chats list minified main window still has same min width limit until chats list will be hidden.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.0.2

**Comment by iklimchuk** [comment]
+1! just asked the same in twitter

**Comment by john-preston** [comment]
@S-ed Unfortunately I cannot allow the minimum size of the window be less than minimum size of the expanded chats list + minimum size of the chat history. Because even if you see only profile pictures in the chats list you can press Ctrl+F or choose to Forward some messages and I'll have to show expanded chats list with chats / messages search results together with the currently opened chat.

**Comment by S-ed** [comment]
@john-preston Even with a checkbox in the settings? Like "allow narrow mode".

**Comment by john-preston** [comment]
@S-ed It is not supported. It won't work well anyway. I can make the minimum allowed expanded chats list width less than it is now, but it'll still be significantly larger than just profile pictures column.

**Comment by S-ed** [comment]
Well ok, no need to haste. Maybe someone figure it out how to make it slim and not to ruin current behavior.

**Comment by iklimchuk** [comment]
damn, I already miss this amazing feature (shortcuts) in my favorite "narrow" layout :)
