### ISSUE TITLE
Git submodules

### ISSUE THREAD

**Issue by xvitaly** [telegramdesktop/tdesktop#3107]
Moving third-party libraries to Git submodules is a bad idea, because GitHub don't include them into Git-tag tarballs, so it will cause problems to Linux package maintainers.

**Comment by john-preston** [comment]
I want to move some lightweight dependencies (like header-only libraries) to git submodules instead of manual cloning to Libraries. How can that be less easy for automatic maintaining? You had to clone them by hand before, they weren't included in the tarballs as well -- they were mentioned only in build instructions.
