### ISSUE TITLE
win+space (changing keyboard layout) blocked by telegram

### ISSUE THREAD

**Issue by ekianu** [telegramdesktop/tdesktop#3194]
### Steps to reproduce
win+space (changing keyboard layout)

### Expected behaviour
keyboard layout must be changed

### Actual behaviour
nothing (blocked by telegram)

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
1.0.27
**Used theme**:
default
<details><summary>**Logs**:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Why do you think it is caused by Telegram?

Also, it works completely fine for me.

**Comment by ekianu** [comment]
fixed on 1.0.29 version. thanks

**Comment by jdmpnn** [comment]
When I switch to Telegram and toggle input language with ctrl+space (Windows 10), it acts like ctrl key stucks. I type something and turn my eyes to the monitor and discover, that instead of typing letters, it has issued some custom actions (obviously, like I've pressed Ctrl+<typed letter>). Version 1.1.19. The languages in the system are English and Russian. Can anything be done, or is this still a bug?
