### ISSUE TITLE
Add option to disable calls

### ISSUE THREAD

**Issue by louwers** [telegramdesktop/tdesktop#3594]
Since I do not have a microphone on my computer, I cannot receive calls on it. Yet when someone calls me I get a big overlay on my screen and the ringing sound is rung. I could prevent all my contacts from calling me using the privavy feature, but I still want to be able to receive calls on my phone.

So I'm requesting an option to disable calls.

Unrelated, but [this issue](https://github.com/telegramdesktop/tdesktop/issues/787) can be closed.

**Comment by auchri** [comment]
> Unrelated, but this issue can be closed.

Thanks!
Please use the template next time.

**Comment by louwers** [comment]
If you have a template for feature suggestions I will update the post.

**Comment by Nexion** [comment]
I always receive the incoming call request via TDesktop first and only a few seconds later I hear it on my phone. Since I can't and don't want to answer it from my desktop, it's a little annoying behavior of software. I would be really happy to have an option of TDesktop to ignore the incoming calls.

**Comment by Aokromes** [comment]
on 1.5.10 you can set calls to "nobody"

**Comment by Nexion** [comment]
> on 1.5.10 you can set calls to "nobody"

This will disable calls globally, not only for TDesktop.

**Comment by afliw** [comment]
Please, add this feature. It's really annoying to have the very intrusive popup every time someone calls (I just answer calls on my phone). I would be nice to add the option to set not to receive calls in the desktop app, or at least configure the notification type (no popup, change the sound, volume, etc). Both options would be great.

**Comment by qgates** [comment]
+1. I use tdesktop on a number of machines but like others only want to take calls on my phone, and don't want the other machines disturbed. Especially on macs, where full screen video is completely lost upon incoming call.

A simple 'mute incoming calls' feature in settings would be perfect, possibly with timer options in hours.

**Comment by Nexion** [comment]
> We therefore assume that the user has lost interest

No, I'm still here.

**Comment by galenhuntington** [comment]
I just found this issue.  This is indeed a serious limitation, and it means I have to remember to close the desktop client anytime I don't want to get randomly rung.

Do these feature requests ever get accepted?  I ask because this issue is over 3 years old, and there doesn't seem to be any hint of movement (nor rejection), and it seems a simple enough feature.

**Comment by memetican** [comment]
Yes this is a huge problem for me, I immediately had to uninstall TDesktop, and that means I cannot use Telegram really either, since it makes it useless for work if I cannot use a Keyboard.

Side note, the incoming calls and LOUD ringing happen even when notifications is disabled on TDesktop.

**Comment by Nexion** [comment]
You can also vote for this issue here: https://bugs.telegram.org/c/1085

**Comment by Nexion** [comment]
Finally :)

**Comment by RememberTheAir** [comment]
From version 2.5.7: settings -> advanced -> calls settings -> disable "accept calls from this device"
