### ISSUE TITLE
Add *scriptable* options to the Windows installer to allow system-wide installation

### ISSUE THREAD

**Issue by terrycloth** [telegramdesktop/tdesktop#3618]
Currently, on Windows you can specify an installation location by launching the installer as admin, and choosing a file path in the dialog that pops up. This can't be scripted, however. The [Chocolatey project](https://chocolatey.org/) has volunteers packaging Telegram who would like to support system-wide installs for users that want it, but would need Telegram's Windows installer to add command line options to support this. See dtgm/chocolatey-packages#303

**Comment by sukharichev** [comment]
I approve, it`s very important option. While we still can`t get a *.msi telegram installer for enterprise deployment, we need at least ability to change the installation path.
Today I rad some requests for related features, and saw a complete misunderstanding. I`ll try to explain, sorry for my English.
If my enterprise users ask me to install the Telegram, I must deploy it company-wide, to provide this communication channel for ALL of them. And it`s a madness to run the installer by hands on every of 200 PC`s.
And we can`t allow users to run the installer themselves, in case  of permissions restriction. Windows domain security model to avoid unauthorized access and virus epidemies is pretty simple: a path where user can execute programs is not writable, and the path user can write is not executable. So we apply GPO to disable to run programs anywhere except of "Program Files" & "Windows" folders, where regular users can`t write by default. So we need programs be placed to "Program Files", instead of "User Profile", and all users files (like configs, messaging history, etc) with write permission placed to it`s own profile. If we have program in user profile, we must to do an exception in the policy for its folder, and any virus can write to it and run from it. We can avoid it by signing all of executables with self-signed certificates, but it`s weeks of work to install own CA, apply new policy, sign all apps, re-sign it on every update... Sounds like a hell, right? Please help us to deliver the world-best messenger to in secure and convenient way to our companies. Ideal solution is ms installer package and admx template for centralized management with Group policy, but command-line options for silent installation will be good enough, simple and quick to release. Thank you anyway for your work.

**Comment by john-preston** [comment]
@sukharichev I use InnoSetup, I guess it should have command line mode with silent install. Also if you run the setup with elevated permissions you can choose any destination folder, like Program Files.

**Comment by Aokromes** [comment]
http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

/SILENT, /VERYSILENT

**Comment by tomghub** [comment]
You miss the point, its not the problem to run it unattended, the path cannot be changed if its running unattended. Its not possible to rollout this software by packaging tools because they are not aware of userprofile folders making it impossible to detect if its already installed or not.

**Comment by Aokromes** [comment]
/DIR="x:\dirname"
Overrides the default directory name displayed on the Select Destination Location wizard page. A fully qualified pathname must be specified. May include an "expand:" prefix which instructs Setup to expand any constants in the name. For example: '/DIR=expand:{pf}\My Program'. cannot help you?

**Comment by bluikko** [comment]
MSI package would be great, no need for duct tape and scripts/switches, just MSTs.
