### ISSUE TITLE
Self Destruct Messages

### ISSUE THREAD

**Issue by electricessence** [telegramdesktop/tdesktop#363]
Any idea when this will be in the works?
Great job BTW, would love to help (when time permits).

**Comment by sigod** [comment]
#5

**Comment by telegramdesktop** [comment]
They are supported only in Secret Chats.

Telegram is a mobile messaging app in the first place. Secret chats are hold only on one client device and can't be synced between them and they stay more secure remaining on the mobile. In my opinion different secret chats on different platforms will confuse users.

Desktop version is done to get full use of it's cloud-based infrastructure with instant sync between devices, including sync between mobile and desktop app. So the desktop app is more about work, with groups up to 200 members and documents of any file type up to 1.5 GB, than about secret chats. And that's why secret chats are not in the near plans for tdesktop.

**Comment by sigod** [comment]
> In my opinion different secret chats on different platforms will confuse users.

Why is that? There's already various numbers of secret chats on _different_ devices.

**Comment by vn971** [comment]
If you're looking for Self-Destruct messages themselves, not tied to e.g. secret chats, then this issue might be of interest: https://github.com/telegramdesktop/tdesktop/issues/9780
