### ISSUE TITLE
[Feature request] Send voice messages

### ISSUE THREAD

**Issue by Ephisray** [telegramdesktop/tdesktop#37]
It would really be nice to be able to send voice messages with the Telegram Desktop Client.

**Comment by JosephStrach** [comment]
+1 would love to have this feature.

**Comment by Ephisray** [comment]
Please add this feature :)

**Comment by fbs1997** [comment]
+1 Please add!

**Comment by luxvio** [comment]
Voice messages would be an amazing thing. I haven't read the details in the spec of how the opus-encoded file with voice message should be sent (if it has bitrate limitations, size, lenght of audio and such).       
       
But it would definitely be an awesome feature. Not only as a "record from mic and send", but also the chance to pick your very own opus-encoded, conformant-to-the-specs file as a voice note (maybe the latter option is easier to implement and could be the first thing to give a try, because it's not about recording and encoding, just make some checks on file and send it)

**Comment by Ibrasau** [comment]
Please, add at least checkbox in settings for on/off this feature. Really needed thing.

**Comment by alim4egg** [comment]
I fully support . We need to send voice.

**Comment by halcion** [comment]
agreed, when you have a desktop version of anything with less functionality, it leaves a lot to be desired

**Comment by halcion** [comment]
great work guys, now how about voice messaging for desktop
v 0.8.17
v 0.8.16 stable 20.05.15

v0.8.15 dev 20.05.15

v 0.8.14 dev 19.05.15

v 0.8.13 stable 12.05.15

**Comment by alinasrabadi** [comment]
Please Add This Feature ;)

**Comment by bil-elmoussaoui** [comment]
This has been implemented to the dev version

**Comment by mbnoimi** [comment]
@bil-elmoussaoui Indeed.. I can see the new commit for [Audio Capture](https://github.com/telegramdesktop/tdesktop/commit/0a7c42c59af6de6a437015d6f07e0eef876bc9de)... Voila

**Comment by Katzen-Gott** [comment]
@Ephisray It was added in v0.19.8. Cold you please close the issue? (there is a button below the comment box)

**Comment by sigod** [comment]
> It was added in v0.19.8

Did you mean v0.8.19? It's not released yet.

**Comment by bil-elmoussaoui** [comment]
@sigod it's a dev version :) you can download it if you want to, or keep using the stable version

**Comment by sigod** [comment]
@bil-elmoussaoui Exactly, it's not stable yet.

**Comment by auchri** [comment]
Released with 0.8.20 @Ephisray @sigod

**Comment by brunobsouzac** [comment]
The new update 0.8.21 left the voice message, but it would be more convenient for those using the desktop a shortcut key to tighten and talk instead of using the mouse.

Something like Ctrl + Space (other than a notice in the space where you enter saying that, guiding users)

And finally, radio voice messages with auto play, so we would listen to voice messages in real time as a Voxer / Zello / Radio. The Telegram iOS already have this option but is not released for Android and not WP. To disable an exposed button would look great in the chat.

It would be perfect for Desktop, iOS, Android and WP.

What do you think?

**Comment by auchri** [comment]
If you have any suggestions, feel free to open a new issue
