### ISSUE TITLE
Change emoji style

### ISSUE THREAD

**Issue by dmxt** [telegramdesktop/tdesktop#3726]
### Steps to reproduce
1. Delete poorly designed Apple emoji
2. Add superiorly designed Twitter emoji

### Expected behavior
Display Twitter emoji: http://emojipedia.org/twitter/

### Actual behavior
Displays Apple emoji: http://emojipedia.org/apple

### Configuration
**Operating system:**
Windows 8

**Version of Telegram Desktop:**
1.1.18 (please allow us to copy and paste this from settings modal)

**Used theme**:
Default. There is a theme?

**Comment by MasterGroosha** [comment]
AFAIK using Apple emojis makes user experience consistent across platforms (Android and iOS apps use Apple emojis as well)

Regarding "There is a theme": Telegram Desktop support custom themes since 1.0 version. You can switch to night mode theme in main menu or find some custom themes in this official channel: https://t.me/themes

**Comment by omkarnathsingh** [comment]
Apple emojis look way better than Twitter ones. The feeling of emotion is lacking in twitter ones. It will be better to stick with current ones.

**Comment by auchri** [comment]
> AFAIK using Apple emojis makes user experience consistent across platforms (Android and iOS apps use Apple emojis as well)

Also search for similar issues.

**Comment by dmxt** [comment]
@omkarnathsingh This is a pure opinion of your own.
