### ISSUE TITLE
Implement 'secret chat' to Telegram on Windows platform

### ISSUE THREAD

**Issue by dmxt** [telegramdesktop/tdesktop#3731]
### Expected behaviour
Ability to have private chat on both party, for an example: person A is on Windows 8 and person B is on Android and they both can chat privately without prying eyes from "big guys".

### Actual behaviour
Mobile phones have private chat feature as well native macOS (from what I heard), and possibly UWP. Windows is left out.

### Configuration
**Operating system:**
Windowos 8

**Version of Telegram Desktop:**
Telegram 1.11.18

**Comment by Maxxie** [comment]
It's a duplicate alright, but is there **any** kind of comment you could give us about this issue?

**Comment by stek29** [comment]
They're all given already.

**Comment by Maxxie** [comment]
The only answer i could find was something like 'it's not planned for the near future' and it's from almost 3 years ago... Not much of an answer in the first place, not really relevant anymore

**Comment by roman-voropaev** [comment]
Maybe they can be implemented in some kind of fork if spec is open?

**Comment by YamashitaRen** [comment]
I'd like to add that Linux too is left out.
What's the grand idea for Telegram ? One cross-platform official client missing an essential feature and each OS having its own Telegram client build from scratch in order to support this feature ?

**Comment by dmxt** [comment]
Yeah, seriously, how hard is it to implement this now basic feature on Telegram **on the most popular desktop operating system in the world**? I'm not meaning to leave off Linux but what was your reasoning to ignore the basic support for the most popular desktop OS, but instead implement it on less popular operating system macOS and ignore Linux despite it's in the same category?

**Comment by zeroone2numeral2** [comment]
>but instead implement it on less popular operating system macOS and ignore Linux despite it's in the same category?

MacOS client != Telegram Desktop. Telegram Desktop for MacOS doesn't support secret chats either, the MacOS client uses some OS stuffs to store secret chat messages that won't work on a multi-platform client (Telegram Desktop)

> I think enough time has elapsed by for us to have a new official comment

There have been some statements around this issue tracker. As of now, Telegram Desktop doesn't store anything persistently - messages and chats are loaded from zero when you open the app. Since secret chats are not on the cloud, they would require the ability permanently store the in a secure way, which is something TDesktop doesn't have yet
