### ISSUE TITLE
Wrong Emoji displayed for Pistol

### ISSUE THREAD

**Issue by Null-Senpai** [telegramdesktop/tdesktop#3757]
### Steps to reproduce
1. Type `:gun:` or paste this emoji: `🔫`
2. A squit gun is displayed

### Expected behaviour
A pistol should appear (Unicode character 1F52B). 

### Actual behaviour
A squirt gun appears

### Configuration
**Operating system:** Antergos Linux

**Version of Telegram Desktop:** 1.1.19 Alpha

**Used theme**: Arc

**Comment by Socialdarwinist** [comment]
The squirt gun is how leftists in tech [sometimes](http://emojipedia.org/pistol/) implement the pistol. The same people are responsible that we have no rifle emoji.

**Comment by Null-Senpai** [comment]
Preventing something from coming into the Unicode standard is one thing, but I believe that at the very least Telegram should display things accurately as they have been declared, and not join Apple Inc. on their little political correctness trip.
Random changes Apple forces onto their users have no business affecting other people as far as I am concerned.

**Comment by Socialdarwinist** [comment]
I agree, and this is another argument for #90.
Why the heck do they use [Apple Color Emoji](https://www.reddit.com/r/Telegram/comments/4ej2oe/why_does_telegram_for_android_use_a_copyrighted/) at all? It adds data size and violates copyright significantly for nothing. And now I know at least one definite reason why repositories of OS distributions cannot have Telegram Desktop.

**Comment by Null-Senpai** [comment]
Huh, good point. I never considered the legal rights issue. And yeah, #90 would solve that. But seeing as they locked the issue, I am guessing they are not interested in allowing this. I guess I will attempt to compile my own version without it, although that REALLY should not be necessary.

**Comment by stek29** [comment]
@Null-Senpai someone sends a water gun, and everyone except one guy with tdesktop gets it, and that one guy gets a revolver. Ouch.

**Comment by Socialdarwinist** [comment]
You can’t possibly “send a water gun”, forthy there is no water gun defined in Unicode. The one guy who gets a revolver is right alone. If somebody sends U+1F52B, it’s a revolver, regardless of how it is displayed. If the communication platform does not show it because of its font, the communication platform has failed. If somebody sends U+1F52B to mean “squirt gun” to mean a water gun, he has abused the language, regardless of how the codepoint is shown.
The display of unambiguously specified encodings belongs to the sphere of risk of the recipient, whereas the sender has to check if he uses the byte sequences according to his encoding correctly. If it is practically possible to conclude contracts with emoji, such representations of codepoints distorting their reality are a liability risk. For example if the sender – possibly using a custom client – sends the aforementioned codepoint as follows:
`I order 8 🔫 for 100 $.`
And the receiver who sees a water pistol and accepts this offer – what do you think he will owe, presuming for both variants that the generic naming sufficiently defines the contractual performance? He assumed that he will deliver water pistols, but he will be obliged to serve actual pistols for a ridiculously low price.

**Comment by stek29** [comment]
> For example if the sender – possibly using a **custom client** – sends the aforementioned codepoint as follows

That's the issue. No matter how bad apple emoji are, Telegram had chosen them as their font. And that font should be the same on all official apps. So this issue is not for TDesktop, it's for Telegram platform. And I think this was already discussed in #3281 #3336 #211.

**Comment by Socialdarwinist** [comment]
No, the issue is that the guy using the client which displays U+1F52B as revolver is the one who is right. Even if it is consistently accross official Telegram clients displayed as squirt gun, it is wrong, and better if Telegram does not ship any emoji font at all, because the Apple Color Emoji font is a liability risk and politically slanted. Yes, if there would be a PR for removing it without replacement, I would opt for it. It would also open more room for #90. In the issues linked in the comment before this there is nary a discussion, they just say “I am for changing it”. Here we have the legal and political arguments.

**Comment by stek29** [comment]
Legal and political arguments with less than5% of userbase caring about it. See Telegram feature philosophy.

What I am trying to say is I don't like apple emoji, I don't like the squirt gun, but it doesn't mean that this issue would be accepted before it gets accepted in other clients.

**Comment by Null-Senpai** [comment]
Firstly, while granted I do not know the exact number of users that care about the display of Unicode 1F52B, there are a **bunch** of people caring about fonts in general. 
Secondly, if 'consistency' is really worth more then the correct display of characters while ignoring potential legal issues, then I suggest Telegram as a whole chooses a better font. Or even better, let people override the built-in font.
Oh yeah, also just wanna point out that in addition to displaying the character wrong, [Apple Emoji is also the minority](http://emojipedia.org/pistol/).

**Comment by stek29** [comment]
I doubt apple would let Telegram for iOS use it's on emoji.

**Comment by Socialdarwinist** [comment]
Using proprietary systems as permeated with digital handcuffs as Apple’s has its price. It’s the users culpability if he uses iOS and sees everything mawkish. Apple users want it that way, and it has always been a contradiction that Telegram is even available for such systems, as Telegram is wooing users with the security argument while that makes no sense in proprietary systems where some vendor in the United States has control about your operating system. Using different fonts would illustrate the actual order in the computer world, that is that it would accept the inferiority of proprietary systems. And I think that it would fit the Telegram company policy in the case of the pistol, that is keeping a distance from poliitical forces like those which Apple represents, those that want to make man weaponless and vulnerable against the interference by the state. Using the Apple font betrays what Telegram stands for.

**Comment by Null-Senpai** [comment]
I agree. If someone purchases an iOS device, whatever drawbacks that come with it (such as incorrectly displayed characters) are their personal problems, I do not see why all other platforms have to suffer  just to accommodate for one.
Also, for a messaging application that is aimed at people who want freedom, security and privacy, it is just _a bit weird_ for it to join apple on their politically motivated censorship. Telegram should not be preventing free expression between two persons.
Lastly, while  I don't have an iPhone to check this on, I would be very surprised if applications could not use their own fonts. Discord is also available for iOS, and that also shares the same set of emojis across different platforms. As far as I have seen, the Linux Desktop, Windows Desktop and Android builds at least do, so I am confident that their iOS build does too.

**Comment by auchri** [comment]
@Null-Senpai This is the wrong place to discuss such platform things.

**Comment by stek29** [comment]
Telegram is a multiplatform app. If iOS user has an issue because of Telegram (like sending a water gun and making everyone see revolver) then users won't say "it's your dumb iOS", they'd say "it's this dumb Telegram" and would delete the app.

Anyway, this is getting messy. I completely agree with @auchri. Go annoy Durov on Twitter hoping he listens to you, and if he doesn't -- well:
> If someone uses an proprietary monopolic messaging service, whatever drawbacks that come with it (such as emoji they doesn't like) are their personal problems


Btw, this really made me laugh. Come on, Telegram isn't meant to be FOSS and geeky, use Tox/IRC/Jabber if you want to have control over what you use and want it to be free (tm). TG is ruled by Durov and nobody stops him from doing whatever he wants (shutting down the tomorrow without any way to recover data for example), TG stands for what Durov stands for.
> Using the Apple font betrays what Telegram stands for.

**Comment by Null-Senpai** [comment]
While I really disagree with catering to one platform, that does not matter. I made my case, and yes, if I dislike it I can do whatever, even fork this thing and compile it without said fonts I guess.

One thing I want to note though is that while Telegram is not free as in, IRC/XMPP/whatever free, it certainly does it's best to market itself as a balanced approach between said services and, say, facebook messenger. The fact that there even is a native Linux client and that we have things like "```" for writing in monospace, or even telegraph, makes me think it is also aimed at the 'geeky' crowd. So I really do not think that I am in the wrong for having any expectations. That said, I can, and probably will, annoy Durov at some point since apparently this is not a TG-Desktop specific thing but rather a telegram-wide thing. 
Whoever is able to, feel free to close this issue.
