### ISSUE TITLE
Huge Memory Leak, Flickering Screen and BSOD

### ISSUE THREAD

**Issue by CodeNameT1M** [telegramdesktop/tdesktop#3762]
I have some serious memory leaks in telegram desktop. it escalated to bsod and flickering screens, had to reset my pc. it happens ramdomly, sometimes at boot, sometimes after a few minutes

windows 10, updates installed until 1.august 2017
telegram desktop version 1.11.0 (if i remember correctly)

**Comment by zhovner** [comment]
That's sound strange. Are you sure that telegram caused this problems? 
You can enable debug mode and collect logs.

**Comment by auchri** [comment]
@zhovner Im almost 100% sure that software is not able to produce a bluescreen. Maybe one of your RAM is dying

**Comment by stek29** [comment]
@auchri if it is, than it's a huge problem in Windows :)

**Comment by Aokromes** [comment]
@CodeNameT1M what's your motherboard? it comes with killer network adapter? if no, i suggest you to try to run windows without open telegram and open another instant messaging application (skype, etc)

**Comment by CodeNameT1M** [comment]
Sorry for the late reply. It was a Memory leak problem. But it looks like Telegram tried to "steal" RAM from the reserved RAM of my onboard graphic Card. Got a old 9500TI and it works again.

**Comment by lorien** [comment]
I have same problem. Telegram client seizes lot of RAM: 1Gb, 2Gb, 3Gb, till my Debian OS starts responding slowly due to the lack of free memory. Then OOM killer kills Telegram and I have few days till next crash.
I think lot of memory is wasted to render F**G stickers and GIFs.
Why does not telegram dev team implement the settings that allows to completed disable F**G stickers and GIFs? I do not want to watch cats and penises and whatever I just like to use telegram for *talking*.

**Comment by CodeNameT1M** [comment]
What hardware do you have?

**Comment by Aokromes** [comment]
#1317 for images thing.
