### ISSUE TITLE
[Feature request] add a way to hide messages from certain users in the chats

### ISSUE THREAD

**Issue by thread13** [telegramdesktop/tdesktop#3772]
This is a re-opening of #1025 and #1281 : when it may be arguable whether messages from a blocked user shall be visible in a group chat -- it would be certainly great to have an option to do so : for one thing, this is a great way to stop feeding the trolls ( by simply ignoring them ), and by the same token this would preserve the freedom of speech )

We can call this "extended block", or "block in chats", or whatever. But it is very clear that such a feature would be a very powerful thing.

**Comment by auchri** [comment]
![image](https://user-images.githubusercontent.com/5092164/29062060-81564a58-7c20-11e7-800b-892373114bc8.png)

**Comment by thread13** [comment]
Ok then. Any hints on how to add feature requests for the major telegram apps? This is _still_ a feature to add, you know.

**Comment by stek29** [comment]
Use Twitter and in app support

**Comment by foxmajik** [comment]
@stek29 Your response is unhelpful and belligerent. The person posting this feature request clearly is not having a hard time using the app; and they clearly don't need consumer support.

**Comment by stek29** [comment]
@foxmajik can you suggest any other way to submit server side feature request?

**Comment by 4jacks** [comment]
I really can't believe you morons are having a hard time since August understanding why a feature would be needed to BLOCK someone on a chat program.  

Telegram is garbage without it. There are a million spam bots, and I can't turn them off, becuase you morons think that 'I would be missing something from the conversation.' Please rub two brain cells together.  Reading this thread was more mind blowing then the spam in the channel I just left. Please know I created an account on GitHub for the sole purpose of calling you morons.

**Comment by stek29** [comment]
@john-preston time for new bio

**Comment by BalooUriza** [comment]
I also agree that this is a badly needed feature.

**Comment by Zap4ick** [comment]
That would be great, I was quite surprised when blocked user appeared in my chats... Maybe any workaround?

**Comment by destroy** [comment]
We need a fork guys...
