### ISSUE TITLE
Can't attach file with non-ascii symbols in name with empty LC_ALL

### ISSUE THREAD

**Issue by stek29** [telegramdesktop/tdesktop#3784]
### Steps to reproduce
- Export `LC_ALL=` (empty) or unexport it.

Then:
- Try to attach file with non-ascii symbols in it's name (drag'n'drop or select via paperclip)
- Try to "save file as" with non-ascii symbols in name

### Expected behaviour
Everything works fine

### Actual behaviour
Non-ascii symbols are replaced with question marks when accessing file, but they're shown correctly in error message.

If file at path with those symbols replaced with question marks doesn't exist, then "File is empty" error is shown.
If file/directory with `?`s exists, then it's used instead.

### Configuration
**Operating system:**: Linux with Nemo and pcmanfm were tested.
**TDesktop version**: 1.1.19

**Comment by john-preston** [comment]
@stek29 Perhaps QFile::encodeName works incorrectly without LC_ALL specified?..

**Comment by stek29** [comment]
@john-preston Idk, I don't have Linux system around, it was reported by user and I asked a friend to test it.

**Comment by daskol** [comment]
@stek29 Bug is reproduced with 1.1.15 and 1.1.19 versions on archlinux host.

@john-preston Yeah, Qt is crazy dealing with encodings on linux. I would like to fix this but the issue is not ordinary as well as solution.  Hope, my long comment will be usefull.

I use simple code following bellow to find out what's going on.
```c++
// qt-encoding.cpp

#include <QDebug>
#include <QFile>
#include <QTextCodec>
#include <QLocale>

int main(int argc, char *argv[]) {
    QLocale locale = QLocale::system();
    QTextCodec *codec = QTextCodec::codecForLocale();
    QString str("example-пример.txt");
    QByteArray bytes = QFile::encodeName(str);

    qDebug() << "language: " << QLocale::languageToString(locale.language());
    qDebug() << "name:     " << locale.name();
    qDebug() << "code:     " << codec->name();
    qDebug() << "source:   " << str;
    qDebug() << "target:   " << bytes;
}
```
My default locale is `ru_RU.UTF-8` and additional one is `en_US.UTF-8`. They are defined in `/etc/locale.conf`. Let's try to play with `LC_*` variables.
```bash
$ LC_ALL= ./qt-encoding
language:  "English"
name:      "en_US"
code:      "US-ASCII"
source:    "example-??????.txt"
target:    "example-??????.txt"
```
```bash
$ LC_ALL=ru_RU ./qt-encoding
language:  "English"
name:      "en_US"
code:      "UTF-8"
source:    "example-пример.txt"
target:    "example-\xD0\xBF\xD1\x80\xD0\xB8\xD0\xBC\xD0\xB5\xD1\x80.txt"
```

```bash
$ LC_ALL=ru_RU.UTF-8 ./qt-encoding
language:  "English"
name:      "en_US"
code:      "UTF-8"
source:    "example-пример.txt"
target:    "example-\xD0\xBF\xD1\x80\xD0\xB8\xD0\xBC\xD0\xB5\xD1\x80.txt"
```

```bash
$ LANG=ru_RU.UTF-8 ./qt-encoding
language:  "English"
name:      "en_US"
code:      "US-ASCII"
source:    "example-??????.txt"
target:    "example-??????.txt"
```
```bash
$ LC_CTYPE=ru_RU.UTF-8 ./qt-encoding
language:  "English"
name:      "en_US"
code:      "UTF-8"
source:    "example-пример.txt"
target:    "example-\xD0\xBF\xD1\x80\xD0\xB8\xD0\xBC\xD0\xB5\xD1\x80.txt"
```

According to docs to `QLocale`, `QTextCodec` and `QFile` resulting encoding is tricky to infer. It depends on lib versions, platform as well as linking flags. Note that Qt doc recommends not to us `toUtf8()` for string conversion in spite of frequent usage utf8 encoding. Still, it is wondered why Qt ignores `LANG` but `LC_CTYPE`.

**Comment by Aokromes** [comment]
this bug is still valid on 1.9.8?

**Comment by reckus** [comment]
@Aokromes Yes, it's the same on 1.9.8

**Comment by ilya-fedin** [comment]
> Yes, it's the same on 1.9.8

```
env | grep LANG
env | grep LC_
```

**Comment by Aokromes** [comment]
can you try on 2.1? @daskol

**Comment by Aokromes** [comment]
@daskol

**Comment by daskol** [comment]
@Aokromes It works perfectely on 2.1.11.
