### ISSUE TITLE
[Feature Request] Block/Ignore user across all groups

### ISSUE THREAD

**Issue by Justinzobel** [telegramdesktop/tdesktop#3909]
Please add the ability to block/ignore a user across groups. Blocking them currently only blocks direct messages.

**Comment by thexbasic** [comment]
In my eyes the current behaviour makes sense. If you don't want to read a blocked person's messages at all, you can ask him to be removed from the group, or leave it yourself. Because hiding specified messages in a chat context will probably lead to more confusion than benefit. However I would agree for a feature/setting so that you don't get notified about blocked people's messages & mention's at all (in groups).

**Comment by stek29** [comment]
#552 and you know that.

**Comment by Justinzobel** [comment]
What's the issue in adding the option?
=
