### ISSUE TITLE
Linux client unable to copy text to clipboard

### ISSUE THREAD

**Issue by Torquill** [telegramdesktop/tdesktop#3939]
The Linux Telegram client is able to read and paste text from the clipboard into the client, but cannot place content from the client into the clipboard, by any of several methods.

### Steps to reproduce:
1. Download Telegram x64 client from website
2. Unpack and move files to /usr/share
3. Run Telegram
4. Select text (optional: press Ctrl-C)
5. Open an editor or browser and a) middle-click or b) right-click and select Paste or c) press Ctrl-V

### Expected behaviour:
The text should be copied to the new destination, either using the primary clipboard (middle-click) or the secondary (Ctrl-V).

### Actual behaviour:
The text pasted is whatever was previously in the clipboard, if anything, not the new selection.

### Configuration
**Operating system:**
Debian 9 x64 with XFCE

**Version of Telegram Desktop:**
1.1.23

**Used theme:**
default

<details><summary><b>Logs</b>:</summary>
I have enabled debug mode, but ~/.TelegramDesktop/ does not exist.  There are no log files in /usr/share/Telegram/ either.

</details>

**Comment by dschwoerer** [comment]
Both works fine in `telegram-desktop-1.2.1-1.fc26.x86_64` (Fedora 26) with awesome.

**Comment by ursg** [comment]
I can confirm this problem still exists in v1.2.6 (30.12.17) on debian with ion3.

**Comment by mmartinez** [comment]
The issue is still present in v1.2.12 alpha with XFCE.

**Comment by ursg** [comment]
Digging into this issue a bit: it is fundamentally related to X11's concept of multiple different "selections" being possible at the same time: https://tronche.com/gui/x/icccm/sec-2.html#s-2.6.1
The "primary selection" is what usually gets selected by marking text, and gets pasted with the middle mouse button. The "clipboard selection" is what you get by using Ctrl+C and Ctrl+V.

Telegram Desktop relies on [Qt's QClipboard class](http://doc.qt.io/archives/qt-4.8/qclipboard.html#details) to handle this in a platform independent manner. This puts the selected URL into the "Clipboard" selection, and it can indeed be pasted into a browser by selecting its URL bar and pressing Ctrl+V.

Note that simply marking the URL as a selection using the mouse cursor puts it into the primary selection, and thus allows it to be pasted with a middle click.

In order to get the expected user behaviour on Linux, Telegram would need to call ```QClipboard::setText(text, QClipboard::Selection)```, thus putting it into the primary selection. I'm uncertain whether this would break other platforms' behaviour though.

**Comment by bitemyapp** [comment]
Still having this issue on Ubuntu 18.04 LTS w/ Telegram 1.8.15 downloaded from their website. The Snap version doesn't have this issue, I don't know why.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by Torquill** [comment]
I haven't experienced this problem for a couple of months now.  I don't know what happened, but it appears to be fixed (for me).

**Comment by sczther** [comment]
I still have this issue on Fedora 31 / Gnome 3.34.4 and Telegram Desktop 2.0.1. Sometimes the clipboard selection freezes in an almost sandbox like manner. Telegram has it's own thing in the clipboard and the rest of the system it's. Restarting telegram helps it.

**Comment by canselcik** [comment]
Still happening. It used to not happen back when I was on Arch but it began happening now that I'm on NixOS.

```
error: : cannot open
error: : cannot open
error: : cannot open
Invalid return value 0 for stream protocol
Invalid return value 0 for stream protocol
```
