### ISSUE TITLE
What languages/localization policy does this project has?

### ISSUE THREAD

**Issue by garex** [telegramdesktop/tdesktop#397]
Our PRs on new langs are become dusty. Does it right place to send em? Or only transifiex? Requests there also without answers. Creating forks with builds for each lang is not a good idea.

**Comment by telegramdesktop** [comment]
For the current moment there are only several officially supported languages. Some will be added in the future, the main idea is "better to have english version than a bad translated one". So, there are some restrictions:

 -- there should be a possibility to make a translation grammatically correct, which is not always so. For example, phrases like "A invited B to group" in some languages require knowing the gender of A or B to build a correct phrase. We don't know that information in the app, so we can't make translation to that language.
 -- perfect translation should have grammatically correct number phrases ("1 user", "2 users", etc), for example arabic language requires six phrases for different cases of "count", it is not supported in the program yet, so such translations can't be accepted yet.
 -- translations to languages with rtl writing are not accepted right now, because the program interface does not support rtl layout, and it is a bad translation without it (arabic, hebrew).
 -- there should be one person, who is responsible for the translation, he must have a good understanding of language, check all of phrases to fit in the program, to make it nice and clean. If we start to support a language we can't rollback and stop supporting it, so he must not disappear suddenly, leaving us without a possibility to deploy translated updates. It is not easy to find such a person from volunteers.

So some languages will not be supported at all (those who does not allow grammatically correct translation with the available information), for some languages the program is not yet ready (rtl etc), some just are not added yet, because the coordinator was not found yet.

**Comment by garex** [comment]
Im' ready to support ru_RU. My wife is english lang teacher and I'm a programmer, who can not  just send something to transifiex, but check it locally on freshly compiled program.

For example WhatsUp has russian lang. We take same method of translation of sex-related info like "did somthing" -> "делал(-а) что-то".

For ru_RU I can say it's a good one now. For others, that are in PR they require to just more complete translation and merge few versions into one.
