### ISSUE TITLE
No tray icon on Ubuntu 17.10 if extensions are enabled.

### ISSUE THREAD

**Issue by omkarnathsingh** [telegramdesktop/tdesktop#3995]
In additions to issue [#3968 ](https://github.com/telegramdesktop/tdesktop/issues/3968) .

In Ubuntu 17.10, if Gnome shell extensions are enabled, then Telegram tray icon doesn't show at all. 

Its a Telegram side issue as "Dropbox" tray icon does appear in the same scenario.

Some links: https://extensions.gnome.org/

**Comment by diazbastian** [comment]
@omkarnathsingh You must provide more information to understand your case, as I have no problems currently viewing the Telegram status icon using the [TopIcon Plus](https://extensions.gnome.org/extension/1031/topicons/) or [KStatusNotifierItem](https://extensions.gnome.org/extension/615/appindicator-support/) extension using the Wayland or Xorg session (Gnome 3.26.1)

![telegram-gnome-statusicon](https://user-images.githubusercontent.com/5126124/31690192-5e1a3be2-b368-11e7-9c3e-1b9cb6256716.png)

What extension are you using? Does this occur with other applications or using other extensions?

Remember that Telegram Desktop requires the `libappindicator` library to display the status icon in Gnome and additionally _-according to the extension you are using-_ additional dependencies are required for additional APIs to work due to the [new Gnome paradigm about status icon](https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/).

**Comment by omkarnathsingh** [comment]
@diazbastian TopPlusIcon Plus does install on Ubuntu 17.10. Its not a native Gnome, make sure of it. 
![screenshot from 2017-10-19 10-20-11](https://user-images.githubusercontent.com/12734027/31754713-437c2598-b4b7-11e7-9b28-052491b1ce90.png)
![screenshot from 2017-10-19 10-20-30](https://user-images.githubusercontent.com/12734027/31754714-43bc65e0-b4b7-11e7-8aa7-454c7b73d9d6.png)


Refer the screenshots, Telegram is running, and there is no Tray icon.

**Comment by omkarnathsingh** [comment]
@diazbastian TopPlusIcon Plus does install on Ubuntu 17.10. Its not a native Gnome, make sure of it. 
![screenshot from 2017-10-19 10-20-11](https://user-images.githubusercontent.com/12734027/31754713-437c2598-b4b7-11e7-9b28-052491b1ce90.png)
![screenshot from 2017-10-19 10-20-30](https://user-images.githubusercontent.com/12734027/31754714-43bc65e0-b4b7-11e7-8aa7-454c7b73d9d6.png)


Refer the screenshots, Telegram is running, and there is no Tray icon.

**Comment by diazbastian** [comment]
@omkarnathsingh Did you check if `libappindicator` is installed on your system? Did you check if the "show tray icon" option is enabled on Telegram?
 
As you can see in #3968 the extension "Ubuntu AppIndicators" displays the status icons in Ubuntu 17.10 and probably the problem is there and not in Telegram. It is also strange that you can't install TopIcon Plus, so I assume it is an Ubuntu problem (consider bugs are common in a distro that has not yet been officially released). Try using the X.org session or GNOME Vanilla session to see if there is a difference.

**Comment by omkarnathsingh** [comment]
"show tray icon" is enabled. You are just blaming the Operating System for everything in short. 
"Dropbox" also shows tray icon, and everything is perfect with that.
`libappindicator` is installed.

Seems devs cant do (rather not interested) in fixing this bug.

**Comment by diazbastian** [comment]
@omkarnathsingh It is not about that, but if you can't confirm the problem in other distributions it is logical to think that it is a specific distro issue. This is reaffirmed by the fact that the extension you are using is only available for Ubuntu and therefore you can't install others extensions (so I asked you to try other Ubuntu sessions). 

This would be better resolved if you gave more information about your system, including the Telegram version, installation source (repository, PPA, Snap package, Flatpak, telegram.org, etc.), other installed extensions or any other changes made that may be related, etc. 

--

I can't confirm this issue. Always reproducible.

### Version of selected component: 
- Ubuntu 17.10 (GNOME 3.26.1) Wayland and Xorg session
- Telegram 1.1.23 stable

### Steps to Reproduce:
1. Go to [telegram.org](https://desktop.telegram.org/) and download Telegram Desktop for Linux 64 bit
2. Decompress, allow execute permissions and run application in local folder
3. Alternatively you can copy the "Telegram" folder into the `/opt` folder and run

### Actual results:
When Telegram is run, status icon is displayed in the system status area.

![ubuntu1710-tgstatusicon](https://user-images.githubusercontent.com/5126124/31826915-cd657fae-b58c-11e7-8cd8-3fb2b3a349f8.png)

### Additional info:
- The size of the icon is too small, perhaps a problem with the extension "Ubuntu AppIndicator" since it is not displayed in the same way using the extension KStatusNotifierItem support which is based using Ubuntu and other distros.
- Using the Flatpak version of Telegram the same results were obtained.
- Using the TopIcon Plus and KStatusNotifierItem extensions in fedora 26 and Arch (GNOME 3.26.1) the status icon is displayed correctly.

**Comment by omkarnathsingh** [comment]
I had upgraded from Ubuntu 17.04 to 17.10. In Xorg, everything seems fine. Problem is only in Wayland. Consulting various people, I have found that people who upgraded are facing issues. I am expecting fixes soon.

**Comment by Aokromes** [comment]
here they say gnome don't must use tray icon https://github.com/telegramdesktop/tdesktop/issues/2191

**Comment by zarinfam** [comment]
https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-appindicator/+bug/1712866

**Comment by omkarnathsingh** [comment]
Issue fixed in Ubuntu in latest fix update.
