### ISSUE TITLE
accented letters cannot be entered with spanish keyboard on linux

### ISSUE THREAD

**Issue by paolobenve** [telegramdesktop/tdesktop#4077]
### Steps to reproduce
1. in your desktop preferences, set spanish keyboard
2. type \` and then `a` (it's the normal way to input `à` on a spanish keyboard
3. you get a simple `a`

The same behaviour happens with every vowel.

If I change the keyboard mapping to italian (italian mapping has single-stroke accented letters) everything is fine.

If I paste accented letters from the clipboard, everything is ok

### Configuration
**Operating system:**

linux ubuntu xenial

**Version of Telegram Desktop:** 1.1.23

**Used theme**: standard (no change)

</details>

**Comment by vdmkenny** [comment]
Probably related to this, I can't enter unicode symbols in telegram with ctrl+shift+u2122 like I can in other text fields on my system.

**Comment by diazbastian** [comment]
@paolobenve check if the [iBus](https://help.ubuntu.com/community/ibus) daemon is running on the system, otherwise i would have to install and run iBus. check if the ibus daemon is running in the system, otherwise you would have to install the package (ibus and related like ibus-qt, etc.) and run it, that will solve your problem.

**Comment by paolobenve** [comment]
it wasn't running, I installed it, run ibus-setup, but nothing changed...

Besides that, is it reasonable that only in telegram the lacking of ibus makes double-strike characters not work? in all other app everything is fine

**Comment by paolobenve** [comment]
ok, it works, thank you
