### ISSUE TITLE
High CPU usage on Linux

### ISSUE THREAD

**Issue by makkarpov** [telegramdesktop/tdesktop#4132]
### Steps to reproduce
1. Run Telegram and do nothing

### Expected behaviour
Telegram should not eat 60-80% of CPU.

### Actual behaviour
Telegram consumes approx. 60-80% of CPU.

![image](https://user-images.githubusercontent.com/1329592/33776001-1f92a85c-dc51-11e7-8ecb-659bd1f2f539.png)

### Configuration
**Operating system:** Fedora 26, `Linux 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
**Version of Telegram Desktop:** 1.1.23
**Used theme**: Default

**Comment by d0tfile** [comment]
Does problem disappears if you restart Telegram? Did you just run it and nothing else? AFAIK there is (or was) problem with GIF. Telegram had high CPU usage after watching GIFs.
On my laptop Telegram takes 0% CPU and ~150MB ram.
May be related: #3987 #3640 #3687

**Comment by makkarpov** [comment]
It disappears, but for a short time. After 10-20 minutes Telegram starts consuming CPU again.

**Comment by Tids** [comment]
@makkarpov Try building telegram system-Qt, all the files are in here: https://aur.archlinux.org/packages/telegram-desktop-systemqt/ (wich is a fix for me)

I have the same issue with Telegram from telegram.org. I think it could be something with Intel Graphicssolutions. Because it happens on both of my intel only laptops, but not on my AMD machines.

**Comment by pizzadude** [comment]
This is just Telegram using your computers resources to create the first batch of TelegramCoin, the new cryptocurrency. Nothing to be worried about.

**Comment by stek29** [comment]
#3640
