### ISSUE TITLE
[Feature Request] Support for Known File Extensions

### ISSUE THREAD

**Issue by shinenelson** [telegramdesktop/tdesktop#415]
Since this is exclusively for the desktop versions, we should support previewing known file-types like pdf, doc, docx, xls, xlsx, ppt, pps, pptx, ppsx, odt, ods, odp, odd, etc. The preview window currently overlays the whole desktop altogether, so why not support the preview of known file types so that it'll be easier to preview documents without having to download them and then have to view them.

**Comment by mirhl** [comment]
Because, I guess, that would start to really bloat the program. 
I mean.. preview (thumbnails) for images and videos are something pretty straightforward, given you already have to handle them.. But documents are just too much imo. 

Especially in those cases (like office suite ones and pdfs made with reader in mind) where nobody but microsoft and adobe have a properly compatible code

**Comment by shinenelson** [comment]
I have no idea how GNOME's Nautilus does it, but I got the idea from
Nautilus. It's a pretty handy feature in Nautilus when you have to just
skip through a file. It previews essentially any file. Probably using the
plugins and apps on the distro, but it does the job, couldn't that be
implemented in the desktop version of Telegram too?

~ shine

**Comment by auchri** [comment]
I agree with @mirhl, it's almost impossible to create a preview from office documents. it would be nice, but it blows up the code and it may be not stable.

Maybe later the documents can be parsed on the server and they send just a preview image to the clients.
