### ISSUE TITLE
Mouse middle click on link

### ISSUE THREAD

**Issue by sirati** [telegramdesktop/tdesktop#4212]
### Steps to reproduce
1.  middle click on a link

### Expected behaviour
In most web browsers a middle-click opens a link in a new tab. Obviously, telegram cannot open something in a new tab as it isn't a web browser. I still expect it to open the link however.

### Actual behaviour
Nothing

### Configuration
**Operating system:**
Win8.1

**Version of Telegram Desktop:**
1.2.3 alpha

**Comment by wwevo** [comment]
That middle click thing is pretty much unique to browsers. Other programs do different stuff there
I would find it irritating for it to have the exact same function as the left click.

**Comment by prototype99** [comment]
yeah sorry to say i'm not feeling it either. for the browser it's an alternate version. for telegram what alternate thing would it do? you may make a more convincing case pushing for the option to change key-bindings, which may make sense for accessibility reasons.

**Comment by Socialdarwinist** [comment]
It would of course open the link in alternative windows as are demanded under #981 and #533 or tabs – nobody has yet opened an issue for tabs in Telegram but it makes sense as Telegram is kind of a parallel web. “Tabs in Telegram” isn’t a joke, power users would love it, and it would make Telegram an economic factor that could threaten the market share of the WWW.

**Comment by prototype99** [comment]
the list of chats to the left is the equivalent of tabs? you can cycle through with arrow keys and if that's too cumbersome you can search? then if you want specific chats available at a moments notice you can pin them? i'm not saying it's a bad idea, i'm just explaining how i see it (and potentially explaining how some developers may see it). Help one person understand, and perhaps the developers will find it easier to understand why people would want/why they should implement it. be careful to make sure you're staying on topic though, this issue is ultimately relating to making it so left click and middle click both perform the same function on a link based on a user's personal preference, not about tabbed telegram. you may be best giving that it's own issue so it receives the attention it could deserve.

**Comment by Socialdarwinist** [comment]
> the list of chats to the left is the equivalent of tabs

No, its radically different. If you browse through channels, the list of chats on the left is of limited help only, for it only shows channels you are subscribed to. If you click from one channel to another and than to another and so on and then forward a post to a friend, then maybe read a message from another friend, you will have lost the channel you had forwarded from, because Telegram does not keep tabs open – you have a contact/channel/group list, and this is not used like tabs in a browser but rather like feeds in a feedreader, still a sui generis thing though.
If there were tabs too, i.e. another bar with channels, opening a new tab with the channel would be an alternative action performed by use of the middle mouse button.
Though having apprehension of a danger of digression, I do not esteem to have actually talked off-topic, since the topic is what could be performed with the middle mouse button, not necessarily what the OP wants it to do.
Attention is a fine thing, but in the end the coding economy decides, and it’s not like there is no other feature that I would like to see earlier.

**Comment by sirati97** [comment]
i think it would still be nice to be able to use middleclick, it doesnt do anything else so its not taking away anything either
