### ISSUE TITLE
No tray icon in KDE 

### ISSUE THREAD

**Issue by liathit** [telegramdesktop/tdesktop#424]
I have no tray icon in Telegram 0.7.8. Please fix it.

**Comment by ScorpionIT** [comment]
try to install libappindicator-gtk3/libappindicator3

**Comment by liathit** [comment]
I install libappindicator but this has not corrected the situation

**Comment by lig** [comment]
Installing `libappindicator-gtk3` fixes the same in Gnome 3 on Fedora 21.

**Comment by susnux** [comment]
Same problem here, 0.7.7 works (with the known bug that the unread messages counter does not disappear).
But no I have to install libappindicator to get telegram working.
Using openSUSE with KDE I have to install this to packages:

libappindicator
libappindicator3-1

**Comment by soee** [comment]
With 0.7.8  the icon shows up in systray (Kubutnu 15.04 + Plasma 5.1.95) but is very blurred. This is probably because it uses small icon size 22x22px. When Telegram is just downloaded and run i think it does not put own icons for example in /usr/share/icons so the system can use the proper size. Can this be fixed somehow ?

**Comment by EliaGeretto** [comment]
@liathit I'm using Arch Linux, with KDE4 and "libappindicator-gtk3" installed, and the icon is present. Which distribution are you using?

**Comment by liathit** [comment]
I am install libappindicator and the icon shows in system tray. Thank, everyone!

**Comment by telegramdesktop** [comment]
From version 0.7.16 tray icons should work through libappindicator in Unity environments and through Qt implementation otherwise (with show/hide of window by left click or other "activate" event). Please check.

**Comment by lig** [comment]
Version 0.7.16 completely ruined tray icon on Gnome 3.

On Tue, Feb 17, 2015 at 8:45 PM, telegramdesktop <notifications@github.com>
wrote:

> From version 0.7.16 tray icons should work through libappindicator in
> Unity environments and through Qt implementation otherwise (with show/hide
> of window by left click or other "activate" event). Please check.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/424#issuecomment-74713955>
> .
>



-- 
Serge Matveenko
mailto: serge@matveenko.ru
github: http://lnkfy.com/1
linkedin: http://lnkfy.com/S
http://spbpython.guru/

**Comment by telegramdesktop** [comment]
Many messages about better working icon through QSystemTrayIcon instead of libappindicator, so I've left libappindicator only for Unity. After some more reports I saw I should return libappindicator in p
Pantheon and perhaps some others. Can you please tell what does "echo $XDG_CURRENT_DESKTOP" tell you in Terminal so I could switch back from QSystemTrayIcon to libappindicator in your case?

**Comment by lig** [comment]
Sorry. Everything works as expected

One need to restart application completely to see new icon. The icon will not work after in app update until complete restart.

**Comment by telegramdesktop** [comment]
Sounds very strange, because in app update _does_ completely restart the application. Seems like there is some kind of rare occuring bug :(

**Comment by lig** [comment]
The icon is missing again. The cause is in "top icons" Gnome extension more likely.

**Comment by sergioad** [comment]
Netrunner 16 TDesktop has not tray icon

**Comment by zeynaliAli** [comment]
KDE plasma 5 + users who installed the required packages and can't see the telegram  system tray consider this that you must add system try widget to your panel.
