### ISSUE TITLE
Color theme issue

### ISSUE THREAD

**Issue by minajev** [telegramdesktop/tdesktop#4246]
### Steps to reproduce
1. Create super group
2.  settings>edit theme>msgInBg> color opacity 0
3. Group Audio files> play/pause symbols (in a group right panel) are not shown

### Expected behaviour
It would be nice to bind play/pause symbol color to something else, for example - windowBg instead of msgInBg

Thank you very much :)

**Comment by john-preston** [comment]
I've reused keys from message history play/pause buttons and ripple animations.

But generally themes with transparency used in places, where default theme doesn't have transparency, isn't supported. It may result in different rendering glitches, because it is impossible to support transparency correctly everywhere.
