### ISSUE TITLE
[Qestion/suggestion] Issues, no support, and periodic sms confirmation 

### ISSUE THREAD

**Issue by JhonSane** [telegramdesktop/tdesktop#4255]
### Steps to reproduce
1. Have phone from country 1 and email
2. Finding yourself in country 2
3. Registrate first time and **only on desktop version forcibly with SMS+EMAIL** 
4. Be in the telegram almost daily, rarely write
5. After learning, more than 6 month sim was blocked as time inactive (operator rules)
6. New day - suddenly find that telegram not logged in and ask sms
7. Used support form web form with email, suggest any type of verification
8. There is no answer or letter after 2 months

### Expected behaviour
Do not beg sms, in case of compulsory mail request at registration, any confirmation of sending there

### Actual behaviour
There is some issues to report on github but I forgot them without direct vision
Will I be able to congratulate my friends on the New Year?
Break of communications
No support
2gb suspended space

### Questions for non-friendly guys
is it need beg email after sms on registration?
is it need сonfirm sms every half a year?
do telegram check numbers for the presence on the network?
do telegram could not receive my accurate location through "desktop" and ask for sms and "kick" after no?

### Configuration
**Operating system:** windows 7 8 10

**Version of Telegram Desktop:** desktop, November version (1.1.23)

**Used theme**: default

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
Mail is used to reset 2FA password. 2FA is about *two factors*. Allowing to use mail instead of phone would reduce it to one factor.
Exactly because of this it is recommended to have a back-up session if you lose your phone (by common sense at least). And why haven't you updated it when you moved? 

> is it need beg email after sms on registration?

Telegram doesn't do that. It asks you for email to reset 2FA password if you set it up. That's the only place where TG asks for your email.

> is it need сonfirm sms every half a year?
> do telegram check numbers for the presence on the network?
> do telegram could not receive my accurate location through "desktop" and ask for sms and "kick" after no?

No, No, No. AFAIK. 
You've likely lost session because of some other reason, and to avoid such situations, you should've changed your number or save a back-up session (for example, in Webogram).

I'm deeply sorry, but TG relies heavily on phone numbers. You should've changed your phone number via settings when you've moved.

Either contact your phone provider, or collect documents showing it's your phone and send them to support. Try contacting https://twitter.com/smstelegram, or using temp account to reach in-app support.

P.S. I've explained all of this to you in e-mail. I don't understand what you've expected when you opened this issue.
P.P.S. Also, I'm not related to "official" Telegram in any way 🙃
