### ISSUE TITLE
[Feature Request] an option to disable particular contact's avatar

### ISSUE THREAD

**Issue by rezapc** [telegramdesktop/tdesktop#430]
Hi please provide an option to disable particular contact's avatar to hide showing that.
Thanks

**Comment by auchri** [comment]
what's the sense of that?

**Comment by rezapc** [comment]
its very clear! make user enable to hide other contacts avatars. sometimes very useful.

**Comment by Cameri** [comment]
I suggested this once and was told to recompile telegram on my own and fix it myself. You know, devs these days lack basic social skills.

This is useful because if someone puts up a really disgusting profile picture, and you are in a group chat with that person, your only option is to suck it up or leave the group chat if you can't handle it.

**Comment by poiuty** [comment]
+

**Comment by menkow** [comment]
Yes guys, Im really need it too! )

**Comment by parserpro** [comment]
+1

**Comment by ProKtorOne** [comment]
+1

**Comment by Cameri** [comment]
+1 some love on this feature request

**Comment by Aokromes** [comment]
Maybe it can be interesting allow users to choice avatar image (Default/None/Choice picture)

**Comment by stek29** [comment]
@Aokromes Default and None -- sure, it won't be that hard, but does it worth it?
Choosing custom pictures would make sense if TDesktop had a local persistent db.

**Comment by Aokromes** [comment]
Sometimes some people on groups uses avatars that you may don't like, and with custom avatar it can allow you to localize people that don't adds avatar and you want to spot on easy way on big groups.

**Comment by trycontrolmymind** [comment]
2015? Seriously? Guys, please

**Comment by johnchristopher** [comment]
I too would like to chime in and support that request.

I like the minimalism of only showing initials (like when Telegram hasn't loaded the picture of an avatar yet).

I wouldn't replace other people's avatar but I can see how some would like to do that.

**Comment by sociopatico** [comment]
please, allow user users to hide someone else's avatatar. I don't want to leave a group just because a guy  is using disturbing pictures

**Comment by baterflyrity** [comment]
Support custom avatars. Hope this will be released until 2030.

**Comment by Muhammadrasul446** [comment]
September 18, 2020. 10 years left.

**Comment by N-ihad** [comment]
So, will they be adding this feature? It's very needed.

**Comment by Aokromes** [comment]
https://bugs.telegram.org/c/406
https://bugs.telegram.org/c/85

**Comment by baterflyrity** [comment]
@Aokromes , why did u close this thread? The feature does not work not and has not even been planned!

**Comment by Aokromes** [comment]
because it needs to be implemented platform wide.

**Comment by baterflyrity** [comment]
@Aokromes  so i guess u want to say that this tracker only for desktop-specific issues and features and this feature request should be further ignored by main telegram team. Am i right?

**Comment by N-ihad** [comment]
@baterflyrity for real, this guy has no clue

**Comment by Aokromes** [comment]
> @Aokromes so i guess u want to say that this tracker is only for desktop-specific issues and features while this feature request should be further ignored by main telegram team. Am i right?

like i said, it needs to be implemented on all applications, not only on telegram desktop, so that bugtracker is the best place to follow the request upvoting.

**Comment by RememberTheAir** [comment]
> so i guess u want to say that this tracker is only for desktop-specific issues and features

Yes, this tracker has always been about telegram desktop and not platform-wide suggestions

> while this feature request should be further ignored by main telegram team. Am i right?

You can either decide to keep this here where literally none of whoever takes decisions at Telegram look, or upvote the card in the new platform. Beyond irritating how everyone here feels entitled of their feature suggestions, there's a thousand of suggestions in this issue tracker, and judging from these issues' comments _every one_ of them is a max priority request that absolutely needs to be implemented because there's millions of users struggling from its absence

**Comment by baterflyrity** [comment]
@RememberTheAir due to i use only desktop i propose the feature only for desktop. Moreover this feature is 5 years old but no dev activity has been attained for whole time. 
And now its closed again without any discussion from devs! Hey, not declined, not approved, not postponed, not reassigned, no guideline for self fixing, just obliviously closed... Well, now i understand that the feature not even in low priority, its in -9548215421 priority level that does not deserve even any time for discussion.

**Comment by RememberTheAir** [comment]
@Aokromes is a bit too hasty in closing issues by just posting two links with no further explanation, but if you open them it's pretty clear that this issue has been moved to Telegram's "bugs & suggestions" platform, and closed here because it's out of the scope of this issue tracker/of tdesktop, since this should be a platform-wide feature and cannot be implemented client-side by an official client
