### ISSUE TITLE
option to archive conversations

### ISSUE THREAD

**Issue by yurigoytacaz** [telegramdesktop/tdesktop#4302]
we currently only have the option to delete the conversation.
it would be great if we could archive it and if we resume the chat, we still had the old log. (=

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3328

**Comment by konga69** [comment]
I agree we should continue with the old log

On Jan 13, 2018 8:13 AM, "Aokromes" <notifications@github.com> wrote:

#3328 <https://github.com/telegramdesktop/tdesktop/issues/3328>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/telegramdesktop/tdesktop/issues/4302#issuecomment-357434309>,
or mute the thread
