### ISSUE TITLE
[Feature Request] Play video/audio while downloading it

### ISSUE THREAD

**Issue by snqlby** [telegramdesktop/tdesktop#4330]
### Steps to reproduce
1. Find any video/audio inside the chat
2. Press the download button

### Expected behaviour
I can play video/audio while it is being downloaded

### Actual behaviour
There is no any playback while downloading it

### Configuration
**Operating system:**
Arch Linux
**Version of Telegram Desktop:**
1.2.6

**Comment by stivens13** [comment]
Since Telegram for Mac supports this feature, I suggest to make it priority to match this functionality on TDesktop. Anyway, any official roadmap is missing and it's hard to say what feature is implemented right now because development is slow right now (or focused on polishing, bug-fixing, and minor improvements rather than on lifting up this client to Telegram-wide available features).

**Comment by stek29** [comment]
> Telegram-wide available features

Two apps (with shared codebase) out of 6 is not platform-wide btw.

**Comment by ArmeF97** [comment]
@stek29 
Android, iOS, Mac
I'd say that only tdesktop is missing. They are the 4 big telegram clients

**Comment by stivens13** [comment]
@ArmeF97 Actually, I think I figured that out. TDesktop uses TDLib, a tg library for easier tg client development which doesn't have all the official tg functions yet ([last commit on TDLib github was in september](https://github.com/tdlib/td/commits/master)). Android, iOS and Mac versions don't use TDLib but their own legacy implementation + they develop new features.

That would be nice to make this fact be clear for everyone since majority of request are concerned the features that TDLib does not support.

**Comment by RememberTheAir** [comment]
@stivens13 TDesktop doesn't use TDLib 🤔

**Comment by Aokromes** [comment]
implemented on 1.5.15

**Comment by YousefSaber** [comment]
this feature was implemented in v1.6(received a Telegram notification ) though I didn't test videos I'll create another issue scope if I faced such problem
