### ISSUE TITLE
[Enhancement] Make automatic emoji replacement immediate and reversible

### ISSUE THREAD

**Issue by HifeFish** [telegramdesktop/tdesktop#4410]
### Feature Request

Implement automatic replacement in a way that shows the replacement instantly and allows one to revert it, e.g. pressing backspace could remove the emoji and show the typed text instead.

### Reasoning

I want to send what I type. Automatic replacement can change the tone of a message. This is especially bad because the replacement happens only after sending the message and I cannot prevent or revert it.

Deactivating Emoji replacement is not an ideal solution, because I would like to keep colon suggestions. 
Issue https://github.com/telegramdesktop/tdesktop/issues/3738 has been closed, so I am not counting on separate options.

</details>

**Comment by RememberTheAir** [comment]
> e.g. pressing backspace could remove the emoji and show the typed text instead

That's nice. Since the developer already stated that there won't be two different settings to replace emoticons and toggle emoji suggestions (`:emoji:`), I think this is a really good solution. Istantly replace emoticons with emojis, and revert the conversion on backspace usage. Would make everyone happy I guess :) no additional options in settings, and the current behaviour is kept and made more predictable

**Comment by Peque** [comment]
@stek29 Would you reconsider opening #3738 again too? (very related to this)

**Comment by stek29** [comment]
@Peque this issue stayed open until it was resolved and shipped in 1.2.20 alpha. I’m now waiting for stable release to close it.
Your issue is closed for a different reason.
