### ISSUE TITLE
Qt's Internationalization support

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#444]
Is there any way to support [Qt's Internationalization](http://doc.qt.io/qt-5/internationalization.html) support instead of used flat strings? 

Until now I couldn't understand why Telegram Desktop uses flat translation instead of Qt way! Qt translation engine very effective and practical for updating translations dynamically instead of manual update.

**Comment by Sollex-21412** [comment]
+1
Also, also still don't understand static linking of qt here.

**Comment by telegramdesktop** [comment]
Qt has some patches here and I like the idea of one binary with less dependencies (it was Windows version firstly, didn't want to deploy an amount of .dlls with the app).

What is the problem with internationalization? I precompile those .strings files in order to get fast and compile-time checked translations (tags replacements are checked for English version at compile time and tags are validated in runtime when loading other languages), I don't see what's the problem, all translations are done through Transifex anyway.

**Comment by SafaAlfulaij** [comment]
The problem is that implementing a new way of i18n will forces you to deal with multi languages with multi plural forms. Arabic has **6** plural forms and can't be translated right now (while just 3 (zero, one and other) are used).
