### ISSUE TITLE
problem view

### ISSUE THREAD

**Issue by javansolo** [telegramdesktop/tdesktop#4494]
Hi
The problem with displaying hashtags and hyperlinks for example at the following address:
https://t.me/refah_chain_stores/24296
رفاه#
Linked and the rest is not Linked

### Configuration
**Operating system:** windows 7 x64

**Version of Telegram Desktop:** 1.2.6

**Comment by javansolo** [comment]
the other @ not linked!!!!

**Comment by javansolo** [comment]
![image](https://user-images.githubusercontent.com/11363999/37397677-725148c4-2791-11e8-90c4-7d7b1b446cd1.png)

**Comment by john-preston** [comment]
@javansolo Thanks for your report, this will be fixed in the next version.

Currently you can try the alpha version from https://desktop.telegram.org/changelog#alpha-version that will show those hashtags and mentions as clickable if you receive them, but not if you send them. In the next version they'll work fine.

**Comment by Lonami** [comment]
So, this is fixed now?
