### ISSUE TITLE
Saving images to disk adds FURTHER compression BEYOND what they were sent with

### ISSUE THREAD

**Issue by omgitsraven** [telegramdesktop/tdesktop#4619]
### Steps to reproduce
1. User A sends User B an image that JPEG compression would be obvious in (i.e. clean lineart, or an old video game screenshot)
2. They use "drop photos here to send them in a quick way", which adds a slight amount of compression (this is fine)
3. User B clicks the image to view it larger -- it looks okay and only slightly compressed.
4. User B then clicks the arrow icon, to save a local copy. They open that local copy, and it is visibly **EVEN MORE compressed** than the copy that they were just viewing in Telegram's interface!

### Expected behaviour
The received image should look exactly the same after saving to disk as it did when it arrived in Telegram.

### Actual behaviour
Telegram for some reason compresses the image EVEN MORE when it writes to disk, instead of writing the data that it received.

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 1.2.17

**Used theme**: day theme, the default flowers background

Here is an image you can use to test:

Here is the original, uncompressed image
![redtest_original](https://user-images.githubusercontent.com/8540042/39089198-122ba87e-458f-11e8-8cd4-48fa76f10754.png)

Here is a **screenshot** of how it looks when I click to view it in Telegram
![redtest_screenshot](https://user-images.githubusercontent.com/8540042/39089200-1726c23c-458f-11e8-9495-ded6673d692d.png)

Here is the file that actually gets **written to my disk** when I try to save it:
![redtest_saved](https://user-images.githubusercontent.com/8540042/39089203-1d21ab8e-458f-11e8-8347-806d08550418.jpg)

In case the difference is not apparent to you, here is a GIF of a closeup comparing those **last two** files:
![closeup_comparison](https://user-images.githubusercontent.com/8540042/39089204-20e54b40-458f-11e8-8af3-298a0f4e372c.gif)

**Comment by soredake** [comment]
@john-preston

**Comment by john-preston** [comment]
@soredake Yes, this is true :( Saving should be done in some different manner.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by omgitsraven** [comment]
Just tested and yes, it's absolutely still happening.

**Comment by omgitsraven** [comment]
This is still happening!

**Comment by omgitsraven** [comment]
This is STILL still happening.

**Comment by ssdd28561** [comment]
2022: this bug is still valid

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/commit/6805259f74a163ea851fee0e1ae743e81bf75c61

**Comment by omgitsraven** [comment]
That's about when *sending* them, though, isn't it?  This bug is about extra compression being added when writing a *received* file to *disk* (more compression than it was *already* received with).

**Comment by john-preston** [comment]
@omgitsraven Saving should be fine in beta already.

**Comment by omgitsraven** [comment]
The problem is **still occurring** in Telegram 3.6 beta.

**Comment by john-preston** [comment]
@omgitsraven how do you test that?

**Comment by omgitsraven** [comment]
@john-preston exactly as described in the "steps to reproduce" at the top of this thread.  (Actually, I guess more specifically, I don't even use two users, I just send it to myself in "saved messages".)

**Comment by omgitsraven** [comment]
Just mentioning again that *this issue is not resolved in Telegram 3.6 beta* and this thread shouldn't be closed.

**Comment by john-preston** [comment]
@omgitsraven Maybe 3.6.1?  Before it was done in media viewer, now it should be in Save Image As from context menu as well.

**Comment by omgitsraven** [comment]
Not fixed in 3.6.1 either, no.

**Comment by john-preston** [comment]
@omgitsraven I can't reproduce that, but there is something strange indeed.

It looks like reading+showing of the JPG is done differently by tdesktop and by, for example, Photoshop. Because they do look different, but the bytes are equal.

I tried that. I took your image from here:

https://user-images.githubusercontent.com/8540042/39089198-122ba87e-458f-11e8-8cd4-48fa76f10754.png

I've sent it "in a quick way", opened the received image in the media viewer and saved to disk. It was "photo_2022-03-25_19-40-59.jpg", 6799 bytes. This is the same size and bytes the image has on the server (6799 bytes too), although it looks different if I open it from disk or if I view it in tdesktop. But.

Then I take this "photo_2022-03-25_19-40-59.jpg" (6799 bytes) and send it back (or once again, or in different chat), "in a quick way". And from the receiver this new photo in tdesktop looks exactly the same, as the first one in tdesktop, it has the same size (6799 bytes) and is saved to the same image if I save it from the media viewer. So it saves exact bytes it gets from the server, but it shows them somehow different inside tdesktop (but even if you send that "worse compressed" file, without any ties to the original, it will look "better" in tdesktop from the receiver - the same way it looks in tdesktop after the first sending). Idk.

I've pressed an arrow in the lower-bottom corner to save to Downloads and got this:

**Comment by omgitsraven** [comment]
Oh wow, that would explain a lot, actually?  At one point I actually tried writing my own command-line telegram client that only dumped images, purely to investigate this bug, and I found that it *still* didn't resemble the version that I saw in the normal telegram client, but I figured that was just yet another bug......   but if Telegram is doing something unusual on *display* of the image, that would explain *both* of these situations....

**Comment by john-preston** [comment]
@omgitsraven I don't really know what it can do, because I just QImageReader::read them 🤷‍♂️ But it looks that way, because at least sending the saved-from-chat image again saves to disk AND shows in tdesktop exactly the same like the first one.

So, image_original is sent A -> B and becomes image_a_b in tdesktop. Then it is saved to disk and becomes image_b.
Then image_b is sent B -> A and becomes image_b_a in tdesktop. Then it is saved to disk and becomes image_a.

Now, image_original is compressed to become image_a_b, but image_a_b looks in tdesktop exactly like image_b_a and image_b has the same bytes as image_a. So it looks to me that they're saved to disk properly. I don't know right now why they look differently and no time to thoroughly investigate it, unfortunately.

**Comment by omgitsraven** [comment]
Well, I'm still *curious* about this mystery, but honestly, your test sounds like a perfect proof that the files really are coming through (and being saved) right, so I guess it doesn't actually matter if it *looks* different in Telegram.  I'm willing to consider this closed then, display mystery notwithstanding!   Thank you for that smart test, it never would've occurred to me!
