### ISSUE TITLE
[REQ] Colorize found characters when using search

### ISSUE THREAD

**Issue by 2ge** [telegramdesktop/tdesktop#4638]
### Steps to reproduce
1. Click on Search, write search pattern

### Expected behaviour
search pattern should be colorized, so one can see it, specially when message is long.

### Actual behaviour
search pattern is found, but not colorized.

### Configuration
**Operating system:** OSX
**Version of Telegram Desktop:** 3.8.2
**Used theme**: Dark

**Comment by stek29** [comment]
> Version of Telegram Desktop: 3.8.2

that's not telegram desktop, that's a different app. You can reach developer via https://t.me/macswift.
You can download telegram desktop at https://desktop.telegram.org or through GitHub releases on this repo.

also, it can't be done properly just on client side -- since server doesn't say where match happened, and it can search with typos or different forms, plurals, etc.
