### ISSUE TITLE
Update via MTProto proxy

### ISSUE THREAD

**Issue by Startname** [telegramdesktop/tdesktop#4665]
### Steps to reproduce
1. in iran telegram is blocked. and i use the my proxy socks5/MTProxy.
2. when i click the check update tdesktop I'm failing. please use of Proxy for checking update!

### Expected behaviour
Possible update telegram desktop in countries that blocked telegram.

### Configuration
**Operating system:** win 10

**Version of Telegram Desktop:** 1.2.18 alpha

**Used theme**: any

**Comment by john-preston** [comment]
@Startname Socks5 should work for update checking. Autoupdate currently doesn't work with mtproto proxy, sorry :(

**Comment by Startname** [comment]
@john-preston  ok. thank you.
but mtproto proxy Strictly in progress. If possible, find a way to bypass this restriction for update tdesktop

**Comment by ffallah** [comment]
The problem is that they have blocked socks5 protocol in their filtering equipment.
Iran's filtering hardware is much more advanced than Russia or China and they have the ability to block layer 7 protocols without the need to block any specific IPs.
If you want to MTProto proxy to work, It should not have any kind of signature which make it separable from white listed traffic. I recommend to obfuscate it into legitimate SSL traffic.

**Comment by amirnapster** [comment]
I tried all proxies that listed in t.me/MtprotoProxies
None of them worked in Iran

**Comment by ffallah** [comment]
@amirnapster It is because current implementation of MTPoro Proxy server is only offered by a low performance PHP based script which crashes the server. thats why those proxies cease to exist after a while. MTProto Proxy is not blocked in Iran, the problem is that Telegram has not released a proper server yet.

**Comment by arashmm50** [comment]
@john-preston I used this source today to create a MTProto proxy. It has a lot of speed

https://github.com/TGMTProto/MTProtoProxy

Did you check this source?

**Comment by Aokromes** [comment]
test after https://github.com/telegramdesktop/tdesktop/commit/03037121aacfe71107dc277d572850e6e8fa1a8f :)
