### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zgl1990** [telegramdesktop/tdesktop#4667]
### Steps to reproduce
1. win10 vs2017 
2. telegram version is 1.2.8
3. error C3779: 'rpl::event_stream<Value>::events': a function that returns 'auto' cannot be used before it is defined

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Configuration
**Operating system:**

**Version of Telegram Desktop:**

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@zgl1990 For now you can replace "auto events() const {" with "producer<Value> events() const {" and it works.

Also you'll need to disable warning 4180, otherwise QMap<bool(*)(), smth> throws a warning about "const Ptr*" with Ptr being a pointer to a function.

But this is a regression :( I hope I'll find time to prepare a minimal example to reproduce that and submit it to msvc team.

**Comment by zgl1990** [comment]
I replace "auto events() const {" with "producer events() const {",and set “Treat warnings as errors” as no,it can't work. many errors like below: 
error C2672: 'combine': no matching overloaded function found 
error C2783: 'decltype(auto) rpl::combine(Args &&...)': could not deduce template argument for '<unnamed-symbol>'
