### ISSUE TITLE
How To Create MTProtoProxy?

### ISSUE THREAD

**Issue by arashmm50** [telegramdesktop/tdesktop#4669]
How To Create MTProtoProxy In Windows Server?

**Comment by ffallah** [comment]
Wow, Iranians all over the place. lol
MTProto is not released yet. lets just hope it is not detectable by Iran's DPI hardware, otherwise it will be useless.

**Comment by arashmm50** [comment]
@ffallah Yes, I think this is not identifiable

**Comment by john-preston** [comment]
@arashmm50 You can see and try an example here: https://t.me/MadelineProto/348

This is not an official mtproto proxy implementation, but some third party made by reverse engineering. But at least it is something working.

Official implementation is not released yet.

**Comment by ffallah** [comment]
Well, I am not sure.
Russia had a lot of issues in filtering the telegram, because they had to block IPs and it is quite difficult to do so without hurting other services and websites, but in Iran, they did it so easily because they have advanced DPI hardware which can check the packets for specific signatures. so no matter how many IPs  telegram used, they blocked it without hurting a single other website or service.
I dont know if telegram team is familiar with the challenge that it is facing in Iran. They need to obfuscate their traffic into white listed traffic, otherwise it will be blocked so easily.

**Comment by arashmm50** [comment]
@john-preston Do you think blocking is possible?

**Comment by john-preston** [comment]
@arashmm50 Everything is possible :) but I hope it will be hard enough.

**Comment by arashmm50** [comment]
I saw in the channel that it was said that the Blockchain would be launched for the next 23 days. is it correct?

Do you know about this time?

**Comment by john-preston** [comment]
@arashmm50 I know nothing about a blockchain.

**Comment by ffallah** [comment]
@arashmm50 This unblockable Telegram myth based on blockchain is a nonsense made by Iranian Telegram channels, there is no such technology.
Blockchain is related to Telegram cryptocurrency which there is not much info about it yet.
