### ISSUE TITLE
UI Enhancement for Gnome based systems

### ISSUE THREAD

**Issue by omkarnathsingh** [telegramdesktop/tdesktop#4679]
Gnome based systems display a additional title bar "Telegram", It can be hidden or given as a option to hide it. 
### Steps to reproduce
1. Open Telegram Desktop
2. Notice Title Bar
3. That's it.

### Expected behaviour
It should display Application name only in Top most bar which displays time.

### Actual behaviour
It displays Application name in top bar and also in a additional bar just below it.

### Configuration
**Operating system:** Ubuntu 18.04 LTS

**Version of Telegram Desktop:** 1.2.19 alpha

**Used theme**: Dark Theme (Issue is theme independent).

I am attaching the tdesktop and Firefox 60 for comparison. Firefox 60 has given this option to hide the title bar under "Customize" settings. 

Telegram:
![image](https://user-images.githubusercontent.com/12734027/39941267-a2e156f8-5579-11e8-9e17-37c4d657b851.png)

Firefox:
![image](https://user-images.githubusercontent.com/12734027/39941312-c873ecfa-5579-11e8-80ef-c88d4f3d0b3d.png)

**Comment by WyRe** [comment]
Personal question (It is just curiosity): What system tray are you using?

**Comment by john-preston** [comment]
@omkarnathsingh That way you'll need some special code for the window system buttons to be placed right inside the application, currently the design doesn't offer any place there.

**Comment by omkarnathsingh** [comment]
@WyRe Thats vanilla Ubuntu 18.04 installation. Flavour : Gnome, System Tray: "Ubuntu appindicators" (package name: gnome-shell-extension-appindicator)

**Comment by omkarnathsingh** [comment]
@john-preston What about hiding it by default then? Its going to do good only to UI by giving more space to user space(a bit of :D) .

**Comment by john-preston** [comment]
@omkarnathsingh Well, how then users will close/minimize the window? I’m not sure it is a good ui practice just to remove the window control buttons completely 🙈

**Comment by GioRixxx** [comment]
That's an "issue" caused by the default plugin installed with ubuntu. Vanilla gnome should only display the title bar, wthout the widged beside the activities button (it displays a titlebar for firefox too, tho). 
Btw, just install some plugin that hide the title bar on maximized windows(al least in software that benefits it). I suggest "no title bar", it adds the quit button in the topbar and you can maximize and demaximize the window by dragging the titlebar to the topbar, or viceversa dragging down from an empty spot in the topbar.

PS: ignore the screenshot showed in the preview on the official gnome site, it's wrong.

**Comment by omkarnathsingh** [comment]
@john-preston Oh forgot that thing.
