### ISSUE TITLE
Forwarding is tonnes slower due to design update

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#4764]
### Steps to reproduce
1. Forward a message.
2. Watch a popup box appear instead of being able to use the sidebar contacts list.
3. Be unable to quickly shift between forward recipients by clicking between them in the sidebar.

### Expected behaviour
As in 1.0 to roughly 1.1, you should be able to forward and click a recipient in the sidebar then be able to click another recipient if you chose the wrong one.

### Actual behaviour
The process is now slower, as you must exit out of a popup box and click the forwarded messages again just to choose another recipient.

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.2.17
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by stek29** [comment]
> The ability to change the recipient is not available in other Telegram apps at all

But it was available before :)

**Comment by S-U-M-1** [comment]
Copying the link to my video of the bug from the closed issue:
https://www.dropbox.com/s/9sfakp3eytd7qns/Telegram%20Forward%20Glitch%20Github.mp4?dl=0

**Comment by john-preston** [comment]
@S-U-M-1 As I explained earlier this is a feature :(

The scenario:
- select messages to forward them
- choose chat to forward them
- start writing comment for this forward
- suddenly receive a message in a different chat and want to reply to it instantly
- continue writing comment for the forward
- send forwarded messages with a comment

is considered much more common than scenario:
- select messages to forward them
- choose chat to forward them
- decide to change the chat to which you'll forward them (why? why don't you select the desired chat at the previous step? only because of a misclick maybe)
- send forwarded messages

So the UI is optimized for the first scenario. Even more, in the new approach you still CAN do the second scenario (but with some extra clicks), while in the old approach you just COULD NOT possibly resolve the first scenario without abandoning the forwarding completely and starting it after that from scratch with selecting the messages.
