### ISSUE TITLE
Switching between forward recipients is slower in post-1.0

### ISSUE THREAD

**Issue by S-U-M-1** [telegramdesktop/tdesktop#4772]
### Steps to reproduce
1. Forward a message
2. Choose the recipient
3. Click another contact in the sidebar

### Expected behaviour
As in pre-1.0, the message should appear ready to forward to the clicked contact.

### Actual behaviour
The messages to be forwarded disappear – they are stuck in the chat of the first-chosen recipient. To switch recipients, one must click the messages to be forwarded then choose another recipient.
Video:
https://www.dropbox.com/s/9sfakp3eytd7qns/Telegram%20Forward%20Glitch%20Github.mp4?dl=0

### Configuration
**Operating system:**
Windows 7
**Version of Telegram Desktop:**
1.2.17 (this has been a problem since 1.0)
**Used theme**:
None
<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by john-preston** [comment]
@S-U-M-1 This is a feature.

**Comment by S-U-M-1** [comment]
@john-preston Well it's slower and worse, as you saw in the video. It should at least have an option to go back to the previous way.

**Comment by john-preston** [comment]
@S-U-M-1 No. You need to change forwarding recipient once in a lifetime when you first misclicked the desired chat.

But there were many complaints that you start writing a comment to your bunch of forwarded messages and you need quickly to reply in another chat. In old version you had to wait till you finish with your forwarding or cancel the forwarding at all, because you didn't need those forwarded messages in another chat.

The new approach still let's you fix your mistake in rare cases of wrong recipient while fixing all the problems of the old approach.

**Comment by stek29** [comment]
Your own #4764
