### ISSUE TITLE
Fullscreen on Windows 10 does not fit to the screen

### ISSUE THREAD

**Issue by mmatrosov** [telegramdesktop/tdesktop#4793]
### Steps to reproduce
1. Open telegram window to full-screen

### Expected behaviour
Window occupies full monitor area

### Actual behaviour
Window occupies almost full area, but little stripe on top is transparent, and little strip on the top is drawn in simple white. See the screenshot.

### Configuration
**Operating system:** Window 10, Version 1803, Build 17134.48

**Version of Telegram Desktop:** 1.3

**Used theme**: The hell is this?..

![image](https://user-images.githubusercontent.com/3617951/40960640-0c225f26-68a9-11e8-901d-b6f6f947c712.png)

**Comment by invised** [comment]
I am also experiencing this issue after upgrade to Window 10 Build 17134

Worth noting that I have two monitors and for me this issue appears only after moving the window to the second monitor and trying to maximize it there, after that the issue is present independent of monitors, unitl full Telegram restart via tray

Also when this little gap appears at the top, window buttons are shifted to the right, and the whole window gets shifted a bit underneath OS taskbar (but only on second monitor)

Very frustrating bug :(

**Comment by mmatrosov** [comment]
> Worth noting that I have two monitors and for me this issue appears only after moving the window to the second monitor and trying to maximize it there, after that the issue is present independent of monitors, unitl full Telegram restart via tray

Yes, exactly the same for me!

**Comment by phpony** [comment]
Fyi try 1.3.0, it was free of this bug for me.

**Comment by mmatrosov** [comment]
Same problem for me in 1.3.

**Comment by phpony** [comment]
Also same problem with Discord app.

**Comment by stek29** [comment]
#4649
