### ISSUE TITLE
Attempting to download a certain file from "Saved messages" crashes the client

### ISSUE THREAD

**Issue by VioletGiraffe** [telegramdesktop/tdesktop#4799]
I have saved the attached file ("tiff") in my "Saved messages". As I attempted to download it, the client would crash every time (Right click -> Save File As...)

OS: Windows 10 x64
Client version: 1.3

Downloading this file is possible with no problems in Telegram X on Android as well as via the web client.

P. S. Unzip the file before testing (GitHub limitation - can't attach a file without extension).

[tiff.zip](https://github.com/telegramdesktop/tdesktop/files/2071089/tiff.zip)

**Comment by john-preston** [comment]
@VioletGiraffe Can you try the latest alpha version from https://desktop.telegram.org/changelog#alpha-version ? If it crashes, it should offer you to send a crash report when you relaunch the app. Does it offer to send crash report? If so, please send it and copy "Your report tag" from the reporting window here. Thanks.

**Comment by VioletGiraffe** [comment]
Sent.
19628a33-a990-4501-9efa-517b39d009c7

**Comment by john-preston** [comment]
@VioletGiraffe That's a common but strange backtrace for the crash report. It happens somewhere deep inside Windows open file path dialog, I don't know what causes it :(

What version of Windows do you use — Windows 10?

Do you have "Don't ask download path for each file" checked or unchecked in Settings?

What download path is set in Settings?

When exactly does it crash? When you click the file (the download arrow or the "body" of the bubble, where the file name is located)? Or maybe you right click it and press Save As? Or something else?

**Comment by john-preston** [comment]
@VioletGiraffe Does it happen exactly (and only) with this file? I would like you to test six different files. Create them in some folder, then send them from that folder to your saved messages, then delete those files from your folder (so that they will be non-downloaded-yet once you relaunch Telegram Desktop).

Can you try a couple of times this click on "Save file as..." (even without actual saving, just to see if it crashes or shows the choose file name dialog box correctly) for:

1. Your problematic "tiff" file.
2. Some other simple text file (with "test" content, for example) without extension.
3. Some other simple text file (with "test" content) with .diff extension.
4. Some other simple text file (with "test" content) with .txt extension.
5. Your problematic "tiff" file after adding .diff extension to it.
6. Your problematic "tiff" file after adding .txt extension to it.

Thank you.

**Comment by VioletGiraffe** [comment]
I can no longer reproduce the crash, possibly because I rebooted Windows since then. I guess this may not have been a Telegram bug after all. Thanks for looking into it.
