### ISSUE TITLE
Custom XKB keybind (AltGr+j → Backspace) not working consistently

### ISSUE THREAD

**Issue by ayekat** [telegramdesktop/tdesktop#4812]
### Steps to reproduce
1. Map `AltGr`+`j` to `BackSpace` in X11 (e.g. with a [custom XKB layout][1] or `xmodmap`);
2. Launch telegram-desktop;
3. Focus a text input box in a conversation or in the group creation pop-up menu;
4. Type some text, then press `AltGr`+`j`.

[1]: https://gitlab.com/ayekat/PKGBUILDs/blob/ddc454e193e147584efee7ac6f2bbfa3db6504e6/ayekat#L18

### Expected behaviour
Text should be deleted as if `BackSpace` was pressed.

### Actual behaviour
Nothing happens (as if no key was pressed at all). Pressing the "real" `BackSpace` key works fine, though.

Interestingly, a similar keymap (`AltGr`+`k` mapped to `Delete`) works fine everywhere.

More interestingly, `AltGr`+`j` works fine in the search box in the upper left corner of the interface.

### Configuration
**Operating system:**
Arch Linux

**Version of Telegram Desktop:**
1.3.0-1

**Used theme**:
The default one.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by ayekat** [comment]
Yes, with tdesktop 1.9.8, this is still the case as described above.

(the up-to-date X11 keyboard layout used is now [this one][1], but it's essentially still the same mapping)

[1]: https://gitlab.com/ayekat/PKGBUILDs/blob/d17110aa3940ab080e5f0157415f944fa46b85eb/ayekat#L38

**Comment by ilya-fedin** [comment]
Can you reproduce this with other Qt 5 apps (VLC, qBittorrent for example)?

**Comment by ayekat** [comment]
Tried in VLC and Qutebrowser. I can't reproduce this issue there.

Note that even in Telegram, it works fine in some cases. It's mostly the chat text input box where it misbehaves.

**Comment by ayekat** [comment]
*(bump)*

**Comment by ilya-fedin** [comment]
> Tried in VLC and Qutebrowser. I can't reproduce this issue there.
> 
> Note that even in Telegram, it works fine in some cases. It's mostly the chat text input box where it misbehaves.

I found that these ones are using QLineEdit, just like search field in Telegram, while chat field is based on QTextEdit (since it's a WYSIWYG), they have different key press handling:
https://github.com/qt/qtbase/blob/5.15/src/widgets/widgets/qwidgetlinecontrol.cpp#L1881-L1908
https://github.com/qt/qtbase/blob/5.15/src/widgets/widgets/qwidgettextcontrol.cpp#L1276-L1291

So this seems to be a Qt bug

**Comment by ilya-fedin** [comment]
Workarounded by https://github.com/desktop-app/lib_ui/commit/b5fb343d6cea52df8cde00e8e3ca1008c05e4589

**Comment by ayekat** [comment]
Thank you for the reply!

So I guess (based on the timestamps of commits here and in lib_ui), I can expect to see the effects maybe with 2.5.3 or 2.5.4?

**Comment by ilya-fedin** [comment]
yeah, 2.5.3 should work

**Comment by ilya-fedin** [comment]
Please note that the main reason of the workaround is #2199, so I recommend to report the problem to Qt so that the problem won't appear if they fix #2199 and something happen so that workaround would removed (they may add some new keybindings with alt, users could create issues about that and workaround will be removed in that case since this is an Qt's undocumented incompatibility with such tools rather than real bug)

**Comment by ayekat** [comment]
OK, I'll direct this to Qt then.

Thanks!
