### ISSUE TITLE
gsl::not_null compile errors with newest GSL

### ISSUE THREAD

**Issue by vitlav** [telegramdesktop/tdesktop#4857]
After commit https://github.com/Microsoft/GSL/commit/cb2d1af89afb76bf50efe8e068c5ea1fc2872274
in GSL I got follow errors:
Telegram/SourceFiles/ui/twidget.h: In member function ‘bool TWidget::inFocusChain() const’:
Telegram/SourceFiles/ui/twidget.h:331:31: error: could not convert ‘(const TWidget*)this’ from ‘const TWidget*’ to ‘gsl::not_null<const QWidget*>’

Telegram/SourceFiles/boxes/abstract_box.h: In member function ‘gsl::not_null<BoxContentDelegate*> BoxContent::getDelegate() const’:
Telegram/SourceFiles/boxes/abstract_box.h:191:10: error: could not convert ‘((const BoxContent*)this)->BoxContent::_delegate’ from ‘BoxContentDelegate* const’ t
o ‘gsl::not_null<BoxContentDelegate*>’
   return _delegate;
          ^~~~~~~~~

and so on

**Comment by john-preston** [comment]
@vitlav Latest GSL is fucked up =(

**Comment by john-preston** [comment]
@vitlav They've willingly made a breaking change that I think is a huge kick for not_null adoption in existing project by making its constructor explicit. So that you can't just pass a pointer (including just taken address of an existing object!) to a method, that wants not_null, you must explicitly construct it.

I think this makes everything verbose as hell with tons of boilerplate and doesn't help anything. But they're the boss. I guess I'll have to stick for v1.0.0 tag on Microsoft GSL for now and then maybe fork-out my own not_null, either way there were some strange things in the old one for me, that were not even commented: https://github.com/Microsoft/GSL/issues/604

**Comment by vitlav** [comment]
Just closed or fixed?

**Comment by john-preston** [comment]
@vitlav they rolled that change back, because it was too breaking even for Microsofts own codebase, but no tagged release with it yet. When the new tagged release will happen it should work fine. Till then v1.0.0 works fine.

**Comment by john-preston** [comment]
@vitlav Commits after microsoft/GSL@9ff6e19 should work fine, but I didn't test it.
