### ISSUE TITLE
block contacts on telegram desktop

### ISSUE THREAD

**Issue by fatmoos** [telegramdesktop/tdesktop#488]
how can i block a contact on telegram desktop

**Comment by Geobert** [comment]
+1 
seems it is not yet implemented

**Comment by netsurfer912** [comment]
just had the painful experience of discovering that there is nothing related to blocking. please add, this is important.

**Comment by Innomen** [comment]
I can't find it on the android either. Wtf :P

**Comment by ppparadox** [comment]
Oh yes there is on android. Open a conversation, click on the contact's name, then on the 3 dots on the top right corner -> "Block".

**Comment by Innomen** [comment]
Ohhh there it is. Ok thanks hehe.

**Comment by Mindstormer619** [comment]
@ppparadox Blocking on Android does not block from the desktop client. I have first-hand experience of this.

**Comment by minishz** [comment]
PLEASE add this feature!

**Comment by Mafste** [comment]
With the recent bot spam, I consider this my no1 feature request.
It's available in the mobile apps so the desktop app is basically not feature complete at the moment.

**Comment by Mindstormer619** [comment]
Why hasn't this been made yet, I wonder. @telegramdesktop, pls :sob:

**Comment by foxmajik** [comment]
It appears to have been removed from the Android app.

There's no longer a "block" option under the ... menu.

**Comment by pouriyaGhasemi** [comment]
sign in to telegram by browser. "https://web.telegram.org"
select the user that u want to delete. in top bar click on name of user.
click on more...
and last click block user.

**Comment by foxmajik** [comment]
@pouriyaGhasemi The problem was not reported against the web app.

And this doesn't fix the other problems I mentioned.

**Comment by pouriyaGhasemi** [comment]
@foxmajik 
Of course. 
someone don't have smartphone and just use desktop app.
if use desktop app.you can access to web app in 1 minute. and can block a user.
sorry. i cant write English well :-)

**Comment by auchri** [comment]
Implemented in 0.8.49 dev

**Comment by niklas-heer** [comment]
Does this feature block the user only for me, or is the user also blocked for others in a group chat?

**Comment by foxmajik** [comment]
Telegram is actually missing a couple of essential control features.

I need the ability to ban someone from chats so they don't invite themselves right back after being kicked.

This situation causes me to have to invalidate the link to the chat I have shared all over various places and to lose potential interest in my chat.

The other essential feature is the ability to block a person *in a specific chat.*

Maybe I don't want to see someone's messages in the My Little Pony chat because they're a drama hound, but I want to see them in the Telegram Desktop Client chat where they have valuable input.

Or even blocking people in chat groups at all! When I block someone it only blocks private messages. I still see their chat.

Here's another scenario where this is essential:

A spammer joins the chat. They begin text flooding. You kick them out. They invite themselves right back in. You kick them out again. They invite themselves back and resume flooding.

This has happened on multiple occasions and has caused huge abandonment of formerly large chats.

The ability to ban OR mute the spammer would be useful. Either or both.

**Comment by Mindstormer619** [comment]
@foxmajik You might want to check out [Liberbot](https://telegram.me/liberbot) or other such chat group admin functionality bots that have cropped up over time in Telegram.

**Comment by foxmajik** [comment]
Thanks @Mindstormer619.

I've been getting a lot of argumentative pushback from devs on this project.

It's nice to see a helpful comment with useful information.

**Comment by Mindstormer619** [comment]
@foxmajik Well, Liberbot goes down from time to time because as an administrator bot, it has to handle a lot of spam from some idiots who have nothing better to do in life. I believe [BotMeNot](https://telegram.me/BotMeNot) and [Teleseed](https://telegram.me/TeleSeed) work as alternatives, though they have their own share of problems. As far as I am aware, Liberbot is the most polished out of them. Downtime is usually short of up to half an hour.

Liberbot downtime and bugs can be reported on the Liberbot Meta group. I don't have the public group URL to it but I can add you manually if you send me your Telegram public handle. Mine is the same as my Github username, so if you don't want to put it out here you can send it there :smiley: 

Happy to help :)

**Comment by foxmajik** [comment]
@Mindstormer619 

If people are struggling to maintain bots that perform these functions they are obviously functions that are needed by the community that uses the software and the API.

This seems like a ridiculous way to manage a problem that could more easily be fixed in the software / API itself.

**Comment by Mindstormer619** [comment]
@foxmajik Well I'm not sure if they had anticipated this particular use of Telegram. The original intent of the public group URLs was for easy group migration. Right now it's actually a lot to code in, especially considering that it has to be done on the server and ALL the different app versions would need updates matching the same, involving more testing and reviewing, all involving time and effort. From what it looks like, right now they're trying to focus on more core features. Of course, we never know how things might change in the future. For all we know they might implement it soon.

Of course, in response to spam they did make a "Report Spam" button appear in all new chats and group chats, so you could get spammers booted from Telegram as a whole :)
