### ISSUE TITLE
Delay of replacement in list after mouse move.

### ISSUE THREAD

**Issue by smasharov** [telegramdesktop/tdesktop#4888]
Sometimes I want to select one chat in the list. I move mouse pointer to it. While clicking mouse on the needed item, item is replaced and I select wrong chat, because of replacement just a moment before click. It is more annoying if I wrongly selected channel with a hundred of unread messages, that I planned to read later, but they are all already marked as read. #775

It is happening because I got new message in the chat currently lower in the list than chat needed by me.

I think it should be delay before replacement of list during several seconds after I move mouse pointer on a list item.

**Comment by enchained** [comment]
Oh, I know that situation too well. What is you version? Cause just yesterday I "mis-clicked" on a channel and it wasn't marked as read due to the new feature/bug from the counter issue.
Also, I want to warn you - even when the counter doesn't reset on the tdesktop, it does reset for me in telegram x most of the times when I open the channel in tdesktop.

**Comment by john-preston** [comment]
@enchained It is reset on the server, but tdesktop buggily shows it as unread once again. If you restart the app to reload the data it will be read already.

**Comment by stek29** [comment]
#1504
