### ISSUE TITLE
Text Box Clearing itself while typing

### ISSUE THREAD

**Issue by teynav** [telegramdesktop/tdesktop#4922]
### Expected behaviour
Unhindered Typing of message

### Actual behaviour
Sometimes while typing a message whole Text box gets automatically cleared and now have to type message again

### Configuration
**Operating system:** Linux Mint 19 (Tara) on Kernel 4.15.0.23 , Windows 7 and Windows 10

**Version of Telegram Desktop:** 1.3.9

**Used theme**: Dark and Normal both

<details><summary><b>Logs</b>:</summary>
Insert logs here (if necessary)

</details>

**Comment by Demetri0** [comment]
I and all my friends have the same problem for about two years.
Ubuntu 18.04/19.04
Telegram Desktop Version: 1.5.11 The latest in the repository. (Maybe it's reasonable to ping Maineiner for update it)

I notice a correlation with changing the keyboard layout

**Comment by AngelBeast12** [comment]
I agree with **Demetri0**. I have the same problem.

**Comment by Demetri0** [comment]
I've upgraded to Ubuntu 19.10 and telegram 1.8.8 bug still reproduses

**Comment by Aokromes** [comment]
i suggest you to download official telegram desktop it's version 1.8.15

**Comment by Aokromes** [comment]
no answer after months, closing, if this bug is still valid, try official version, not some distro package.

**Comment by 23rd** [comment]
Actually, it's still a problem. If I understand correctly, it is related to the drafts with poor connection quality.

**Comment by Demetri0** [comment]
> Actually, it's still a problem. If I understand correctly, it is related to the drafts with poor connection quality.

If that's so - It would be fair enough for me to have an option to disable drafts, as it is useless functionality for me.

**Comment by Demetri0** [comment]
For experiment I tried to limit my connection (via `wondershaper`) to 128Kbps/32Kbps/2Kbps and type while a 15 minutes, seems like there are no difference... bug happens sometimes but it is not depend on network speed.

**Comment by Demetri0** [comment]
Shouldn't be closed

**Comment by ILoveSkilledCoders** [comment]
I don't understand why this isn't being fixed.

I'm not even on Linux yet. Win 7.

I opened a bug report & someone pointed me to here.

**Comment by MajFontana** [comment]
Please fix this. I've been experiencing it in the desktop app for more than a year. It doesn't occur consistently, but it does occur frequently, and when it does, it's very frustrating. I often have to resort to an external text editor when writing any text longer than a few sentences.

Best advice I've been given so far was to disconnect my mobile phone from the internet, because the mobile app could supposedly be causing the bug, but I haven't got a chance to test it yet, because I often have my PC connected to my smartphone's hotspot. Besides, it sounds like a rather inconvenient workaround.

I'm using Windows 10 on my desktop and Android 9 on my mobile. The mobile data connection seems stable with a bandwidth of 25/20 mbps. The problem occurs with cable internet as well.

**Comment by ILoveSkilledCoders** [comment]
> Please fix this. I've been experiencing it in the desktop app for more than a year. It doesn't occur consistently, but it does occur frequently, and when it does, it's very frustrating. I often have to resort to an external text editor when writing any text longer than a few sentences.
> 
> Best advice I've been given so far was to disconnect my mobile phone from the internet, because the mobile app could supposedly be causing the bug, but I haven't got a chance to test it yet, because I often have my PC connected to my smartphone's hotspot. Besides, it sounds like a rather inconvenient workaround.
> 
> I'm using Windows 10 on my desktop and Android 9 on my mobile. The mobile data connection seems stable with a bandwidth of 25/20 mbps. The problem occurs with cable internet as well.

It's not due o the phone. I'm on PC & it happens frequently. And I'm on Win 7, so it has nothing to do with Win 10 either.

**Comment by LaG1924** [comment]
I also have this problem and hope to get this bug fixed as soon as possible. The details of my case will follow, if it is useful:
I have been using Telegram for over 5 years. However, the problem started over the last year.
About two years ago we changed the ISP, the throughput increased, but packet losses also appeared (constantly from 1% to 30%).
All my devices (desktop, laptop and phone) are connected to the same network.
Mostly I only use desktop and laptop, so the problem only reproduces on those.
Other users of the same Wifi network also complain about this problem, although they have it less often (but they also use the telegram less often).

**Comment by vak** [comment]
dear developers, could you please add some clear tags to the very, very frustrating bug, e.g.: **confirmed, urgent, stale** ?

Look, maybe it is just not seen by developers, albeit this bug is annoying since June 2018. 

Duplicate issues are created and closed. Is it possible to prioritize this bug somehow?

**Comment by john-preston** [comment]
@vak I can't reliably reproduce that :( Although I did see it several times on my own. I'll ask for logs from someone who faced it recently with debug logs enabled and who's willing to share them.

**Comment by Kinrany** [comment]
Typing something in a chat and then switching to the main menu seems like a good way to trigger draft saving.

**Comment by Demetri0** [comment]
I just want to say that Draft feature is one big bug in my opinion. (sorry for being straightforward)

Drafts, in my opinion, should not be shared between devices. They are overriding themselves, they produce a very annoying bug with clearing textbox. There is no benefit to having such an implementation of drafts.

I understand that my point of view is radical, and there are people who find it helpful in some cases, but could it be an option that I can untick in settings?

**Comment by Kinrany** [comment]
I too think that making drafts local to each client is preferable to the risk of losing data. Saved messages cover all the cases where you'd use drafts to move between devices.

There could be an extra button for using a draft from another device that is only shown when the text box is empty.

**Comment by RememberTheAir** [comment]
I can't count the number of times cloud drafts saved my ass from losing long texts so hopefully this gets fixed on tdesktop instead of disabling the sync feature, since tdesktop is the only client affected by this problem to such an annoying degree

**Comment by vak** [comment]
Drafts is a great feature, but -- as we see -- very hard to implement. 

Being implemented in the current form it _kills_ underlying _fundamental_ feature of any messenger -- "you can type reliably". Currently one can't type reliably. 

The bug puts the limbic system of my brain on fire, when I carefully type in the math formula in the message and suddenly it gets instantly removed with no chance to undo... aaaargggh.

If draft feature is too difficult to implement -- let us disable (I'll do!) before it gets fixed and then I'll be first to re-enable it back!

**Comment by john-preston** [comment]
@vak I hope I'll be able to fix it in the next version.

**Comment by vak** [comment]
@john-preston many thanks! BTW, if you know the source code, then perhaps you could tell us where the essential part of draft sync code is located? Maybe we could help somehow?

I was never asked, but my gut feeling says that it has smth to do with timestamps, which are _never_ accurate. Keeping clocks in sync is rather unrealistic assumption/requirement. If so, then the solution should be shifted from being time-dependent towards being dependent on "inner clock of message evolution"

Like "I", "I ", "I t", "I ty", "I typ", "I typo", "I typo**\b**", "I typo**\b**e", ... 

where deletions are also a part of the whole story to avoid the wrong (mis-)matches from different time-points.

**Comment by Demetri0** [comment]
Thank you a lot. 4 years we lived with this bug... I hope finally it fixed ^_^

**Comment by vak** [comment]
@Demetri0 @john-preston I saw the sources in their new form. 

To be honest, when I am seeing `UnixtimeFromMsgId` kept in code, I am quite skeptical on successful fixing (maybe I am wrong though!). It still looks like the whole story is very much depending on the _very accurate time sync_ between different peers. It doesn't look as a robust basis...

**Comment by john-preston** [comment]
@vak No, it does not. It uses the reply of "save draft to server" request to know the exact timestamp that was after the saving done on the server.

Server includes a timestamp in all draft updates, so if we ignore all the draft updates with timestamp below or equal the real response timestamp from the server, we will never apply our own old draft saved, even if by some reason server will send this update back to us (which was happening in case getDifference was invoked with a bad timing).

**Comment by john-preston** [comment]
@vak So when we count "UnixtimeFromMsgId", we use the resulting "unixtime" not for comparing it with our local "unixtime" (which could be out of sync) but with "unixtime" of the same server, that processed our request for draft saving (and saved it together with the draft).

**Comment by vak** [comment]
@john-preston many thanks for your answers! 

Even if we ignore local time the setup still looks vulnerable to me.

usually there are many server instances. Even here we get another source of time dissync. If this dissync is greater than the interval of the two consequent request "save draft to server" then we could (probably) get trapped in this situation again. 

Since the "save draft to server" request could come from different clients (e.g. one from PC and another one from the smartphone) the time delta between them could be arbitrary tiny.

Maybe I am wrong and missing smth. (I don't try to enter endless arguing, just am letting you know my thoughts and doubts !)

**Comment by john-preston** [comment]
@vak This issue is not about draft syncs between different devices (when you type something from your smartphone, then something from your desktop, in the same chat). This is indeed not very predictable.

If you send a draft from your phone, it indeed will be applied on your desktop. But the original issue (and the problem that was fixed here) was while using a single device all the time. It was you just typing on a not-so-good connection to Telegram APIs and suddenly getting last parts of your text erased (applying your own draft, from the same device, later in time, because server sent you this update "in case you missed it").

And for that issue the fix should work at all times.
