### ISSUE TITLE
[bug] Action "Delete message" doesn't deletes the message on remote side

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#499]
When deleting the message(s), deletes only message(s) on my (local) side, but not on remote.
Remote participant(s) still see the deleted message(s).

Linux Mint, Mate 64bit, Telegram v. 0.7.16

**Comment by joshery420** [comment]
I could be wrong, but I'm pretty sure that the synchronized delete (that is, deleting a message for both local and remote) is a feature of Secure Chats, not all conversations.

Deleting a message in a regular chat simply removes it from your local chat log, as you've seen, which I believe is correct by design.

https://telegram.org/faq#q-how-are-secret-chats-different

**Comment by ezdev128** [comment]
@joshery420 yes, maybe you are correct. But it is still unclear what the behavior in plain conversation.
Probably, Telegram team should explain it well at FAQ.

**Comment by Gruenbaer** [comment]
See [https://github.com/telegramdesktop/tdesktop/issues/1284#issuecomment-268943252].
It is senseless to call a function delete if it doesn't delete, or just deletes in some cases...
