### ISSUE TITLE
Secret chat

### ISSUE THREAD

**Issue by Marocco2** [telegramdesktop/tdesktop#5]
Are you going to add this feature? Thanks :)

**Comment by SVSagi** [comment]
Everyone, I told about desktop telegram application did ask for secret chat, after they installed it. Still hoping for it.

**Comment by SVSagi** [comment]
Everyone, I told about desktop telegram application did ask for the secret chat option, after they installed it. Still hoping for it.

**Comment by electricessence** [comment]
So it sounds like one of the challenges for this is that a secret chat can only happen from one client to another and can't be synchronized across multiple clients.  I'm fine with that!  Even if a secret chat can only exist for the current session!

This is a great open source implementation.  I would like to contribute.  How can I help?  I would prefer to discuss a plan instead of forking and doing my own thing.

**Comment by stormcloud-gnu** [comment]
Yeah, please add this feature. Most users agree that this is much more important than anything else.
I chose telegram mainly because of the desktop client AND the secret chat, and it's really a shame that i can't have both at the same time. I don't want to move to another app because except from that issue, telegram is just PERFECT; it works like a charm.

**Comment by Marocco2** [comment]
Could you, @telegramdesktop , reopen this issue, so new users don't make requests about secret chats, please? Thanks :)

**Comment by tuxflo** [comment]
I also think that secret chat should get the highest priority. I can't tell my friends that they have to use the commandline version (telegram-cli) for secret chats.

Thanks a lot.

**Comment by hydrosIII** [comment]
Secret chats are currently implemented in the OS X client. Also they are implemented in telegram-purple and cutegram, other two telegram clients. And the telegram-cli for linux.

https://github.com/majn/telegram-purple
https://github.com/Aseman-Land/Cutegram

**Comment by jefferai** [comment]
I have the OSX client, as does another user. Both of us are on 0.7.10. The other user has an option in the compose drop-down to make a secret chat; I don't. No idea what the issue is.

**Comment by Someguy123** [comment]
@jefferai There are two versions, the cross-platform Tdesktop which has no support for secret chat, and there's also the app store version which DOES have secret chat (but only works on OSX).

You're probably using the tdesktop

**Comment by zaxebo1** [comment]
with reference to https://github.com/telegramdesktop/tdesktop/issues/363
the author of tdesktop replied that  "Secret chats are hold only on one client device and can't be synced between them and they stay more secure remaining on the mobile." 
my reply>> So be it. Even if secret chats can be held only one client device without syncing, still with that limitation it will be great feature to have . Everybody is just dying to have this feature in TDesktop.
Also, When native OSX version client can have this feature, then why not TDesktop? The same refutation logic should apply to both the clients.
IMHO, this is the topmost requested feature in around my all know users group. If this secret chat functionality in TDesktop comes , then telegram usage will beat whatsapp in very short time. This should be prioritized above any other feature request, in my humble opinion.

**Comment by zaxebo1** [comment]
also note that the (unofficial) client "for linux" - cutegram also **supports secret chat**
see http://aseman.co/en/products/cutegram/

It would be really really great if we have some client for MS-Windows too , which supports secret  chat

**Comment by intika** [comment]
http://aseman.co/en/products/cutegram/
Multiplatform client with secure chat

**Comment by zaxebo1** [comment]
I have already mentioned this third party telegram client "cutegram" with support for secret chat.
 I do not know that when "third party apps" can implement this, then why "official client" can not implement this heavily requested/waited feature? 
The whole single point benefit of "telegram" over "whatsapp" for the end user is secret chat, otherwise there are infinite number of apps for chatting. They need to take this secret chat demand (on desktop client)  very seriously.

**Comment by intika** [comment]
You are absolutely right zaxebo !
cutegram is full of features but seems a little buggy comparing to official application, i think they have a lot to do... but you are exactly right it does not make sens at all ! 
linux get more flexibility with pidgin plugin, also mac have a similar solution... 
personally i don't like the feeling of the computer client, they are making same mistake as windows 8, "it's not a tablet !!! it's a pc !!!" 
i just have one hope, the linux pidgin plugin released to windows, it's not yet the case... once we will get that we could use it in a nice way on windows like other chat client... (that plugin support secret chat)
at least it could be nice if we have secret chat on the web version also... 
... 
but let's be honest don't forget that the app is intended for phone at the first place, and it do his job, secret chat for computer would be awesome but... any way...

**Comment by wp9015362** [comment]
Hello,

I was about to use Telegram Desktop and expected it to support secret chats.

But then I noticed that it currently does not support secret chats.

That is extremely unfortunate.

Please add support for secret chats to Telegram Desktop and please make it a number one priority.

This is really needed IMHO (and apparently others seems to agree).

Could you please make it happen?

It would be much appreciated.

Regards

**Comment by animalillo** [comment]
A lot of people it's expecting secret chats, I just keep wondering why it's not implemented as it's one of the most requested features.
And it's a core part of the telegram, which made me use it in the first place (and a lot of people I know).

**Comment by mikeadamz** [comment]
Pretty bummed that there's no secret chats on the desktop app.. @telegramdesktop

**Comment by rezapc** [comment]
+1

**Comment by turboexe** [comment]
+1. taking into account that OS X telegram allows for secret chats.

**Comment by caizixian** [comment]
@turboexe It's different from this cross-platform version.

**Comment by turboexe** [comment]
@caizixian sure, but I'm pretty sure that win/linux allows for the same network/crypt functionality as OS X does. may be implementations would differ for different operating systems but the programming community has lots of patterns to hide it inside.

**Comment by caizixian** [comment]
Totally agree with you.

**Comment by caizixian** [comment]
@turboexe It's the key function and should be implemented asap.

**Comment by brasslan** [comment]
Why does Tdesktop exist???  I will tell you that I downloaded a copy because web.telegram.org won't do secret chat.  If Tdesktop doesn't do secret chat, then I will just use the web app instead.  I'm very disappointed in the 'official' desktop app for this shortcoming!  I was expecting to have new encryption keys on the desktop client and therefor would not be able to sync chats between phone and PC.  That would be fine, and exactly what I want because the secret key on my phone should NEVER leave that device.  The desktop client should be able to create and store some encryption keys that will never leave my desktop.  I should be able to delete and create new keys at will.

**Comment by zaxebo1** [comment]
Never seen such an insensitive project manager. Goodbye "telegram", hello "line". Why to keep two three messengers on my mobile and desktop . Atleast "line" can do voice calls too and hidden chat feature. Line also has desktop client. Already whatsapp has got voice calling too. Anyway, if secretc aht does not come desktop app, i see no reason why telegram should occupy my diskspace.

If telegram managerment can not understand and be concerned about what community wants deeply, then hell with this project and hell with its insensitive management. Goodbye

**Comment by crossroads1112** [comment]
Bump

**Comment by gabrielbauman** [comment]
Would a patch be accepted to add support for this?

I don't care about syncing for the moment, just the ability to do a secret chat from my desktop. It was quite surprising to start inviting people to use Telegram only to start getting complaints... "why can't we do secret chats when not on our phones?"

**Comment by intika** [comment]
Following this closed issue 
and 
https://github.com/telegramdesktop/tdesktop/issues/118

i created a new issue to ask dev deeply about that otherwise i think i'll be looking for a real privacy concerned chat app...

**Comment by Mosrite** [comment]
I agree! It's no problem that this feature wasn't implemented from the start. But the fact that the developers aren't even willing to look into it even though this is most probably the feature most asked for becomes more and more a deal breaker.

**Comment by mikeadamz** [comment]
Actually, Secret chats aren't supposed to be transferred between clients.
It's because the encryption keys are device specific and one devices keys
can't decrypt another devices chats.

Q: How are secret chats different?

Secret chats are meant for people who want more secrecy than the average
fella. All messages in secret chats use end-to-end encryption. This means
only you and the recipient can read those messages — nobody else can
decipher them, including us here at Telegram. Messages cannot be forwarded
from secret chats. And when you delete messages on your side of the
conversation, the app on the other side of the secret chat will be ordered
to delete them as well.

You can order your messages, photos, videos and files to self-destruct
<https://www.telegram.org/faq#q-how-do-self-destructing-messages-work> in a
set amount of time after they have been read or opened by the recipient.
The message will then disappear from both your and your friend's devices.

*All secret chats in Telegram are device-specific and are not part of the
Telegram cloud. This means, you can only access messages in a secret chat
from their device of origin.*


https://www.telegram.org/faq#q-how-are-secret-chats-different



On Mon, Mar 30, 2015 at 11:43 PM, Gabriel Bauman <notifications@github.com>
wrote:

> Would a patch be accepted to add support for this?
>
> I don't care about syncing for the moment, just the ability to do a secret
> chat from my desktop. It was quite surprising to start inviting people to
> use Telegram only to start getting complaints... "why can't we do secret
> chats when not on our phones?"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/5#issuecomment-87964782>
> .
>



-- 
Mike Adams <mike.adams@unix-security.net>
Cell: 916.538.4013

"Any intelligent fool can make things bigger, more complex, and more
violent. It takes a touch of genius -- and a lot of courage -- to move in
the opposite direction."
-Albert Einstein

**Comment by Mosrite** [comment]
Wouldn't it be possible to transfer private keys from one device to another? Like it is possible with PGP keys?

I see non-secret chats basically as a temporary solution until end-to-end encryption is implemented per default and end-to-end encrypted chats are accessible from every device (at least if the key is transfered manually). If Telegram doesn't work on this, I would finally switch to TextSecure as soon as their browser-based client is ready.

I think the Telegram team should consider a bit more what their "selling proposition" is here (even if they don't actually sell anything). Whatsapp and Facebook Messenger offer a significantly bigger user base. Messenger is accessible from basically every device and Whatsapp at least offers a browser-based client. So the cloud component isn't really a unique feature of Telegram (anymore).
Telegram's secret chats are not default and they are device-specific which means many people don't use them regularly or even don't use them at all. So, we can conclude that most messages sent with Telegram are not end-to-end encrypted and thereby not as secure and privacy friendly as most of us would like them to be. The only "unique" thing that Telegram offers at the moment is not belonging to Facebook which, if you ask me, is definitely not enough in the long run. People (and even the non tech savvy ones) are looking for an IM that finally offers a high level of usability and privacy that works cross-plattform. Currently, Telegram's chances would be very good to take that position if they would focus more on secret chats, especially their security and their usability. Instead, they introduce a bunch of new stickers every month or so...

**Comment by mikeadamz** [comment]
The reason secure chats are not synced is that they do not exist on the
server. The messages are sent between specific devices via the telegram
servers, and then discarded. In order for them to be synced, the messages
would need to be stored on the telegram server indefinitely. Storing the
messages means they (telegram) can be ordered to hand them over to the
court for civil or criminal proceedings.

Additionally, if your private keys never leave your device, they can never
be intercepted and used to decrypt your private communications. I know it
seems overly paranoid, but isn't that kind of why you want secret chats in
the first place?

-Mike

On Tue, Mar 31, 2015 at 10:29 AM, Mosrite <notifications@github.com> wrote:

> Wouldn't it be possible to transfer private keys from one device to
> another? Like it is possible with PGP keys?
>
> I see non-secret chats basically as a temporary solution until end-to-end
> encryption is implemented per default and end-to-end encrypted chats are
> accessible from every device (at least if the key is transfered manually).
> If Telegram doesn't work on this, I would finally switch to TextSecure as
> soon as their browser-based client is ready.
>
> I think the Telegram team should consider a bit more what their "selling
> proposition" is here (even if they don't actually sell anything). Whatsapp
> and Facebook Messenger offer a significantly bigger user base. Messenger is
> accessible from basically every device and Whatsapp at least offers a
> browser-based client. So the cloud component isn't really a unique feature
> of Telegram (anymore).
> Telegram's secret chats are not default and they are device-specific which
> means many people don't use them regularly or even don't use them at all.
> So, we can conclude that most messages sent with Telegram are not
> end-to-end encrypted and thereby not as secure and privacy friendly as most
> of us would like them to be. The only "unique" thing that Telegram offers
> at the moment is not belonging to Facebook which, if you ask me, is
> definitely not enough in the long run. People (and even the non tech savvy
> ones) are looking for an IM that finally offers a high level of usability
> and privacy that works cross-plattform. Currently, Telegram's chances would
> be very good to take that position if they would focus more on secret
> chats, especially their security and their usability. Instead, they
> introduce a bunch of new stickers every month or so...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/5#issuecomment-88179405>
> .
>



-- 
Mike Adams <mike.adams@unix-security.net>
Cell: 916.538.4013

"Any intelligent fool can make things bigger, more complex, and more
violent. It takes a touch of genius -- and a lot of courage -- to move in
the opposite direction."
-Albert Einstein

**Comment by Mosrite** [comment]
If an organization really wants to read my messages and is powerful enough they just can. They could infiltrate my phone and read the unencrypted messages or steal the key.

For encrypted mails the system works pretty well: Encrypted messages are stored on servers but the server operators cannot read them due to the encryption. The messages can only be decrypted locally by the clients. As long as the users does everything correctly this is pretty secure. (OK, key management for PGP is a mess, but that's another story.)
I have to admit, I don't know whether it is possible to avoid meta data with this system. But: Why not use this "imperfect" but still end-to-end encrypted system for normal chats per default and leave the system that is currently called "secret chats" as additonal opt-in as it is right now?

I'm neither a programmer nor a crypto expert so I don't know which system would work for Telegram and which wouldn't. I'm just saying, technically, it is possible as e-mail uses it and I think XMPP+OTR does so, too.

And as most users have two or even three devices nowadays they most probably would want to keep them in sync. And they already can, e.g. by using Facebook messenger. So why bother using Telegram? This would only make sense if Telegram would offer something special, i.e. end-to-end-encryption that is easy to handle and enabled by default without exception.

**Comment by intika** [comment]
This is not the real question secret chat does not need to be synced... 
other client that offer secret chat on computer work fine, and a secret chat stay where it get initiated (device)

**Comment by zaxebo1** [comment]
@intika : even more the question is that one more official client of telegram **on MacOSX** only - **supports secret chat** .
 But the generic official client written in Qt(for Win/Linux/Mac) does not supports secret chat. And they are giving weird logics for this. If your team yourself can implement it officially for MacOSX special client, then why not for Qt based offical client.

Its so funny.

**Comment by intika** [comment]
@zaxebo1 : they just wont do it
now when it's come to the real why no one know 
will se what the dev answer on #619

**Comment by KenetJervet** [comment]
Sad. I guess the author won't read this thread any more. We may have to look for alternative clients.

**Comment by SvetoslavH** [comment]
+1
I genuinely do not understand how this is not a priority.
Unless you want to mess around with users data, there is no point at all of not implementing secure chats. Emoji improvements are nice, but I don't see how this has higher priority in a messaging app, which claims to be aimed at security.
Annoying and ignorant.

**Comment by jmaris** [comment]
+1 as well. This really is very important

**Comment by PeterDaveHello** [comment]
Any updates? It's one of the most important features of telegram, should have it on desktop! Thanks!

**Comment by Webbrother** [comment]
+1
Secret chats feature must be implemented asap.

**Comment by lgommans** [comment]
+1 for secret chats.

> Secret chats require offline message history and state storage, which is not done at the moment and is not in current plans

Regarding that, offline message caching might be useful (the last 100 or so messages for every contact/group chat is not much, storage-wise). Often enough I have slow Internet (mobile / public hotspot) and loading message history takes a while. Or if the Telegram servers are slow or down.

**Comment by kleuter** [comment]
+1

**Comment by btcid** [comment]
+1 this is ridiculous. i moved from skype & subrosa because of secret chat.

**Comment by labmir** [comment]
a must for me too +1

**Comment by skornev** [comment]
+1

**Comment by sitex-pro** [comment]
I'm waiting for this feature too.

**Comment by syddel** [comment]
Not having secret chat on desktop clients seems absurd. There's no need to worry about syncing between desktop and mobile when secret chat is used. Just make it very clear to users that secret chat is tied to the device.

If you did want to sync secret chats, this is still possible. Just make the first Telegram client send secret chat messages in received to the user's other clients (it will mean syncing all of the user's public keys with all of the user's Telegram instances, but this shouldn't be a problem).

Even without sync, secret chat is the killer feature.

**Comment by Dega704** [comment]
Don't get me wrong; Telegram is a solid messenger overall.  Secret chat, however, is the entire reason why I and pretty much everyone else use it.  We probably wouldn't have bothered trying it otherwise.  I couldn't care less about having sync on secret chats.  Sacrificing convenience for security and privacy is something everyone should understand by now.

**Comment by crossroads1112** [comment]
The fact that the last comment was yesterday, ~9 months after this request was closed should be an indicator of how badly this feature is wanted

**Comment by Marocco2** [comment]
Please, reopen this issue!!

**Comment by animalillo** [comment]
@Marocco2 I dont think the owner of the project does look this issue, tho is one of the most ever wanted and requested features from the users of a program after the windows 8 start menu.

**Comment by PhilippVerpoort** [comment]
I perfectly agree, that secret chats are a must have for any Telegram implementation.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i tried cutegram as somebody suggested. its an ok client but the official one is better. the problem with secret chats on desktop seems to be that mobile devices take priority. so i was unable to start a secret chat from my desktop client to my gf's desktop client. it would go to her phone instead. and if she started one from her desktop, it would go to my phone. so yeah some desktop clients like cutegram support desktop->mobile secret chats if the desktop client initiates the chat. but no desktop->desktop i dont think. for that, clients will need to somehow pick which session to start the chat with. just putting that there for whoever is interested

**Comment by zaxebo1** [comment]
@berrythesoftwarecodeprogrammar :  
It will be great, if you put your observation into cutegram's issues also.
https://github.com/Aseman-Land/Cutegram/issues
Probably someday cutegram may solve this too

**Comment by gloeglm** [comment]
I would love to have a true secret chat with my family

**Comment by gloeglm** [comment]
Is this only lacking in desktop or also in the app versions?

**Comment by animalillo** [comment]
@gloeglm this only happens with this telegram implementation, and noone can understand why, mobile app supports scret chats

**Comment by gloeglm** [comment]
So if everybody is using the mobile app, a fully secure three-way chat is possible?

**Comment by animalillo** [comment]
Nope @gloeglm, secret groups are not available

**Comment by gloeglm** [comment]
Ah, thats what I was asking - are there any plans for implementing that?

2015-09-02 19:16 GMT+02:00 Marcos <notifications@github.com>:

> Nope @gloeglm <https://github.com/gloeglm>, secret groups are not
> available
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/issues/5#issuecomment-137176153>
> .
>



-- 
Michael Glögl
identity: https://keybase.io/mgloegl
email: m.gloegl@gmail.com
phone: +49 176 63887241
linkedin: https://de.linkedin.com/in/mgloegl

**Comment by PhilippVerpoort** [comment]
@gloeglm: Very good question, which I also have been asking myself several 
times. Secure group chats and secure chats to share among different devices 
are an important feature, that is still missing.

However, this is a bit off-topic for this report. I assume this would have to 
be implemented into the API rather than in the individual applications.

**Comment by kleuter** [comment]
Secure group chats and secure sync is not technically possible and will never be implemented. They won't be secure then. Secure chats are only possible between 2 endpoints.

**Comment by 0nse** [comment]
@kleuter I'm not deep in Telegram's home-brewed encryption but "technically impossible"? Couldn't a group chat simply be realised as communications to many different endpoints? So, if I have a group chat between A, B and C and A wants to post message `m` to the group, it would
* `s_1 = encrypt(m, B_pk)` encrypt the message with B's public key
* `s_2 = encrypt(m, C_pk)` and do the same for C. Then, A would
* `send(s_1, B)` send the first secret to B and
* `send(s_2, C)` the second to C.

Both recipients would be able to read the message, which would have been encrypted between 2 endpoints each. Yes, this adds some overhead, but—as far as I don't overlook something—it seems far off from being "not technically possible". If performance really were an issue, secret group chats could be limited to say 50 people.

**Comment by PhilippVerpoort** [comment]
@0nse: Although, this is still the wrong place to discuss, I perfectly agree 
with you.

This may not be possible with the current version of the Telegram API, 
however, the API could be improved to allow for secret group chats and secret 
sync.

In Threema you can do that. Threema is in Germany a well-known competitor to 
Telegram. I must admit, that Threema is actually a lot better than Telegram 
ATM (secret group chats, no binding of accounts to phone numbers -- I have 
absolutely no idea, why Telegram people came to this mad idea of excluding 
people without a phone number). However, Threema is non-free software. 

Nevertheless, I think, Telegram will have no future, if secret group chats are 
not implemented at some time.

**Comment by zaxebo1** [comment]
@PhilippVerpoort 
Threema seems to be good, but has two problems:

1) it has no web or Desktop version like telegram, in case I want to chat without mobile (in case of long long typing and discussion)

2) most important is that , I do not use non-open source software on my android phone. And their client seems to be closed source. Atleast they should open source the client, just Like Telegram.

**Comment by akviol** [comment]
I started to use Telegram yesterday and was very disappointed when found that no secret chat in desktop version for windows. The idea of Telegram was in security from start and they missed it to tataly for win desktop. The published reasons like "it is not high priority" disappointing even more. Guys! Two years! What is hight priority for you then???

It couldn't be an issue due to few sessions, it's easy at least execute termination for all other sessions except one that was confirmed from recipient.

So, it looks we see a simple sabotage of main Telegram's idea.

**Comment by zQueal** [comment]
Without the secret chat feature Telegram is literally no different than any other service based messenger out there...

**Comment by jeifour** [comment]
Really this is important. Telegram is better because it has things like a polished desktop client etc. and having secret chats is also one of the main advantages of Telegram for me. This is really disappointing, I mean that it isn't even considered.

**Comment by vasaka** [comment]
wow, a year passed and still no secret chats.

**Comment by jvoisin** [comment]
On the other hand, it's open-source, feel free to implement it yourself ;)

**Comment by akviol** [comment]
Only client is open-source. To implement such things the server side code is also should be opened.

**Comment by auchri** [comment]
No, it's enough to know which [api functions](https://core.telegram.org/schema) are available and how the [encryption works](https://core.telegram.org/api/end-to-end).

**Comment by zQueal** [comment]
> No, it's enough to know which api methods are available and how the encryption works.

This is insane, and would not, by definition, be encryption. For all intents and purposes, encryption is data security. How is sending information, encrypted or unencrypted, via insecure channels which you know nothing about because they're proprietary data security? Well, it's not. Encryption does not equal trust and trust does not equal encryption.

In addition to that the MTProto encryption standard which is used by Telegram specifically states that its not suited to be used by anything but mobile devices.

To get encryption working reliably on a desktop application a new encryption method and transport protocol would need to be devised which is entirely different from what Telegram is currently using. The time involved is too costly for them to invest in. That's probably why we haven't seen encryption on the desktop application yet.

It's also why I've moved to greater pastures and many, many others are beginning to do the same.

**Comment by auchri** [comment]
> This is insane, and would not, by definition, be encryption. For all intents and purposes, encryption is data security. How is sending information, encrypted or unencrypted, via insecure channels which you know nothing about because they're proprietary data security? Well, it's not. Encryption does not equal trust and trust does not equal encryption.

The guys from Cutegram implemented also the secret chat without knowing the source code of the server ;)

**Comment by Someguy123** [comment]
@auchri @zQueal Correct. CuteGram has the secret chats on Windows, and the official OSX client has also had them since forever.

**Comment by akviol** [comment]
Totally agree!!! I think they have all code ready for Windows too and I'm 100% sure with that. But always we have some stupid politics and stuff that we not aware of. Maybe even some hidden agreements with concurrents...

**Comment by jeifour** [comment]
"and the official OSX client has also had them since forever" Are you speaking about MAS version because I use the normal Desktop client on OS X (at least sometimes, I'm mostly on Linux) and I don't have secret chats. I refuse to use "App Stores", regular package managers are superior.

**Comment by auchri** [comment]
@jeifour This one: https://itunes.apple.com/us/app/messenger-for-telegram/id747648890

**Comment by jeifour** [comment]
@auchri Is source code available? And what are generally reasons to make two different applications that run on the same platform? That is all a bit strange to me.

**Comment by auchri** [comment]
@jeifour Yes, here: https://github.com/overtake/telegram


> One is our native OSX app, the other is the OSX version of our multiplatform client— Telegram Desktop. Both are official. Both started out as unofficial apps by two different developers and vary in design and functionality.

> The OSX app features native OSX design and supports secret chats. Telegram Desktop is optimized for photo and document sharing, as well as sending long text messages. Try both and pick one that suits your day-to-day Telegram usage best.

(From [Telegram FAQ](https://telegram.org/faq#q-why-do-you-have-two-apps-in-the-mac-app-store))

**Comment by Mosrite** [comment]
To all those people talking about technical impossibilities: Maybe it's time to switch to another protocol, e.g. OMEMO. It's E2E-encrypted and is absolutely capable of handling cloud-based chats and muti-device approaches: http://conversations.im/omemo/
I'm not a crypto expert but I think it is even more secure than the current Telegram protocol.

So: No, it is not impossible, other communication services already support it right now. The people who are in charge of Telegram just don't care of improving security and privacy of Telegram. The Telegram protocol has been the main issue of criticism from the beginning of Telegram on but it hasn't been dropped yet and I'm pretty sure it won't any time soon.

**Comment by telegramdesktop** [comment]
@Mosrite Yes, it was criticised alot, although no unresponded and unresolved questions about Telegram protocol were stated yet.

Anyway this conversation has nothing to do with Telegram Desktop app, which is a client app that just works with the current Telegram API.

**Comment by Mosrite** [comment]
I understand. But I don't see that the developers of the clients would appreciate an improvement of encryption either. No matter if for desktop, web or mobile clients, it is always stated: "won't work, and we are not in charge" instead of "we would love to implement this and will discuss this with the telegram core team".

So, where would be the right place to suggest modifications to the protocol?

**Comment by jvoisin** [comment]
>  I'm not a crypto expert but I think it is even more secure than the current Telegram protocol.

Then don't suggest modification to the protocol.

**Comment by jeifour** [comment]
This issue isn't about changing the protocol anyway, it's to implement "secret chats" as already supported by the protocol into this specific client. As the implementation of secret chats into a multitude of mobile clients and into Cutegram has been successful, it's unlikely that there's a defect in the protocol itself that is the problem here.

**Comment by zQueal** [comment]
> This issue isn't about changing the protocol anyway, it's to implement "secret chats" as already supported by the protocol into this specific client.

Telegram uses its own encryption standard which isn't implemented on anything but mobile because that's specifically what it's designed for.

> As the implementation of secret chats into a multitude of mobile clients and into Cutegram has been successful, it's unlikely that there's a defect in the protocol itself that is the problem here.

These chat messages may be "secret", but they do not use the Telegram encryption standard. As a result, [their encryption is a complete joke.](https://github.com/Aseman-Land/Cutegram/issues/178)

**Comment by jeifour** [comment]
I didn't try Cutegram, but I used Canonical's client for Ubuntu Touch, and it allowed me to have a "secret chat" with an iOS user. So at least in some parts these 3rd party clients are adhering to a standard, don't they? (I'm not saying they're implementing it correctly.)

**Comment by zQueal** [comment]
> So at least in some parts these 3rd party clients are adhering to a standard, don't they?

It's entirely possible--however, using Cutegram as an example I can't find __any__ information to their encryption standard other than they use OpenSSL. That's it! So I have to assume that they're not. Encryption needs to be verifiable or why would I trust it?

As with Telegram I can go online right now and read about the finer points of _MTProto_ and [how it's implemented for perfect forward secrecy.](https://core.telegram.org/api/end-to-end)

**Comment by jvoisin** [comment]
You could read its [source code]( https://github.com/Aseman-Land/Cutegram ), to see that they are (obviously) implementing MTProto, because it's a telegram client.

**Comment by mancvso** [comment]
Please note that Cutegram only supports kwallet for key storage atm. It can be installed in Ubuntu without pulling-in the whole KDE desktop :)

**Comment by temmokan** [comment]
@zQueal "Telegram uses its own encryption standard which isn't implemented on anything but mobile because that's specifically what it's designed for."

Total bullshit. From programmer's viewpoint, ther's no problem implementing (in fact just recompiling) exactly the same features fo rdesktop clients.

Th ealck of secure chats in desktop version make it just "one of many" instant messengers, completely nullifying the primary *declared* advantage of the TM. Pity the desktop developers do no tunderstand that.

**Comment by matthiasbeyer** [comment]
:+1: We want encryption on the desktop app.

**Comment by Dega704** [comment]
This is obviously falling on deaf ears.  I gave up and switched to Wickr a while ago.  It does everything I wanted out of Telegram and then some.

**Comment by aphirst** [comment]
@Dega704 Is there really a point? Wickr is proprietary.

**Comment by aphirst** [comment]
I do have a technical question, though. When, say, someone opens a Secret Chat with me, they only get the option to type into it after, say, my phone gets online and the 2 devices perform the handshake. However, what is *supposed* to happen if the "recipient" of the Secret Chat has n>1 devices online at that time with Secret-Chat-capability (be they 2 mobiles, or a mobile and a desktop client)? What determines which client "receives" that Secret Chat?

**Comment by Dega704** [comment]
It is proprietary and has had an independent audit.  That's the best I can do for now.  If you find a better alternative that's open and has all of the same features let me know.

**Comment by aphirst** [comment]
Well Telegram does have the Encryption you need if you use the mobile versions or if you use cutegram or the Pidgin plugin (with which you can even daisy-chain the encryption by using OTR on top, though of course only with other Pidgin-Telegram users).

**Comment by matthiasbeyer** [comment]
@Dega704 and others... what about tox? I mean, it is not in usable shape by now, but it will be an alternative, right?

**Comment by aphirst** [comment]
@matthiasbeyer I use Tox too but it's not really viable on mobile connections, at least at the moment.

**Comment by jvoisin** [comment]
[hahahahahhahahahahhahahhaahahha]( https://github.com/irungentoo/toxcore/issues/1379 )
Yeah, so, thanks but no thanks.

**Comment by matthiasbeyer** [comment]
@jvoisin Just because one person is an ***hole this does not mean the project is not valueable. Anyways, this is not subject of this issue, is it?

**Comment by telegramdesktop** [comment]
@aphirst Currently all devices receive the request to open the secret chat and the one that does it first gets it. This works well with the idea of secret chats being available only on mobile apps, because in 99% of cases you have only one mobile device authed + some others on different platforms (home pc, work pc, laptop, tablet, etc).

**Comment by aphirst** [comment]
@telegramdesktop Thanks for clarifying!

I wonder whether perhaps it might be a good idea to implement a means for a client to present the option to "reject" a specific Secret Chat request, so that it can be deferred to another logged on device? Even without the Secret Chats in the official desktop client, I do indeed use Cutegram on one of my desktop machines, and I have 2 Telegram sessions on my phone (I dualboot two custom ROMs).

I'd be curious to know what you think, at least. As I'm sure you've become lucidly aware, secret chat capability in the desktop clients is very strongly desired by the community irrespective of whether it was considered by the Telegram project. :smile:

**Comment by FiatPax** [comment]
Please implement this already...

**Comment by miphe** [comment]
Yep, this is the first feature I looked for after adding contacts.

**Comment by robsonsobral** [comment]
Just to let let you all know that the [pidgin plugin](https://github.com/majn/telegram-purple) already has a Windows version and it supports secret chats.

**Comment by skepticatt** [comment]
Oh my god.! Approximately everyone who installed Telegram was did it due to the Secret Chat functionality. If telegram desktop is not going to support it, then what is the point of Telegram? Whatsapp already does my daily commute, and facebook messenger is a great cloud based IM too. Telegram only enters with its privacy and security, but , to be honest, I see that telegram falls short of its claims. 
Disappointment.

**Comment by stayen** [comment]
@skepticatt I have contacted the Telegram support channel online. They confirmed the secret chats in desktop implementation are low priority feature (??). "We will implement it sometime, no definite plans, though".

So yes, a disappointment - the primary privacy tool is, in fact, low priority (low importance?) feature.

**Comment by skepticatt** [comment]
@stayen This is infuriating. Goodbye Telegram! You sucked anyways...

**Comment by haraldkrischner** [comment]
Low priority for a substantial security feature? That's pathetic. What is high priority then? Animated Stickers or what?

**Comment by rorycornell** [comment]
+1 we would use telegram more.

**Comment by slick97477** [comment]
I also agree use this on android alot because of the encryption, but why is it advertised across the board for encryption but yet it is not actually available on desktop version

**Comment by matthiasbeyer** [comment]
Is it also a low prio feature that the "encryption" is secure or what? How much time do they invest in _secure_ encryption when they invest this little time in encryption at all?

**Comment by DaFri-Nochiterov** [comment]
Please. Telegram got new secret chats v2.0, when we got this secret chats in TDesktop? :crying_cat_face:

**Comment by cjs-cynic-net** [comment]
Yet another vote for getting secret chats in Telegram desktop.

**Comment by auchri** [comment]
Please discuss further at #871 :)
