### ISSUE TITLE
Malicious link that crashes all Telegram Desktop clients

### ISSUE THREAD

**Issue by MihaZupan** [telegramdesktop/tdesktop#5021]
### Steps to reproduce
1. Send a link
2. User clicks the link
3. Client crashes

### Expected behaviour
The callback should be validated.

### Actual behaviour
The callback is not validated!

### Configuration
**Operating system:**
Windows
**Version of Telegram Desktop:**
1.3.10
**Used theme**:
Doesn't matter

### Details
Yesterday I reported a security issue related to the passport feature that makes clients leak their IP address #5020 
This time the link can crash all Telegram Desktop clients.
The passport authentication request link has a callback field. That field is not validated - therefore it can itself be a tg:// link. This allows for recursive links. The callback can in itself be an authentication link - crashing the client when trying to 'visit' it.
Example link: https://gist.github.com/MihaZupan/aaf6c4f4daeb8be3af08bd8bd9bfc113

**Comment by MihaZupan** [comment]
The same link also affects the Android client, not crashing it, but bugging out the UI (black bar in the contacts list)

**Comment by ValdikSS** [comment]
@john-preston, the crash was due to nullptr dereference at https://github.com/telegramdesktop/tdesktop/blob/v1.3.10/Telegram/SourceFiles/passport/passport_form_controller.cpp#L2192
Your commit prevents this codepath, but it's better to check for nullptr there anyway.

**Comment by john-preston** [comment]
@ValdikSS I'm afraid that nullptr in _view was a coincidence. The crash was because the FormController was destroyed while being in the middle of its own method. And after that _view could've hold any garbage, not only nullptr. This is a logic error and it was fixed by (I hope) removing a possibility to destroy the FormController before trying to access _view.

Checks on _view should not be required in FormController in any place, because _view is created in FormController-s constructor and it never is destroyed while FormController is alive. You can think of it as a not_null pointer (but it is a unique_ptr, so it can't be marked not_null right now). This means that in any place that you're allowed to read _view variable value at all (meaning that FormController that holds it is not yet destroyed) it must be not nullptr. And if it accidentally holds nullptr you have no right to even read that variable value in that place (because that means that FormController is already destroyed).
