### ISSUE TITLE
URL with double hash won't open

### ISSUE THREAD

**Issue by Beelzenef** [telegramdesktop/tdesktop#5036]
### Steps to reproduce
1. Search a URL with double hash on it
2. Send it to anyone and click on it to open!

### Expected behaviour
Sending/receiving this [link](https://www.mapbox.com/mapbox-gl-js/api/#map#aretilesloaded) should open mapbox documentation in my favourite browser

### Actual behaviour
When clicking at the link, nothing happens, link is not opening anywhere.

### Configuration
**Operating system:** MacOs High Sierra 10.13.4

**Version of Telegram Desktop:** 4.2.1

**Used theme**: Reindhart

**Comment by stek29** [comment]
This is not Telegram Desktop.
You can download Telegram Desktop at https://desktop.telegram.org.

Also, you can report issues in app you're using at https://t.me/macswift.

---

Regarding this particular issue.

In RFC3986 terms part after `#` is named "fragment", and here's the set of characters allowed in it:

```
unreserved  = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
pct-encoded = "%" HEXDIG HEXDIG
pchar         = unreserved / pct-encoded / sub-delims / ":" / "@"

fragment      = *( pchar / "/" / "?" )
```

As you can see, `#` is not allowed in fragment.

And `NSURL` is RFC3986 compilant:

```
cy# [NSURL URLWithString:@"http://example.com/#foo"]
#"http://example.com/#foo"
cy# [NSURL URLWithString:@"http://example.com/#foo#bar"]
null
cy# [NSURL URLWithString:@"http://example.com/#foo%23bar"]
#"http://example.com/#foo%23bar"
cy# [NSURL URLWithString:@"http://example.com/#foo%%bar"]
null
```

However, `open` seems to handle this correctly: doing `open 'http://example.com/#foo#bar'` opens `http://example.com/#foo%23bar`

So, percent encoding all invalid chars in fragment on client side is indeed a reasonable thing to do.

This issue has been reported by me to the dev of macOS native app because it was fun to investigate, but it is definitely not a good idea to report macOS native app issues on this repo. (also, fyi, TDesktop does percent encoding on those links)
