### ISSUE TITLE
Weird text cursor when typing multi-line messages

### ISSUE THREAD

**Issue by ihordv** [telegramdesktop/tdesktop#5041]
### Steps to reproduce
_This issue might be OS-specific as my friend told app behaves as expected on macos_
1. Open chat with a user
2. Type any multi-line text (even shift+enter is enough)
3. Cursor becomes weird.

### Expected behaviour
Same (vertical line) text cursor  is used for both single-line and multi-line messages. Example of normal cursor:
![image](https://user-images.githubusercontent.com/1430830/43530398-21524156-95b6-11e8-8536-b0c47b9d6c4f.png)

### Actual behaviour
Text cursor has weird 'tick' at the top right part when typing multi-line message.
![image](https://user-images.githubusercontent.com/1430830/43530432-38f243c4-95b6-11e8-8a38-8dde9a3caef8.png)

### Configuration
**Operating system:**
Antergos/Arch Linux
Kernel: 4.17.11-arch1
KDE plasma: 5.13.3
KDE Frameworks: 5.48.0
Qt Version: 5.11.1

**Version of Telegram Desktop:**
1.3.10

**Used theme**:
Default, though I can reproduce the issue in Dark theme as well.

**Comment by john-preston** [comment]
@ihordv This thing looks like Qt's display of what RTL / LTR text is currently being typed.

I think this happens when you include some RTL characters when your system language is thought as LTR by Qt or vice versa — perhaps it thinks that there is something RTL about your system, so it displays that currently you're typing an LTR part of text.

**Comment by ihordv** [comment]
@john-preston, thanks for the clues. After some googling I found [QTBUG-69665](https://bugreports.qt.io/browse/QTBUG-69665). I think you can close my issue.
