### ISSUE TITLE
Theme Editor - a few suggestions

### ISSUE THREAD

**Issue by BlackRedDead** [telegramdesktop/tdesktop#5044]
### Pipette Tool
A Pipette Tool to select areas to edit in the Theme Editor.

Steps to operate:
1. Select Pipette Tool.
2. Point and click the Area where the Surface or Text is or would appear you want to edit.
3. Get a list in the Editor with all the Entrys (of the Surfaces/Texts) of the selected Area to edit.

### Representation or editor view
Actually we edit themes on our own Telegram, but many entrys we might never see and have no idea how they look like!
I personally prefer dedicated editors, but i understand that the effort to make them and keep them updated is to high!
but it would be nice to get some sort of representation feature, with a standarized screen to edit most common entrys and take a screenshot from it and the possibility to display things actually edited like phone call boxes, just as someone edits an connected entry - as else we might never see them. ;-)

### Connections
Like those premade, like "windowShadowFgFallback: windowBg;" wich looks in the Editor like:
> windowShadowFgFallback
> =windowBg

A new Field in the cc window to connect another entry to the actual or vice versa and a context menu Entry too

### Categorys
While it is already helpfull that many Entrys using simliar Nameparts, sometimes it is not enough or even lead to confusion as Entrys named simliar attach to different Parts of the Client.
It would be helpfull to define categorys like "Chatwindow"; "Usercolors"; "Mainmenu"; "Contextmenu"; "Window"; ...

**Comment by john-preston** [comment]
@BlackRedDead The first one is too complicated, I'm afraid it is not planned.

The second one is supported, you press a color - color editor opens - now you can search and click in the colors list on the right to make a "connection".

**Comment by BlackRedDead** [comment]
well, i agree it might be to complicated to implement such tool, but overall we need something better than just entrys and descriptions, at least a better representation, most entrys i never ever saw and don't think i will ever see them in my use! - so any form to test how they look like would be nice! :)

Please further describe or aid with screenshots what you mean, as if i right click an entry all i get is the cc window, and there i can only define colors - not connections!
if i change an entry with an connection to another entry it's connection gets lost - wich is logic and okay, but to reestablish connections after i found out that they are good as-is i need to open the palette external and change it manually! - very inconvenient ;-)

**Comment by john-preston** [comment]
![image](https://user-images.githubusercontent.com/17900494/43662355-48864c36-976e-11e8-91ce-5500051c3237.png)

Here on this screenshot you edit a color in a box with palette and stuff. On the right you see full list of keys in your theme.

Current edited key has active background (blue in this case).

All keys AFTER the one you edit have disabled background (dark grey in this case), default cursor when you place mouse over them and no "over" state, because you can't click them, they're AFTER the edited key and connections can only be done to keys BEFORE the current one.

All keys BEFORE the one you edit have default background (white in this case), pointer cursor when you place mouse over them and a default "over" background (light grey in this case), because you can click them and by that make connection. If you click some of the keys BEFORE the one you edit its value is previewed in the box. If you save the value in the box after that (without changing it anyhow) you'll save a connection.

Also the top-bar search is still available in this state and you can filter the keys, they'll still have the respectful background colors and ability to click the BEFORE ones to make connections.

**Comment by BlackRedDead** [comment]
wow, what a hidden feature :D
but things for the great heads-up explaination 👍 

an idea how to shot down unknown entrys?
actually i paint them pure green and wait to stumble across one, then i search for those #00F and repaint a suspected entry after another cyan until i find out wich one it is. :-/
but hell, there are also values where i know i will never stumble across them! :-(

**Comment by john-preston** [comment]
@BlackRedDead There are some short descriptions for each key.

**Comment by BlackRedDead** [comment]
Key? - idk but i call it Entry... (like `windowBg`)
Yea, but those Descriptions can be misleading at times, as some Elements are to similar to clearly differentiate them by Text only - especially in English in my eyes! ;-)
Also an full fledged optical Editor would be much easyer - but i like it that Telegram let you edit nearly every Surface independently while offering the Ability to connect them for easyer editing of Color Palettes!

But i have no Idea what could be a Solution for that Concept flaw without a ton of Work. :-(
The Descriptions are already good, misleading at times but that could be a Language issue!
(like "history" - i never hear'ed in that Context and we have a total different Word for that)
A "Switch to edited Surface" Function or "display a Surface example" would be nice, but again a lot of work i guess. :-/

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by Aokromes** [comment]
@BlackRedDead

**Comment by Aokromes** [comment]
no answer for more than 1 month, closing.
