### ISSUE TITLE
Reversed natural scrolling

### ISSUE THREAD

**Issue by ciuff** [telegramdesktop/tdesktop#508]
The last update got me an unpleasant surprise on Ubuntu 12.04: now i have to scroll in reverse, instead of using natural scrolling. Please fix

**Comment by hobarrera** [comment]
I'm having the same issue.

Just in case it's not clear: I've configured xorg to use natural scrolling. Telegram seems to override this, hence, I've old-school scrolling, which is extremely annoying.

Per-application natural scrolling is a really bad idea, for the record, since users are incapable of overriding their instincts regarding scroll direction on a per-application basis. This should really be left to the OS.

**Comment by auchri** [comment]
Duplicate #494
