### ISSUE TITLE
Tray Icon broken with Gnome3 since 0.7.17

### ISSUE THREAD

**Issue by ernstblecha** [telegramdesktop/tdesktop#510]
For me the tray-icon **only** worked with 0.7.16, i am using Gnome3.12.2 (NOT fallback!) on Gentoo

> echo $XDG_CURRENT_DESKTOP
> GNOME

> echo $DESKTOP_SESSION
> gnome

**Comment by EmptyStackExn** [comment]
New release 0.7.17 added cases-switch with respect to `$XDG_CURRENT_DESKTOP` variable in order to switch between `QSystemTrayIcon` or `libappindicator`.

Refering to bug #491, the problem is that @ernstblecha and I both have the same `$XDG_CURRENT_DESKTOP` but different `$DESKTOP_SESSION`. @telegramdesktop, I suggest to refine the case-switch w.r.t. `$DESKTOP_SESSION`.

In this way,

1. `XDG_CURRENT_DESKTOP=GNOME` and `DESKTOP_SESSION=gnome` would use `QSystemTrayIcon`
2. `XDG_CURRENT_DESKTOP=GNOME` and `DESKTOP_SESSION=gnome-classic` would use `libappindicator`

**Comment by ernstblecha** [comment]
I just checked the internet on this and it seems that relying on these variables is kind of touchy, as different distributins fill them with different values (gnome-fallback vs gnome-classic...).

So even with this change in place i would expect further "bugs" of this type. Maybe it is possible to allow a manual override via the settings menu (Auto, QSystemTrayIcon, libappindicator) or a command line switch?

**Comment by EmptyStackExn** [comment]
Manual override :+1: As you said via the **settings menu with a three-choice-radio button (Auto, QSystemTrayIcon, libappindicator)** seems to me a good idea !

**Comment by ernstblecha** [comment]
Sorry for bothering, just managed to fix my problem: libappindicator was not installed on my system.
Obviously libappindicator is not an integral part of Gnome3.

Problem is fixed!
