### ISSUE TITLE
doubt about the codes and the architecture

### ISSUE THREAD

**Issue by asok00000** [telegramdesktop/tdesktop#5128]
Why draw everything rather than to use Qt's controls or QGraphicsView ?Because of performance or others？

**Comment by john-preston** [comment]
@asok00000 Given a requirement to follow design pixel-perfectly I wasn't sure that going with existing Qt controls will work for me, so I started using custom widgets. This was a cause of some really bad architecture decisions (regarding separation of UI and logic), but I try (very slowly) to make things better.

I didn't consider QML at the moment, because I just needed a simple way to write an crossplatform UI application with custom UI controls and Qt Widgets looked like the easiest approach.
