### ISSUE TITLE
Constantly accessing hard disk with v1.3.15 

### ISSUE THREAD

**Issue by Double-A-92** [telegramdesktop/tdesktop#5134]
### Steps to reproduce
1. Install the current alpha (v1.3.15)
2. Start Telegram and let it run (even in the background)

### Error behaviour
Telegram is writing or reading something from my hard drive with (0.4 MB/s) **constantly**. This causes loud disk noises and does never stop or pause as long as Telegram is running. It also doesn't depend on message activity, or scrolling in older message history. It happens all the time, no matter what I'm doing with Telegram.

### Configuration
**Operating system:**
Windows 10 1803

**Storage:**
1 SSD and 2 extra disk drives.

**Version of Telegram Desktop:**
1.3.15 alpha

**Used theme**:
default light

**Comment by john-preston** [comment]
@Double-A-92 That's strange. Can you contact me at t.me/preston so I'll ask you for details?

**Comment by Latesil** [comment]
Have the same issue. Fedora 28, 64bit, Telegram 1.3.16 alpha. After one day of usage it wrote 31.9 Gb of data.

**Comment by Double-A-92** [comment]
Btw, mine stopped doing that after I let it do it for an hour...

**Comment by john-preston** [comment]
@Latesil in other cases it was clearing old unlimited image / sticker / gif cache, that sometimes had more than a million files. Please check if ~/.local/share/TelegramDesktop/tdata/D877F783D5D3EF8C has too many files.

If it does that means Telegram 1.3.16 alpha clears them one by one and it'll stop utilizing hdd so much when it's done.

Otherwise you can just delete this whole folder at one from Terminal, but then once you launch Telegram Desktop you'll have to login again.

**Comment by Aokromes** [comment]
this bug is still valid?

**Comment by tim77** [comment]
> this bug is still valid?

Seems like no more this bug for me. Telegram 1.9.8 from RPM Fusion.
My old bug report: https://bugzilla.rpmfusion.org/show_bug.cgi?id=5099
