### ISSUE TITLE
Application does not adopt when changing screen scale on Windows.

### ISSUE THREAD

**Issue by sohrabtaee** [telegramdesktop/tdesktop#5145]
My laptop has screen scale of 150% because it has a very high resolution and my external display has a scale of 100%.

Although interface scale is set to Auto in the settings, every time I change my display, I have to go to settings and change the scale of Telegram Desktop accordingly.

**Comment by Aokromes** [comment]
#1121

**Comment by ddonetskov** [comment]
Not sure why the issue has been closed. Is that resolved and relevant changes will be published soon?

If that's not the case, I'd like to confirm it's still the issue for me. My configuration is
- the Windows client 1.3.14 on Windows 10,
- a WQHD 14'' internal screen with the 175% system scaling factor and the 150% scaling factor set in Telegram,
- an FHD 24'' external screen with the 100% scaling factor.

The client is rendered usable on the internal screen (though I'd appreciate a bit larger fonts with the same size interface elements so the font size setting would be handy here too) but when I move its window to the external screen, it's shown too large.

That's the annoying issue especially given most of the other applications which are being actively developed do not suffer from it. Hopefully, we'll get a fix for it. P.S. Otherwise, the Telegram client is great. )

**Comment by sohrabtaee** [comment]
I closed it because it's a the same as issue #1121

**Comment by lucidyan** [comment]
@sohrabtaee 
The original issue #1121 is almost three years old. Same issues are created with an enviable regularity, then devs close them as duplicates and people continue suffering. 

So is there any information about when you will take this in your milestone or somewhat?

**Comment by stek29** [comment]
@lucidyan person you're replying to is issue author and has nothing to do with TDesktop :P

**Comment by lucidyan** [comment]
> @lucidyan person you're replying to is issue author and has nothing to do with TDesktop :P

Oh my! :smile: 
Maybe then you will clarify this or just mention responsible devs in the main issue #1121?

**Comment by rsteber** [comment]
@sohrabtaee This issue should definitely not be closed, because the Auto Scaling feature just stops working a few weeks and approximately two updates ago.

**Comment by john-preston** [comment]
@rsteber This issue is about changing the scale while the app is running, which was never supported :(

Changing the scale with the app relaunch will be fixed in the next release.
