### ISSUE TITLE
Option for message formatting (-- to ‏‎−, >> to », << to «)

### ISSUE THREAD

**Issue by ghost** [telegramdesktop/tdesktop#522]
Hi.
I want to report a bug in the telegram desktop version. (Linux)
The problem of the character: Dash. Or (-)
When two characters Dash, taken together, the result rather than the (--) becomes a long line. (‏‎−)
But when the two characters together Dash, the text first, this problem does not exist.
For example:
http://s4.picofile.com/file/8173777318/snapshot.png

**Comment by joshery420** [comment]
+1

**Comment by ppparadox** [comment]
+1

**Comment by ciuff** [comment]
+1 
Same for >>, becomes  » and the respective for <<

**Comment by CyberMew** [comment]
What's the problem that's causing this issue to not be fixed within a short period?

**Comment by auchri** [comment]
Because it's not an issue for some people

**Comment by ciuff** [comment]
maybe make it an option? enable/disable auto formatting

**Comment by auchri** [comment]
Yes, that's why I added the enhancement label

**Comment by Mindstormer619** [comment]
+1 This is a REAL pain when sharing something like a couple lines of code. Especially when the code is too little to use a pastebin, but then there go all your `cout<<"Hello world";` statements.

**Comment by auchri** [comment]
Also don't remove multiple spaces

**Comment by xenogenesi** [comment]
+1 

why not using a modifier for the replaced text? Like <kbd>alt</kbd>+<kbd>-</kbd>

Best would be to have a way to escape the text to send, untouched (without Emojis or replace at all)

Please leave the original text as it is, is really a pain passing command lines between Mac and Linux (try using it with a terminal noob and then call it a feature again), I think is just this code in `historywidget.cpp`:

    QString HistoryWidget::prepareMessage(QString result) {
    	result = result.replace('\t', qsl(" "));
    
    	result = result.replace(" --", QString::fromUtf8(" \xe2\x80\x94"));
    	result = result.replace("-- ", QString::fromUtf8("\xe2\x80\x94 "));
    	result = result.replace("<<", QString::fromUtf8("\xc2\xab"));
    	result = result.replace(">>", QString::fromUtf8("\xc2\xbb"));
    
    	return (cReplaceEmojis() ? replaceEmojis(result) : result).trimmed();
    }

(btw, nice app, keep up the good work)

**Comment by ralesk** [comment]
Those four lines should just be dropped.  Those who want to use those characters will enter them (character map, keyboard layout, whatever other means).

**Comment by ppparadox** [comment]
Updates? This is really frustrating, especially for IT guys like us!!!

**Comment by Noiwex** [comment]
Is author dead? Hello?

**Comment by nvx** [comment]
This is an issue for me as well.

**Comment by auchri** [comment]
@Mindstormer619 you can now surround your statements with \`, for example \`cout<<"Hello world";\`

**Comment by Mindstormer619** [comment]
Yes of course. Thanks a lot for this :smile:

**Comment by rasubuntu** [comment]
+1

**Comment by unknownlighter** [comment]
+1

**Comment by ivan-hilckov** [comment]
+1

**Comment by freeman1981** [comment]
+1

**Comment by winsento** [comment]
+1

**Comment by nvx** [comment]
Not sure why the 4x +1's in quick succession, but didn't this get fixed already? Single backtick quoting for inline quoting, or triple backtick for block quoting.

**Comment by neongreen** [comment]
@nvx: single backtick quoting is for stuff like code, bash commands, etc (and it shows, correspondingly, in monospace font and a different color). While this covers most (but not all) cases where `--` or `>>` is used, it'd still be nice if it was possible to turn autoreplacement off completely for people who never use it (because we have ‘—’ and ‘«»’s on our keyboards, or for some other reason).

Generally, I don't see why not add customisation options for *everything* that people request to have an option for. If devs are worried that too many options would harm usability for people who don't want to customise everything, they could just put rarely used options on some separate page (like µTorrent, Firefox, Chrome, etc all have done with the concept of [customisation flags](http://www.androidauthority.com/chrome-flags-android-customization-607899/)).

**Comment by akomba** [comment]
This is easily the most annoying "feature" of telegram. Please get this fixed or make it optional. Thank you. I love the rest.

**Comment by edmundlaugasson** [comment]
In 0.9.40 still not fixed :(

**Comment by Lithas** [comment]
I agree, the '--' syntax is really useful for a lot of things (for example, our chats use a bot that implements per-user karma by scanning for "user++" or "user--" comments. There are workarounds, but none of them are intuitive or easy to use.

**Comment by aix27249** [comment]
+1 to fix this ASAP. It is really, really frustrating, especially when you forget about this 'feature'.

Even if someone is using this, please make this optional.

**Comment by Noiwex** [comment]
My coworker was really frustrated when he discovered, that some public SSH
key was violently mutilated thanks to your client.

**Comment by stek29** [comment]
@Noiwex Maybe your coworker would use ``` next time?

**Comment by Noiwex** [comment]
Oh that's great to pay attention to not intuitive "feature" that was added
just because author was feeling like so. There is no real reason for this.

Meanwhile, Telegram OS X doesn't make such surprises.

**Comment by oslerw** [comment]
Using backticks isn't an appropriate workaround for display names. I'd like to put two literal `<` in my name, but it always gets converted.

**Comment by Innomen** [comment]
So apparently they've "fixed" this by spreading the bug (no, it's not a feature when it lacks an off switch, simply apply this logic to the light in your bedroom) to additional clients. (Android at least.)

Might be the last straw for me. Might be time to switch apps altogether if this one is just gonna turn into the incredimail/myspace of IM solutions.

**Comment by lindhe** [comment]
Also, I don't think it makes sense that `--` becomes `—` (aka. em-dash). It would make more sense to convert it into `–` (aka. en-dash) and have `---` become `—` as in LaTeX.

In English, em-dash is much more common than en-dash, but in Swedish en-dash is the standard. So it's really useful to be able to write both (especially for me on Linux, where unicode input does not work because of QT or something like that).

**Comment by ralesk** [comment]
@lindhe I would say to be able to type –, or ” for that matter, is the task of your keyboard layout, not some application (and no other application, apparently, Telegram Desktop is unique in mangling these characters in messages).

**Comment by joshsleeper** [comment]
@john-preston @auchri
This issue is easy to fix, has no real negative consequences of fixing it, and has been active for _way_ too long.
Telegram is first and foremost a **chat application**, not a tool for writing technical documents or prose.

Please just remove those four cases of forced autoformatting (in **all** clients) and be done with it.

**Comment by lindhe** [comment]
@ralesk Not quite true. All applications using Markdown does this (Github, Reddit and Slack comes to mind). I like markdown, since not everything can be written very nicely only using the keyboard (especially **bold** and *italics*, but also having different types of dashes is useful and rare to find on keyboards). I just wish Telegram was more consistent with it.

One would expect the usual unicode input thing (ibus?) to work properly, but that is not Telegrams fault: #1033

**Comment by Lithas** [comment]
I would probably be willing to give up my decrement if I got native bold and italics. Without getting the other benefits of markdown, however, this really makes no sense to me.

**Comment by ralesk** [comment]
@lindhe I haven't had Slack change my `--` or my `"` into anything it shouldn't be.  Markdown is an entirely separate issue, but it does interfere with `*doing things in asterisks*` which, since we lack `/me` is all we have — just something to keep in mind there.  I do agree that supporting it the same way is important, and as such the first Markdown rollout in Telegram was a pain and a mess.

I don't think GitHub changes these either, even outside of verbatims -- if anything these should remain as they were, and I haven't employed anything "strange" in the source of the message either. (Preview said dashdash and ASCII quotes)

**Comment by ralesk** [comment]
(To go on a tangent with the Markdown thing: if there's a reason I like BBCode is that it's so obvious and extensible, and does not interfere with random things by accident (interpreting rogue asterisks and dashes as formatting); too bad it went out of fashion)

**Comment by Reloecc** [comment]
I would like to join all the people here: may we get rid of it, please? If needed, keep it for mac users only.. they deserve it.

**Comment by tarstars** [comment]
+1

This feature is really annoying when sending some code snippet. Please, provide a way to disable it.

**Comment by eddex** [comment]
I wrote a telegram bot that runs brainfuck code. It's common to have code like <<<+++>>>--- etc.
The bot can't be used with the Telegram desktop app because of this "feature". I have to convert the characters back to normal on my server, which would not be necessary it the text would just be sent as is.
As many mentioned before, I think it would be useful to have a setting to turn this "feature" on/off.

**Comment by Noiwex** [comment]
FIX THIS

**Comment by lindhe** [comment]
@eddex For that rather specific use case, maybe having it it `code style` (using surrounding backticks `) would suffice?

**Comment by ctrlbru** [comment]
Really frustating when you paste command lines or plsql snippets, should be an option.

**Comment by proea** [comment]
@auchri

https://github.com/telegramdesktop/tdesktop/issues/522#issuecomment-154837695 
it does not work for multiline text

**Comment by ralesk** [comment]
@proea triple ` works for multiline.

**Comment by ralesk** [comment]
That said the preformatted characters is exactly something *nobody* wants.

**Comment by stek29** [comment]
@ralesk I do.

**Comment by proea** [comment]
@ralesk Thanks

```````` (9`) changes automatically to `
it makes impossible to write ``` in the body ``` ```

**Comment by ralesk** [comment]
@stek29 Curious. What's your reason for it? Pretty much everyone I've talked to via Telegram is annoyed by the random text replacement.

@proea Yes, that's the limitation of the markdownish syntax being used.  Raise it in a separate bug.  But I don't think it's common to want to type triple grave inside a code block.

**Comment by stek29** [comment]
@ralesk Because I use `--` as `—` a lot :)

**Comment by auchri** [comment]
@stek29 I think you are the only one 😉

**Comment by lindhe** [comment]
@stek29 In all other applications, I can write — by typing unicode 2014 (on Gnome (Linux) that is <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd><kbd>2014</kbd>, and I know there is some kombination to do it in Windows too). It's just bizarre that Telegram can't do it.

In LaTeX and most flavours of markdown, em-dash is `---` while `--` is en-dash. So it's still stupid that Telegram has it this way.

And, as already mentioned, there is no way to revert the change. I don't know how many times I have had scripts fail because someone pasted it in Telegram.

**Comment by proea** [comment]
@lindhe  I agree with you!

**Comment by ralesk** [comment]
@lindhe This is a Qt application. The <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>U</kbd> thing is a Gtk-only feature, sadly not adopted by X11 or as far as I'm aware, Wayland, and Qt believe that it should be the job of something lower down (again X11 or Wayland) and they refuse to implement it :D (not sure to smile or cry tbh)

**Comment by lindhe** [comment]
I'm aware. 😿 😭 😭

**Comment by Walkman100** [comment]
@ralesk <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>u</kbd>, <kbd>2014</kbd>, <kbd>Enter</kbd> works for me in Telegram.

**Comment by edmundlaugasson** [comment]
@Walkman100 Ctrl+Shift+u, 2014, Enter does not work for me. Using Telegram Desktop 1.1.19.
When to create dash using mentioned shortcut keys in some text editor and then copy to Telegram - then there are seen those dashes but when to copy such command from message directly to command-line and press enter then you will get errors because these dashes are not correct ones. You can try e.g. with command _sudo dpkg --configure -a_

**Comment by lindhe** [comment]
@Walkman100 What version of Telegram are you using? What OS are you running and what package did you install?

**Comment by Walkman100** [comment]
Telegram Desktop v1.1.19, not installed from a package (what?), Linux Mint 17.3 Rosa, Qt: 4.8.6, KDE Development Platform: 4.14.2, Plasma Desktop Shell: 4.11.11

@edmundlaugasson Don't get me wrong, I am completely in favour of dropping this "feature" completely, I know how painful it is

**Comment by ralesk** [comment]
hahahaha FOUND IT

You know what enables <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>U</kbd> in Qt/KDE applications?  iBus.  I quit it and the feature disappeared.

**Comment by Walkman100** [comment]
Hah, yep that did it. Quit it from the notification panel and Ctrl+Shift+U disappears. BTW anyone who did this to test and can't figure out how to start it again, `ibus-daemon -d` does the trick. Also `> ibus version` gives `IBus 1.5.5`.

If anyone has IBus running and Ctrl+Shift+U doesn't work in telegram, try right-clicking on the IBus icon in the system tray => Preferences => Advanced tab and tick the "Share the same input method among all applications" checkbox ([image](https://user-images.githubusercontent.com/5454764/29339420-75fd81e4-821a-11e7-9a7a-25be28ba31ea.png))

**Comment by lindhe** [comment]
This seems not to be enough for me. I installed iBus (1.15.6), ran `ibus-daemon` and made sure "Share the same input method among all applications" was active. No luck.

I'm on Arch Linux, running Telegram 1.1.19 with Gnome running in the background of i3wm.

**Comment by ralesk** [comment]
For the record: I'm on Fedora 24, Mate desktop, and had iBus so I can type Japanese on it but haven't actually messed around in the settings whatsoever... No idea if Fedora does any config wildly different from Arch.

But the tangent aside: I still hope Telegram will stop mangling messages at some point. (whatever happens with triple-tick messages on editing also seems to show something horribly wrong is going on instead of the raw message getting parsed up for display)

**Comment by Innomen** [comment]
Guys, telegram is now the Facebook of IM clients. They've got their vendor-locked base, and now it's all about fluff features and the downhill run. The server code will never be open sourced. And you're almost certain to never see the changes you/we want.

**Comment by john-preston** [comment]
@Innomen Facebook never had (and never will have?) open-source client apps :)

**Comment by Innomen** [comment]
@john-preston 
So if the NSA released an IM app, with an open source front end and a closed source server you'd call it open source and trust it.

/smh

I guess we collectively deserve all this abuse.

Keep cheerleading for a Russian billionaire. I'm sure you'll rake in all the thumbs.

https://duckduckgo.com/?q=pavel+durov+telegram+censor+back+door+register&atb=v76-2_u&ia=web

**Comment by SepehrP** [comment]
Helo. How can I write in blue format in telegram?

**Comment by ralesk** [comment]
This isn't a support forum, and there's no colour markup in Telegram.

**Comment by Noiwex** [comment]
QT must be really hard to grasp.

**Comment by mikevmk** [comment]
Fuck this shitty "feature", is it too hard to make this optional?

**Comment by wsxy162** [comment]
Telegram is no a input method, I don't want it to determine which word need to be transformed. That's not the client's business.

**Comment by AndydeCleyre** [comment]
I just want to clarify that surrounding text with backticks, any number of backticks, is absolutely not a solution, as it will miserably mangle text which already contains backticks.

If you really think text mangling is a feature, please run a poll, split by platform, to see if your users agree, or if you are working against them.

**Comment by JuanPotato** [comment]
I'm totally going to attempt to add this in, hopefully they accept the PR.

**Comment by davtur19** [comment]
Could you put in the settings a way to disable this "features"?

**Comment by JuanPotato** [comment]
That's the plan yo

**Comment by JuanPotato** [comment]
Update: if I could compile this then I might have had something by now

**Comment by louwers** [comment]
Sad to see this being a problem since 2015... Telegram is used extensively by tech-savy users. Sharing console commands and snippets of code is a pain with this 'feature'.

No other application besides Microsoft Word does this , and even there it can be turned off.

Should just be removed altogether in my opinion. I don't want to live in a world where every application implements it's own macros.

**Comment by stek29** [comment]
> Telegram is used extensively by tech-savy users

That's not true.

**Comment by davtur19** [comment]
Instead of continuing to say crap about the fact that it is useful, do you want to put a button to disable it or not?

**Comment by NicMan37** [comment]
even for me this "features" is hateful

**Comment by louwers** [comment]
@stek29: Did you read the rest of my comment? A lot of users are annoyed by this (as evidenced by this thread). It's a bad design to have every app implement its own macros, especially if it can't be turned off.

**Comment by Vechus** [comment]
This is stupid. You should almost add one of these three possibilities:
1. a button to activate / deactivate this feature
2. custom characters for formatting
3. only hotkeys for formatting like every text editor, so you can avoid any other problem

**Comment by JuanPotato** [comment]
Y'all should stop being so damn hostile towards the developers of something
you get for free

**Comment by Vechus** [comment]
Yes sorry if I showed hostility about that, I just think it's better to add one of the three corrections I proposed to avoid any problem with formatting. Everyone has his own keyboard, OS and habits, so if you add the possibility to customise hotkeys / characters for formatting text, that would be just good and nobody would get any trouble while texting.

**Comment by louwers** [comment]
@JuanPotato It's never OK to be hostile towards developers. Sorry if if I came across that way.

That being said, Telegram not for free. We're collectively providing the KGB with valuable information it can use to poison Western democracies.

**Comment by PeterMX** [comment]
> I'm totally going to attempt to add this in, hopefully they accept the PR.

**Comment by PeterMX** [comment]
> I'm totally going to attempt to add this in, hopefully they accept the PR.

@JuanPotato do you get progress?

**Comment by ricardo-vargas** [comment]
+1

**Comment by JuanPotato** [comment]
@PeterMX see the message following that one directly

**Comment by PeterMX** [comment]
so I made a PR, let's see what happens!

**Comment by joshsleeper** [comment]
#4553 if anyone wants to give it a 👍

**Comment by davtur19** [comment]
I found how to fix this without recompiling everything, I used x96dbg and I applied a patch, for those who want this is the patch to apply
- Open Telegram.exe in x96dbg
- After which you import the patch and apply it
**It works on version 1.2.15 of desktop telegram, it is very likely that it will not work on another version, so make a backup of the old exe file**

File name: `patch.1337`
Content of the file: 
```>telegram.exe
00883FC8:50->58
00883FC9:F8->0B
00883FCA:12->17
0088401E:C4->58
0088401F:09->0B
02830B59:3C->00
```

Before applying the patch you can check what is going to change so you can be sure it is not a dangerous change

**Comment by k3a** [comment]
Unbelievable, such a pain in the ass and they were unable to fix it in 2 years calling this a "feature"?! What the fu*k, seriously, this is a major problem!! Don't tell me I have to make a private fork of the client to apply that one line #4610 patch to fix this!? I would like to see a person who daily writes two dashes and expecting it to replace to a  — bullsh*t. Can't you make it configurable? We, IT people, are sharing UNIX double-dash commands often and this wastes our time.

**Comment by JuanPotato** [comment]
@k3a I've said this before and I'll say it again, don't be so damn hostile
towards the developers of a program you get for free. We're all humans,
treat them with some respect.

**Comment by k3a** [comment]
Sorry, I over-reacted, I agree. I am also a developer so I know how difficult it is and I also actively donate money to free software project. But the main reason was not that "I miss a feature and I demand it from a free program". The reason was that it is a serious problem known for 2 years, wasting people time world-wide, requiring a few-line change and someone called it a "feature" almost closing this as "WontFix". This would be similar to https://bugs.chromium.org/p/chromium/issues/detail?id=362356. But I don't want to start an offtopic, I just explained my overreaction and sorry again. I love Telegram and devs have made awesome work so far but this should have been fixed a year ago already. :P

**Comment by Reloecc** [comment]
@k3a you know you can enclose your text with tripple ` to get it not re-formated, right? just do a ```--bash command```

**Comment by ralesk** [comment]
We know @Reloecc and it doesn't matter. No other application replaces -- with — and >> with » and so on.  It's unexpected and it's bad practice.

**Comment by Noiwex** [comment]
![](https://media.giphy.com/media/b7f0X8Okk1uyk/source.gif)

**Comment by hertell** [comment]
Please get this annoyance fixed. Text i write should be sent and received unaltered. It's hard to understand why this is so difficult to get. I have not seen any reasonable reason why this idiotic textconversion has to be done without asking the user!!

**Comment by ralesk** [comment]
@stek29 ???

**Comment by zeroone2numeral2** [comment]
@ralesk replacements can be reverted whit backspace, from the latest release

**Comment by john-preston** [comment]
@ralesk It doesn't happen in clipboard paste.

It doesn't happen in monospace blocks, including possible blocks (not-yet-closed blocks staring with backtick or triple backtick).

And it can be reverted by backspace or ctrl/cmd + z in all other cases.

**Comment by Noiwex** [comment]
It's still unwanted useless feature that no other program does. It's action
is not obvious and it popups randomly. It goes against all UX in telegram
desktop.

**Comment by john-preston** [comment]
@Noiwex Sorry :(

**Comment by joshsleeper** [comment]
@john-preston 
many of us really appreciate the effort to help make this less of an issue, so thanks a ton for that work!
:+1: :ok_hand: :heart:

that said, I'm really having a hard time understanding why you feel to strongly about keeping this replacement by default.

can you help us understand why, even amidst all of the comments here and otherwise, you still feel that the automatic replacement is the correct default?

I feel like you've held your ground pretty well on this topic and I'd love to know why.

**Comment by john-preston** [comment]
@joshsleeper Because it is too small a thing to be kept in Settings at all (they're complete mess right now and adding some strange checkboxes that are irrelevant for 99% of users will make it even worse), so the only way of keeping them at all is keeping them on by default.

For the majority of users this is not an issue at all, because they don't post some C++ code or I don't know what else. For some of the left this is a feature, because this is an easy way to type popular in text conversations non-english-layout symbols.

I really don't wee where exactly that gives a problem except for the C/C++ code snippets that you write by hand in the message field (not past from your code editor) and you don't use markup for them (like surrounding it in backticks). But for those extremely rare cases you can just undo the replacement.

**Comment by hertell** [comment]
I have been using this version of Telegram on a mac from more or less from the beginning, but this idiotic Microsoft-way-of-thinking where someone/or something decides what i should write instead of letting me write what i want DRIVES ME just CRAZY.

I did a quick test with the other osx-version of telegram found here https://macos.telegram.org (https://github.com/overtake/TelegramSwift), and that version DID NOT replace my -- with − or >> and << with « and ».

I am tempted to switch to the other telegram, but that version too has some fishy issues going on like that the actual binary-version is not matching the source which again seems to violate the GPLv2-licence (https://github.com/overtake/TelegramSwift/issues/166). If that mess will be sorted out, then I'm going to swap.

just my 5cents...

**Comment by joshsleeper** [comment]
@hertell right idea, but it feels like the wrong attitude.
We're requesting that someone change something for us in an app we don't pay for whatsoever.
If we want them to do the work for us and give us what we want, we need to show some respect for all the work they already do.

---

@john-preston thanks for much for the timely, detailed response. I super appreciate it.

I totally get your stance that most users (an assumption, but probably a correct one) aren't posting code snippets back and forth in Telegram.
I've done it, most of my friends have done it, but I acknowledge that we're probably not the majority here.
Point valid and acknowledged. :+1:

I also acknowledge that you view the settings menu as far too cluttered, which I more or less agree with. I'm sure that's something that can be resolved in the future for sure, and I'd wholly support some sort of "Advanced" settings category for toggling micro-level app adjustments like this.

What I will say is that, regardless of usage, I strongly dislike having my chat programs automatically change my message contents for any reason.
This isn't just about `--` to `‏−` or `>>` to `»`, but about expectations and separation of concerns.

## Expectation Examples

* I do expect my mobile phone keyboard, regardless of program I'm using, to automatically correct my spelling or typos.
    * side note: I _also_ expect my mobile phone keyboard to present me options for _disabling_ those automatic corrections if I so choose
* I **do not** expect my desktop keyboard, regardless of programing I'm using, to automatically correct my spelling or typos.

These expectations generally hold true, and apply the same across the operating system.
Most desktop keyboards do nothing to adjust what was typed, and most mobile keyboards help us constantly because typing accurately on a 3" wide keyboard is, unsurprisingly, hard.

Taking those examples a step further, I would say:
* I do expect specific programs (generally document writers) to automatically replace some symbols as I type, because programs designed for specific purposes have specific needs.
    * Microsoft Word is one such obvious example, replacing symbols like `"` and `'` with smart quotes, `--` with en dash, and `---` with em dash. These are deemed sensible replacements, because Word is a document writer, and designed specifically for writing things like documentation, articles, and essays. Note that _many_ people still disable these replacement features out of various frustrations that come with using the specialty symbols.
* I **do not** expect non-document writers to automatically replace some symbols I type _unless_ there is a clear trigger/token for doing so.
    * This includes messaging programs, browsers, email programs, music management software, text editors, and numerous other categories of software.
    * Messaging programs and text editors are two oddities in that both sometimes may **offer** completions or replacements using tab/enter as a key to accept the change, but these changes almost never occur automatically without the user's distinct input acknowledgement.

## Broken Expectations

While the character replacements in Telegram may be viewed as useful by some, there's no denying that they go against these expectations that I believe many of us hold.
Yes, you're providing a way to quickly undo the replacement, but I would argue that it's significantly more sensible to present a way to quickly **make** the replacement.

Take a look at GitHub's token system for example.
If everytime someone typed the word `laughing` it was automatically replaced inline with 😆, people would riot.
However, by tokenizing that replacement with `:laughing:` instead, they ensure that the only time they're doing text replacement is when a user has explicitly informed the system that it would like such replacement to happen with the surrounding `: :` tokens.

This gives the user explicit control over how the messages they send are presented, rather than having to constantly tell the system that it made the incorrect assumption.

## Final Thoughts

I would request that you give this some more consideration.

At the end of the day, I still feel strongly that this feature is not just undesired, but actively frustrating for a specific chunk of the userbase.
More importantly, I still believe that we're not being unreasonable as to why it's frustrating for us.

#4553 already attempted to implement the setting for you, but you seem rather averse to a setting given the state of the settings menu which makes sense to me.
I believe that the number of people bothered by the removal of this autoreplacement is probably extremely small, especially since it only applies to a select few character combinations.

Again, thanks for all your hard work and don't let the angry mob get you down.
Just because we're opinionated doesn't mean we can't be rational, and I hope you can see why we're convinced that keeping this feature is more irrational than rational.

**Comment by EmuAGR** [comment]
Sometime around the start of June I started to miss the << conversion to «! That autoformatting is useful in Spanish, we use that symbol for quotation!

If you want to keep code as is, use the triple back accent ```...

**Comment by k3a** [comment]
If you need the automatic "<< conversion to «" then there is something wrong in my opinion. Maybe you should have a « key on your keyboard then.

**Comment by EmuAGR** [comment]
My keyboard is a ISO-Spanish standard one. It doesn't include the "« »" characters.

This was a nice feature from Telegram to us, in a tiring English-centered world. By recommendation of the "Royal Spanish Accademy", angular/latin quotation marks are preferred:
http://lema.rae.es/dpd/srv/search?id=SSTAZ5sDyD6h59vijX

**Comment by john-preston** [comment]
@EmuAGR If you have "Replace emoji" enabled in Settings those replacements (<< to « and >> to », together with -- to —) should work right while you type.

**Comment by EmuAGR** [comment]
Thank you for that tip. I wanted the feature as before best, but I think this is a fair tradeoff.

**Comment by hertell** [comment]
As @joshsleeper pointed out, there are people who have expectations on how different applications behave. What drives me nuts are those applications who try to outsmart their users in any way. Eg Msword beautifies the text people write by default, but luckily this can be disabled without any problems.

I would though say that creating any application that tries to outsmart their users are completely on a wrong track. That will never satisfy all of the users and there will always be someone who will not be happy. That's why I have the strong opinion that anything that gets autocorrected should not do that by default. For example domain-names containing unicode-characters can be rewritten into punycode (the name translated using just pure ascii-charactes) by people not being able to write those characters. So what would happen if someone would be writing an URI in punycode like http://xn--caf-dma.eu (http://café.eu)? Telegram would send this user to either a non-existent site or a completely wrong site!

**Comment by hertell** [comment]
@wsxy162 Exactly!!

**Comment by ruv** [comment]
Regarding Settings at all (yes, they already need a "search in settings" functionality), why don't have just a config file with all these rare or very special options (in addition to the already exists `shortcuts-custom.json`)?

**Comment by blacklat** [comment]
> Because it's not an issue for some people
> 
> It's a feature, not a bug

you're wrong, if the character shown is different from the one provided it is an error

**Comment by ralesk** [comment]
Vaguely related is the replacement of ®, © and ™ with some emojis that are :registered: :copyright: and :tm: — those three emoji not only shouldn't exist (every semi-modern character set and font since the 90s has native ®, ©, ™ marks), but also they look jarringly different from the text itself.

Unfortunately this fad is massively popular elsewhere as well (Discord forcibly replaces too, upon entry).

**Comment by CyberMew** [comment]
Wow. Just got email update for this. 5 years since my post and this thread is still going strong 💪 😂 😂

**Comment by albertnetymk** [comment]
When I share text containing backtick (`) between my PC and phone, the lack of options to turn this off does feel annoying. Plaintext is enough for me.

**Comment by ralesk** [comment]
@alvgalrus I just noticed this part from your comment but I want to answer it because it's unrelated to the bug (or any fixes to the bug)

> Also, packed with this change, I found that when I type "~", the editor shows a long line,
but the chat shows it fine.

This is a Freetype issue with some fonts (at some sizes), mainly at Slight hinting — I've never seen it happen in Windows at least.  It's much more common with the tilde accent on letters, where it looks like a macron instead.  See #950 or #27 here, or https://savannah.nongnu.org/bugs/?23537
