### ISSUE TITLE
[Feature inquiry] "Last Seen" referring to general use rather than only Telegram use?

### ISSUE THREAD

**Issue by rpodric** [telegramdesktop/tdesktop#5260]
### Steps to reproduce
1. Both parties enable "Last Seen" in Settings.
2. Variously use and don't use Telegram for chatting, observing the "Last Seen" time.

### Expected behaviour
To have the option for the "Last Seen" counter to consider the use of the mouse/keyboard--anywhere in the OS, not just with Telegram--in determining its "Last seen" time. This is the way Skype, Skype for Business, and some others have done it for a long, long time.

Is this something being looked at for the future?

### Actual behaviour
Telegram considers only use of Telegram itself. If you're not doing something with it, you're not there, as far as the other party knows anyway. But of course you often are there. Like many, most of the time I'm not doing something actively with Telegram, so it appears to people like I'm pretty much always away.

### Configuration
Windows 10

**Version of Telegram Desktop:**
1.4.3

**Used theme**:
Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by stek29** [comment]
Telegram's approach to "Last Seen" is a bit different from Skype/Discord's -- and I doubt it's going to change.
Even if it is, it would be a change which affects platform as a whole -- because meaning of being "online" would be completely different -- and because of that should go through in-app support or twitter.
