### ISSUE TITLE
emoj `:flag_my:` -  wrong pic

### ISSUE THREAD

**Issue by GoLangsam** [telegramdesktop/tdesktop#5323]
### Steps to reproduce
1. Enter `:flag_my:`
2. Look
3. Wonder

### Expected behaviour
Tell us what should happen

I should see the [Burmese flag](https://en.wikipedia.org/wiki/Flag_of_Myanmar)

### Actual behaviour
Tell us what happens instead

I see some US Flag

### Configuration
**Operating system:**
M$-Win7

**Version of Telegram Desktop:**
1.4.3

**Comment by RememberTheAir** [comment]
[Works correctly on 1.4.4 beta](https://my.mixtape.moe/nelmji.jpg), which includes some emoji improvements over 1.4.3, according to its changelog. I assume this will probably will be fixed once the stable release will be updated too

**Comment by GoLangsam** [comment]
thx - I'll keep an eye on it
@RememberTheAir

**Comment by RememberTheAir** [comment]
Lol right, I'm sorry. That sun + moon + stripes fooled me

**Comment by DaFri-Nochiterov** [comment]
You shouldn't see [Burmese flag](https://en.wikipedia.org/wiki/Flag_of_Myanmar) flag because `🇲🇾` is [the flag for Malaysia](https://emojipedia.org/flag-for-malaysia/).

For Burmese flag combination of [`🇲🇲` is used](https://emojipedia.org/flag-for-myanmar/), means it is `:flag_mm:` in any client that supports text shortcuts for emojis.

**Comment by GoLangsam** [comment]
@DaFri-Nochiterov
How blind I was - shame on me!
:bowing_man:
