### ISSUE TITLE
Fix security risk because of ambiguous characters in current font

### ISSUE THREAD

**Issue by AoDev** [telegramdesktop/tdesktop#5353]
### Expected behaviour
Telegram should display text without ambiguous characters.

### Actual behaviour
The current font displays ambiguous characters like the letters `i` and `L`.
**Usernames and websites can be spoofed** by exploiting this characteristic of the current font.

- Some Telegram users get scammed.
- Some Telegram users lose money.

### Suggestion

- Use a default font without ambiguous characters.
- Let people change the font.

This is a very simple change that can greatly improve the security of Telegram end-users and would be a good selling point for the platform, showing it cares for users security.

### Configuration
**Operating system:** Any (OP uses OSX)
**Version of Telegram Desktop:** Any (OP uses 4.5.1)
**Used theme**: Any (OP uses "Day classic")

**Comment by john-preston** [comment]
@AoDev I don't understand. You suggest not displaying letters 'i' and 'L'?

**Comment by AoDev** [comment]
@john-preston No. I am saying to not use a font with ambiguous characters.

i and L look the same

This is a screenshot from Telegram:

<img width="167" alt="screen shot 2018-11-05 at 13 18 18" src="https://user-images.githubusercontent.com/1526150/47997777-53ad1580-e0fd-11e8-9775-8664d4bda147.png">

But the reality with an unambiguous character fonts is obvious:

<img width="212" alt="screen shot 2018-11-05 at 13 19 31" src="https://user-images.githubusercontent.com/1526150/47997843-8ce58580-e0fd-11e8-9672-4661ee0c2efc.png">

Scammers use this to present themselves as someone they are not.

**Comment by john-preston** [comment]
@AoDev All modern UI fonts show 'I' and 'l' very similar (see default Android, default iOS, default macOS, default Windows 10).

The default font can be switched to something completely different (like your screenshot) because of that issue. Maybe some day custom fonts will be available for tdesktop, some users will be able to fix that for themselves in that case.

I think it is a good idea to stop giving money to someone based on their name appearance on the screen.

**Comment by AoDev** [comment]
> I think it is a good idea to stop giving money to someone based on their name appearance on the screen.

The problem is a bit more subtile than that. The particular case where I have seen this, but not limited to it, is when people look for technical help in community channels.

Scammers will present themselves as an admin (using ambiguous characters) and ask the future victim to perform a set of actions that will lead to a loss of assets. But, they phrase their instructions in a way that it sounds legit and like nothing bad will happen, on the contrary, the victim thinks she is being helped.

Unfortunately, the ignorance of the person is at fault here, but we can not put the entire responsibility on her. She came to the channel in the first place to seek help for something she does not understand fully.

Scammers exploit this. This is a vicious circle. The font issue can help break that circle.

**Comment by john-preston** [comment]
@AoDev Sorry, but there is no way the default font will be changed to something like that.

If the victim comes to a group there is an easy way to know if admin writes a message, each message from admin has an "admin" badge. Yes, such radical font changing could help someone not attentive in some rare cases, but this won't justify such font for every other user of the application.

Absolute majority of users will be significantly affected in a negative way without any benefit from such change. They won't ever get in such situation, they don't even manage any "assets" in Telegram, they just chat with their friends / relatives / collegues.

**Comment by AoDev** [comment]
Sure, then, just let people change the font and the different communities may setup guidelines for their users with a recommendation.

**Comment by Aokromes** [comment]
maybe one easy workaround is show all uppercase / lowercase usernames to stop scam and a bit larger font on profile and show username next to name on chat.

**Comment by stek29** [comment]
@AoDev then they'll put "Username: IamTheRealUser" in their bio and catch some people like that.
Sorry, but it's user's fault if xe's stupid.

**Comment by AoDev** [comment]
@stek29 
> Sorry, but it's user's fault if xe's stupid.

First, you are not "sorry" when you say something like that. If you were "sorry" you wouldn't say it in the first place. It just allows you to follow with something condescend about people.

Second, people have always made stupid mistakes when out of their confort zone.  I hope you behave perfectly in every new situation you face.

Third, I didn't suggest a complete rewrite of the Telegram app. Just presented a case where being able to change the font would help prevent hundreds of people from being scammed every day in the groups I've been. Other people have also been asking to be able to change the font for other reasons like simple aesthetic. So it's a feature that is wanted.

**Comment by stek29** [comment]
Let me rephrase it: it think it's user fault if user doesn't check that he is talking to someone trustworthy when it's about something that can lead to money loss. It's not different from phishing emails -- if you go and give out your password to some site without getting sure it's the site you are looking for, then it's your fault. And that's what I call stupid.

I used to fall into such traps before, and I probably would do it again in future. And that would be a stupid thing for me to do.

Regarding the case you have mentioned -- admins have "admin" label in chat.
You can easily create a bot which checks for users with such names and usernames, if you can't do it manually.
You can have guidelines which suggest users to check for admin label before going to private messages with someone.

And I'm absolutely sure there still would be users who'd get scammed. Even if there are such guidelines, even if font is changed to make usernames easily distinguishable.
It would help some users, but not all of them.

Just to make it clear: I am not affiliated with Telegram in any way. I'm not TDesktop developer, I do not work for them, and even if I did, my comments are just my personal opinion, and do not represent Telegram.

This issue has came down to custom font selection: that's why I have closed it in favor of #90.
