### ISSUE TITLE
(Some) Unicode emoji 9 & 10 not displayed

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#5388]
### Steps to reproduce
1. Send this

Emoji 9
🤦 Person Facepalming
🤷 Person Shrugging
🤸 Person Cartwheeling
🤼 People Wrestling
🤽 Person Playing Water Polo
🤾 Person Playing Handball
🤹 Person Juggling

Emoji 10
🧙 Mage
🧚 Fairy
🧛 Vampire
🧜 Merperson
🧝 Elf
🧞 Genie
🧟 Zombie
🧖 Person in Steamy Room
🧗 Person Climbing
🧘 Person in Lotus Position

### Expected behaviour
See them as emoji

### Actual behaviour
Can't see them as emoji

### Configuration
**Operating system:** Win 10

**Version of Telegram Desktop:** 1.4.7 beta

**Used theme**: dark

**Comment by NonnEmilia** [comment]
It's curious because with tdesktop 1.4.7 beta on Windows I found those emojis in the emoji panel (and I can send them), but doing a copy-paste from the list it shows me the system emojis...

![immagine](https://user-images.githubusercontent.com/2818194/48570258-3dc10100-e904-11e8-8b2d-f1d269c680f4.png)

On the right of the screenshot you can see the copy-paste from the above list then three emojis found and sent from the emoji panel.

**Comment by NonnEmilia** [comment]
The previous screenshot was not really clear, but the vampire lady was the standard one.

I post am updated screenshot with emojis without skin colours.

I noticed also that when I pase an emoji, like the "thumb up" one, from web to the input text it is "converted" in the tdesktop font; when I paste an emoji from the list above it remains in the b/w font.

![immagine](https://user-images.githubusercontent.com/2818194/48580938-c9e12180-e920-11e8-9d55-57ae90858fff.png)

**Comment by ArmeF97** [comment]
It's the same, the vampire lady is a lady, so there is the gender character next to the vampire one, I think that's the issue here

**Comment by brftalkmst** [comment]
Also, didn't feel like I needed to start a new thread since it's about special characters, the special text characters are no longer visible from tdesktop whereas a few updates ago they were as well. The characters are visible on mobile and web but not desktop even though some Windows user say they can and have confirmed it. I see squares in stead of the text.

**Comment by ArmeF97** [comment]
Maybe it's fixed in https://github.com/telegramdesktop/tdesktop/commit/ec2a1b3ddbd46bcf694b583caa2ee7b25f0f9cc6

Someone please test it :+1:
