### ISSUE TITLE
Ctrl+Delete is broken on 1.4.8-1.5.1

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#5453]
### Steps to reproduce
1. Type anything
2. Get to beggining of word
3. Click Ctrl+Delete

### Expected behaviour
The word in front of text cursor should be removed

### Actual behaviour
Nothing

### Configuration
**Operating system:** Windows 10 1803 Home

**First known version of Telegram Desktop with this bug:** 1.4.8 Beta

**Latest version with this bug**: 1.5.1

**Used theme**: Midnight

**Comment by OctoNezd** [comment]
Still broken on 1.5

**Comment by mayorandrew** [comment]
Also broken on 1.5.1. For me it is a very important systemwide hotkey, so sad to see it gone in telegram,

**Comment by LucaRed** [comment]
Still broken on **1.5.1** on both **Linux** and **Windows**. It's very annoying since I use Ctrl+Delete frequently to delete the following word.

**Comment by f1ztech** [comment]
+1 please fix it, very annoying

**Comment by aphirst** [comment]
I can confirm the same behaviour in `1.5.1-3` on Arch Linux x86_64. CTRL+BACKSPACE still works, curiously.

Out of curiosity, I checked the keyboard shortcut wiki (and its history) to see whether this was some kind of intentional removal, but this hotkey is never expressly mentioned, so I figure this must just be a mistake in the newest builds.

**Comment by john-preston** [comment]
@aphirst It was used in-app, I'll fix that in the next build.
