### ISSUE TITLE
ignore user on group

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#552]
How about add one option to ignore users on group chats? :)

**Comment by auchri** [comment]
no api for that

**Comment by Aokromes** [comment]
So... where i can feature request this? :)

**Comment by auchri** [comment]
I just wrote it to the telegram support and a update to groups is "soon" coming :)
I also mentioned #696

**Comment by Aokromes** [comment]
Cool :)

**Comment by Justinzobel** [comment]
Kinda poor that this hasn't been implemented.

**Comment by Aokromes** [comment]
any new on this issue?

**Comment by Justinzobel** [comment]
@Aokromes seems the Telegram devs are completely uninterested in adding this much needed feature.

**Comment by stek29** [comment]
@Aokromes I think the main concert is the fact it breaks conversation, and has other bad side effects.
And tbh I doubt it fits feature philosophy.
But I can't relate at all because I have no users in my blacklist (except nasty bots) :D

**Comment by wchristian** [comment]
@stek29

Would you at least be willing to provide some guidance for enterprising experimenters to hack this in on their own? I tried figuring out which source files relate to rendering of only the chat, but due to the profusion of files, vague naming, lack of in-file documentation of purpose, and lack of overall file-purpose map have so far failed to do so.

I guess this could be indirectly seen as an inquiry on whether the docs could be improved to help on-board contributors?

(Note: I don't have recent experience with cpp, but lots of it with other languages, so this is not a mere hypothetical.)

**Comment by stek29** [comment]
@wchristian Wish I could XD

If it was me, I'd start with looking up lang key for "edited", then seeing where is that rendered, and then go up until you find method you need :)

**Comment by wchristian** [comment]
@stek29 Good suggestion, also since i didn't miss one, i guess i'll ask for docs on this to be made. :)

**Comment by Justinzobel** [comment]
@wchristian let us know if you fork it, I'd be interested in a more useful Telegram client that doesn't require hacky qt patches to build :)

**Comment by stek29** [comment]
@Justinzobel There are lots of ways to do it already: look in AUR for examples
