### ISSUE TITLE
Ability to remove the @ sign

### ISSUE THREAD

**Issue by OctoNezd** [telegramdesktop/tdesktop#5527]
On phone I can hold the @ icon and it will forget about all mentions, including voice ones. 
But tdesktop has no such feature

**Comment by stek29** [comment]
> including voice ones

What do you mean?

**Comment by OctoNezd** [comment]
When someone replies to your message you cant remove the mention icon unless you listen to voice message

**Comment by OctoNezd** [comment]
![image](https://user-images.githubusercontent.com/15308404/50690468-7d6fb380-103e-11e9-9637-ba3bdcb2e537.png)
I talk about this icon

**Comment by Edicksonjga** [comment]
https://github.com/telegramdesktop/tdesktop/commit/b00ca217b3d95a161030f20884abed09c58df5c8

**Comment by john-preston** [comment]
@Edicksonjga Why do you want to hold the icon and not listen to the voice message?

**Comment by Edicksonjga** [comment]
I do not want to keep the icon pressed. Maybe @OctoNezd prefers two taps in "@", instead of one in "Play". I like how it is now.

PD: Telegram crashes after right clicking on the label inside the pack (right click does not perform any function), hide the panel of the sticker pack by right clicking anywhere inside the panel.

**Comment by ilya-fedin** [comment]
> Why do you want to hold the icon and not listen to the voice message?

Some people uses that "feature" for trolling. They just spam you with voice messages and you should to listen them all.

And I just don't like to listen voices.
