### ISSUE TITLE
Monospace hebrew text with ctrl+shift+M not working

### ISSUE THREAD

**Issue by mugavri** [telegramdesktop/tdesktop#5558]
### Steps to reproduce
1.  select text in hebrew charters
2. push on ctrl+shift+M

### Expected behaviour
the text Should be Monospace format

### Actual behaviour
the app is minimize...

### Configuration
**Operating system:**
win 10 1803 pro

**Version of Telegram Desktop:**
1.5.5 beta

**Comment by 23rd** [comment]
Can't reproduce.

**Comment by mugavri** [comment]
why?

select this text : "שלום עולם" (ctrl+A)
and then cntl+shift+M

**Comment by 23rd** [comment]
![image](https://user-images.githubusercontent.com/4051126/50742700-cf236400-121f-11e9-8c97-e77738a3155d.png)

**Comment by mugavri** [comment]
you did with cntl+shift+M ?

**Comment by 23rd** [comment]
Ctrl + Shift + M.

**Comment by mugavri** [comment]
![ctrl shift m](https://user-images.githubusercontent.com/12531879/50742897-9a141300-1219-11e9-8637-7eb41533fe56.gif)
show here.
now its minimize even in english if i copy text in hebrew ro clipboard

**Comment by MasterGroosha** [comment]
I checked with both **1607** and **1809** builds of Windows 10 LTSB/LTSC and for me it works fine (text becomes monospaced). Maybe there're any problems with regional settings? I'm using Windows in Russian with Russian regional settings.

**Comment by arieljannai** [comment]
Came here to add about this issue, since I'm also facing it:
**The problem occurs if the keyboard is set to Hebrew** (I guess that it's the same for other non-latin based characters), **no matter the language of the text**.
If I'm using Hebrew right now, and I'm pressing <kbd>Shift</kbd> with the button where <kbd>M</kbd> and the Hebrew letter <kbd>צ</kbd> sits together, the result will be just `M`, it behaves like turning on the <kbd>caps lock</kbd> for one key press. So Basically, the <kbd>Shift</kbd> is "lost" and we get <kbd>Ctrl</kbd>+<kbd>M</kbd> which minimizes the app.
I'll try to add a recording of it

**Comment by damnfella** [comment]
Wanna know how you fix this issue OwO

**Comment by damnfella** [comment]
@stek29 , I think **this issue can be reproduced** only if you use Hebrew as your **system locale.**
Please give this issue an appropriate label.


I wanna know how this issue gets fixed OwO

**Comment by arieljannai** [comment]
Still relevant

**Comment by ilya-fedin** [comment]
#4977
