### ISSUE TITLE
Feature Request: Privacy Settings (Last online time disabling) for PC

### ISSUE THREAD

**Issue by AryanShadowhunter** [telegramdesktop/tdesktop#560]
Add privacy options in settings panel (for example: Enable/Disable the "Last online Time")

**Comment by cobalto** [comment]
Yes, more Telegram options being accessible from the desktop client is a good thing, not crucial, but a good thing.

**Comment by AryanShadowhunter** [comment]
"Privacy" is strongly crucial for me.

**Comment by cobalto** [comment]
I wrote "no crucial" considering that Telegram is mainly mobile, you need a phone number after all, and this configuration is propagated to the desktop app even without the option to change it there, not as it was not important the desktop app to have it.

**Comment by eduardomezencio** [comment]
I think this is really crucial, because some people (like me) don't even use android/ios/whatever phones and access telegram only from the pc. We have no way of accessing that configuration, as far as I know

**Comment by shabidoo** [comment]
I've clicked on the "duplicate links" for all of these posts. It seems that all of them have been closed....however no one has given any answers as to why this isn't being implemented. They all sort of link to one another in a circle where you are referred to other pages where nothing has happened.

#1285 refers to #560
#1290 refers to #560
#1325 refers to #560
#1584 refers to #560

The on the page #560 we are reffered to:

#1285, #1290, #1325, #1584

Which, as we have seen...all link back to #560

There is one more link on #560 which links to:

#2356 

That's a new page...only that is linked back to #560 (only with a question mark this time).
_________________

It seems as though no one knows what to do or what to say. One of the reasons I use telegram is because I can easily hide whatever details I decide and also so I can easily sign off (which almost no other app let's you do). So it would be nice to be able to hid last seen and online status...on the windows version as well as the android one. I've read one argument in these posts that since the mobile platform is the main one...such settings should be limited to that platform...perhaps because of security. I cannot imagine any reason why toggling "last seen" is some kind of security threat or an essential setting that should be accessible only when logged on a phone directly connected you the telephone number associated with the mobile. I would definitely like to have this setting on the PC

**Comment by john-preston** [comment]
@shabidoo It works on PC when you edit it from mobile, so it is not a big deal — just change it on mobile and that's it. I agree it should be added some day, but currently it can be a problem for those, who use only desktop and nothing else and even doesn't have a phone supporting telegram.

**Comment by stek29** [comment]
@john-preston It can and it is: I have a friend with no smartphone.
He solved it with android emulator.

**Comment by edmundlaugasson** [comment]
There are many other privacy issues, look this comparison - https://www.securemessagingapps.com

**Comment by stek29** [comment]
@edmundlaugasson How is that link related to this particular TDestkop issue?

**Comment by sergeevabc** [comment]
People of my circle use classic phones, not smartphones, to stay less distracted.
So there is no way for them to set up Last Seen setting, however it is crucial for privacy.
Please, be so kind to add it to Telegram Desktop.

**Comment by john-preston** [comment]
@sergeevabc It is available in the alpha version already, please try it out from https://desktop.telegram.org/changelog#alpha-version

**Comment by sergeevabc** [comment]
@john-preston, thank you, sir. It works.
