### ISSUE TITLE
[Feature Request] Ability to hide the title bar on Gnome.

### ISSUE THREAD

**Issue by Miesvanderlippe** [telegramdesktop/tdesktop#5648]
### Configuration
**Operating system:**
GNOME Shell 3.22.3
Debian 9.6

**Version of Telegram Desktop:**
1.5.11
**Used theme**:
Default dark

### Request
In some apps (like Firefox Quantum and VSCode) you can disable the titlebar, or use it to house the menu's. This way, an app takes up way less vertical space. Also, the titlebar isn't themed with the app so it's really ugly. 

To do it in Firefox Quantum go to menu -> customize -> uncheck 'title bar'

**Comment by paulomanrique** [comment]
+1, this feature is welcome.

**Comment by Hax7** [comment]
This feature would be nice, actually I've been reading in Gnome wiki about switching to header bars instead of title bars and using something called CSD(client side decoration), you can read more about it here https://blogs.gnome.org/tbernard/2018/01/26/csd-initiative/ there is even a mockup for Telegram desktop client.
![image](https://user-images.githubusercontent.com/18662960/56473042-9e81d600-646e-11e9-8bd2-b501f6856aad.png)

**Comment by stek29** [comment]
Is this #4358 dupe?

**Comment by Hax7** [comment]
> Is this #4358 dupe?

I guess so
