### ISSUE TITLE
[Critical] DNS request while using mtproto will cause crash

### ISSUE THREAD

**Issue by kmahyyg** [telegramdesktop/tdesktop#5693]
### Details

Check here: https://bugs.archlinux.org/task/61757

### Configuration
**Operating system:** Linux

**Version of Telegram Desktop:** 1.5.13

**Used theme**: Default

### Maybe there's a solution

- Change the working flow, **DO NOT THROW SEGV WHEN THE NETWORK IS UNSTABLE, IT'S NOT TG's PROBLEM BUT THE NETWORK's**, open a dialog to notice user when error accumulated to a certain number.

- Telegram is anti-censorship. But the problem is, in China, you cannot use any Google Service except Google maps and Google translate(These server of the two services listed below is running inside China Mainland.) Please change the DNS-over-HTTPS workflow.

I see `QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://www.google.com/resolve?name=<MY PROXY DOMAIN HERE>&type=1")` in the gdb session, two issues here:

1. `www.google.com` cannot be used for chinese.
2. The DoH Domain is `dns.google.com` instead of `www` one.

Seems that the related code is here:

https://github.com/telegramdesktop/tdesktop/blob/0f4909621b079cd3be4599f55e39587dc122fc1e/Telegram/SourceFiles/mtproto/special_config_request.cpp#L45-L53

**Comment by kmahyyg** [comment]
By the way, the code of `mtproto` seems have a lot of critical bugs, you may need to re-examine them.

**Comment by john-preston** [comment]
1. I don't understand why Qt segfaults in its Network implementation :( Perhaps it can be fixed somehow in Qt. Or maybe I use it incorrectly, but I don't know how exactly.

2. The basic google domain instead of dns.google.com subdomain is used knowingly. It works as expected if the basic google domain is available. The request should fail without crashing if it is not available, like it does if the network is disabled on computer in any other country.

3. Please elaborate on the mtproto proxy critical bugs, I have no idea about those.

Fixing PRs are always welcome.

**Comment by john-preston** [comment]
It looks like I've found a good crash report, perhaps I'll be able to find the problem. I'll try to look into that within a week.

**Comment by kmahyyg** [comment]
Any progress? Thanks for your hard work.

**Comment by john-preston** [comment]
@kmahyyg Not yet, sorry :(

Please elaborate on the mtproto proxy critical bugs, I have no idea about those.

**Comment by john-preston** [comment]
@kmahyyg I didn't find anything for now :(

It looks like that issue: https://github.com/telegramdesktop/tdesktop/issues/5218

And it looks like it is not in tdesktop code :(

**Comment by kmahyyg** [comment]
Thank you. I consider it as a bug in Qt. Another program written in Qt also met this problem.
