### ISSUE TITLE
Downloading/Streaming video

### ISSUE THREAD

**Issue by alisentinel** [telegramdesktop/tdesktop#5781]
Hello, It's a disaster UI design in newest telegram desktop version.
There is no difference between downloaded movies/audio files and not downloaded files.
It really need a difference like telegram android, there should be a button for only download medias and another button for playing it. thanks

Expected behaviour:
Difference between downloaded and not downloaded videos

### Actual behaviour
There is no difference between downloaded media and not downloaded medias

**Version of Telegram Desktop:** 1.5.16 (Beta)

**Comment by john-preston** [comment]
@alisentinel It can be marked somehow. And why do you need to see the difference?

**Comment by RememberTheAir** [comment]
I push for a "download only" option too, similarly to what both the mobile apps have. Before 1.5.16, all you had to do to download a video was just to click on it. Now you either have to play it, or you have to right-click, and select a path where to save the file on disk. That adds extra steps to an already established behavior, "fragments" downloaded files around your disks (not going to find my default Telegram download directory every time I'm going to download a video), and is inconsistent with the mobile apps' experience (that have a "download only" icon - even though streamable content on mobile is more "consume & go" then on desktop).

I know we are still on beta, I just wanted to make sure the dev will at least consider to add an option to only download a video/song without having to fully play it or to manually select a download path.

**Comment by john-preston** [comment]
@RememberTheAir When you fully play it you still don't download.

Why isn't it "consume & go" on desktop? The largest video platform in the world (YouTube) just plays videos, why download them? But you always have the option using Save As.

**Comment by RememberTheAir** [comment]
@john-preston I didn't say desktop is not "consume & go", I said it's less oriented to that when compared to mobile apps (that have a "download only" option anyway)

Anyway, there could be a bunch of reasons to just want to download a file. Eg. my main use case is that my connection is crap and streaming is most of the time useless to me because of buffering, and so it probably is in many countries where internet is not generally fast. So if I wanted to save a bunch of videos to watch later, I have to manually save them every time. It wouldn't be that much of a problem if it always worked like that, but 1.5.16 broke the previous behavior forcing us to take a longer path to just save the file, and this actually is pretty annoying tbh, and easily fixable too I suppose? I don't think adding a small "download" icon next to the "play" one would be a big deal, and also would be consistent with the mobile apps. I ignore all the background download details so it might not be this trivial

**Comment by alisentinel** [comment]
@RememberTheAir 
Anyway, I think it's better to follow telegram android mechanism, I hope u add another button for downloading medias, I think it's very necessary

**Comment by mehti1367** [comment]
In another word: Show download button on mouse hover around videos

**Comment by RememberTheAir** [comment]
❤️
