### ISSUE TITLE
Missed voice, audio and video options in automatic download settings

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#5789]
### Steps to reproduce
1. Settings - Advanced - Automatic media download

### Expected behaviour
Voice messages, audio and video options should be visible

### Actual behaviour
Only photos, round video messages, files and gifs are visible

### Configuration
**Operating system:** Windows 7, Arch Linux

**Version of Telegram Desktop:** 1.5.17 beta

**Used theme**: Any

**Comment by john-preston** [comment]
@aNNiMON This is intended. They're streamed now, so no need to download them first. Voices for example were not even downloaded to a file, only to an internal encrypted cache, like now with all streamable data.

**Comment by aNNiMON** [comment]
@john-preston just noticed that mobile clients have almost the same options
![image](https://user-images.githubusercontent.com/1321838/54354072-619c1580-465e-11e9-8eb8-7098d9d3b1a4.png)
But videos option still exists. In mobile clients they streamable too.

**Comment by john-preston** [comment]
@aNNiMON This is because mobile apps are downloading files to actual real files while streaming them. But in tdesktop streaming is done by caching file parts in a special media cache, that takes exactly the space that is needed for the parts of the video you've watched. The side effect is that for now you're either watching streamed video or you're downloading it to a file in your Downloads folder, not both at the same time. So automatic downloading will prevent you from watching the videos you've just received until they're fully loaded.

**Comment by aNNiMON** [comment]
Thanks for explanation and for such a great long-awaited feature :+1:
