### ISSUE TITLE
[Feature Request] Show local time (zone) when private messaging someone

### ISSUE THREAD

**Issue by rusins** [telegramdesktop/tdesktop#5806]
People can get annoyed if you send them a message while they're sleeping. It would be useful if you could see the local time for the person you are messaging based on their time zone. Here's a mock-up of how it could look:

![time](https://user-images.githubusercontent.com/3919420/54491301-ab366b80-48bd-11e9-9dc2-512a8203d745.png)

**Comment by xvitaly** [comment]
This will a potential privacy breach.

**Comment by rusins** [comment]
Just like you can toggle which people can see your "last seen" status, you should be able to set which people can see your time zone. Seems simple to me.

**Comment by RememberTheAir** [comment]
I don't think it's a good idea to have one more item in the settings for such a niche need, especially now that we are going to get two new privacy settings options (forwards/profile picture privacy). Also would create many false-positives for people connecting from countries where Telegram is blocked (eg. Iran, Russia) that have to tunnel their traffic through a VPN

**Comment by rusins** [comment]
I suppose you could use the same "last seen" privacy toggle for this as well, as they're very similar.

**Comment by FelixFurtmayr** [comment]
I would appreciate this feature very much. Every time I have to look the time up for the other country it takes me 30 seconds, where it could be just displayed there.

Maybe only specify a country for the other person? No need to transfer further info from them.  In this case the time could be wrong if the other person changes location. But it would still work in 95% of my cases and without any privacy violation.

**Comment by FelixFurtmayr** [comment]
I guess the layout suggestion of rusins is good, as I put the time in the same spot when I just opened another issue for this feature ;-)

**Comment by yashpalgoyal1304** [comment]
migrating over from https://github.com/telegramdesktop/tdesktop/issues/8269#issuecomment-663341855

I was thinking of such a feature from quite a long time. It would help me immensely when talking across time zones and would reduce lengthy discussions regarding times and reduce misunderstandings.

Also, this can be made approximate, for example in a range of 45 minutes maybe??

I was very happy to discover that such a feature already exists in some software. Giving example from [RocketChat](https://rocket.chat/) instance : https://chat.inkscape.org/channel/inkscape_user

![goCgTTsvjN](https://user-images.githubusercontent.com/19423063/88360561-c360a980-cd93-11ea-8489-de7b5d242285.gif)

**Comment by FelixFurtmayr** [comment]
One field to specify a timezone for the other person - that's it. Just like I can give a nickname for them. No security issue, as it will not fetch something from them.

I'm also still interested in the feature.

**Comment by ilya-fedin** [comment]
> One field to specify a timezone for the other person - that's it.

This is a client-only bugtracker, while your feature request needs to be implemented on server side. No one who can implement this hears you.

**Comment by FelixFurtmayr** [comment]
Let me summarize - only to see if I understand correct:
No argument on the feature itself, but concerns about possible implementations (which are not really discussed yet).

In my opinion it is good to first discuss the advantages of a feature. None of my customers buys "software" from me, they all want a solution, a certain case to be solved.  I also have to close many tickets. Still I will try to answer in a productive way or tell why something is low prio and give a reason for that.

Like  yashpalgoyal1304 moved his topic here, I also was told to move it here. I get now the impression, that there is no discussion wanted, as there is little discussion on the feature itself.

The reason why I take the time for it is because I see the feature as important (6 other people I know will be very happy with it) and I consider telegram to be one of the best messaging apps. Therefore I spend time here. For now you are just convincing me to not spend my time.

**Comment by Aokromes** [comment]
> Like yashpalgoyal1304 moved his topic here, I also was told to move it here. I get now the impression, that there is no discussion wanted, as there is little discussion on the feature itself.

well, like you have realized, this ticket is still open even if it needs server side implementation to avoid duplications, but to be clear, i doub durov will give ok to such feature.

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
