### ISSUE TITLE
Enter key confirms emoji suggestion instead of sending the message

### ISSUE THREAD

**Issue by deselect** [telegramdesktop/tdesktop#5927]
The problem is with unwanted replacement of text smiles to emojis.

When typing text smile (like ":)") in the middle of the message, emoji suggestion bar appears, but disappears immediately when I continue typing, it's OK.

But everything changes when I finish my message with ":)" - emoji suggestion bar appears, I press Enter key to send my message but instead it works like confirmation for emoji suggestion, and I get emoji in text field instead of message being sent.

Version: Telegram Desktop 1.6.7 on Windows 10 1803 x64.

**Comment by john-preston** [comment]
@deselect It always worked that way, enter selects the first item of the suggestions. Maybe some specific ones should be removed, like ":)".

**Comment by john-preston** [comment]
@deselect You can always disable emoji suggestions in Settings.

**Comment by luixo** [comment]
@john-preston 
Disabling emoji suggestions doesn't work. Apparently the bug is in this option, because before the update I wasn't even aware emoji suggestions exist.
This started to occur only in the latest versin of Telegram Desktop (5.1.1 166798).

**Comment by john-preston** [comment]
@luixo Current Telegram Desktop version is 1.6.7, so I'm not sure 5.1.1 is a correct version number.

**Comment by Aokromes** [comment]
@luixo  you look to use telegram macos, not telegram desktop.

**Comment by luixo** [comment]
That's true, my bad.

**Comment by Pecon** [comment]
It feels like the emoji selections just need a different control flow for them. I generally want to be able to lookup emojis by their name, so I keep emoji suggestions enabled. But, as stated in the issue it makes things awkward when I want to write a normal emoticon. Perhaps the list of emoji suggestions could show up but start without focus by default? So instead of hitting enter immediately selecting the emoji, you would need to hit the right-arrow (or hit tab to use the first selection like it currently does).

This could probably warrant an option in the chat settings.

**Comment by john-preston** [comment]
@Pecon If right now I just remove selection by Enter it will break behaviour for all, who use suggestions (not ":)", but some words, like typing ":lik" or something similar) and pressing Enter. So I think maybe remove just ":)" suggestion at all.

**Comment by nuclight** [comment]
For 2.1.13, the behaviour of title is still actual, after : and emji name hitting Enter does replace to Emoji. However, with both ":)" and ":-)" the are not replaced by Enter. Probably bug is not actual anymore.
