### ISSUE TITLE
Warn users about the switch to supergroups

### ISSUE THREAD

**Issue by mirh** [telegramdesktop/tdesktop#5977]
I'm not here to argue with your [internal policies](https://telegram.org/blog/permissions-groups-undo) or anything, but the difference between "basic groups" and supergroups is not just something "technical" which the final user shouldn't even have to care for. 

For example, I'm now getting the administrator [badge](https://github.com/telegramdesktop/tdesktop/commit/85b3d3f64d5cc7b82a00ce402445c2568fd67eb3) in my plain group of friends, just for having cluelessly experimented once in the past with permissions. 
And I guess like should I ever want to quit from it, it wouldn't be the same thing to "clear and exit" versus just "leave". 
(I also am not the [first](https://github.com/telegramdesktop/tdesktop/issues/5593) being [baffled](https://github.com/telegramdesktop/tdesktop/issues/5642) from this)

With no way of ever switching back, it seems something still very important to point out.

**Comment by john-preston** [comment]
@mirh Difference between "Delete and Exit" and "Leave" will be in the fact that if you join back and the setting is "Show old history to new members", you'll see the old history.

I'll ask about the badges. The idea was to make just "groups", without confusing destinction.

**Comment by mirh** [comment]
I mean, that's laudable if the only difference is really exclusively absolutely technical (I seem to remember humongous groups required a different kind of handling server side?). 
But if there are actual user-facing differences, and ***especially*** with no damn way to switch back, that's no good.

**Comment by Lonami** [comment]
Would it help if tdesktop created supergroups directly? At least there would be less surprises on these "implicit upgrades".

It surprises me that normal chats are still around, really. Sounds like a burden to maintain.

**Comment by john-preston** [comment]
@Lonami There is a reason for that burden. There is a hard limit on amount of supergroups one user can be part of.

**Comment by Lonami** [comment]
Ah, right, probably due to how updates are delivered to supergroups instead of normal groups. So getting rid of normal groups is not really an option it seems.

**Comment by mirh** [comment]
Supergroup or normal group is not really the point. 
It should be having them work just like you want. 

And if there's no way not to have needless admin badges in your plain family chat, and if for the love of god there's no way to switch back to a normal one even once you do away with all the amenities you may have tried for fun.. Then there should be a warning at least.

**Comment by john-preston** [comment]
@mirh I’m afraid the solution would be to add admin badges to normal groups 🙈

**Comment by Lonami** [comment]
@mirh if you hate admin badges so much, you can use a custom language pack with them removed.

**Comment by mirh** [comment]
It's not really much for some OCD reason, it's more about not appearing as god in every single one of your messages. 
And, to another level, it add useless noise/complexity to the chat, yes.

**Comment by mirh** [comment]
So.. this is an api issue then 
(even though I wouldn't have thought this to be considered a backend matter)

_What gives?_

**Comment by wzyboy** [comment]
A little OT here since it's more of Telegram Android / iOS issue, rather than a Telegram Desktop issue, but I could not find anywhere else to share my experiences with the surprise of "implicit upgrades".

My friend and I had a nice and old small group. There were only three members: my friend, me and a bot. One day my friend asked me if I could give her admin rights. I tried to toggle the settings, and suddenly the group was converted to a supergroup.

We did not know what happened at first (not until I inspected the JSON events output by Telegram CLI). We quickly found that we cannot reply nor pin old messages before the conversion. On Telegram Desktop, when you try to reply to an old message, you get an error:

> You cannot reply to a message that was sent before the group was to a supergroup. Do you wish to forward it and add your comment?
> [CANCEL] [FORWARD]

But on Android / iOS, when you try to reply to an old message, you just implicitly forward it.

Also, you could jump to old messages by clicking dates on Telegram Desktop, but not on Android. You could only scroll line by line, until you find you old message. You'll even get an error "message does not exist" when you try to jump to old history from shared media screen.

I agree with the OP that users (admins) need to get a warning before the converting.
