### ISSUE TITLE
api bot no longer sees "leave group/delete group/delete and exit" messages when a chat member deletes a group

### ISSUE THREAD

**Issue by sublimited** [telegramdesktop/tdesktop#5987]
Previous behavior was, as follows:
Bot will see a request from the servers if a person left with a key "left_chat_member",
now, nothing happens.

### Steps to reproduce
ios:
1. create a group with a bot
2. slide channel, in channel list, with the bot in the group
3. press delete

osx: 
1. create a group with a bot
2. press "delete and exit"

### Expected behaviour
The bot should get a request with a json payload from telegram server, just like the "leave group" or "delete and exit" behaves.

### Actual behaviour
Nothing happens

### Configuration
iOS 12.0 (16A366) - telegram v5.6
OSX 10.14.4 - telegram desktop 5.1.1 (166797) Stable

**Comment by RememberTheAir** [comment]
This is not an issue of tdesktop (also I guess you're not even using tdesktop because last current version is 1.7, you're probably using the native MacOS app).

You should speak with [@botsupport](https://t.me/botsupport) about that. By the way, bots do not receive left_chat_member updates when the group has more than 50 (or 100/200, I don't remember) members
