### ISSUE TITLE
Cloud Flare DNS

### ISSUE THREAD

**Issue by minutesinch** [telegramdesktop/tdesktop#6029]
### Steps to reproduce
1. Open Telegram Setting
2. Open Proxy Part
3. You Cant See CloudFlare DNS

### Expected behaviour
Add Cloud Flare DNS in Proxy Part To Telegram Desktop to Avoid Government and ISP Spy Users With DNS Logs and Cloud Flare DNS Help To Have Stable Connection with More Speed Special For Users in Censored Countries That Using MTPROTO, Socks5 and HTTP Proxies.

### Actual behaviour
There is no DNS For Stable Connection

### Configuration
**Operating system:**  Windows 10 1809 (17763.253)

**Version of Telegram Desktop:** 1.6.7

**Used theme**:Default

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by theel0ja** [comment]
Telegram Desktop already uses Google DNS-over-HTTPS, instead of your system DNS server for censorship resistance, as blocking `www.google.com` is nearly impossible without breaking things such as reCAPTCHA.

## Ways to check this

Set proxy address to `whoami.v4.powerdns.org`, port can be whatever you want. See an outgoing connection to a Google IP with that port you set.

For example, `173.194.169.71`

Source code in question: https://github.com/telegramdesktop/tdesktop/blob/a59353df9f93b244c72b93e73224d5eac4f6fee7/Telegram/SourceFiles/mtproto/special_config_request.cpp

**Comment by minutesinch** [comment]
please add cloudflare dns over https on tg desktop
