### ISSUE TITLE
Error when editing a message and pasting a long message

### ISSUE THREAD

**Issue by saranya-vatti** [telegramdesktop/tdesktop#6030]
### Steps to reproduce
1. Visit https://web.telegram.org/
2. Message some,say "abc"
3. Click on the "abc" message and click on Edit
4. Paste a long message that would normally trail to twomessages
5. You see an Error message with "One of the  params is missing  or invalid"

### Expected behaviour
It should split into two messages and paste.

### Actual behaviour
An error is thrown and the message is not edited.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
Version 0.7.0

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

Error snippet
![telegram_errorthrown](https://user-images.githubusercontent.com/9262705/57987448-51c1f880-7a36-11e9-8cad-4d3e22f78f13.PNG)

**Comment by Sasha-Sorokin** [comment]
Sorry to say, but this is unrelated to **Telegram Desktop**. For Telegram Web, please report your issue at https://github.com/zhukov/webogram/issues.

It is worth noting that this is **intended behavior** and the only problem is normal error message missing in Telegram Web. There is no way you can split long message content (>4096 characters) when editing already sent message: it would mean Telegram will have to insert another messages with content parts in chat **history** right after the edited message, which is unsupported and no good to further implement because it's hard and can be abused.
