### ISSUE TITLE
FEATURE: Option to delete all content from a group if member is removed from group

### ISSUE THREAD

**Issue by luisalvarado** [telegramdesktop/tdesktop#6046]
This relates to a security issue between the members of a group and a member that gets removed from it. Cases like a company using telegram for work related activities, events and more, or even managing multiple types of accounts for clients. The needs to have this feature is very important to make sure there is no security related breaches when using telegram.

 
### Steps to reproduce
1. Create a group of 3 or more and add multiple messages to it
2. Remove a member from the group
3. The removed member can still see all of the previous chat content

### Expected behaviour
Offer an option to delete ALL GROUP CONTENT from the member that was removed. As in, if a member is removed from a group, he/she should not be able to still see the content of the group. This includes previous conversations, files, audios, etc including their own messages in the group. As of today, they can still see previous information.

### Actual behaviour
When a member is removed, they can still see previous information.

### Configuration
**Operating system:**
All of them

**Version of Telegram Desktop:**
Telegram Desktop 1.7 but this happens on all devices.

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by RememberTheAir** [comment]
This is not always how Telegram apps behave with the chat history of a removed member.
If a group has not been converted to supergroup, the user will still be able to see the chat history. On the other hand, with supergroups, removed users will not be able to see it.

I don't know if you are familiar with the concept of groups/supergroups - long story short (edit: it turns out it is not so short, duh), until not-so-much time ago there were two different types of groups with different functionalities. Supergroups, being the most advanced type of groups, had more functionalities and it was possible to convert a group to supergroup (but not the opposite: every group starts as normal group, it is possible to convert them to supergroup but not to take a step back). Telegram recently decided to hide this difference and now all groups offer by default what supergroups were offering before. Underneath, there groups and supergroups are still there, but now the apps hide that to users and convert groups automatically when [one of the tools which are available to supergroups only](https://t.me/tgbeta/3424) are used.

The gist here is that you can change someone's permission to trigger the group conversion to supergroup. In this way, when someone is removed from the chat, he's not going to be able to see the history

**Comment by luisalvarado** [comment]
Hi @RememberTheAir thank you friend, I am familiar with the group and super groups, but on both cases (The group am referring to is super group just in case) they can still see the information and there is no option to say "Removed members can't see the previous information from the group".

**Comment by RememberTheAir** [comment]
Mmmm, supergroups disappear from your chats list if you are removed from them. Are you sure the group is not public?

**Comment by luisalvarado** [comment]
> Mmmm, supergroups disappear from your chats list if you are removed from them. Are you sure the group is not public?

Sorry for the late response. Yes the group is not public. It happened on 3 groups. The member was removed from the group but could still see the history of the group on their phone or desktop version of telegram, up until the point when they got removed from the group.

**Comment by luisalvarado** [comment]
Hi friend, just to make sure the idea behind this was understood. The result should be that, if a member is in a group and gets removed, the whole group gets removed from their history too. This can be an option for the admins of the group to avoid security related issues later. This way, the removed member can't see anything in the group, can't see the group or the last messages he/she typed in there. Nothing.

I also read the link provided here and loved your answer there about this whole issue. Thank you.

**Comment by SmartManoj** [comment]
api issue ?
