### ISSUE TITLE
Mac OS - make Telegram start hidden on system boot

### ISSUE THREAD

**Issue by Intenditore** [telegramdesktop/tdesktop#6104]
Mac OS 10.14.5
Telegram 1.7.3
Every time system boots Telegram client pops up on the desktop with no respect to "hidden" setting in user > autostart control panel
Please, fix it or at least add an option to chose, the behaviour is distracting

**Comment by malmentm** [comment]
I have to agree, it's ridiculous that this is not an option yet.

**Comment by hk4140** [comment]
I really got annoyed with this problem too and I've devised a makeshift solution using AppleScript.

```
delay 2
tell application "Finder"'
	set visible of process "Telegram" to false
	set visible of process "Activity Monitor" to false
end tell
```

Open Script Editor, paste the script above and save it as Application and add it to startup applications; You're welcome.

You might want to adjust the delay time as you'd like so that the script does not run before Telegram runs, but just right after it.

Credits to: https://imojito.com/telegram-osx-hidden-startup.html

**Comment by lawdt** [comment]
I have to agree. need to hide telegram to tray at startup

**Comment by soluchok** [comment]
I have this problem as well. Looking forward to the fix :)

**Comment by ilya-fedin** [comment]
Seems to be a duplicate of #1380
