### ISSUE TITLE
[Feature Request] Add geo tag to an already existing group

### ISSUE THREAD

**Issue by ArmeF97** [telegramdesktop/tdesktop#6172]
Like title says, it would be nice to add geo tag to an already existing group

**Comment by RememberTheAir** [comment]
tdesktop doesn't allow you to send your location so I don't think it is going to allow to pick one for geochats either. #1193 was closed because implementing location picking on a multiplatform Qt app is quite a pain. Anyway, three years have passed from the latest comment from the dev so we might expect some news (I'm not optimistic btw). This also applies to #6171 I guess

**Comment by Aokromes** [comment]
i don't think this belongs here, instead api.

**Comment by ArmelliniFederico** [comment]
> 
> 
> i don't think this belongs here, instead api.

Maybe you are right, but we don't know for sure if APIs can do that or not, if they can, the feature request can exist

**Comment by stek29** [comment]
@ArmelliniFederico api doesn’t allow it.

**Comment by ArmelliniFederico** [comment]
@stek29 
Fair enough. Is there any public way to know what apis can do?

**Comment by stek29** [comment]
There are no docs, if you’re asking for them

**Comment by ArmelliniFederico** [comment]
@stek29  
So how can you say that?  Where do you get info?

**Comment by stek29** [comment]
@ArmelliniFederico because I don’t need docs to work with API, I have experience in working with it and I have talked to TG devs about it.

**Comment by RememberTheAir** [comment]
@ArmeF97 btw tdesktop includes in its sourcecode the [latest API schema available](../blob/dev/Telegram/Resources/scheme.tl). Hard to read but you can understand what the API allows to do. It's also what unofficial clients use to generate their internal MTProto types and functions
