### ISSUE TITLE
Secret Chat 

### ISSUE THREAD

**Issue by intika** [telegramdesktop/tdesktop#619]
Following the closed issue without solution 

https://github.com/telegramdesktop/tdesktop/issues/5

Please consider adding secret chat a lot of users are asking for it 

I know you already answered on 

https://github.com/telegramdesktop/tdesktop/issues/118

The main dev seem concerned about privacy problem, and look trust-able regarding it's background, i can't understand why you ignore this so called privacy purpose

Is not the main purpose of Telegram about security privacy and transparency to the user ? then why giving less importance to what's most important ?

I mean a lot of user are asking themselves if we still should trust telegram because of that... 

Any way a perfect privacy solution would be server open-sourced, and installed on a particular server with high security system that is made for that purpose not a classic distro, i doubt it's the case for telegram, but for now i think there is no real secure stuff it's just marketing. (tell me that i am wrong)

At least i think using telegram is less damageable comparing to whatsapp 

Thanks a lot

**Comment by zaxebo1** [comment]
When one more official client of telegram on **MacOSX only - supports secret chat** .

But the generic official client written in Qt(for Win/Linux/Mac) does not supports secret chat. 

If Telegram LLC's one team can themselves implement it officially for MacOSX special client, then **why not other team can implement it for Qt based offical client. They are running on the same protocol.**

**Comment by auchri** [comment]
Duplicate #363 #236 #118 #73 #68 #5 #598 #246 
Use search please before creating new issues!

**Comment by zaxebo1** [comment]
@auchri:
all these issue numbers you listed have been closed. And users there are just venting their frustration on closed issues. 
So intika opened this new issue, so that the developers can read the users demand on this single feature , esp. on #5.
This issue is continuously being opened and reopened in new numbers, is itself a testimonial that you people closing of this feature request is simply wrong.

**Comment by auchri** [comment]
#598 #246 aren't closed

**Comment by zaxebo1** [comment]
Anyway, i don't know if somebody has taken on its ego - to not implement this single feature -for which people are dying. Even if money is raised  on crowdfunding websites for this single feature implementation, still you people will get tens of thousands dollars for this single feature.

Or atleast let there be an official plugin API in the official Qt client, so that people can make their plugin to do this.

**Comment by raistlinmaestre** [comment]
It's a shame it's not implemented yet. I really like the client and I use it more than in my mobile phone for more convenience and easy of use than in a phone, but this is a key feature. At least I can use telegram-cli for secret chats until this gets implemented.

**Comment by namoplasta** [comment]
Unfortunately linux is 1% market share, and all liberal ideology of Ayn Rand is individualistic and egoist and only focuses when it brings personal benefit in the market and demand, then it is normal that developers look with disgust to Linux.

About secret chat will be two implementation modes, or when a competitor does, or when the Valve top Linux in the games and the linux system grow in market share, otherwise do not expect developers look kindly on linux, it is even possible to linux version to be discontinued, it is not the first time this has happened with other applications.

**Comment by SanKro** [comment]
@namoplasta but windows is 95% market share, tdesktop should be around 99% market share and it still is only in the itunes(appstore) client. 

for me they just should get rid of the special appstore OSX client and focus on the Qt Client (tdesktop) because it runs on every plattform and is the defacto standard.

But that would include so much more work - since the "everything in one binary" crap is bullshit on linux and osx, they need to support systemnotifications on linux and osx and need to learn how to implement app-indicators für win, freedesktops (xdg standard!) and osx. 

right now they do everything to force everyone to create an own client.. but maybe thats the plan

**Comment by namoplasta** [comment]
Mac Os is 5% market share, the only explanation for it is because Pavel Durov (Owner of Telegram and VK) is apple fanboy and is a fan inspired in Steve Jobs (See in VK profile.), but the Mac is a very expensive system and in other countries is not everyone can buy, I believe it is a waste of effort in the MAC, as the Telegram has more potential on Linux and Windows QT Client.

**Comment by intika** [comment]
i don't trust telegram any more, and continuing with that politic will make the application die or it will never have a huge public interested in it... 
i think many users me included won't develop an advanced desktop client themselves (with encrypted chat etc) because the server side is closed source. it's like working for someone for free it's not really beneficial to the community.
for sure they started this whole think opensource client side to have less work to do, but was this for a purpose of security and transparency to the user ?! i doubt that right now

**Comment by zaxebo1** [comment]
@intika : i have already reached this conclusion long back, and as a influential social person got all the person in my connection to migrate from telegram . I just hate telegram just because they ditched the users by not implementing secret chat in desktop client. Its better to be back to line, whatsapp - atleast line has voice calling facility and secret chat both.

The way telegram treats its community is pathetically exposed. Hell with it. I replied on this thread because in my email the updates to this and related thread to which I once onaswered, keeps coming. Otherwise i have just hate this super-egoistic attitude of telegram and loathe them

**Comment by squirrelboot** [comment]
It's true that priority needs to be re-considered in terms of the secret chat functionality in Telegram. It prevents users from the seamlessness that makes Telegram so appealing to people in the first place.

**Comment by DW-rocks** [comment]
Why don't you work together with **overtake**? His app provides secret chats: https://github.com/overtake/telegram

Couldn't it be implemented easily?

**Comment by intika** [comment]
@DW-rocks OSX and linux have secret chat implemented

**Comment by zaxebo1** [comment]
@intika : I just tested "Linux" client 0.8.24 , it has secretchat NOT IMPLEMENTED.
Only OSX client has secretchat implemented.

**Comment by intika** [comment]
@zaxebo1 yeah but it's doable with other good clients like pidgin + plugins... regarding windows version where we just have a buggy "cutegram" for that purpose... 
...
We should all put our effort together and create a full opensource secure communication app with end to end connectivity without server and with all features (Skype like/Encryption/Privacy) etc. the fact and the matter is that it's possible without a lot of effort.

**Comment by intika** [comment]
@zaxebo1 here is my skype text me when you are free "intikos" ;)
Nice to see an awaken dev ! :) :+1:

**Comment by DW-rocks** [comment]
@intika Maybe the secret chat is hidden too good for me... I'm using OS X 10.9.5 and I can't find the function to open a secret chat.

Yes! Do something together, that is a very good idea, I'm wondering why so many Open Source developers allways have to "brew their own soup".... If we'd work alltogether for THE SOLUTION (TM) for one problem, we'd kick those corporate a***** before their money & narcism destroys the future of our children.

I can't program but I could translate things, or make some little GFX if needed...

**Comment by auchri** [comment]
Or work on secret chat for telegram desktop? ;)

**Comment by SanKro** [comment]
Just help out Cutegram. sure its buggy in some moments, but its 100% opensource, active, most parts are already in and its easy to help out.

the other part would be to help out the telepathy project with its telegram part...

but just create another client ... :D hehe that would be not worth a thing...

**Comment by zaxebo1** [comment]
@intika  : I think @SanKro suggestion is good one. Cutegram which already has secretchat implemented(which I didn't knew earlier), then it will be good idea to stabilise it.
I will evaluate cutegram by installing it today .

**Comment by SanKro** [comment]
@auchri no. because tdesktop is a mess. just some little things
1. i dont follows any freedesktop/xdg standard
2. it needs a patch for Qt
3. it is build to be a static-integrated binary blob
4. its made to be desktop-independent (it wont follows look and feel of any desktop -> i hate that!)
5. it has an auto updater wich makes it impossible to install systemwide and stay secure
6. while it is opensource - its hard to modify or even to build!
7. telegram for PC is only the unlucky stepchild of telegram for Mac OS X -> nobody actually cares about it -> otherwise there would be no reson to even develop an own client for OS X, but use tdesktop on every PC Plattform -> it's Qt5... 
8. since its the official client -> most bugs and userrequests will be ignored because its just to much
9. as an official client, it will never have some advanced features... look at android where telegram is a official client, but plus massenger is the same with advanced features..

so there are good reasons to support an inofficial client and make it awesome! and right now, cutegram is my favorie on PC Plattforms

**Comment by danger89** [comment]
Bye bye, due to this issue I will leave tdesktop. I have 3 years time to implement secret chat feature. I will use cutegram now.

**Comment by intika** [comment]
i even no longer use telegram lol, it's like giving your stuff to the Russian instead of the CIA... all the same... if the server side is open then only then we can talk about a real secure chat system and even then the used server need review... 
may be an open crypted system that does not need server and use it's own cryptography technology a kind a torrent system... any way we are doomed for the moment...   
to stay on topic ... an other alternative could be https://github.com/majn/telegram-purple/ to use with pidgin...

**Comment by andriusign** [comment]
Truly shame that there still is no secret chats on cross-devices implemented. I guess that many of the answers above convincing not to use Telegram. Sad...

**Comment by Xunius** [comment]
Testing Telegram 1.9.4-0.3 on Manjaro Linux. There is no secret chat option. I guess that many of the answers above convincing me not to use Telegram anymore. Sad...

**Comment by aBARICHELLO** [comment]
For those that are looking for using secrets chats on Linux there's `telegram-cli`: https://github.com/kenorb-contrib/tg
