### ISSUE TITLE
[Feature Request] Sort Channel Members by last seen

### ISSUE THREAD

**Issue by SmartManoj** [telegramdesktop/tdesktop#6269]
### Describe the solution you'd like
Add a toggle button to sort

**Comment by 23rd** [comment]
#3957.

**Comment by RememberTheAir** [comment]
@SmartManoj since you're just suggesting every possible feature that goes through your mind, I would just like to say that Telegram Desktop (as it has been repeatedly mentioned in this repo) usually doesn't implement stuffs that are not implemented or going to be implemented in the mobile apps first. So issues such as #6266, #6267, #6268, #6269 all would need to be supported by the mobile apps first.

It's nice that you're trying to improve the app but before opening a feature request issue you should figure whether they actually make sense and would be needed by someone (eg. #6240 is totally nonsense) or are possibly going to be implemented.

I am in no way part of Telegram and I don't hold any authority in this repo but as someone who often lurk here, I think you should try to figure out a bit better how tdesktop development usually proceeds, before opening dozens of feature requests based on your needs

**Comment by SmartManoj** [comment]
#6266, #6268 are implemented in TelegramX
#5515 would partially solve #6269
Is there any rule, that it should be supported by the mobile apps first
#6267 why is it not implemented like Export chats feature because it is not an api issue?
Later they can implement in mobiles.

#6240 I thought why we have to separate message.
In telegram x , they group message by received time with vertical bar

**Comment by RememberTheAir** [comment]
Telegram X is an experimental client so its developer has more freedom, so it really shouldn't be considered what drives tdesktop's development.

> Is there any rule, that it should be supported by the mobile apps first

See this: https://github.com/telegramdesktop/tdesktop/issues/3490#issuecomment-306056072 - also there are many other statements like that from the developer.

Also, have a look at [contributing.md](../blob/dev/.github/CONTRIBUTING.md):

> Telegram Desktop is not a standalone application but a part of Telegram project, so all the decisions about the features, languages, user experience, user interface and the design are made inside Telegram team, often according to some roadmap which is not public.

Since the leading apps are the mobile apps, tdesktop doesn't have much freedom in deciding what new features can be introduced, small fixies and desktop-related improvements aside.

About the issues you mentioned:

- .5515 is not closed, and since it's supported in the mobile apps, I guess they might add it. Your issue has been closed because it's a duplicate.
- .6267 this is a niche need, would require its own UI and is not implemented in the mobile apps. I don't get your point about the Export tool
- .6240 this is the most niche and unneeded feature request I've ever seen here lol, why would tdesktop offer you a way to wrap a forwarded message between stickers? How many people would find that useful? Why would the developer invest his time on that, when the other apps don't support it either? How many times do you need to do that? Also I don't get the Telegram X point

I'm not telling you to stop to suggest things. Just try to be a bit more coherent with what are tdesktop's freedoms, and also use the templates properly

**Comment by SmartManoj** [comment]
> * Export tool
Like Export tool , implement feature first in desktop then on mobile

> * Telegram X point
telegram x group messages by minutes with a vertical bar ; Will send a pic soon

**Comment by SmartManoj** [comment]
Also improve the templates

**Comment by SmartManoj** [comment]
> * Will send a pic soon
Tdesktop
![image](https://user-images.githubusercontent.com/7231077/61050389-87ff7100-a404-11e9-957f-adc94773e3e5.png)
![image](https://user-images.githubusercontent.com/7231077/61050695-39060b80-a405-11e9-8542-f6c99cfe3e01.png)

TelegramX
![image](https://user-images.githubusercontent.com/7231077/61050807-72d71200-a405-11e9-9d3e-f4c44290a880.png)
