### ISSUE TITLE
Add emoji autocomplete

### ISSUE THREAD

**Issue by vishnu-narayanan** [telegramdesktop/tdesktop#627]
Add support for emoji autocomplete suggestions for telegram desktop upon typing colon [ : ] . This feature is already implemented on webogram.

![image](https://cloud.githubusercontent.com/assets/3526167/6979284/70370296-d9ff-11e4-80ac-34fc67e16af8.png)

Full list : http://www.emoji-cheat-sheet.com/

**Comment by edewaal97** [comment]
Would love this to be added.

**Comment by fotanus** [comment]
Would you guys accept a PR with this feature if I write it?

**Comment by jeyemwey** [comment]
:+1:

Would also love to see that in future versions. It works so much faster to write the emoji*name* than moving the mouse over the smiley and search for the right one with the mouse.. :)

**Comment by Peque** [comment]
I would love to see this implemented as well, really the only thing I am missing in the desktop version. Those shortcuts are not only implemented in Webogram, but in Github as well :wink:, and many other webs!

@fotanus I bet they will accept it. Are you working on it? :blush:

**Comment by fotanus** [comment]
Sorry, I kind of missed the reply. I'll try to implement this feature on this weekend!

**Comment by Peque** [comment]
@fotanus Did you finally try to implement this feature? How did it go? :blush:

**Comment by fotanus** [comment]
@Peque not quite well actually, check #1489. If you feel like tackling it, please by any means do!

**Comment by TiagoDanin** [comment]
Nice :+1:

**Comment by nemobis** [comment]
I see emoticon/smiley/emoji autocompletion in Telegram web 0.5.5, but it's quite annoying because most of the time, when I type a colon, I'm not looking for emoticon suggestions; I would welcome being able to disable it.
![telegram-colon](https://cloud.githubusercontent.com/assets/901528/17275763/3b3ddc6c-5713-11e6-8824-3f4deee312a3.png)
![telegram-colon-done](https://cloud.githubusercontent.com/assets/901528/17275764/3b6134fa-5713-11e6-8245-3d224f994966.png)

The other problem is that the suggestion dialog can only be dismissed by pressing space. If you type an emoticon at the end of a message, or for some other reason you press enter after a colon without having pressed space, the dialog covers the chat until the next time you type a space, and you can't see your own message or any reply.
![telegram-colon-enter](https://cloud.githubusercontent.com/assets/901528/17275774/b54a0ba2-5713-11e6-9e37-18e31b8a19b3.png)

**Comment by stek29** [comment]
@nemobis @m-ober please look at these: [pull request](/zhukov/webogram/pull/1207) and [issue](/zhukov/webogram/issue/1203)

**Comment by maximbaz** [comment]
I believe the following section of CONTRIBUTING.md literally means that no pull request for this feature will be merged. If this is going to be implemented, it has to come from Telegram developers.

> Unfortunately we do not merge any pull requests that have **new feature implementations**, translations to new languages and those which introduce any new user interface elements.
> 
> Telegram Desktop is not a standalone application but a part of Telegram project, so all the decisions about the features, languages, **user experience, user interface and the design** are made inside Telegram team, often according to some roadmap which is not public.

**Comment by john-preston** [comment]
I am afraid it is really more annoying thing than a feature, as told by @nemobis.

**Comment by maximbaz** [comment]
@john-preston it depends on the implementation - I can tell you, it is *very* useful on Slack. This just needs to be unobtrusive. For example, on Slack the popup will not appear unless a user enters `:` and a minimum of two characters after it (so any textual emojis like `:)` or `:D` do not cause pop-up to open), and the popup is closed immediately once a user selects an emoji to post.

**Comment by Peque** [comment]
@john-preston I also find this very useful, rather than annoying. It is not only Slack or Webogram implementing this, note how GitHub does the same. `:wink:` :wink:

**Comment by Akronix** [comment]
Any news on this?

**Comment by arieljannai** [comment]
> I am afraid it is really more annoying thing than a feature, as told by @nemobis.

@john-preston Do you think there's a way of doing it that it won't be annoying?

I find it very comfortable, and I can see that a lot of people too.
For example, I don't think the github autocomplete for emoji is annoying, it's just a little pop-up menu when typing a colon - **:** .
It's also poping only if the colon is not connected to other text - doesn't jump: jump : 

Maybe there can be a shortcut for opening this menu. Like typing colon and then ctrl+space

**Comment by Akronix** [comment]
I agree with @maximbaz that a right implementation is not annoying at all.

Regarding @nemobis comment I'd suggest you to post an issue in webogram repo and we can discuss further how to improve the UX.

**Comment by chrjguill** [comment]
There's already a "replace emoji" thing in the settings, with a list - would it be possible to at least allow users to define their own substitutions?

**Comment by goncalor** [comment]
An alternative to this would be to add a search field to the emoji drawer. Searching an emoji right now is really painful. Opening the emoji drawer and start typing something like "house" and see related emojis is pretty straightforward.

**Comment by oxydron** [comment]
One thing that would be great is while you type the double-dot emoji, when you end it, the code got replaced by the emoji and show the related stickers panel. This would be wonderful.

**Comment by ajsb85** [comment]
Simple, the same functionality of the actual emojis but extended.

![image](https://cloud.githubusercontent.com/assets/663460/26101320/0575b86e-3a31-11e7-8abc-3d1efd199a89.png)

**Comment by Akronix** [comment]
What's wrong with using the same keywords for emojis that Github uses `:smiley:` it's more accurate and exact than `:-D`?

**Comment by chrjguill** [comment]
Something like what discord does would be ideal, I think

**Comment by maximbaz** [comment]
Hey 🙂 

I've recently implemented emoji autocomplete for a different messaging app called [Wire](https://github.com/wireapp/wire-webapp). I'm not using Telegram anymore and will not submit pull request here, but since I spent quite some time on designing unobtrusive and intuitive behavior for emoji autocomplete, I thought I'd share these insights with you guys, which would hopefully help or inspire you implementing this as well. 

In the end, we all want better emoji for everyone, right? :smile: 

First of all, [emoji-cheat-sheet.com](http://www.emoji-cheat-sheet.com/) is an obsolete list, it is not maintained anymore and is certainly not the most complete one (last commit is [1 year ago](https://github.com/WebpageFX/emoji-cheat-sheet.com)). Don't use it. Luckily, one of the famous emoji providers called EmojiOne started to host [a similar list](https://github.com/emojione/emojione/tree/master/extras/alpha-codes). It is open for pull requests, and has a higher chance of staying up to date. I know Telegram is not using EmojiOne, but don't worry - the list itself is independent of the emoji style. Highly recommend to use that list.

As for the annoyance point, I believe I managed to make it as unobtrusive as possible. These are the rules I created for showing autocomplete:

- At least one non-space character is typed after colon, so `list: a, b, c` will never show autocomplete, but `ha-ha :s` will show it.
- Obviously, autocomplete shows only those emojis that match your query after colon. So `:)` will not show autocomplete as well, because no emoji name starts with `)`.
- In order not to mix automatic ASCII emoji replacements with autocomplete, only typing lowercase letters will show autocomplete. In other words, typing `:D` will not show autocomplete and will potentially convert to :smile:, but typing `:d` will show autocomplete where you can select `:dancer` and many others. Such rule is easy to learn, very useful in life.
- Typing several words is allowed via space, this helps searching through the list (remember, full list contains more than 1500 emojis!)
- The list of emoji is initially sorted alphabetically, but as you keep using the app it will count which emojis you used and how many times, and will put most used emojis on top of the list. This means, maybe for the first time to enter 😉 you will need to type `:wink`, but next time just after typing `:w` the `:wink` is already on top of the list.

A picture is worth a thousand words, so... demo time!

![wire](https://cloud.githubusercontent.com/assets/1177900/26527384/3b8f84be-4393-11e7-8a50-841b83bf7ccb.gif)

By sharing this with you, I hope it will spark the discussion and at the same time demonstrate that it is possible to have useful and unobtrusive emoji autocomplete.

The code for this feature [is open source and available](https://github.com/wireapp/wire-webapp/blob/dev/app/script/view_model/ConversationInputEmojiViewModel.js) in Wire repository, if interested I encourage you to take inspiration from it (just double check with the license).

**Comment by stek29** [comment]
@maximbuz thanks for sharing, I've never thought of those.
I doubt js code can help, but general concepts would be useful imo.

**Comment by oxydron** [comment]
@maximbaz very nice mate, good insights on behavior.
Cheering here for this to be implemented.

**Comment by wOvalle** [comment]
+1

**Comment by john-preston** [comment]
@maximbaz Thanks! Used some of your hints :)

**Comment by Akronix** [comment]
Thank you very much, @john-preston. This was the only thing I liked webogram over telegramdesktop!

Now this issue may be closed?

**Comment by vishnu-narayanan** [comment]
Finally, been waiting for this for ages. :) cheers @john-preston

**Comment by jeyemwey** [comment]
Can @john-preston please link the PR to this issue? And thank you!

**Comment by auchri** [comment]
which PR? 😲

**Comment by jeyemwey** [comment]
Ugh never mind, I thought, he created a PR with the code..

**Comment by kipusoep** [comment]
This is a nice feature, but has a down-side (at least for me).
I use :p and :-p a lot, which is the :yum: emoji. But when I use one of these shortcuts the emoji autocomplete list pops up and after pressing <enter> to send the message, the first shortcut emoji is selected.
Kind of annoying.

**Comment by arieljannai** [comment]
@kipusoep If that's the only thing, you can use `:y` instead - the first result will be the `yum 😋 ` emoji.

Also, remember you can add a space to dismiss the emoji selection menu

**Comment by kipusoep** [comment]
Well it's a breaking change and interfering with a habit, which should be prevented imo.
Isn't it possible to have aliases for the basic emoji's, like :-) ;-) :-p etc.

**Comment by arieljannai** [comment]
The developers could answer about what's possible or not.
About:
> Isn't it possible to have aliases for the basic emoji's, like :-) ;-) :-p etc.

The aliases still work as they did before, the only difference is that you should type another character such as space to close the menu and use the basic aliases.

I think that a good suggestion would be an option to turn this functionality on/off from settings.

**Comment by kipusoep** [comment]
NOFI, but I'm having some issues with asking the developers to add on/off settings, because of https://github.com/telegramdesktop/tdesktop/issues/2541 ⛔️

**Comment by arieljannai** [comment]
Hmm well, I have no idea about the asking issues..
I agree that [consistency](2541#issuecomment-254799140) is very important, especially when the app is cross platform and the users expect it to be pretty much similar. The Developers are trying to stick with a guideline that holds for any of the Telegram apps.
Also, don't forget most of the project is [built by a single man](https://github.com/telegramdesktop/tdesktop/graphs/contributors), so it's very understandable that he can't accept any suggestion, even if it might be useful (such as adding the thing that bothered you to the settings)

____

How about asking if a PR by you will be accepted to add this to the settings?

We need to separate features that aren't following the project guideline from the ones that can be added, but are in a low priority and therefore won't be developed.
I believe that features that fall under the second category would be accepted as part of a good and detailed PR - worth asking in my opinion.

**Comment by oxydron** [comment]
I agree with @kipusoep  it should have a on/off option.

**Comment by Alex131089** [comment]
> I agree that consistency is very important, especially when the app is cross platform and the users expect it to be pretty much similar. The Developers are trying to stick with a guideline that holds for any of the Telegram apps.

About consistency, the webogram client use a much better behavior IMO : there's no emoji selected by default when you type `:p` for example, so you can press [enter] (if you only send this, or if you finish the message by this especially) and the text will be sent as expected, there'll be no replacement (with `:pig:` for example).
Also, the tdesktop behavior seems to be annoying only when `:<something>` is at the end of the message (or is the message).
(No need to say I'm pretty annoyed with this too, using `:p`or `:x` is very common)

**Comment by edewaal97** [comment]
You are right. It doesn't autocomplete when you use a capital letter, like `:P` or `:X`. A better implementation is to autocomplete when you type the second letter after the colon.

Also I would like to draw attention to the following enhancement which lets us create shortcuts for the emoji we want to send. Just like with MSN messenger back in time. (nostalgia right?) https://github.com/telegramdesktop/tdesktop/issues/780

**Comment by heaven** [comment]
This is the worst feature I see in the Telegram Desktop! I can't get rid of this garbage autocompletion, how to turn this off?

**Comment by yashpalgoyal1304** [comment]
> ![image](https://cloud.githubusercontent.com/assets/3526167/6979284/70370296-d9ff-11e4-80ac-34fc67e16af8.png)
> 
> Full list : http://www.emoji-cheat-sheet.com/

i am afraid this is not the case anymore. For example the site is showing `:simple_smile:` :simple_smile: code, but it is not working on Telegram desktop, rather :slight_smile: works on tele (as well as GitLab)

**Comment by ariannavabi** [comment]
**Inserting Emojis Using the Function Keys**
Hey there!
So I just realized that the function keys don't do anything on Telegram Desktop, so I was thinking it would be handy to be able to send emojis using them. Not sure whether this thing is handy for all the users or not, but for those who wish to have that option, here's a simple code I just wrote that does exactly that:
https://github.com/ariannavabi/WindowsUtilities/tree/main/Telegram%20Emojis%20Shortcuts/Version%201.2

It would also be nice to send emojis in a non-animated format for both sides. I also wrote a code for that in the link I mentioned but I really wish that the option becomes available in feature Telegram updates.
