### ISSUE TITLE
Сделайте, что можно было в чате прослистывать вверх вниз клавишами управления курсором (стрелки) и листать PgUp Page Down/

### ISSUE THREAD

**Issue by dmitry-sensei** [telegramdesktop/tdesktop#6292]
### Is your feature request related to a problem?
A clear and concise description of what the problem is.

**Comment by dmitry-sensei** [comment]
Тупой гитхаб сожрал остаток текста

**Comment by SmartManoj** [comment]
Translation

Make it possible to browse up and down in the chat with the cursor keys (arrows) and flip through PgUp Page Down /

Blunt github devoured the rest of the text

**Comment by SmartManoj** [comment]
Current behaviour is like that only

**Comment by SmartManoj** [comment]
Translate to English and send 
https://translate.google.co.in

**Comment by dmitry-sensei** [comment]
> @dmitry-sensei на самом деле, тупой - не совсем гитхаб...
> Поле "Subject"/"Summary" в которое ты пытался написать простыню для **КРАТКОГО** описания проблемы "парой слов", а для полного есть поле "Description", в котором ты оставил дефолт.
> 
> Плюс, не смотря на то, что @john-preston всё-таки русскоговорящий, это, всё же, "неофициальная инфа без пруфов", так что тикеты тут создаются на универсальном языке (английском), чтобы разработчики могли понять что ты хочешь. Ты же не для себя пишешь, а для них.

**Comment by msva** [comment]
by the way, request is irrelevant, since it already works as requested (although, first press on "Arrow Up" goes to "edit last own message", but next of that you can freely list the chat with up/down arrows And PgUp/Dn works out of the box).

--
На случай, если ОП не умеет в английский:
Всё и так работает ровно как запрошено: PgUp/Dn работает из коробки, а стрелки - первое нажатие на "вверх" включает редактирование последнего отправленного сообщения, но если нажать ещё раз - чатлог прекрасно пролистывается вверх. И вниз, если нажать "вниз".
