### ISSUE TITLE
[Feature Request] Auto theme switch

### ISSUE THREAD

**Issue by AlexMak58** [telegramdesktop/tdesktop#6359]
### Is your feature request related to a problem?
It is inconvenient to manually turn on a light theme in the morning and dark in the evening.

### Describe the solution you'd like
I want to be able to set time intervals manually or automatically by location (sunset — dawn)

**Comment by ai** [comment]
It could be better just to respect system dark/light theme switching, rather than having built-in UI for theme switching schedule.

Modern OS like macOS and Linux allow you to switch system theme by schedule.

This is how I see implementation:

1. Telegram subscribe to OS theme changes.
2. If the theme was changed, Telegram changes it too.
3. Switcher allows changing app themes separately until OS will change the theme again.
4. Telegram saves the last OS theme before closing. During the startup, it compares previous and current OS themes to detect theme changes.

The current best practice to detect a dark theme in Linux is to check `-dark` ending in the theme name.

**Comment by jurf** [comment]
If this is hard to implement, a keyboard shortcut for night theme toggling could be a good workaround in the meantime.

**Comment by ilya-fedin** [comment]
> and Linux

There's no universal settings storage on Linux, each DE have it's own settings. KDE uses kdeglobals file, LXQt uses configs in ~/.config/lxqt, reading settings of GTK-based DE requires linking to GTK, which is a harmful dependency for a Qt application (you'll get conflicts with embedded platformtheme plugins, like qgtk3 and qgtk2).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/3613
