### ISSUE TITLE
Unexpected "You can't forward here" notification

### ISSUE THREAD

**Issue by giuseppeM99** [telegramdesktop/tdesktop#6384]
### Steps to reproduce
1. Select a channel chat without admin permission
2. Press enter
3. 

### Expected behaviour
Nothing should happen

### Actual behaviour
A toast notification says that i can't forward there

![immagine](https://user-images.githubusercontent.com/8383704/62820908-f18daf00-bb6b-11e9-9621-f3800fdc2777.png)

### Configuration
**Operating system:**
Linux 5.2.4-1-MANJARO #1 SMP PREEMPT Sun Jul 28 09:02:51 UTC 2019 x86_64 GNU/Linux

**Version of Telegram Desktop:**
1.8.1 (beta)

**Used theme**:
https://github.com/Recouse/TDesktop-Dark-Theme

**Comment by arieljannai** [comment]
Since I just wanted to open an issue about it, I'll add on that:

In chats you have permission to write, the behavior until lately was that <kbd>Enter</kbd> inside a chat will jump to the bottom of the chat, to see the latest message (of course, only if the text area is empty).
I find it very useful, and wish that this behavior will be kept for all chats.

**Comment by giuseppeM99** [comment]
This also happens when you click on a public group username and press enter while not being a member, it used to join the group.

**Comment by 23rd** [comment]
Should be fixed now.
