### ISSUE TITLE
[Feature Request] Better implementation of custom titles

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#6392]
### Is your feature request related to a problem?
Telegram announced custom titles in the latest update, I like their implementation on mobile clients, but not the one on Telegram Desktop. Two things should be added:
 1. possibility to check admin's title in admins permissions even if I can't edit it (atm I can just with the ones I can edit);
 2. Display admin's title in group info and group members search.

### Describe the solution you'd like
1. Simply add it :) ;
2. Remove the star and replace it with a texture or a tooltip with the title

**Comment by seth-rah** [comment]
### Summary
Missing instances of custom titles compiled below.

### Steps to reproduce
1.  Open group
2.  View group info
3.  Scroll down to member list (instance 1)
4.  Select member list (instance 2)
5.  Press back
6.  Select 3 dots top right
7.  Select Manage group
8.  Select Members (instance 3)
9.  Select close
10.  Select Administrators (instance 4)

### Expected behaviour

Member list always populates displaying custom titles. (mobile screenshot)

![image](https://user-images.githubusercontent.com/2222634/85404070-b6675500-b55e-11ea-86f6-35b1004cc0f8.png)

### Actual behaviour

Member list only shows a star indicating who an admin is.

![image](https://user-images.githubusercontent.com/2222634/85404226-ef9fc500-b55e-11ea-9b9f-b4bb14e83ce7.png)

### Configuration
**Operating system:** Windows 10 1909 Build 18363.900

**Version of Telegram Desktop:** 2.1.12

**Used theme**: Custom

**Comment by Remu-rin** [comment]
Not resolved.

**Comment by Remu-rin** [comment]
Still relevant.

**Comment by 23rd** [comment]
Is it still relevant?

**Comment by Remu-rin** [comment]
No, it got fixed at some point.

**Comment by seth-rah** [comment]
This has indeed been addressed. 

I think this issue can be closed.
