### ISSUE TITLE
Telegram is stuck on all virtual desktops

### ISSUE THREAD

**Issue by j4hangir** [telegramdesktop/tdesktop#6418]
I heavily use Windows Virtual Desktops and the only program/app that is misbehaving is Telegram. I have one desktop dedicated to communications, here Telegram, but whenever I open telegram it firstly **Shows up in all other desktops**, and secondly when I switch back to its own virtual desktop it doesn't **Regain Focus**.

**Comment by j4hangir** [comment]
This happens apparently only when *Tray Icon* option is used.

**Comment by EN20M** [comment]
To further specify it only happens when "Show Tray Icon" is selected but "Show Taskbar Icon" is unselcted. Additionally to falsly showing up on all virtual desktops it does not appear in the task view pane at all (due to this I belive it is more of an issue with Windows' virtual desktops and/or their handling of windows that are only related to a trey icon rather than a taskbar icon).
