### ISSUE TITLE
[Feature Request] Support Windows 10 Share

### ISSUE THREAD

**Issue by MarcAnt01** [telegramdesktop/tdesktop#6438]
### Is your feature request related to a problem?
Windows 10 share would allow to share files to Telegram and to share files from Telegram to other apps (less important, but still a thing)

### Describe the solution you'd like
Implement it both from the "share to" and from the "share from"
![image](https://user-images.githubusercontent.com/43090263/63654914-4d1d8680-c781-11e9-8553-d57f7777fd43.png)

### Describe alternatives you've considered
Not applicable

### Additional context
https://docs.microsoft.com/en-us/windows/uwp/app-to-app/share-data
This is for uwp and C#, but actually the new Microsoft Edge Chromium brower supports it and is a standard Win32 application

**Comment by xmha97** [comment]
Hello, Please add support for the native Windows 10 Share dialogue.

![Windows 10 Share dialogue](https://user-images.githubusercontent.com/23485114/79740939-b310dc80-8315-11ea-9ab6-8933b24e421f.png)

**Comment by MarcAnt01** [comment]
It looks like just “share to” is possible and not “share from” in Win32 apps

**Comment by xmha97** [comment]
> 
> 
> It looks like just “share to” is possible and not “share from” in Win32 apps

"Send to" menu is obsolete and not widely used. 
![Windows send to menu](https://user-images.githubusercontent.com/23485114/79749223-11dd5280-8324-11ea-95b1-271e66a54871.png)

Microsoft added the share feature instead of the "Send to" menu.
![Windows File Explorer](https://user-images.githubusercontent.com/23485114/79750666-90d38a80-8326-11ea-9ead-043801d18f4a.png)


Also, apps use the share feature, not the "Send to" menu. For example:

Firefox:
![image](https://user-images.githubusercontent.com/23485114/79749299-35080200-8324-11ea-9180-697143b73aa3.png)

Adobe Products (like Photoshop or Illustrator)
![image](https://user-images.githubusercontent.com/23485114/79749394-62ed4680-8324-11ea-83b1-eb0033e78cfe.png)

All Windows 10 Built-in Apps (like Photos and Voice Recorder)
![image](https://user-images.githubusercontent.com/23485114/79750009-70570080-8325-11ea-93e8-94ad4cc0c74d.png)

**Comment by MarcAnt01** [comment]
No, I mean share from Telegram Desktop to a UWP
