### ISSUE TITLE
[Feature Request] Add keyboard shortcut for silently sending messages

### ISSUE THREAD

**Issue by arjunbajaj** [telegramdesktop/tdesktop#6448]
### Is your feature request related to a problem?
To send a silent message, a user has to right click on the send button and click on "Send without Sound"

### Describe the solution you'd like
A keyboard shortcut would be nice for sending messages silently. Maybe Alt+Enter?

### Describe alternatives you've considered
Another way would be to implement a toggle mode to send messages silently. This would allow the user to send multiple messages without sound before disabling the mode. The mode should be automatically disabled after a certain time-frame of inactivity to avoid a perpetual silent mode.

**Comment by Sasha-Sorokin** [comment]
All hands for toggle in menu instead of action menu<sup>[1]</sup> and **maybe** disabling it after some time<sup>[2]</sup>, but I think there should be a workaround then to send message when clicking the toggle so you don't have to do routinely thing the same way it is now (when you right click after writing every single message).

What about holding Shift when clicking toggle to send silent message right away, without enabling silent mode? I know Discord uses such approach to skip dialog boxes in a few situations, but it's hard to describe visually<sup>[3]</sup>, probably. But it's nowhere harder than describing that right clicking on send button does wonders.

**[1]** The reason is quite simple: some people prefer to send several messages instead of using line breaks or dots (same rules as all lowercase to normal tone, CAPS TO TALK LOUD; it's a chat<sup>**^1**</sup>), whatever. Why would we *punish* or *force them* to change their writing style and write posts instead of sending a few simple messages? (By making them *struggle*<sup>**^2**</sup> because of decision to do so)

> **^1** [why typing like this is sometimes okay. — Tom Scott on YouTube](https://youtu.be/fS4X1JfX6_Q)

> **^2** “when you right click after writing every single message”

**[2]** When I say “maybe” I see both advantages and disadvantages of that approach. When automatic disabling is useful so you don't forget about this toggle, I see also a very few shy people who would like that notifications from them would be always delivered without sound, and that “this damn machinery starts to do all work for them when not asked”.

Not that I have much sympathy for this minority, I just think that this could be done another way — instead we may put an [“arrow-ed tip”](https://i.imgur.com/x5TxUwd.png) that would show up after some time and tell “Messages will be delivered silently. Click to disable this.” Plus to that, we may just put the same “silent ball” button as in channels or add add it above sending button (not sure if [this](https://i.imgur.com/zzE8EsN.png) would look alright, but there's a room for imagination: maybe just add red dot as with calendar, eh?).

**[3]** Could be done as when user enables this toggle we simply display [“centered notice”](https://i.imgur.com/oxXoZz3.png) telling “Hold Shift when clicking ‘Send without sound’ or press Alt+Enter to just send message silently.” Easy, not annoying, helpful.

That's my feedback. ~~Thanks me for coming to your TED talk~~

**Comment by damnfella** [comment]
also, a shortcut for sending scheduled message?

I'm voting on CTRL+ENTER for silents and ALT+ENTER for Schedules

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/1060
