### ISSUE TITLE
[Feature Request] Remove preview from all mesages by default or from current message

### ISSUE THREAD

**Issue by joobei** [telegramdesktop/tdesktop#6478]
### Is your feature request related to a problem?
Link previews take too much space from our group chat. This is a group of trusted users/nerds so security is not an issue. 

### Describe the solution you'd like
- Setting to remove all previews
- Hotkey to remove preview from currently composed message (instead of having to move hand to mouse and aim on 'x' RE: Fitts law jesus christ!)

### Describe alternatives you've considered
- Remove message previews as a recipient.

### Additional context
<img width="580" alt="problem" src="https://user-images.githubusercontent.com/2638631/64115741-acd2ed80-cd90-11e9-8534-f0f68b1b5346.png">

**Comment by MasterGroosha** [comment]
First of all, you can disable link previews completely for the whole chat (applies to new messages only) or per-user. If you are one of admins of group, check "Permissions" settings.
Second, is your issue about the app from your screenshot? Because on screenshot I see Telegram for macOS, not Telegram Desktop.

For Telegram for macOS issues, please report issue to https://t.me/macswift (that group is run by app developer)

**Comment by joobei** [comment]
I was not aware of the existence of such option because I am not the group admin. I will ask our admin thank you. Nevertheless it might be nice to have this option as a recipient. If this issue is not relevant to Telegram-desktop then feel free to close this issue. I thought I am using telegram desktop on my macos and https://desktop.telegram.org/ has a link for download for macos so what exactly is the difference? :)

**Comment by RadRussianRus** [comment]
If you're requesting feature for Telegram Desktop, then it's fine.
But app on screenshot is https://macos.telegram.org/, not https://desktop.telegram.org/, they are different. So if you want to request feature in macOS app, you'll need to go to https://t.me/macswift then, as @MasterGroosha said.
