### ISSUE TITLE
[Question]  not getting any response from telegram volunteer support

### ISSUE THREAD

**Issue by Sibasish** [telegramdesktop/tdesktop#6498]
I am not getting any response from Telegram volunteer support. Has the support been migrated to somewhere else or some other platform? Please let me know where can I approach the volunteers or any support group of Telegram. It has been more than 1.5 years and I am not getting any response from the Volunteer support of Telegram.

**Comment by Aokromes** [comment]
sorry this thing doesn't belongs to telegram desktop.

**Comment by LucaTheHacker** [comment]
cringe

**Comment by puppy0cam** [comment]
I like the enthusiasm but this isn't the place. I understand the pain though.

**Comment by Sibasish** [comment]
Then please suggest the right place to approach telegram.

**Comment by puppy0cam** [comment]
Visit settings, then press "Ask a Question". This will direct you to Volunteer Support! They are very overloaded with questions and if you do not receive a response within a week, give them another message. If you have to do this multiple times, I recommend also deleting the previous bump message so that they can more easily find your question and not have to scroll through a infinite amount of bumps.

**Comment by Sibasish** [comment]
There are a lot of questions that had been lending there over 1.5 yr. And I have been trying doing all that you suggested but still I am not getting any response.

**Comment by Aokromes** [comment]
stop adding noise here, this tracker is for telegram desktop bugs or feature requests, ask a question being slow to answer or don't answer at all is a thing we cannot help you to fix.
