### ISSUE TITLE
Support for OSX 10.6.8?

### ISSUE THREAD

**Issue by richdb** [telegramdesktop/tdesktop#657]
Is it possible to support osx 10.6.8? I really not want to update to newer OSX versions, and I think it is not that hard to support osx 10.6.8? I hope this is possible. Thank you already :)

**Comment by NeoLegends** [comment]
Supporting older tech is usually quite a pain up the a... I wouldn't expect a version to support Snow Leopard soon.

**Comment by kleuter** [comment]
Qt 5.4+ doesn't support 10.6, Telegram is based on Qt, so the answer is obvious

**Comment by telegramdesktop** [comment]
@richdb can you help me with testing? I have to divide Telegram Desktop for OS X to two versions, because Qt 5.5 drops 10.7 support as well and I can't afford loosing it too, so I can try to build 10.6 version upon Qt 5.3.2 (but I'm not sure other 3rd party libraries could be used there), but I can't test it, because even Parallels doesn't want to launch OS X 10.6 for me.

**Comment by telegramdesktop** [comment]
Version 0.8.44.dev from the bottom of that page https://desktop.telegram.org/#dev-version should work in OS X 10.6

**Comment by kleuter** [comment]
**telegramdesktop**, how is it possible? Qt 5.4/5.5 doesn't support 10.6 ?

**Comment by turnmusic** [comment]
Any chances to have working build for old 10.6.8 32bit?

**Comment by john-preston** [comment]
@turnmusic Sorry, no way. I'm afraid I can't build 32bit version with my toolset, or at least I don't know how.
