### ISSUE TITLE
Windows 10 Notification Center / Telegram icon with blue background

### ISSUE THREAD

**Issue by tooomm** [telegramdesktop/tdesktop#6570]
### Steps to reproduce
1. Receive one or several Telegram messages
2. Open the Windows Notification/Action Center
3. Check the icon that groups all Telegram notifications together

### Expected behaviour
A shiny, nice Telegram app icon should be shown. With transparent background.

The Microsoft Store or Windows Settings notification use transparent icon backgrounds there already, so that should be possible.

### Actual behaviour
An tiny, ugly icon with a blue background is shown. Blue on blue 👎 
![blue-on-blue-icon](https://user-images.githubusercontent.com/9874850/65258043-8805a680-db02-11e9-8e23-b31e97b78b6e.png)

### Configuration
**Operating system:** Windows 10 1903

**Version of Telegram Desktop:** 1.8.8

**Used theme**: default

**Comment by GlassedSilver** [comment]
The color of the background is the system accent color. Since mine is set to pink it shows the blue Telegram icon with a pink background.

The result is the same though, a boxy icon where the actual icon could be a bit bigger and without background. This is mildly annoying, but something I'd love to see addressed.

I'm adding this info so a dev who opts to tackle it knows which data is pulled possibly facilitating finding the code in quote in question that needs to be fixed.

**Comment by tooomm** [comment]
Thanks for the valuable input and additional description! @GlassedSilver

**Comment by Aokromes** [comment]
this issue is still valid?

**Comment by GlassedSilver** [comment]
> 
> 
> this issue is still valid?

Sure is

**Comment by tooomm** [comment]
This is even more an issue now that the most recent Windows 10 20H2 update shows the icon on every single notification pop up, not only in the notification center.

**Comment by GlassedSilver** [comment]
Begone stale bot, this is still an issue. >_>

**Comment by GlassedSilver** [comment]
Still an issue as always

**Comment by GlassedSilver** [comment]
No it will not, stale bot

**Comment by GlassedSilver** [comment]
reopen please
