### ISSUE TITLE
Respect user set "send" hotkey over entire app

### ISSUE THREAD

**Issue by VitRom** [telegramdesktop/tdesktop#6634]
At present when the Settings/ Chat setting/ Messages/ Send by... hotkey is set to Ctrl+Enter (and new line by Enter) it works only for "true" message sending while a very similar functions like Message Forward or Image Attachment annotation/comment behaves reversed to the user set settings (Enter/newline does Send).

Subj.

**Comment by RememberTheAir** [comment]
I agree with this, it took me like one year to figure out I had to use SHIFT to add a new line to images captions, I initially thought it wasn't possible at all

**Comment by mikkovedru** [comment]
@Aokromes 
I don't think that it is an `enhancement`. It should be marked as a `bug`:
1. Text field not adhering to the settings is a bug.
2. (lack of consistent behavior) Keys having a different and even **opposing** functionality in the seemingly similar text fields is a bug.
3. "Multiline text field" functionality is not used by people, because the normal way doesn't work. Thus de-facto this functionality is not provided to people (read: not working). That should also make it a bug.

**Comment by joe247** [comment]
Yes, this 👇🏻 does _not_
![Screenshot from 2020-01-22 21-44-06](https://user-images.githubusercontent.com/38415384/72911816-b15c6a80-3d60-11ea-9761-024cd9069bb1.png)
work here 👇🏻 :
![Screenshot from 2020-01-22 21-43-44](https://user-images.githubusercontent.com/38415384/72911822-b3bec480-3d60-11ea-99dc-ce8236af27b1.png)

**Affected Version**: v1.9.4 (Latest Stable)
**Workaround**: <kbd>Shift</kbd>+<kbd>Enter</kbd>
