### ISSUE TITLE
Hotkey : and b to bring up emoji causes crash

### ISSUE THREAD

**Issue by LoKaDah** [telegramdesktop/tdesktop#6636]
### Steps to reproduce
1. Type ":" and "b"
2. This causes crash even if something other than b is entered, then edited in.

### Expected behaviour
Shouldn't cause crash.

### Actual behaviour
App crashes.

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
1.8.12
**Used theme**:
Standard night mode

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by weaver299** [comment]
It sure does!  Windows 10.. "Tinted" night theme....

**Comment by nithax** [comment]
I've located the issue of the crash via reverse engineering with a debugger. 

Seems there's a null entry or null pointer in the 'b' suggestion list and the crash is caused by dereferencing a nullptr. It happens after trying to suggest 'bath' and the the next entry is nullptr.

![Evidence](https://i.imgur.com/LQSM6zH.png)
