### ISSUE TITLE
[Feature Request] TLS transport mtproxy support

### ISSUE THREAD

**Issue by p1ratrulezzz** [telegramdesktop/tdesktop#6655]
Mobile clients already support TLS wrapping of the traffic (with "ee" secret prefix)

There was a commit in the history about this but the UI doesn't allow to check if it working or not.

Here as an example: https://t.me/proxy?server=krasnaya.zalupa.dns-cloud.net&port=443&secret=eedd4b59d80dffd44717ca42f0ca3d15b3 - can't be added in TG Desktop

**Comment by MasterGroosha** [comment]
EE-proxy works fine in recent TDesktop builds.
As far as I see, your secret has both "ee" and "dd" symbols in the beginning. Isn't it a typo? (extra "dd" symbols might be part of your secret, but might be just a typo).
I haven't tried official MTProxy in EE-mode, but [Python version](https://t.me/proxy?server=groosha.space&port=443&secret=eed3a2219e5edc0a75d7a2ad18b3ff89e567726f6f7368612e7370616365) in EE-mode works like a charm. Also my secret in EE-mode is longer than yours, since a TLSv1.3-compatible domain name should be also included in has in the form of hash.

**Comment by john-preston** [comment]
@p1ratrulezzz This is indeed invalid proxy link, sorry.

**Comment by p1ratrulezzz** [comment]
@MasterGroosha , no, it is a part of the secret. The other variant is https://t.me/proxy?server=krasnaya.zalupa.dns-cloud.net&port=443&secret=dddd4b59d80dffd44717ca42f0ca3d15b3

(this one works in TGDesktop)

**Comment by john-preston** [comment]
@p1ratrulezzz 'ee' secret is a different type of secret, not just any 'dd' secret with replaced first byte.

**Comment by MasterGroosha** [comment]
@p1ratrulezzz Maybe this will help you: http://seriyps.ru/mtpgen.html

**Comment by p1ratrulezzz** [comment]
Thanks. Will see how to make it work with official mtproxy

**Comment by MasterGroosha** [comment]
I've just checked it again. Official mtproxy in EE-mode works fine with Telegram Desktop. If you have any further questions, email me (address in profile)

**Comment by p1ratrulezzz** [comment]
Yes, got it working,

So, to make it work.

1) Generate a random secret 

```
export MT_SECRET=$(head -c 16 /dev/random | xxd -ps)
```

2) Choose a fake domain: www.google.com and encode it

```
export SUFFIX=$(echo google.com | tr -d '\n' | xxd -ps -c 200)
```

3) Print your final secret:

```
echo "ee${SECRET}${SUFFIX}"
```

4) Run mtproto-proxy with --domain google.com
