### ISSUE TITLE
[Feature Request] Handle Spotify protocol

### ISSUE THREAD

**Issue by theMatthes** [telegramdesktop/tdesktop#6679]
### Is your feature request related to a problem?
When sharing Spotify URIs in Telegram, they are not handled and displayed like regular text
### Describe the solution you'd like
Mark the URLs like any other links and automatically open the associated program (like with the `start` command in windows)
### Additional context
By Spotify URI, I mean URIs like `spotify:track:4uLU6hMCjMI75M1A2tKUQC`
Edit: Ok i found a similar issue: #1201

**Comment by marcoValkyriweb** [comment]
Is there a reason you can't copy the URL instead?

For groups I recommend using https://telegram.me/spotybot , useful for those who don't have Spotify so they can preview.

**Comment by pindab0ter** [comment]
I would like to see general handling of arbitrary URI schemes, at the very least by allowing it when creating a manual link (e.g. using CMD+K on desktop client).

**Comment by marcoValkyriweb** [comment]
CTRL/CMD+K currently says URL, there's no confusion there.
![image](https://user-images.githubusercontent.com/34270069/68932731-def2c980-079b-11ea-9b65-1ca185444e93.png)

Currently Spotify has a direct share to Telegram:
![image](https://user-images.githubusercontent.com/34270069/68932920-414bca00-079c-11ea-812a-53d002bb0bd5.png)

So what OP wants is that URI is treated as a link, so you can open it directly in the desktop app instead of having it open the link in-browser and using the Spotify web player.

This means ctrl+k should have an option for allowing invalid links, this would allow for spotify: URI to work. Maybe as a pop-up if link is invalid, ask if URI and still want to post? Or whitelist applications/URI based on e.g. pull requests (just check that it starts with e.g. spotify: or be more specific and have the type associate as well, e.g. spotify:track:).

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/299
