### ISSUE TITLE
[Feature Request] Better privacy settings/antispam

### ISSUE THREAD

**Issue by user38192** [telegramdesktop/tdesktop#6699]
Please, add next features:

1. Settings - Privacy and Security - Group invite settings - add option **Nobody** 
2. Settings - Privacy and Security - Profile Photo - add option **Nobody**
3. Add setting "\Who can send me private messages" with options: Everybody, Only my contacts (it will be very good antispam-feature). Users, who are not in your contact list, will not be able chat with you)
4. Add setting to hide you account from global search

**Comment by 23rd** [comment]
[twitter.com/telegram/status/1110096945337589761](https://twitter.com/_/status/1110096945337589761) =)

**Comment by yashpalgoyal1304** [comment]
> [twitter.com/telegram/status/1110096945337589761](https://twitter.com/_/status/1110096945337589761) =)

u forgot that telegram provide customisations in the form of exceptions (whitelist and blacklist), dont u?? 😅 

![image](https://user-images.githubusercontent.com/19423063/88501409-09627b00-cfe9-11ea-9d86-b69f509e0ad4.png)

**Comment by yashpalgoyal1304** [comment]
One more person asking for it. https://twitter.com/XenophiliaBlack/status/1382983076389720064
you are soooo arrogant telegram people. in capital letters.

**Comment by john-preston** [comment]
@yashpalgoyal1304 no I'm not :(

**Comment by RememberTheAir** [comment]
I think it would be better to bring the discussion under [this ticket](https://bugs.telegram.org/c/1649) in the official bugs & requests platform

**Comment by yashpalgoyal1304** [comment]
@john-preston sorry, this was not intended at particularly u. My main target for vent in this issue was the person behind that shit stupid reply on twitter. 

The thing is, i used to put lots LOTS of time & efforts in making suggestions for improving tg. Telegram was VERY dear to my heart. 
But seeing following things in tgbetachat and tg updates broke my heart very badly.
- nobody giving a fuck about improving tg, and the people there just interesting in shit chatting ALL the timmmme
- my input going in vain all the time, and getting arrogant replies, which literally felt like *"deal with it, that's our decision, fuck u"* (just look at above twitter reply)
- such pooooor implementations of most all new features
- sooooo much pride on those animated shit things, i am like,\
*"ohkayyy, got that u like animated shits, and animations. but why acting like it's soo great thing. how about fixing the actual ux...."*

my main pain causer and heart breaker is telegram android. But tgdesktop have scope for improvement in the most basic ux too.
