### ISSUE TITLE
[Feature Request] Needs a starred messages feature 

### ISSUE THREAD

**Issue by kartikch918** [telegramdesktop/tdesktop#6736]

**Comment by damnfella** [comment]
but but- You can do that already with **"SAVED MESSAGES"**... 

Maybe you are asking a button to send the selected messages directly to saved. (well, forward > saved)

**Comment by RememberTheAir** [comment]
Also: the API doesn't support to save messages in a specific chat, so this should be labeled API issue

**Comment by kartikch918** [comment]
@damnfella, @Aokromes  
I updated the issue with a hopefully better explanation.
Does it still count as an API side drawback and cannot be implemented?

**Comment by RememberTheAir** [comment]
Uhm, so you are basically suggesting a button somewhere in a chat screen (eg. your mockup) that will show only the messages you have forwarded in your saved messages? Or rather something similar to WhatsApp's starred messages, where you star a message in a chat and can see it only from there? (sorry am stupid)

Either way, would it need to be supported by the API? Short answer is no. Long answer yes because otherwise the client would have to fetch the whole history of your saved messages' chat and filter out everything that does not belong to your current chat, which would be a very wasteful way of implementing it. Also, this is the kind of feature that users would expect to find in _all_ the major apps (Android/iOS/desktop) so it would need to be implemented server side at this point. I like the idea though. I also would like to have a way to filter my saved messages based on their origin chat

**Comment by kartikch918** [comment]
Yeah you do get my point @RememberTheAir with the Whatsapp starred messages and how you can filter them by accessing them from different chats.

A server side solution would be a more efficient one but it doesn't matter now because they closed my issue. 

<i>RIP</i>

**Comment by damnfella** [comment]
@Aokromes Isn't it better to use `unsolved` label for unsolved API issues? :3

**Comment by kartik918** [comment]
@damnfella Did you mean ``unsolved``?

**Comment by Aokromes** [comment]
well, it's not solved or unsolved, it simply doesn't belong here.
