### ISSUE TITLE
Hide conversations from the conversation list

### ISSUE THREAD

**Issue by hertell** [telegramdesktop/tdesktop#678]
Please add a feature to close chats / display a selected list of people on the left pane instead of having to delete them. I prefer to display in left pane only those people i send messages to and not people i don't (want to) send messages to...

**Comment by joebex** [comment]
+1

**Comment by completit** [comment]
:+1:  +1

**Comment by cobalto** [comment]
Or, as in the mobile plataforms, have two lists, one with only "chats", another with only contacts.

**Comment by joebex** [comment]
I agree with you cobalto, that would be consistency across all platforms!

**Comment by hertell** [comment]
joebex: Yes, it should look and behave the same on all platforms (+ webfrontend) :-)

**Comment by zaz600** [comment]
close and don't load messages before it'll opened (joined) again

**Comment by lucaciavatta** [comment]
' I prefer to display in left pane only those people i send messages to...'
I completely agree. 
+1

**Comment by hertell** [comment]
Why was this issue closed? Does this mean that this feature-request was ignored?

**Comment by auchri** [comment]
No, but only conversations are now shown in the left pane

**Comment by hertell** [comment]
This is not what i was suggesting when opening the issue. What i was suggesting was to have an option to hide/close a chat so that it won't be listed in left pane. Now if you wan't to remove a person from the left pane you need to delete the chat, which means that you loose the chat-history.

**Comment by auchri** [comment]
That makes no sense to me but ok

**Comment by hertell** [comment]
Well, there are people you chat with frequently, and others you chat much more seldom with. By hiding those who are more seldom worth a chat could by hiding  clean up space in the left pane

**Comment by harpereaves** [comment]
@hertell +1

**Comment by mba2431** [comment]
++1 it's very good idea, for example hide a contact and all conversation with that contact not show in conversation list...

**Comment by hertell** [comment]
I hope this enhancement will be implemented soon!
I give more examples why there should be an option to hide chats in the left pane: 
You sit in a meeting sharing your screen on a videoprojector. You get a message from someone commenting that is taking part in the meeting remotely. When opening the chat you see a long list of different people you have been chatting with. One of the messages visible is from your horny wife/lover/ex.. Obviously you don't want that everyone will see such messages (of maybe you want.. ;-) )..

Please add this option!

**Comment by fedorovdima** [comment]
> One of the messages visible is from your horny wife/lover/ex..

Nice example! What about maybe some group(s) of contacts that could be collapsed and hidden?

**Comment by gurghet** [comment]
+1

**Comment by halibegic** [comment]
+1

**Comment by jbarreneche** [comment]
Another use case is the telegram messages informing new functionality. I don't want to see them in the middle after I have read them. And I don't want to delete them because sometimes is useful information.

**Comment by cpjeanpaul** [comment]
If I am in a group of +18 and lend my cell to my little son? It would be nice to be able to hide some conversations and later access them with a key

**Comment by auchri** [comment]
@cpjeanpaul Set up an pin code so he can't access telegram.

**Comment by cpjeanpaul** [comment]
Wife? :)

**Comment by auchri** [comment]
what?

**Comment by iHandy** [comment]
We can hide conversations list by minimising the telegram window. But just hide latest messages will be also a good improvement.

**Comment by risingballs** [comment]
I'd like to second the fact that archiving (hiding, but keeping) chats is a incredibly important feature. A simple "Done" button like on the FB pages manager (messaging) next to a chat would for example be amazing, but then again a tap-hold menu to hide it would be fine really.

**Comment by auchri** [comment]
No api for that

**Comment by hertell** [comment]
WTF? You just close this issue because there is no api for such feature?? Then the fix the API so this kind of feature could be created!

**Comment by auchri** [comment]
@hertell I think you are clever enough to figure out that this repo is only for Telegram Desktop and not for the api or other stuff.

**Comment by gurghet** [comment]
I think what he meant by that was "no api for that" which in his language means:
No=open
Api=an issue
For=to create
That=that API

**Comment by stek29** [comment]
@gurghet no, it doesn't

**Comment by privetstas** [comment]
Hello! B.T.W. There is a way to hide all muted chats in tg desktop app. It's called "workmode"
Click"Settings" and when the settings panel is opened just write "workmode" on the keyboard.
When you will finished a writing you will see popup message.

**Comment by iHandy** [comment]
@privetstas 1.2.6 doesn't behave like you described. Nothing happening after write "workmode" in settings.

**Comment by stek29** [comment]
@iHandy just to verify: your keyboard layout was set to English, right?

**Comment by iHandy** [comment]
@stek29 my bad, not english, with english it works well)

**Comment by zaz600** [comment]
@privetstas add more choices: hide muted, show unreaded or unreaded first

**Comment by DmacMcgreg** [comment]
Can this be added on mobile and Mac version as well? It is extremely helpful, as I have many group chats or channels I do not want to lose the history of, but do not want to receive alerts, or clog up the chat panel on the left.

**Comment by SilentGene** [comment]
@DmacMcgreg Agreed. Hope the developer can add this feature to the following new versions.

**Comment by kli0rf** [comment]
I've seen many feature request these guys are simply ignoring. I'd say 9 of 10. :) Some sort of Microsoft style.
Anyways, the ability to hide (and not to delete) certain chats from the chat list on the left pane of TDesktop is the key feature most of them users need. I don't even see the point of reasoning the WHY to the devs, since it's more than obvious.

**Comment by RememberTheAir** [comment]
@kli0rf Keeping the "_most of them users need_" and "_I don't even see the point of reasoning the WHY to the devs_" statements aside, I think the purpose of "archiving" a chat is to permanently hide it from the dialogs list, because you are not interested in it but still want to have it archived somewhere, just in case. Or because you find the amount of notifications coming from a specific chats annoying. Then, archived chats should be hidden on all your other clients (eg. mobile client or other tdesktop installations) because that's how one would expect it to work (imagine having to manually the same chats from every client on every login). That's why it is marked as API issue, that's something that needs to be supported by the backend first, tdesktop can't do nothing about this. If Telegram gets enough requests on [Twitter](https://twitter.com/telegram) or via the in-app support, they might start to think about this

**Comment by kli0rf** [comment]
@RememberTheAir hiding chat != archiving chat. And the ability of TDesktop to hide muted chats in workmode is kind of a proof there's no API limitations.

**Comment by RememberTheAir** [comment]
@kli0rf workmode is an hidden setting you can't enable unless someone told you it exists. It's part of a set of debugging triggers hidden in the app, so not really something to use as comparision. In the [contributing guide](https://github.com/telegramdesktop/tdesktop/blob/17cde3426a55b69536406e54d7c3eaaef8378db4/.github/CONTRIBUTING.md#what-contributions-are-accepted) it's stated that all major features are established by Telegram's core team first, so yes, platform-wide features like this one must be supported by the API first. Expecially when them not being synced across devices implies the repetition of the same work on every client.

> hiding chat != archiving chat

Mmmm. With "archiving" I mean hiding a chat from your chats list without having to delete it, implying you should be able to find it somewhere in the app with an option to un-hide it if needed. Are we talking about different things? 🤔

**Comment by risingballs** [comment]
> @RememberTheAir hiding chat != archiving chat. And the ability of TDesktop to hide muted chats in workmode is kind of a proof there's no API limitations.

I have to agree, and to stress again how important this is. Although archiving would be good enough. It is one of the most basic features and there is nothing worse than having to look at old chats (names, and especially the avatars) you do not want to see, but keep.

Also, only being able to hide muted chats is terrible. Hiding read chats, or "ok'd" chats, would make more sense. There is not much I'd send you over to FB for, but look at how they handle page messages. Once you're done with them, click the checkmark and they go into hiding, leaving the inbox (and the brain power) open to new ones. This is really important unless you have your best buddies open in TG all the time, chatting with them all the time. Often we get messages and we just want to read, reply, and be done with it.

**Comment by RememberTheAir** [comment]
> Hidden or not hidden, that's not he point. What i'm saying, that it has nothing to do with the API, since the same functionality is already enabled, meaning that allegation about API limitations is complete bullshit.

There is no API to do that. Just to clarify what I'm talking about when I say "API": with"API" I refer to the MTProto API, which is how tdesktop interacts with Telegram and that's how things get synced across clients. No API method to hide chats -> no cross-clients sync. "workmode" being a thing doesn't mean anything in this case for two reasons: it's an hidden/debug feature you can't enable unless someone told you it exists, and it's a client-side thing that doesn't need any sync. Hiding chats is different, they need to be synced since we are talking about a multiplatform, cloud-based messaging service - and you can't sync hidden chats if MTProto doesn't support that. And that's the reason why this issue is closed and marked as "API issue" - because this feature goes beyond tdesktop's development

About the meaning of "archive", then yes, we are talking about the same thing than. I've never used Hangouts so I didn't interprete the term in that way

**Comment by kli0rf** [comment]
> No API method to hide chats -> no cross-clients sync. "workmode" being a thing doesn't mean anything in this case for two reasons: it's an hidden/debug feature you can't enable unless someone told you it exists, and it's a client-side thing that doesn't need any sync.

Ok, that makes sense. Synching hidden chats accross all them clients you're connected from would be a great thing. Nevertheless, even hiding not important chats per client basis would make users' life much easier.
