### ISSUE TITLE
[Feature Request] Disable online dots

### ISSUE THREAD

**Issue by zakutin** [telegramdesktop/tdesktop#6799]
I would like to propose the feature on possibility to disable the online dots below the avatar image. In my opinion, these online dots are counter-private. There are couple cases where users can feel themselves uncomfortable with the actual counter-private situation:

- Case 1: Person A comes online. Person B sees it from the contact list and wants to contact him, even if the person A doesn’t want to be spotted. This can be "boss - worker" case or "advisor - student". Prior the dots were introduced, the person B had to open the contact A to see, if person A is online, or was online at certain time, or last seen recently, if person A set the option "nobody can see my last status". Otherwise, the actual feature "Who can see my last seen time" with option "Nobody" enabled – becomes worthless, since person B sees person A explicitly.
- Case 2: There are three contacts A, B and C. Every contact has another two contacts respectively. There are certain situations, when it is undesirable for contact A to see if B is chatting with C. This could be "wife - husband - friend" case or when C is friend to A, but not to B. I personally got the question onetime: "Are you chatting with B now?" Obviously, there are private chats for that, but it doesn’t conceal your online dot presence.

Yes, all these and another cases were in era of ICQ and Skype, and I never reacted on this back then. But, since the telegram messenger poses itself as a privacy oriented messenger, it would be nice to have the possibility to disable the online dots.

Getting to the telegram desktop settings, Privacy and Security, Last seen & online, I do not understand, what "online" stands for, since even I set it to Nobody, everyone can see my online dot.

The feature can be implemented in section "Last seen & online" with the same restrictions as for "last seen" option – once this option is enabled, you will not see the dots from another contacts.

This feature request relates to Android, iOS and other devices and operating systems as well.

**Comment by RememberTheAir** [comment]
All the cases you have described can be managed simply using the "last seen" privacy setting. The green online dot is shown the same exact way the "online" status is shown when you have a chat with someone opened in front of you. That means that if you are hiding your last seen status to eg. your boss, he won't see any green online dot when you are online chatting with your girlfriend. The green dot follows the same visibility rules of the online status: when it's hidden to a person, this person will see it only when certain actions that are obvious indicators of your online presence happen: you mark as read a message from this user, you have been typing something to this user for a while, you send a message to this user, you send a message in a chat with this user.

Obviously, if you do not hide your last seen to someone, there's nothing forbidding him to stalk you by checking your last seen time. If you hide it, the two situations you have described should not happen because if you hide your last seen to A, A will be able to see your presence only when you are chatting _directly_ with him or send a message in a group where you are both members, for a few seconds

**Comment by zakutin** [comment]
All right, thank you! This paragraph clarifies a lot. I did somehow missed it. That was confusing, why the dots are still visible, even if "Nobody" is enabled. Just tested it once again with friends phone.
