### ISSUE TITLE
[Feature Request] Add option in group permissions -- voice messages

### ISSUE THREAD

**Issue by banderlog** [telegramdesktop/tdesktop#6882]
I am unable to restrict voice messages in group. Long voice messages is a bad thing in text messenger.

**Comment by RememberTheAir** [comment]
> text messenger

Hmm. Is Telegram a _text_ messenger? Medias are a key element in every modern chatting platform - even if Telegram is no exception, it gives a way to restrict users from sending some kind of context and I think we miss more granular permissions because there are already quite a bit available and they fit most people's needs. You should agree with your chat members to avoid voice messages because they disable people who're not able to listen to them to participate in the discussion. This is usually commonly agreed upon in public chats I believe

By the way, this needs also to be supported at API-level

**Comment by banderlog** [comment]
So inability to restrict voice messages is a feature, you saying?

**Comment by RememberTheAir** [comment]
No. I'm saying Telegram probably thinks there's not enough room for that too

**Comment by 23rd** [comment]
I'm sorry, but I don't understand exactly what the problem is.
When we talk about images, stickers, animations, we're talking about visual content that you can accidentally see, even if you don't want to. That's why we have permissions for this content.
When we're talking about audio content, there is absolutely no one making you listen to it, and as I said before (https://github.com/telegramdesktop/tdesktop/issues/6872#issuecomment-565801996) you can just skip it.

Anyway, you opened an issue that is not related to the Telegram Desktop.
Please request your feature to the in-app support or on Telegram's Twitter.
