### ISSUE TITLE
Telegram opening with the wrong window size

### ISSUE THREAD

**Issue by Hezkore** [telegramdesktop/tdesktop#6924]
### Steps to reproduce
1. Put Telegram Default interface scale to 125%
2. Have Monitor scale set to 125%
3. Resize Telegram to an okay size for the monitor
4. Shut down Telegram
5. Open Telegram
6. Notice that it's now 25% bigger than before
7. Repeat step 4 and 5 and Telegram will eventually grow to cover the entire monitor

### Expected behaviour
I expect Telegram to start with the same window size as when I closed it

### Actual behaviour
It keeps growing in window size and eventually covers the entire monitor

### Configuration
**Operating system:**
Windows 10

**Version of Telegram Desktop:**
v 1.9.3

**Used theme**:
Night

**Comment by Hezkore** [comment]
Example GIF:
![2020-01-01_05-12-06](https://user-images.githubusercontent.com/1727541/71638044-72e9f900-2c55-11ea-90fb-b0e4db97c235.gif)

**Comment by roughnecks** [comment]
I have a similar issue.

I'm used to minimize Telegram to the Application Bar (not the tray bar) and every time I open it up, its window is not the same size I left it.

1) Open Telegram
2) Maximize it
3) Minimize to Application Bar
3) Click on Telegram Icon in Application Bar
4) Telegram opens up windowed (no more maximized)

**Comment by roughnecks** [comment]
P.S. I didn't remember that I'm using 125% scale too.

**Comment by demensh** [comment]
The issue appeared after updating to 1.9.3 from 1.8.15
Using 100% scale

Also noticed that after restoring Telegram from minimized state and maximizing the window, Maximize button doesn't change to Restore until you press it once again, i.e. the behavior is:
1. Restore Telegram from minimized state (it restores with some arbitrary size - that's the issue #6924)
2. Press Maximize button (window maximizes, Maximize button stays intact)
3. Press Maximize button once again (nothing bappens except Maximize button changing to Restore)
Expected behavior: window control buttons reflect window state

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6804
