### ISSUE TITLE
GIF opens in full screen

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#6943]
### Steps to reproduce
First issue with autoplay **disabled**:
1. send any gif to any chat
2. click on it to play
3. it's will opens in full screen
4. this issue only with gifs sended by you

Telegram relaunch helps with already sended gifs.

Second issue with autoplay **enabled**:
1. send any gif to any chat
2. click on it
3. it's opens in full screen with no way to pause
4. this issue with all gifs, not only sended by you

This is a bug because you can pause the round video messages but not videos and gifs.

### Configuration
**Operating system:** win10 ltsc 1809

**Version of Telegram Desktop:** 1.9.3

**Used theme**: default dark

**Comment by john-preston** [comment]
@Neurotoxin001 The second is intended and always worked that way.

**Comment by Protonator** [comment]
I also got this bug (first issue) since I switched to version 1.9.3. (Windows 10 Pro Version 1909)

**Comment by Poojawa** [comment]
a toggle to have it go full screen or to keep it loaded inline would be wonderful.

**Comment by Neurotoxin001** [comment]
Update to 1st issue:
When you edit (or add) caption to GIF — it's become "fixed" and doesn't open in full screen.

**Comment by Brawl345** [comment]
8fb2772093fd81646affd52d4767a7c8e70a0e7d says it's fixed, but it's not. Restarting TDesktop works, but sending GIFs and then playing them will still open them in fullscreen (assuming you have autoplay disabled).

**Comment by Neurotoxin001** [comment]
Still not fixed in 1.9.4.

**Comment by Protonator** [comment]
> 
> 
> [8fb2772](https://github.com/telegramdesktop/tdesktop/commit/8fb2772093fd81646affd52d4767a7c8e70a0e7d) says it's fixed, but it's not. Restarting TDesktop works, but sending GIFs and then playing them will still open them in fullscreen (assuming you have autoplay disabled).
> Tested in v1.9.4.

Confirmed with 1.9.4 under Windows 10 Pro.

**Comment by Tynach** [comment]
Probably a related issue: if you click on someone else's gifs (or your own if you restarted Telegram since posting them), you can use the mouse wheel to scroll back and forth through the gif history.

However, for gifs you posted yourself in the current session (as in, you have not restarted Telegram since posting them), you can't use the scroll wheel to go through the gif history of that group/conversation.

For some reason, starting with 1.9.3, gifs you have just posted are treated slightly (but not entirely) differently than all the other gifs in a chat. This was not the case with 1.8.x and prior.

**Comment by Neurotoxin001** [comment]
1.9.6 not fixed

**Comment by john-preston** [comment]
@Neurotoxin001 Yeah, sorry, I forgot to include that fix in that build.

**Comment by Neurotoxin001** [comment]
Does this fix can fix this https://github.com/telegramdesktop/tdesktop/issues/6957 too? Or it's different issues?

**Comment by john-preston** [comment]
@Neurotoxin001 Yes, this should be the same problem.
