### ISSUE TITLE
[Feature Request] List users seen by

### ISSUE THREAD

**Issue by miloszowi** [telegramdesktop/tdesktop#6973]
### Is your feature request related to a problem?
Sometimes when talking in group chat when only me and one of the other members are talking, I am not sure if he is the one who saw my message. 

### Describe the solution you'd like
It would be very nice to see 'seen by: [userlist]' below the message so we could see who actually saw the message.

### Describe alternatives you've considered
It could be just avatars instead of names.

**Comment by jeffythedragonslayer** [comment]
This will require a change to the Telegram API.  This function mentions a view counter, but no kind of map from users -> booleans on whether they've seen the message.  (Documentation says it's for channels but since it can return CHAT_ID_INVALID I'd assume it works for chats as well).

https://core.telegram.org/method/messages.getMessagesViews
