### ISSUE TITLE
[Feature Request] It would be nice to have a "select all messages" option in groups or channels that one has admin rights on

### ISSUE THREAD

**Issue by lemmy04** [telegramdesktop/tdesktop#7253]
### Is your feature request related to a problem?
I m using a telegram channel to send and receive error messages from various servers, and when I've seen them (and dealt with what was going on) I would like to remove them from the channel. Right now I have to manually select each of them, which is a pain.

### Describe the solution you'd like
I would like to have a "select all" option pop up as soon as one message is selected.
Also, a "clear history" like in one on one chats would be good, but it should be limited to be available only to admin users.

**Comment by lemmy04** [comment]
yay stalebot strikes again. no action on this?

**Comment by lemmy04** [comment]
yay stalebot strikes again. no action on this?

**Comment by lemmy04** [comment]
no reaction at all from developers for more than 12 months.

**Comment by john-preston** [comment]
You can use a supergroup, each user can clear history for himself there.

Such a button would be very confusing, because there is no way (from API point of view) select all messages and do some actions with them. It could request history and delete them one slice after another, but such usage is not considered supported, channels have different use case. Maybe some fork could implement such feature, but not here.

**Comment by lemmy04** [comment]
well, if it can't be done at all...
