### ISSUE TITLE
Incorrect group's member list preview

### ISSUE THREAD

**Issue by Twi1ightSpark1e** [telegramdesktop/tdesktop#7325]
### Steps to reproduce
1. Hover mouse over members amount in group chat view.

### Expected behaviour
Member list preview shows all members of chat, at least with scrollbar.
![memberlist_preview_expected](https://user-images.githubusercontent.com/10437907/75851621-34aaba80-5dfb-11ea-92bb-1666fe39d6f6.png)

### Actual behaviour
Preview contains just few members, or does not shown at all. After opening Group Info and closing it, preview works flawlessly.
![userlist_preview_actual](https://user-images.githubusercontent.com/10437907/75851729-82bfbe00-5dfb-11ea-85c2-5df726fc0331.png)

### Configuration
**Operating system:** Windows 10 1903

**Version of Telegram Desktop:** 1.9.19 beta

**Used theme**: Night Mode

**Comment by xscd** [comment]
I have the same issue this also leads to failure of @ mentioning users. They don't appear have to manually open group info and load the user list. Then it can successfully see the @ list. I assume this is a server side problem because it started happening yesterday. Both happens stable&beta meanwhile mobile and web applications(?) work fine.

**Comment by jeffythedragonslayer** [comment]
I see 5.5 members in the preview (bottom of last person's profile pic and status are cut off) on 1.19.20

**Comment by RememberTheAir** [comment]
I think this specific issue (wrong members list in the dropdown preview) has been fixed with 1492571

**Comment by Twi1ightSpark1e** [comment]
I can't reproduce this issue on 1.9.20. Both member list preview and @ list works fine for me. I think issue is resolved.
