### ISSUE TITLE
[Feature Request] Save deleted message in history (when deleted outside)

### ISSUE THREAD

**Issue by dim0xff** [telegramdesktop/tdesktop#7408]
I'd like telegram to kept deleted messages on my side (when messages were deleted outside) with note like 'was deleted'

It is very inconvenient when somebody removes messages in chats.
And especially when person removes MY OWN messages from private chats.

Deleted messages could be marked as "deleted by USERNAME", but saved on local device until app memory is cleared by device owner.
It is also useful to add 'clear deleted messages' button to chat context menu to permanently clear deleted messages from device chat history.
And sure, deleted messages will only be available on device which received these messages: if device was offline when message has been written and then removed, user will never know about this message.

Right now I have to use some 'chat bot' — app which listens telegram api for my account and permanently saves history to file.

**Comment by RememberTheAir** [comment]
This is not going to be implemented for sure, as it is inconsistent with how all the other clients work, and also because deleted messages are designed to be deleted for good, leaving no trace.

> if device was offline when message has been written and then removed, user will never know about this message.

They are designed to work this way. I'm quite sure that, when Telegram was designing how deleted messages should behave, they considered the implementation you are suggesting and decided the way it works now was the right path to take. So I doubt they will ever change that - and for sure tdesktop is not going to drift in a different direction alone

**Comment by dim0xff** [comment]
> This is not going to be implemented for sure, as it is inconsistent with how all the other clients work, and also because deleted messages are designed to be deleted for good, leaving no trace.

I really can't understand why device owner does not own data on his device.
Why not add switcher for "save deleted messages" with default "Off"? It is strange.
