### ISSUE TITLE
Which is more secure, system package or official flatpack package? [Question]

### ISSUE THREAD

**Issue by Nokia808** [telegramdesktop/tdesktop#7470]
Hi. I'm a Fedora user, & Telegram desktop is already available to me from 2 sources:

1) from my official Fedora repositories version 1.8.15
2) from FlatHub as flatpak: version 1.19.21

Certainly flatpak is more up-to-date. Moreover, it is official package made by you not by 3rd party maintainer. I'm already installed your official flatpak package from FlatHub. But from time to time I read in Internet articles saying that if you have an application available to you from both flatpak & distro repositories it is more secure to use distro .rpm/.deb package even it is older ...... So, please what is your recommendation regarding security point of view: continue using your official flatpak package from flatpak or remove it & install .rpm package from my official Fedora repositories ?

**Comment by xvitaly** [comment]
> from my official Fedora repositories version 1.8.15

Hello. I'm Fedora maintainer. There are no Telegram Desktop in the official repository due to ffmpeg dependency (we cannot ship ffmpeg due to US patents use). Telegram Desktop package provided by the semi-official RPM Fusion repository and it always up to date. Current version in stable is 1.9.21 (latest available).

I think you are still using Fedora 30 release, which is almost deprecated an no longer heavily maintained. Please update to Fedora 31 as soon as possible.

> I'm already installed your official flatpak package from FlatHub.

Flatpak is not official too. It maintained by [third-party people](https://github.com/flathub/org.telegram.desktop/graphs/contributors) and Flathub is a third-party repository.

> install .rpm package from my official Fedora repositories ?

I suggest yo to update your Fedora installation to version 31. Telegram Desktop will be updated to latest version too.

**Comment by Nokia808** [comment]
@xvitaly 
Thank you for response, & for your correction & making things clear. 
However, for being a conservative use of Fedora: use each version of Fedora for 13 months then upgrade to after next version, i.e from Fedora 24 to 26 then to 28 then to 30 then to 32 ...... I will continue to use flatpak package, because from your replay it is clear that you do not maintain updating Telegram for each version of Fedora more than 6 months from it's release date ......

Upgrading OS every 6 months is horrible specially in country like Iraq where Internet & electricity services are both bad ........

**Comment by ilya-fedin** [comment]
> Flatpak is not official too. It maintained by [third-party people](https://github.com/flathub/org.telegram.desktop/graphs/contributors) and Flathub is a third-party repository.

AFAIK @grulja and @john-preston have an agreement that flatpak package is official too

**Comment by grulja** [comment]
I would consider it something like official. The telegram package in Flathub is co-maintained also by @john-preston, which gives it some creditability I would say.

**Comment by xvitaly** [comment]
> AFAIK @grulja and @john-preston have an agreement that flatpak package is official too

No. Official == built only by upstream developers (non-developers should have no access). All others builds are third-party.
