### ISSUE TITLE
workmode or alternative

### ISSUE THREAD

**Issue by danielalejandroamaro** [telegramdesktop/tdesktop#7515]
Could you please reactivate the workmode, or at least allow sorting by not muted first, I have a lot of groups and channels and it makes it very difficult for me to use telegram now, thanks in advance

**Comment by RememberTheAir** [comment]
See #7483

**Comment by danielalejandroamaro** [comment]
Now that I know how to do it, I propose one of the proposed folders as workmode, It will be helpful

**Comment by jlsjonas** [comment]
@RememberTheAir that's a workaround... but not a solution.
Workmode (should) apply to the eventual list, lack of a workmode toggle like we used to have just makes folders useless, as you can't have workmode enabled while... (you've guessed it) at work.
Especially since all the notification counts would still come through. 👎

**Comment by AlexByte** [comment]
@jlsjonas What is eventual list? Why you can't select workmode folder on work? Or you want to [hide ](https://github.com/telegramdesktop/tdesktop/issues/7534)folders list on work?
I personally ignore the notification count of all chats
![image](https://user-images.githubusercontent.com/25251772/78032088-235abc80-736d-11ea-88c1-cc615b382f75.png)

**Comment by jlsjonas** [comment]
>eventual list
the "actual" list, unrelated of what folder is selected

>Why you can't select workmode folder on work?
Because then I still have an unordered list of items. Workmode is a feature that's unrelated to folders.

Workmode => hide unmuted chats from the interface completely
folders => order chats based on logical groups, which might include a mix of muted & unmuted chats

**Comment by Nashev** [comment]
You can make a folder with unmuted chats, it will be similar to workmode

**Comment by jlsjonas** [comment]
@Nashev yes, I did that already, but that makes folders useless when in workmode, ALSO, as already mentioned... my unread counter is now just utter garbage

**Comment by jlsjonas** [comment]
As escaping goes into the all chat, I still believe this is relevant, perhaps an option to set which filter to escape to/set by default?
