### ISSUE TITLE
[Feature Request] Exclude folders in folder settings

### ISSUE THREAD

**Issue by yfdyh000** [telegramdesktop/tdesktop#7542]
### Is your feature request related to a problem?
One type of conversation wants separate unread counters and browsing, so add to a folder. However, the "Unread" folder and others still contains them.

### Describe the solution you'd like
Provide an existing Folders group in "Excluded Conversations" screen.

### Describe alternatives you've considered
A folder option to hide its conversations in other groups, or quickly add to exclusions (difficult to organize).

**Comment by reallyuniquename** [comment]
#7517?

**Comment by yfdyh000** [comment]
> #7517?

Nope, although it is also great.
I want to exclude some folders while the folder contains conversation types.

**Comment by damnfella** [comment]
I think what you're asking for is this?
#7875

**Comment by damnfella** [comment]
Btw, this is not necessarily an API issue.

**Comment by RememberTheAir** [comment]
@damnfella it is, since this kind of "all the chats that are already in another (specific?) folder" filter is supposed to work as the "read" filter, for example. The only thing a client would be able to do to provide this feature without any support by the API is to manually add all the chats in the selected "blacklisted" folder to the "excluded chats" list, which is not an ideal solution because this list needs to be updated manually - it won't be updated automatically when the content of the selected folder changes because the API doesn't support that

**Comment by reallyuniquename** [comment]
Valid.

**Comment by damnfella** [comment]
Much needed!

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/
