### ISSUE TITLE
[Question] Does telegram open attachment dialog and hides behind the parent window by default?

### ISSUE THREAD

**Issue by Keyikedalube** [telegramdesktop/tdesktop#7587]
On Debian sid (GNOME desktop) when I click the attachment button, the dialog window opens and hides behind the parent window
Is this intentional or a bug from Telegram or my Desktop Environment?

I filed a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916589) regarding this to Debian BTS two years ago
No update from the maintainer...

**Comment by ilya-fedin** [comment]
Check the issue on static binary.

I can say that debian maintainer (like all other debian maintainers) is crazy and uses [a very non-standard configuration](https://salsa.debian.org/debian/telegram-desktop/blob/mymedia/master/debian/rules#L8-9) (forces GTK dialog instead of give Qt a chance to handle it, replaces spellcheck library with the one that unstable and have no gui to manage dictionaries inside the app, uses rlottie from debian packages that disables coloring of big emojis), [heavy patches the app](https://salsa.debian.org/debian/telegram-desktop/-/tree/mymedia/master/debian%2Fpatches) and even [replaces a part of code](https://salsa.debian.org/debian/telegram-desktop/-/blob/mymedia/master/debian/rules#L36).

**Comment by Keyikedalube** [comment]
Thanks, @ilya-fedin for the insight :)

I'm not a Debian maintainer so I wouldn't understand why the upstream code was modified before packaging
However, I did read about Debian policy and learned one or two reasons (researching) why this distro patches heavily while distros like arch and fedora are upstream-friendly

**Comment by Keyikedalube** [comment]
Switched from GNOME to XFCE desktop environment today and noticed this issue isn't reproducible on the latter DE

Could be Debian GNOME specific issue or configuration mess up on my computer

Closing this issue
