### ISSUE TITLE
Doesn't reconnect!

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#765]
After disconnecting the Internet then reconnect it. Telegram unable to reconnect once again so I've to restart it to make it online!
- Linux Mint 17.1 xfce x64
- Telegram 0.8.17

PS. This issue doesn't occur under Windows.

**Comment by soren121** [comment]
As a workaround, you can go into the settings and briefly change the connection type, then change it back.

**Comment by mbnoimi** [comment]
@soren121 this suggestion doesn't fix anything! It's not a practical solution to change connection type whenever this issue occurred (which by the way it happens a lot)!

**Comment by soren121** [comment]
Yeah, it happens to me too...

And in case you didn't know, I'm not the developer. Just another Telegram user.

**Comment by cobalto** [comment]
"workaround"

**Comment by bil-elmoussaoui** [comment]
Just fix this please :+1:

**Comment by auchri** [comment]
#941

**Comment by julianxhokaxhiu** [comment]
I can confirm that this issue is still there. I'm periodically switching network on per-day basis, and since I'm using a Docking Station, everytime I unplug and replug the PC ( so Ethernet -> Wifi -> Ethernet ) Telegram is no more able to reconnect, until I restart the App.

Of course, no actions are taken and both devices are always up, enabled and connected.

This occours on Windows 10 x64 AU

**Comment by mbnoimi** [comment]
This issue no longer occurs
