### ISSUE TITLE
update unread message counter

### ISSUE THREAD

**Issue by Aokromes** [telegramdesktop/tdesktop#775]
i have some groups with 1000s of daily messages and sometimes i start to read the unread messages, but all the messages are marked as read i sugest to update the unread counter instead mark the whole group as read.

IE:
i have 1000 unread messages, i read 200, unread counter now shows 800 left.

edit for people unable to find this issue:

All messages in chat mark as read

Disable mark every message as read on open chat

displaying new-unread messages according to their viewing

Unread counter in windows desktop version

Unreaded posts in channels

Scrolling one unread message marks all as read

Opening chat group marks all messages as read, even unseen messages

Telegram mark all messages as read

All messages in chat mark as read

**Comment by enchained** [comment]
I think we're halfway there.
https://github.com/telegramdesktop/tdesktop/commit/71e0e6ac4db5e37c98bcc39e75d157ff0df087ea
In 1.3.7, I can confirm that, at least, the counter doesn't reset until I read to the very bottom.
Other things yet to confirm:

- While coming back to continue catching up with messages, do you still lose your old reading position when there are new messages since then? It jumped right to the new messages in the past, losing the reading position, but now, without immediate counter reset, it could possibly be not an issue anymore.
- Do you still lose your reading position on the app restart/crash? (too afraid to test).

I have a lot of messages in some channels and most of the time I was catching up with them in iOS Telegram X because it both updates the counter and remembers the position. but it would be much more comfortable to do so on the desktop, of course.

P.S. If your tdesktop version is less than 1.3.7 and it doesn't offer to update, simply download latest stable installer from here https://github.com/telegramdesktop/tdesktop/releases. I had that issue, possibly due to being in Russia. Didn't even knew about the update until I read it in the news and European friend said that her client just updated.

**Comment by john-preston** [comment]
@enchained I'm afraid currently this is a bug 😭

**Comment by nuclight** [comment]
Vote up this bug, very annoying to have to read some chats on mobile.

**Comment by nuclight** [comment]
@auchri this is wrong label "enhancement", this is definetely a bug as tdesktop behaviour here is differ from "upstream" mobile platform

**Comment by nuclight** [comment]
Vote up. This is especially needed soon as some platforms/versions support will be dropped in next months.

**Comment by nuclight** [comment]
Where could be priority of bugs / work plans on them could be seen?

**Comment by aNNiMON** [comment]
Please, rename this issue for better understanding and search purposes

**Comment by JSBmanD** [comment]
Why this issue is here from 2015? It's a bug that shouldn't be in a modern messenger app. In Telegram X on mobile everything is ok.

**Comment by Aokromes** [comment]
pull requests fixing this bug are welcomed.

**Comment by kirsan31** [comment]
I have looked into the code... And this is not a simple bug :( This is not implemented at all.
For entering a chat (for channels a bit differ) with a new messages current algorithm is: if we are reading server history (have loaded unread messages from server - have opened chat with unread messages) - tell server that we have read all downloaded messages regardless of current scroll position.
For new messages in current opened chat similar problem, but different code. And you need take this into account: 
<details><summary></summary>

![Snipaste_2019-10-18_17-12-13](https://user-images.githubusercontent.com/17767561/67105644-d07fb500-f1d1-11e9-9f97-0446fd11a9be.png)
</details>

So, for fixing this bug existing implementation must be seriously extended. And for doing this right, we need to understand current one. And I have no time for this :(

**Comment by Ali-Hamed** [comment]
this definitely a popular bug since Aokromes opened the issue on May 31, 2015 ,almost 5 years with no progress.
insane 😒😢

**Comment by aryanrawlani28** [comment]
My apologies. I tried searching but didn't think this issue went all the way back to 2015. Crazy!
Hope we can fix this somehow!

**Comment by kirsan31** [comment]
I can add to my [research](https://github.com/telegramdesktop/tdesktop/issues/775#issuecomment-543799317), that definitely this is not an `enhancement` this is 100% `bug`...

**Comment by Aokromes** [comment]
theoricaly fixed by future 1.9.15
