### ISSUE TITLE
[Question] Why you don't upload APPX package to releases page?

### ISSUE THREAD

**Issue by xmha97** [telegramdesktop/tdesktop#7792]
Hello,
Why you don't upload the APPX package to the [releases page](https://github.com/telegramdesktop/tdesktop/releases)?
Now I have to download APPX package using https://store.rg-adguard.net/
Currently, some open source applications in the Microsoft Store do this.
Like MusicBrainz Picard:
![image](https://user-images.githubusercontent.com/23485114/80914109-c59c0480-8d5e-11ea-8d2a-d843522e1c17.png)

**Comment by john-preston** [comment]
I don't build them for regular releases, only for the Microsoft Store. It usually happens later. Also I'm not sure that the same package that is built for the Store can be installed on the end-user system. I recall there was something tricky with the code signing, so that you build appx for the Store one way and for the direct installation the other way.

I see no reasons to use such version instead of the full-featured one from the current releases.
