### ISSUE TITLE
cannot attach files - telegram desktop linux 2.1.2

### ISSUE THREAD

**Issue by granger75** [telegramdesktop/tdesktop#7812]
### Steps to reproduce
1.  open telegram
2.  in chat, click on attach button
3. 

### Expected behaviour
A child window should open to pick files (it used to before 2.1.1 - regression?)

### Actual behaviour
nothing happens

### Configuration
Mageia linux 7
Kernel 5.6.8
Plasma 5.15.4
Qt5 5.12.6

**Version of Telegram Desktop:**
2.1.2

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: Official website

**Used theme**: Oxigen

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by ilya-fedin** [comment]
Can't reproduce with
```Operating System: KDE neon 5.18
KDE Plasma Version: 5.18.4
KDE Frameworks Version: 5.69.0
Qt Version: 5.14.2
Kernel Version: 5.3.0-51-generic
OS Type: 64-bit
Processors: 4 × Intel® Core™ i3-3217U CPU @ 1.80GHz
Memory: 1,9 ГиБ
```

**Comment by granger75** [comment]
Backwarding to version 2.1.0. It's working.
Maybe my Plasma and QT versions are not "cutting edge" ;-)
BTW: possible workaround: copy from Dolphin/paste to Tdesktop a file is still working in 2.1.2 .

**Comment by ilya-fedin** [comment]
I think your system for some reason has `xdg-desktop-portal` and doesn't have xdg-desktop-portal-kde.
xdg-desktop-portal doesn't have API to check if there are a t least one backend, if tdesktop detects xdg-desktop-portal - it uses it on KDE, even if there no backend installed.

But this should never happen, xdg-desktop-portal should require virtual package that provides backends, so that there are should always be at least one backend. Sounds like a bug for distro maintainers :thinking:

**Comment by granger75** [comment]
You're right!
I had xdg-desktop-portal installed, but no xdg-desktop-portal-kde.
I installed it, rebooted and it's working.
I think I'll drop a line to Mageia maintainers!
Thank you. Problem solved.
Should I close it or you?

**Comment by ilya-fedin** [comment]
> Should I close it or you?

I can't, you can or @Aokromes
