### ISSUE TITLE
[Ubuntu] [Bug] Telegram steals window focus on new message 2.1.5

### ISSUE THREAD

**Issue by TheTeaParty** [telegramdesktop/tdesktop#7887]
### Steps to reproduce
1. Use Ubuntu 20.04 with GNOME 3.36.2
2. Receive new message from unmuted chat

### Expected behaviour
Do not steal active window focus

### Actual behaviour
Telegram steals window focus on new notification from unmuted chat

### Configuration
**Operating system**: Ubuntu 20.04 with GNOME 3.36.2

**Version of Telegram Desktop**: 2.1.5

**Installation source (Linux Only)**: snap

**Used theme**: Night

Was ok on 2.1.4

**Comment by ilya-fedin** [comment]
Actually this is not a bug, but a feature: https://github.com/telegramdesktop/tdesktop/issues/223
You can disable it in notifications settings

**Comment by onesvat** [comment]
I think that it should not have come as selected. It is very annoying at the beginning.

**Comment by ilya-fedin** [comment]
> I think that it should not have come as selected. It is very annoying at the beginning.

Implementation is on window manager side. Some window managers just highlight the window as taskbar (as windows), others are focus the window.
It is unknown what actually will happen.

**Comment by TheTeaParty** [comment]
Ah yes ``Draw attention to the window`` was checked by default after update :/ It will be good if it will come unchecked by default.

**Comment by ralesk** [comment]
No window manager should steal focus on WM_HINTS.flags[UrgencyHint], so I feel the issue should be taken to Gnome devs if that's what actually happens (or to Ubuntu if they managed to mess up something when they patched Gnome).  Many applications use (or have used in the past) this feature and all it should ever do is highlight the taskbar/dock/whatever item — as it does outside of the Gnome world.  On Wayland, there's no protocol for this (according to a reddit post about swaywm), so maybe some weird and buggy implementation of the feature is the source of the problem if your system uses Wayland instead of X11.

**Comment by dgutov** [comment]
This is a problem on Ubuntu 19.10/GNOME/Xorg.

One might expect you'd test this on the #1 popular Linux desktop before changing the default.

> Many applications use (or have used in the past) this feature and all it should ever do is highlight the taskbar/dock/whatever item

Many applications indeed. But I have only seen this problematic behavior with Telegram, on recent versions.

**Comment by jbcebe-seekers** [comment]
This should be an opt-in feature. This behaviour easily captures passwords by accident
