### ISSUE TITLE
[Question] How to force sticker set update?

### ISSUE THREAD

**Issue by rkam88** [telegramdesktop/tdesktop#7904]
Hello!
I'm using a bot to create stickers but sometimes new stickers don't appear inmediately in the set.
It was mentioned in https://github.com/telegramdesktop/tdesktop/issues/1356 that stickers in the set update not more than once in an hour.
Is there any way to force-update the sticker set in a users collection with the bot's help or by the user directly in the desktop or Android client?

If not - is there any way to retrieve the status of the new sticker?
So far my tests have shown than after adding a new sticker to a set, the StickerSet object returned by https://core.telegram.org/bots/api#getstickerset always contains the new sticker: does this guarantee that a user adding the set will see the new sticker in it? If not - how can I find out when the added sticker becomes available/visible to users?

**Comment by Aokromes** [comment]
i vote this is server side.

**Comment by RememberTheAir** [comment]
@Aokromes uhmmm, why? There is an api to fetch the whole pack, the client would just have to figure out a way to cache the whole pack when it is requested by the user.

For example, I have noticed that when you click on a t.me/addsticker url, tdesktop will show you the full pack, included a sticker you have added one second before (I assume it requests the full pack to the API?) - but even after showing you the full pack, if you go to your stickers panel, you'll still have to wait some time before seeing the pack as you saw it after clicking on the t.me/addsticker url. I think that after showing you the full pack after clicking the link, tdesktop might also update its local cache (without further network requests, because I think it just have to use the data requested when you click on the url)

**Comment by damnfella** [comment]
To force update the sticker set in your stickers panel, you can try removing the sticker set first, and then adding it again. 

P.S. Don't forget to send a sticker the set somewhere before removing it, so that you can add the sticker set again. (or it will be kinda lost forever).

A shortcut to removing and adding quickly, is searching the sticker set, then removing it. The `ADD` button automatically appears (unless you close the search or make a new search)

**Comment by rkam88** [comment]
> [as a user] To force update the sticker set in your stickers panel, you can try removing the sticker set first, and then adding it again.
This indeed works, thank you! I'd still like to find a way to automate it with the bot, but at least it's something.
@damnfella regrading the shortcut, do you know if I can make a link to the search page with results (like the t.me/addstickers/... one)?

**Comment by Aokromes** [comment]
> @Aokromes uhmmm, why? There is an api to fetch the whole pack, the client would just have to figure out a way to cache the whole pack when it is requested by the user.

server side limitation of amount of updates  to avoid overload.

**Comment by rkam88** [comment]
> > @Aokromes uhmmm, why? There is an api to fetch the whole pack, the client would just have to figure out a way to cache the whole pack when it is requested by the user.
> 
> server side limitation of amount of updates to avoid overload.

@RememberTheAir seems to have a point though, when you click a t.me/addstickers url, it seems to fetch the pack anyway, why not use that info to update local cache?

**Comment by damnfella** [comment]
> @damnfella regrading the shortcut, do you know if I can make a link to the search page with results (like the t.me/addstickers/... one)?

Not sure I understand 🤔

**Comment by rkam88** [comment]
> > @damnfella regrading the shortcut, do you know if I can make a link to the search page with results (like the t.me/addstickers/... one)?
> 
> Not sure I understand 🤔

A link, that you can press, telegram opens, the stickers search screen is shown and the set I want is shown there. It could look, _for example_, like t.me/searchstickers?query=Animals

P.s. about t.me/addstickers - you can open individual sets by a link: see t.me/addstickers/Animals

**Comment by ilya-fedin** [comment]
> [as a user] To force update the sticker set in your stickers panel, you can try removing the sticker set first, and then adding it again.

For me just opening stickerpack in a popup works

**Comment by damnfella** [comment]
> For me just opening stickerpack in a popup works

 i was on windows 10, the last time I tried forcing sticker set update.

**Comment by RememberTheAir** [comment]
This issue still doesn't have a proper solution, so I would keep it open

**Comment by ilya-fedin** [comment]
@RememberTheAir the type of the issue is question and question was answered
