### ISSUE TITLE
[Feature Request] Please include build version to an application version

### ISSUE THREAD

**Issue by ezdev128** [telegramdesktop/tdesktop#791]
Please include build version to an application version.
If some bug occurs, it is impossible to refer to the version because it is the same (e.g., 0.8.17).
Also, please INCLUDE the message with all the changes (even if it was just typo correction) to each released version. It's no difficult, right? But for example, for me it is important to see what changes were made since the last update.

**Comment by joshery420** [comment]
I couldn't agree more. Version numbers are important since they help track down bugs, so please either ALWAYS update the version number or start including a build number too.

**Comment by Aokromes** [comment]
Well, git don't uses build versions, instead build hash. Maybe the same used on TrinityCore can be done:
```
TrinityCore rev. 2e457b3be418+    2016-11-05 01:52:38 -0300 (master branch) (Unix, None, Static)
                         ^^                    ^   ^^                                        ^^                      ^      ^         ^
                         git hash             |    git commit date                    git branch          |        |           Static/Dynamic libs
                                                  source is modified by compiler                            |        Compile mode (debug, release, releasewithdbg, custom (none)
                                                                                                                               Plataform

**Comment by john-preston** [comment]
@joshsleeper Every release the version is increased, so I don't understand what is the problem.

**Comment by joshsleeper** [comment]
@john-preston When I sent this message over a year ago that just wasn't the case, though.

We would often see multiple updates to the desktop app without any sort of version number bump (that I could see, at least) or patch notes, just like @ezdev128 said in the original issue report.

These days the situation is much better. It's been quite some time since I saw an update to the desktop app that didn't include a version bump.

**_That issue aside_** (since, from my standpoint, it's been fixed since the initial report), your release notes do still leave something to be desired, which was @ezdev128's other request
More often than not updates have no release notes at all, leaving us to browse the commit history of this repo to try and see what changed.
The only time we get real release notes are when new features are being added, but I feel like knowing which bugs have been fixed or what little tweaks have occurred is just as important to many of us.

Not the main topic, so feel free to divert the discussion elsewhere if you'd prefer that, but please do recognize that more consistent patch notes are something that has been asked for many times.

**Comment by john-preston** [comment]
@joshsleeper No official public version was ever released with the same version number, so that's strange. Perhaps you used some non-official builds that were followed up on GitHub not exactly together with the versions that were presented at https://desktop.telegram.org or through the auto update. But ok, I'm glad it's fine.
