### ISSUE TITLE
[Feature request ] Inline gif handling

### ISSUE THREAD

**Issue by sullivanmatt** [telegramdesktop/tdesktop#8]
Hello!  First, thank you for taking the time to create and maintain this client - I really enjoy using it.

One feature I would absolutely love to see is HipChat-style inline gif animation for attached photos.  Likewise, if a URL for an image is posted (so a URL ending in jpg, png, gif, etc), auto-display that image inline.  Perhaps the existing "Delete message" functionality could be employed to allow the user to hide/delete the image if they find it offensive.

I'd love to assist, but I'm a Python / C# guy and after tinkering for a while I couldn't make it happen.  Thanks!

**Comment by joshery420** [comment]
+1 for this.

**Comment by Surye** [comment]
:+1: For webm as well

**Comment by ianhyzy** [comment]
I'd also like to just be able to paste a url and have the gif/webm sent

**Comment by JochemKuijpers** [comment]
Response to what @ianhyzy said: I think there should be a distinction between sending an image and a link to an image. You can preview it, but you should not hide the link. In some cases you actually want to communicate a link instead of an image.

**Comment by ianhyzy** [comment]
@JochemKuijpers Maybe this could be done with a dialogue similar to the two buttons that appear when you drag an image to send it in the UI?

**Comment by Christilut** [comment]
+1 for webm support (starting to become the new GIF standard)

**Comment by elboletaire** [comment]
What about APNG? 

http://littlesvr.ca/apng/gif_apng_webp.html

**Comment by JochemKuijpers** [comment]
Telegram is not a media player, so I'd say we don't need support for exotic specifications like animated PNG. 

By the way, those comparisons aren't really fair, as GIF is limited to a 256-colour palette. I'd like to see the same test with 24-bit color animations. My guess is that APNG and WebP will be much closer in filesize and Lossy-WebP will probably be smaller than both.

**Comment by ianhyzy** [comment]
APNG really isn't used anywhere and doesn't have as much support as .webm

**Comment by zouden** [comment]
@elboletaire that page compares APNG to animated WebP, but neither are widely-used formats; Chrome doesn't support either of them. The future of GIF definitely appears to be WebM, the video codec.

**Comment by elboletaire** [comment]
> Telegram is not a media player, so I'd say we don't need support for exotic specifications like animated PNG. 

Then why use webm? Sorry but I can't get it. APNG is more closer to GIF than webm.

> By the way, those comparisons aren't really fair, as GIF is limited to a 256-colour palette. I'd like to see the same test with 24-bit color animations. My guess is that APNG and WebP will be much closer in filesize and Lossy-WebP will probably be smaller than both.

Yes, I would like to see it too.

Thanks everyone for your super-fast-clarifications.

**Comment by zouden** [comment]
I'd say the majority of GIFs being made and shared today are clips from a video, so that's why it makes sense to use a video codec like WebM instead of an image format like APNG. And with the big sites like Imgur getting behind WebM, that's the format that we should be focusing on, IMHO.

**Comment by JochemKuijpers** [comment]
> Then why use webm? Sorry but I can't get it. APNG is more closer to GIF than webm.

Because WebM is not an endangered species, as opposed to APNG and Animated WebP. 

GIF isn't about lossless animations, it's just one of the first formats to bring animations to the internet. GIF isn't lossless anyway, since you have to convert the animation to a (max.) 256-colour palette and you only have one bit for the alpha-channel.

I can see why you would want APNG, because it would be cool to support semi-transparent, high-quality animated pictures. I'd like that too. but these things take a lot of time. It's just not realistic to add support for these exotic formats :)

**Comment by elboletaire** [comment]
> Because WebM is not an endangered species, as opposed to APNG and Animated WebP. 

If they are in endangered is because nobody (like you guys) support them. Firefox has support for apng since my memory can remember.

> I can see why you would want APNG, because it would be cool to support semi-transparent, high-quality animated pictures. I'd like that too. but these things take a lot of time. It's just not realistic to add support for these exotic formats :)

Yes! And doing that we could have transparently-animated stickers too.

I thought that [someone started doing all the dirty job](https://github.com/apngasm/apngasm), but searching it now I can see it was just an apng assembler (I thought they also built some SDKs, but I was wrong..).

Anyway, I understand that the better is to use the most used format despite all my personal drawbacks :sweat_smile: .

Again, thanks for your responses :smile:

**Comment by Innomen** [comment]
I say tg should and could support any image or media format a browser does. It doesn't have to be a "media player." 

"but these things take a lot of time"

I very seriously doubt that. 99% of apps are developed based on other apps. We're all standing on the shoulders of giants here and tg isn't the first chat app. 

No one is writing in machine code from scratch. It can already parse X image formats. I see no compelling logical defense of it being exceptionally hard to expand the base of accepted/displayed images.

All the linux gallery/photo apps would seem to have code for displaying X formats. Recycling should be possible from somewhere. This isn't reinventing the wheel, this is basic drag drop media support which tg opened the door to. If a browser (among others) can do it then tg should be able to do it. All of which have open source examples.

FWIW webm is crazy popular on 4chan.  Which like it or not is a sizable and valid chunk of Internet usage and culture. Not to mention all the forums.

I would say the issue is simply one of priority. Gifs and webm definitely need to be next unless it would be easier to implement the adoption of other formats.

I wouldn't be surprised if at some point it'll be easier for them to drop in some code form some other project, use it as a generic image decoder and suddenly tg supports like, everything.

**Comment by JochemKuijpers** [comment]
@Innomen FYI, my point about Telegram not being a media player wasn't as much about WebM as it was about APNG and animated WebP. I've yet to see my first animated WebP or APNG out in the wild.

Of course you can add a ton of codecs and media libraries to Telegram. The point is, that takes time that could be spend on more important features. It would also make Telegram slower, bigger, more demanding, etc. If that's what you want, go ahead and create a pull-request.

I'd rather have a fast and light-weight chat client with as much functional features as possible. And if someone were to send me some weird media file, I'll just open it in another program.

**Comment by ianhyzy** [comment]
.webms aren't just on 4chan, imgur has their gifv format which is just a
webm (or h264). All gifs uploaded to imgur are auto converted to gifv now.

**Comment by Innomen** [comment]
_"I'd rather have a fast and light-weight chat client..."_ 

Yeah because stickers are mission critical. /smh

No one cares how big the app is. It's as meaningless as high score. Just ask steam and netflix and anything else that uses bandwidth constantly or downloads stuff or both. Apps are freaking tiny compared to the primary uses of pcs and smart phones these days.

What matters is utility. 

Also, I entirely doubt expanded image/media support will lead to a human detectable hit to speed unless the code is sabotaged to create said delay.

Stop scolding us.

**Comment by JochemKuijpers** [comment]
I'm just giving my opinion like everybody else here. All I'm saying is, we can't have *every* format, so someone has to draw a line. Imo, WebM is okay, animated PNG or WebP just aren't used as much.

What kind of feature request do you think developers would work on?
A: "Let's add inline GIF support because it's used quite frequently by these communities. Oh, and by the way, GIFs are being replaced by WebM so support for that would also be neat."
vs
B: "Let's add inline support for these hundred media formats. Here, I've seen them used in other media players too, they clearly exist!"

I'm guessing we all know the answer to that..

> Yeah because stickers are mission critical. /smh

It's a feature I thoroughly enjoy. Certainly more than obscure media format support.

Let's focus our conversation on this specific feature request. If you want other media formats supported, I'd suggest to create a new ticket. I hope I clarified my argument(s). You're free to respond but I'll leave it at this.

**Comment by Innomen** [comment]
_"I'm just giving my opinion like everybody else here. "_

You're trying to scold people who don't share that opinion into silence. That's not what others here are doing.

_"What kind of feature request do you think developers would work on?"_

I don't care. If people want it, they have a right to ask. Period. Stop scolding them for it.

**Comment by JoshStrobl** [comment]
Came here to also state I would appreciate gif support. I'm not even saying gif files from the Internet, but even gifs sent as photos or documents (TIL discovered lack of gif support after dragging a gif in from a folder into desktop client). To me gifs help express emotion and add another element (sometimes amusement) to a conversation.

**Comment by ianhyzy** [comment]
Joshua, you can send inline gifs on desktop, but you have to send them as a
file. This isn't clear, but it does work.

**Comment by JoshStrobl** [comment]
@ianhyzy Ah, wasn't aware. Well, nice to know :smiley:

**Comment by Innomen** [comment]
_"Joshua, you can send inline gifs on desktop"_

Not really. You can either send it as a file, in which case they have to open it with a second app to see it animate, or you can send it as an image (drag drop) in which case it is a static first frame.

So I'm curious, what you mean by "inline." Like as opposed to what?

**Comment by ianhyzy** [comment]
If you send a regular animated gif (not webm) it will let you view it in
telegram as an online gif.

**Comment by JoshStrobl** [comment]
> Not really. You can either send it as a file, in which case they have to open it with a second app to see it animate, or you can send it as an image (drag drop) in which case it is a static first frame.

Seems pretty convoluted in that case.

**Comment by ianhyzy** [comment]
Yes, yes it is. Hopefully it can be changed.

**Comment by zouden** [comment]
This isn't correct- clicking on the thumbnail will make it play inline.
It's not obvious though.

**Comment by Innomen** [comment]
_"This isn't correct- clicking on the thumbnail will make it play inline. It's not obvious though."_

All that happens for me when you click it is that it brings it forward and darkens the background (no animation) just like how it does with normal jpgs.

**Comment by JoshStrobl** [comment]
> All that happens for me when you click it is that it brings it forward and darkens the background (no animation) just like how it does with normal jpgs.

Same. *just tried it*

**Comment by zouden** [comment]
To clarify, I meant when it's sent as a document. I get a thumbnail and a
"open with" button. Clicking the  thumbnail makes it play inline.

**Comment by Innomen** [comment]
Ahhh, true. Ok. That's pretty close, but i still say it should just send them like jpgs, except that when clicked they animate. No sending like a document, no sending like a jpg.
