### ISSUE TITLE
mouse cursor 

### ISSUE THREAD

**Issue by scr2em** [telegramdesktop/tdesktop#8069]
Hello, 
I don't know if It's just me or not, but I find the mouse cursor while clicking on any section uncomfortable.
![image](https://user-images.githubusercontent.com/4671486/84579229-7f5daa80-adcc-11ea-8252-9675a091d1b2.png)
![image](https://user-images.githubusercontent.com/4671486/84579254-a61be100-adcc-11ea-8685-3394afc7fed4.png)

 It should be a "pointer" cursor instead of the normal cursor.
thanks

**Comment by ilya-fedin** [comment]
> It should be a "pointer" cursor instead of the normal cursor.

but pointer cursor is the normal cursor :thinking: 

I don't see cursor on the screenshots

**Comment by scr2em** [comment]
> but pointer cursor is the normal cursor 🤔
pointer cursor (hand) isn't the normal cursor (default)
> I don't see cursor on the screenshots
cursor doesn't appear in Print-Screen.

**Comment by ilya-fedin** [comment]
> cursor doesn't appear in Print-Screen.

what's wrong then?

**Comment by ronso0** [comment]
I'm having issues with the cursor, too.
(Posting here since i think it' related. If not let me know)

* On Ubuntu Studio (Ubuntu + xfce4), the cursor changes from the OS theme to some dark theme
This is gard to recognize in 'drk mode'
* when hovering a chat the cursor changes to a tiny left-handed pointer
![telemouse](https://user-images.githubusercontent.com/5934199/85203314-22527f00-b30d-11ea-9ac9-dffe46cb64e2.png)

I'd appreciate to have the cursors of the OS theme in the entire app.

**Comment by ilya-fedin** [comment]
> (Posting here since i think it' related. If not let me know)

no, probably you're using snap, snap doesn't have a good integration with system themes

> I'd appreciate to have the cursors of the OS theme in the entire app.

Sorry, but this impossible until snap developers make a way to use system themes

**Comment by ronso0** [comment]
oh, thanks for the hint, it's indeed a snap package.
Will check the deb from Ubuntu repos.

**Comment by ronso0** [comment]
Everything looks nice in the deb version!

**Comment by ilya-fedin** [comment]
> Everything looks nice in the deb version!

deb version is [a bad choice](https://github.com/telegramdesktop/tdesktop/issues/7587#issuecomment-610294095)
