### ISSUE TITLE
To be more open minded

### ISSUE THREAD

**Issue by mbnoimi** [telegramdesktop/tdesktop#807]
Many community contributers complain from your project administration because one AND only one person moderates the commits and ton of merge & feature requests ignored.

May you please be more open minded and change your current administration policy for this project?

Personally I'm very frustrated from the current policy and because of it I stopped my contributions cuz I believe you'll ignore them in same way you do to other merge requests.

Using the current policy means wasting community efforts because of forking to a new clients... [see this plz](https://github.com/Aseman-Land/Cutegram/issues/67#issuecomment-109983894)

I believe many community members agree with me that this project need another policy... Do you?

**Comment by ezdev128** [comment]
The same with translations. I'm working on Russian and Ukrainian languages on transifex any my PR (btw, any of) were even reviewed.

**Comment by mbnoimi** [comment]
@ezdev128 That's a full prove this project isn't community friendly.

**Comment by ezdev128** [comment]
@mbnoimi I agree with that... unfortunately.

**Comment by auchri** [comment]
I've suggested @telegramdesktop to help him to manage the issues (closing false of resolved ones) but he didn't respond.

**Comment by Foodfast** [comment]
Agree with OP

**Comment by joshery420** [comment]
Agreed. Bringing a few people on-board to help with pull requests and bug fixes is really becoming necessary. Don't get us wrong @telegramdesktop, you're still doing damn good work. We just all have high standards haha. Let some people help you!

**Comment by ezdev128** [comment]
I've looked to Cutegram and I see it more friendly. 
Comparing Cutegram to Telegram I see a quite different view.
```
+--------------------------------------------------+---------------+--------------+
| Feature                                          |   Telegram    |   Cutegram   |
+--------------------------------------------------+---------------+--------------+
| Open mind (listen to the views of members)       |     no        |      yes     |
| Complexity code compilation                      |     yes       |      no      |
| Used standard OS components (e.g., QT)           |     no        |      yes     |
| QML                                              |     no        |      yes     |
| Used original OS Look'n'Feel                     |     no        |      yes     |
| Look'n'Feel Customization                        |     no        |      yes     |
| Used OS notifications (e.g., libnotify)          |     no        |      yes     |
| Multi account login                              |     no        |      yes     | 
| Secret chats                                     |   OSX only    |      yes     |
| Work offline                                     |     no        |      yes     |
| PR review                                        |     no        |      yes     |
| Localization PR                                  |     no        |      yes     |
| Packed binary                                    |     yes       |      no      |
+--------------------------------------------------+---------------+--------------+
```

As long as @telegramdesktop team keeps their eyes closed, the Cutegram's team will do the game!

**Comment by mbnoimi** [comment]
@ezdev128 I totally I agree with you about Cutegram but there is a critical issue Cutegram misses it which is following the recent changes on Telegram API

Telegram isn't open source so the official client(s) always gets recent API changes because @telegramdesktop already knows them before public announcement of Telegram API which is completely disturbing.

**A SIDE NOTE**
Day after day I feel that Telegram fools us by claiming Telegram is open source!!! They are bunch data collectors just like Whatsapp guys and other alternatives because Telegram server is much important than any client(s) which is completely closed source and no one in the community knows what's going on there. So the openness of Telegram (server/client) is just a publicity for spreading Telegram and I wish I'm wrong because open source community really misses this kind of projects.
Personally I'm very frustrated from Telegram and I want to replace it but unfortunately I didn't find any respect open source alternative.

**Comment by ezdev128** [comment]
@mbnoimi I guess the server side has some information collection points (like messages/images/audio records spying/exporting) and this is why they can't release the server's code. I don't believe it has some unique algorithms of encryption and so on.
Also I guess they (tlgm team) afraid that community will use their server in some LAN's without official server (like IRC networking) and therefore no profit.
IMHO.

**Comment by mbnoimi** [comment]
While Whatsapp, Google apps, facebook.. etc share their users information with NSA and other U.S. agencies I believe Telegram does with some kind of Russian agencies.

Claiming open source is just a kind of deception (in addition to the publicity) because no matter they said our servers are safe and we don't share users info. with governments (while I'm sure they do) the the only prove is opening god damn source code of Telegram server.

I think the community must expose this kind of deception to warn the users that Telegram isn't open source,

**Comment by lbguilherme** [comment]
May I ask why was this closed?

**Comment by oktayaa** [comment]
@mbnoimi 

"While Whatsapp, Google apps, facebook.. etc share their users information with NSA and other U.S. agencies I believe Telegram does with some kind of Russian agencies."

Telegram's founders were basically kicked out of Russia for refusing to do business the way Putin wanted. They are based in Germany now and they are far more likely to share data with the western block (USA, UK, France, Germany etc) than with Russia.

I don't know what "deliverable" the originator of this request was expecting but it is still a bit weird to CLOSE the issue without so much as a comment.

**Comment by john-preston** [comment]
@oktayaa Well, it is what it is. Issues (at least open ones) here are used to report bugs (and sometimes ask for features, though it is not that interesting) and not for wide spread discussions about the human nature and all.

I (as the project author) try to implement it in the best way for the majority of Telegram users (as myself and other members of Telegram team understand it).

I don't work with the community much because it rarely brings some real value, but it has a great ability of consuming any amount of time, like attempts to start a discussion above about "closed server side source code means they share data with a government" (how this two are even related? how can opening the server side source code stop anyone from sharing data with any government?) and equally productive topics.

**Comment by oktayaa** [comment]
@john-preston People naturally have certain expectations from an open source project; more so than one that is hosted on a platform that is specifically designed for collaboration. 

I can imagine it being pretty time consuming to deal with the general public at large and appreciate that you or the rest of the team might not want to engage with people. However Telegram likes to advertise the fact that their protocol and clients are open source extensively. This increases the expectations of the people since there are a lot of projects where the project authors are actively seeking the users' participation. This is basically the way open source is done although different projects have different ways of going about it.

If telegram's position is to stay away from the "community" it should just make the code available and not be present on collaboration platforms. This is their right. And it is probably better than giving people the false belief that their contributions (such as they are) are desired. 

Regardless the Telegram _client_ issue tracker is not the place to discuss the politics of the closed source _server_ code. This is why I was trying to bring some perspective into it. I have no reason to think Telegram is sharing data with any government. Having said that if the source were to be open one could verify for themselves that nobody on the server side can read people's chats. This is how opening the server side code can stop anyone from sharing data (except meta data. and even for that there might be sufficient technology) with the government. Again. This discussion does not belong here so I will not continue further.

Best.
