### ISSUE TITLE
Unable to open channel links t.me/c/{id}/1

### ISSUE THREAD

**Issue by aNNiMON** [telegramdesktop/tdesktop#8108]
### Steps to reproduce
0. In examples below I use channels t.me/desktop and t.me/durov, you must not be a member of these channels before opening links
1. Send a public channel link in the format: t.me/c/{channel-id}/123. For example https://t.me/c/1001595379/64 or https://t.me/c/1006503122/116
2. Try to open a link

### Expected behaviour
The channel opens on the specified message id as it opens now in Android mobile clients.

### Actual behaviour
> Unfortunately, you can't access this message. You are not a member of the chat where it was posted.

----

### Further steps
3. Now let other user forward any message from these channels to your PM
4. Do not read this forwarded message, just click on https://t.me/c/1001595379/64 or https://t.me/c/1006503122/116 again

### Actual behaviour 
The channel normally opens on the specified message.

###  One small issue
If you try to open a link without message-id: https://t.me/c/1001595379 you will receive 
> Username @c not found

but in mobile clients the message is

> Chat info not found

----

### Configuration
**Operating system:** Windows 7, Arch Linux

**Version of Telegram Desktop:** 2.1.12

**Installation source (Linux Only)** - the official website

**Used theme**: Any

**Comment by aNNiMON** [comment]
Still an issue in 2.4.3

**Comment by Aokromes** [comment]
works for me on 2.4.8

**Comment by Aokromes** [comment]
https://t.me/tgbetachat/1

**Comment by Aokromes** [comment]
works for me on 2.4.8
https://t.me/durov/1

**Comment by aNNiMON** [comment]
Issue still exists in 2.7.5 beta
https://user-images.githubusercontent.com/1321838/117541541-03400700-b01d-11eb-96ea-506d743ef83f.mp4

**Comment by aNNiMON** [comment]
Still an issue

**Comment by lu4t** [comment]
still an issue

**Comment by aNNiMON** [comment]
still an issue

**Comment by aNNiMON** [comment]
4.4.1 still reproducible

**Comment by john-preston** [comment]
@aNNiMON It's strange, how did you decide those links should work? Apps don't provide them in such way and any link of t.me/c/{id} that an app provides is given with a warning "only members of this chat / channel will be able to use them".

The problem is, Telegram API doesn't allow to access a channel (even a "public" one, that has a username) only by it's ID. It requires a pair "(id, access_hash)". So if I'm not a member of a channel (even a channel with a username) and I get a link "t.me/c/{id}" I can't open this channel, because server won't give anything to me by ID only. When I search the public chats by a username ("durov", "desktop") the server returns channel information to me (including its ID and access_hash).

If I accessed the channel locally (for example, someone forwarded me a message from that channel), then I already have ID and access_hash and I can resolve the "t.me/c/{id}" link locally, without even accessing the server - I know the channel and I can open it.

But if I didn't access the channel locally I can't get it using ID alone.

I suppose it works in Android only because it has a local database of channels that holds the pairs ID / access_hash of all channels you accessed from the log in time. If somebody creates a new channel, adds a username to it, creates a link "t.me/c/{id}" and sends to you (and won't show this channel in any way to anybody else) I think the android app won't open this link too.

**Comment by john-preston** [comment]
![Screenshot_20230102_104208_Telegram Beta](https://user-images.githubusercontent.com/17900494/210201216-093c6973-8b18-4cc1-86a5-de1ed7fe7249.jpg)

This is how a tap on a private post link in a public channel that wasn't ever opened in this app looks on Android. The difference is the Android app holds much more pairs ID / access_hash, because it saves them in the local database between the app relaunches.
