### ISSUE TITLE
inline keyboard inside bot continuously sends answers. beta 2.1.15

### ISSUE THREAD

**Issue by vasyaivanovpv** [telegramdesktop/tdesktop#8187]
### Steps to reproduce
1. click on button on inline keyboard inside bot

### Expected behaviour
expect one anwser message

### Actual behaviour
answer comes endlessly about every 30 seconds

### Configuration
**Operating system:**
windows 10
**Version of Telegram Desktop:**
beta 2.1.15 and beta 2.1.16 (stable 2.1.13 not bag)

**Comment by john-preston** [comment]
@vasyaivanovpv I tried several bots, like bot father and quiz bot and didn't notice anything. Can you share what bot can I try to see the issue and what should I do exactly?

**Comment by vasyaivanovpv** [comment]
example @getmediabot

> @vasyaivanovpv I tried several bots, like bot father and quiz bot and didn't notice anything. Can you share what bot can I try to see the issue and what should I do exactly?

**Comment by podpolka** [comment]
I confirm that the error is present, and not only in the new beta. She is critical because bot scares subscribers. The first comments were seen from about 05/10/20 to 05/18/20. I reported this error on @BotSupport but I did not receive any answers or recommendations


What I just did not try - I can not solve this error.
The problem is not only in answerCallbackQuery but also in sendDocument


Example:
press the button kellback_test1
if (action.indexOf (kellback_test)! = -1)
{
    script response_to_action;
    return
}

And here the error is located on the server side of the telegram, or in the api library
I am using the node telegram bot api library

The problem is that even after stopping the bot, and even after turning off the server where the bot is located, telegram servers remembered clicks on kelbeks, a loop occurs, and on behalf of the client there are constant sends to clicks on the inline keyboard

Logs show the following: a person clicks on an inline keyboard, each click has its own kelbek_id, the id constantly changes with each new click
Only the person doesn’t press the keyboard, he isn’t in the telegram at all, he closed the client, and all the same click on kelbek_test1 arrives on his behalf and the new and new kelbek_id is assigned

**Comment by podpolka** [comment]
I will supplement the following information:

The user who complains - beta 2.1.14
His problem is this:
Presses the inline button - the Bot sends him what he pressed every 30 seconds. And the bot repeats this action endlessly.
The user exited the telegram and the bot continues to send him messages.
In the logs shows that the user constantly clicks on the same button

Prior to version 2.1.14, the problem was slightly different:
The user presses button1, button2, button3, button4, button5
The bot sends a response to pressing1, to pressing2, to pressing3, to pressing4, to pressing 5, to pressing2, to pressing3, to pressing4, on top of pressing5

**Comment by john-preston** [comment]
@vasyaivanovpv I was told that this may happen because answerCallbackQuery was not called.

**Comment by podpolka** [comment]
Once again, I will add:
At the expense of the fact that when the user is offline (the client is off) - I was wrong. If you re-enter then the problem goes away. If the bot writes something, the problem is not detected. If you simply click keaboard in the bot, the problem is not detected.
The problem is detected only by clicking on the inline keaboard.

If you reset updates via the link when it is running
https://api.telegram.org/bot{{token}}/getUpdates?offset=-1
I get here:
{"ok": true, "result": []}

But if you stop the bot, then the information in the browser is filled in by the link, and it is clearly visible there that the button comes from a user who does not click it

**Comment by vasyaivanovpv** [comment]
> @vasyaivanovpv I was told that this may happen because answerCallbackQuery was not called.

Thanks. that solved the problem!
