### ISSUE TITLE
[Important] Built in bot gallery for group administrators 

### ISSUE THREAD

**Issue by temporallyaccount** [telegramdesktop/tdesktop#8214]
There are huge amount of various community contributed bots available for telegram platform.

#### Feature Description
- Add most featured and simple bot gallery to telegram application with categories
- Display the gallery during new group creation wizard and suggest to add them.
(only display 4-5 perfect bots for each category and not so long bots list)

#### Bots categories
- Bots for security
  - Scan shared images, software and files for binded malware, spyware, exploits, unsafe sites.
(@DrWebBot @SafeDNSBot)
- Bots for detect adult content filtering
  - Detect posted adult images, videos and slang words
(@littleGuardianBot - require add to a group to make it work)
https://telegram-bot.in/#how-does-pornfilter-work - old site version
https://api.telegram-bot.app
- Bots for translation
  - Help translate posted messages on group in different languages
(@YTranslateBot @betterTranslateBot @BabelgramBot @voicybot)
- Bots for spam control and verifications
  - Detect spam messages, unwanted posts or adveritisings and display human verifications.
(@shieldy_bot @silentcbot @SpamKillerRobot)
- Bots for group manangement
  - Make group administrators work easy
(@RobomizBot  @RemoveURLsBot @snazzybot @topics_bot)
- Bots for greetings and welcome messages
  - Display welcome messages when user join to group and other greetings
(@RulesRulesBot @MissRose_bot)
- Bots for developers
  - Help developers for keep in touch with repositories and hunt bugs
(@GitHubBot @gitlab_bot)
- Bots for enjoyment
  - Enhance telegram groups experience
(@quickdeskbot @music @wiki)

Above only few bots that i searched for create this feature request

#### Additional details

If telegram consider to review and add existing bots then It's quite easy to implement that feature for telegram applications then we're happy to hear about ETA.

**Comment by valaria247** [comment]
**Why this feature request more important?**
We have noticed bad lucks in telegram groups since years; it doesn't seems reduce. I think every group administrators should aware about some powerful bots to manage their groups properly.

Below are several notable problems on telegram.
 - Post adult images, videos, slang and shocking contents (that's too disgusting thing ever on telegram)
 - Post binded spyware, exploits with applications in tech groups, with pdfs, docs in e-book sharing groups and other.
(personally, i have helped for 2000+ infected users in some groups. so far many people unware about that except malware, viruses, trojans and the word about 'hack')
 - Difficulties to manage groups due spams, unwanted topics and advertising contents
