### ISSUE TITLE
Playback device

### ISSUE THREAD

**Issue by cristianfraser** [telegramdesktop/tdesktop#828]
I have 2 audio ouputs connected to my PC, and when using telegram for desktop and changing the default audio playback device, Telegram keeps playing its audio through the former default output and not the selected one.

eg: The default audio devive are my speakers, I change it to my headphones and every audio output of my PC is through my headphones except for telegram, which keeps playing through my speakers.

**Comment by Katzen-Gott** [comment]
Isn't it same as #776 or #783 ?

**Comment by auchri** [comment]
It's the same as #776, but #783 is different

**Comment by woomiez** [comment]
There really needs to be an option to map audio devices to events in TDesktop...
I'm gaming or playing music through my onboard soundcard (which for this reason is set as default device), and I want the notification bleeps on that, but I want to conduct voice calls or record messages through my USB headset. There currently seemingly is no way to achieve this.
