### ISSUE TITLE
Building with non-wayland stack no longer possible with v2.1.20

### ISSUE THREAD

**Issue by rugubara** [telegramdesktop/tdesktop#8282]
### Steps to reproduce
1.  have a linux system where wayland is not configured for mesa, gtk+ and QT 
2. try to build telegram-desktop
3. 

### Expected behaviour
The build system should respect the system configured and build for X only and use X APIs

### Actual behaviour
Since I'm on the Gentoo, the build system forces me to rebuild my graphics stack for wayland - and I don't want it. 

### Configuration
**Operating system:**
Gentoo Linux

**Version of Telegram Desktop:**
2.1.20

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:
Distribution package

**Used theme**:

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
</details>

**Comment by rugubara** [comment]
https://github.com/telegramdesktop/tdesktop/commit/b587328fedaeea8fab34ce329ef8a687cb77238d This commit introduced an unconditional include of wayland headers. This should be configurable. Not everyone is jumping on wayland yet.

**Comment by ilya-fedin** [comment]
DESKTOP_APP_DISABLE_DBUS_INTEGRATION already added a lot of maintenance burden. I think minorities that using source-based distros can patch the code themselves to get rid of unneeded functionality and dependencies, while all other users getting prebuilt packages with all features activated in a binary form anyway. So that I assume that the issue should be closed as wontfix to prevent future maintenance burden, since wayland (and other packages that are not loved by minorities, like libdbus, libsystemd, libpulse) integration will be only further.

**Comment by magnus-gross** [comment]
I honestly couldn't care less if this was just a build dependency. But since this is a [runtime dependency](https://github.com/archlinux/svntogit-community/commit/1613397e6ddad585fb58e0abd01e4f1a2a168b92#diff-91e904bd64036c9c236ce84542f97781R11), this is not really that great especially for such a small feature.

Not everyone wants to jump to Wayland and honestly comparing it to any of dbus, systemd or Pulseaudio is ridiculous. Any of the last three are well-accepted standards in modern Linux distros, while Wayland certainly is not (even despite the efforts to push it for literally over 10 years).

This still isn't that much of a dealbreaker for me personally, just want to chime in my 2 cents, that it does make less sense to build workarounds for missing dbus, when you require some nonstandard stuff like Wayland.
There isn't even a single DE besides Gnome, that supports Wayland in an usable state.

**Comment by ilya-fedin** [comment]
>  But since this is a [runtime dependency](https://github.com/archlinux/svntogit-community/commit/1613397e6ddad585fb58e0abd01e4f1a2a168b92#diff-91e904bd64036c9c236ce84542f97781R11), this is not really that great especially for such a small feature.

tdesktop links to qtwayland just like it links to libxcb and libxcb-screensaver. It is impossible to provide some features on both display servers without linking to their libraries simultaneously.

**Comment by ilya-fedin** [comment]
btw, the linked PKGBUILD has a error: gtk3 is a runtime dependency too
