### ISSUE TITLE
error while loading shared libraries: libatomic.so

### ISSUE THREAD

**Issue by xhdix** [telegramdesktop/tdesktop#8299]
### Steps to reproduce
1. Open Telegram

### Actual behaviour
```
$ /home/username/.local/share/Telegram/Telegram -- %u
/home/username/.local/share/Telegram/Telegram: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

### Configuration
**Operating system:** Fedora 32

**Version of Telegram Desktop:** (IDK! Install beta is enabled) updated in: 2020/07/24

**Installation source (Linux Only)** the official website

**Used theme**: Default: Night mode

**Comment by xvitaly** [comment]
> Fedora 32

You can install packaged version from RPM Fusion repository or use Flatpak.

**Comment by andreyorst** [comment]
> > Fedora 32
> 
> You can install packaged version from RPM Fusion repository or use Flatpak.

not a solution for this particular problem. Perhaps static build missing this library?

@xhdix `dnf install libatomic` fixed the issue for me

**Comment by xhdix** [comment]
> You can install packaged version from RPM Fusion repository or use Flatpak.

I don't want to use them.

> Perhaps static build missing this library?

Definitely

> @xhdix dnf install libatomic fixed the issue for me

Yes,thanks! But it's a good opportunity to stop using Telegram for a few days. :P

**Comment by xvitaly** [comment]
> I don't want to use them.

Why? Packaged version built from official sources and linked against system-wide libraries.

Flatpak version built from the same sources too and is the semi-official.

**Comment by andreyorst** [comment]
> Flatpak version built from the same sources too and is the semi-official.

Telegram officially shipped as a binary, and this binary seem to miss a dependency it needs to work. On official site, there is no installation guide, that mentiones any additional dependencies needed to be installde, so this is clearly an error in binary build. If it was shipped as a package, it would be packaging issue, that would be addressed to package maintainers, but currently we have a problem of unsatisfied dependency, that breaks working application by update, which is a huge issue. Suggesting unofficial installation methods is not a solution, so please stop fooling around. If user does not want to use flatpak it is his business, and since there's no official flatpak build please do not suggest it in the official bug tracker. If you do not know how to deal with this issue, please ping someone who does, otherwise explicitly mark your suggestions as workaround, and not a problem solution to avoid confusion. Thanks.

**Comment by xvitaly** [comment]
> Telegram officially shipped as a binary, and this binary seem to miss a dependency it needs to work.

Yes, it built against bundled libraries from Ubuntu 14.04 LTS and there is no way to track dependencies for out-of-repositories static binaries.

Dnf will automatically resolve and install all the needed dependencies, but only for applications from repositories or well-packaged single RPMs.

> Suggesting unofficial installation methods is not a solution, so please stop fooling around.

For GNU/Linux users the official installation method for opensource applications is its repository.

I'm Fedora and RPM Fusion maintainer btw.

> since there's no official flatpak build

Flathub is the official installation source for Telegram Desktop.

**Comment by andreyorst** [comment]
> I'm Fedora and RPM Fusion maintainer btw.

Cool!

**Comment by john-preston** [comment]
@andreyorst This was a bug in configuration scripts, it will be fixed in the next version in couple of days. Thank you for your report!

**Comment by ilya-fedin** [comment]
> and since there's no official flatpak build please do not suggest it in the official bug tracker

![image](https://user-images.githubusercontent.com/17829319/88467702-49cad780-cec9-11ea-8373-911d5ae2d761.png)

**Comment by andreyorst** [comment]
> > and since there's no official flatpak build please do not suggest it in the official bug tracker
> 
> ![image](https://user-images.githubusercontent.com/17829319/88467702-49cad780-cec9-11ea-8373-911d5ae2d761.png)

Then this is a separate issue of an official webpage not providing all official ways to instal telegram, that perhaps as well should be addressed

**Comment by Aokromes** [comment]
try on 2.2.0

**Comment by xhdix** [comment]
@Aokromes , Thanks! It's fixed. But I had to log in again! However, there was no such problem for another account with a different `workdir`.
