### ISSUE TITLE
[Feature Request] Cannot disable animated sticker of 🎯

### ISSUE THREAD

**Issue by mumbleskates** [telegramdesktop/tdesktop#8303]
### Is your feature request related to a problem?
When a "🎯" emoji (target, bull's eye) is sent on its own an animated sticker / game is played instead, even if "Large emoji", "Replace emoji automatically", and every other emoji-related chat option is disabled.

### Describe the solution you'd like
Disabling "Large emoji" in chat settings, on both desktop and mobile (!), should disable the large animated presentation of the emoji and others with similar behaviors.

### Describe alternatives you've considered
A completely different option other than "Large emoji" that could also be unchecked to disable this would maybe be nice, but that seems superfluous.

### Additional context
These are surprising and disruptive. Many of us are here to communicate, not play minigames.

**Comment by yashpalgoyal1304** [comment]
Tangentially related: 
The emoji minigames' (🎲 :dart: :basketball: :soccer: <add others>) animation shall be included in the [animated emojies group](https://t.me/addstickers/AnimatedEmojies) to provide the alternate for using those. saying as i guess that that is an official sticker pack. Since only one animation can be picked, the winning case's animation seems a nice fit.

**Comment by yashpalgoyal1304** [comment]
stake bot go away.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/6203
