### ISSUE TITLE
Use system window decorations on XFCE

### ISSUE THREAD

**Issue by rossnomann** [telegramdesktop/tdesktop#8310]
### Expected behaviour

In previous versions of Telegram Desktop  (< 2.2) I had system window decorations.
Like in Firefox for example:
![image](https://user-images.githubusercontent.com/28867223/88491123-c933d600-cfb1-11ea-8463-d96b3a2a8aa3.png)

### Actual behaviour

Now I have something different:

![image](https://user-images.githubusercontent.com/28867223/88491177-347da800-cfb2-11ea-88cb-e7218e788c54.png)

Please return system decorations back

### Configuration
**Operating system:** Xubuntu 18.04.4 LTS

**Version of Telegram Desktop:** 2.2

**Installation source (Linux Only)** - the official website

**Used theme**: Night

**Comment by Aokromes** [comment]
go settings, advanced, change "use system windows frame"

**Comment by rossnomann** [comment]
Thanks

**Comment by septatrix** [comment]
@Aokromes The option does not seem to be available on Telegram v2.4.0 from snap

**Comment by WhyNotHugo** [comment]
> go settings, advanced, change "use system windows frame"

The name of this setting is very confusing:

- When unchecked, a Windows-like titlebar is used.
- When unchecked, no frame is added to the window.

**Comment by septatrix** [comment]
> The name of this setting is very confusing:
> 
> * When unchecked, a Windows-like titlebar is used.
> * When unchecked, no frame is added to the window.

You wrote unchecked twice. I  assume you are using Gnome under Wayland or a similar compositor setup which does not support server-side decorations. What this means is that (if enabled) Telegram asks the desktop environment to provide a titlebar and such. This is known as server-side decorations (as opposed to client-side decorations) and is not supported under wayland.

**Comment by WhyNotHugo** [comment]
Whoops. I meant:

- When unchecked, a Windows-like titlebar is used.
- When checked, no frame is added to the window.

I'm not using gnome though I'm clearly understanding that most users seem to be using this, since most software is starting to make the assumption that all users use gnome.

I'm using swaywm, which does support windows borders just fine. The borders are configured via sway, and are renders for Telegram regardless of this checkbox's value. This is expected; I've configured sway to add certain borders and it respect my settings.

> This is known as server-side decorations (as opposed to client-side decorations) and is not supported under wayland.

This is not correct. Both style of decorations are perfectly supported on wayland. Even Qt supports it, as described here: https://doc.qt.io/qt-5/qtwaylandcompositor-server-side-decoration-example.html
