### ISSUE TITLE
Support for Mac OS 10.11 and below ending September 2020

### ISSUE THREAD

**Issue by qgates** [telegramdesktop/tdesktop#8330]
Have had several notifications indicating tdesktop support for OSX versions below 10.12 is coming to an end, and that I should upgrade OSX. I'm asking kindly that you consider reversing or delaying this decision for a period because upgrading OSX is not possible on older Macs. In addition to owning and using newer Macs there are many users, colleges and charities using older machines, still in service and working perfectly for entertainment, internet browsing and other routine computing tasks.

Firefox has indicated support for 10.9-10.11 until at least mid 2021 and AFAIK Chrome hasn't indicated ending support, so it would be great if tdesktop could continue support for older OSX versions for a further period.

Thanks for considering.

**Comment by Aokromes** [comment]
the decision was taken months ago.

**Comment by john-preston** [comment]
@qgates The problem with them is that they are not supported by the modern Qt versions which are used for the app on all other platforms and system versions. Qt 5.12 is macOS 10.12 and above:

https://doc.qt.io/qt-5.12/supported-platforms.html

And the modern released version is Qt 5.15 with Qt 6 coming some time later this year.

Maintaining a version which builds against older version of Qt is painful because you need to check all the used APIs to see if they are too new for you. Also building this separate version is painful too, because it takes a lot of time.

And right now the percent of macOS/OSX users from all tdesktop users is less than 5% with percent from OSX users of macOS/OSX users is less than 0.2%, so it is a lot of effort and developer time for less than 0.01% of the user base.

I do understand your point, but right now this is really a problem for me.
