### ISSUE TITLE
Album preview overlapping

### ISSUE THREAD

**Issue by makisukurisu** [telegramdesktop/tdesktop#8392]
### Steps to reproduce
1. Send an album with last one tight photo and previous to it much wider photo (like №9 - 2000px wide, №10 - 500px wide)
2. Open album
3. While preview is visible - scroll from wide to tight photo

### Expected behaviour
No wide photo in preview

### Actual behaviour
Wide photo (if wide enough) appears in preview behind tight

*see pic for better understanding*

![image](https://user-images.githubusercontent.com/49622129/89622769-368e1380-d89c-11ea-9bd0-313c6bb533a7.png)

*Or video of how to reproduce and bug itself*

[link](https://youtu.be/QWht9xd2y1s)

### Configuration
**Operating system:** Windows 10

**Version of Telegram Desktop:** 2.2

**Used theme**: Night (but it does not matter)

**Comment by Remu-rin** [comment]
Also:

### Actual behaviour
1. Stepping animation is not smooth, or there is no animation
2. Thumbnails look weird. If current picture has horizontal orientation, it can overlap part of the next picture, or space before next picture is too small. For some images it makes it hard to see what thumbnails are showing. When current picture has vertical orientation it's the opposite, too much space before next picture.

### Expected behaviour
1. In old versions (i.e. 1.8.1, I don't know when exactly those things degraded, probably in a several last months) stepping animation is smooth.
2. In old versions current thumbnail were not overlapping part of the next picture, and space between current thumbnail and other (to left and to right) looked the same for pictures with different orientation.

**Comment by Remu-rin** [comment]
Not fixed in 2.4.3.
