### ISSUE TITLE
Telgram asking for phone number even on Desktop?

### ISSUE THREAD

**Issue by 0vermind** [telegramdesktop/tdesktop#841]
Hi, I would like to compliment for the great project.
Can I know the reason Telegram is asking for phone number even on desktop?
I see a lot of potential users in proposing Telegram for replacing old style irc channels for communities.
Is that possible?

**Comment by kenniki** [comment]
This is a design choice Telegram made, and asking this in this completely independent project is pointless. Also, the chances of this happening are pretty much nil.

**Comment by ezdev128** [comment]
@kenniki then why Telegram supports @username's? Why it's impossible to auth by username?
I think this feature is useless too

**Comment by sander85** [comment]
You can search contact by @username. Telegram has no passwords implemented. The whole logging in is built on phone availability. At least you must be a real person and have a number for your account. Some bots can't fill up the system with spam.

**Comment by kenniki** [comment]
The @username concept was implemented in order to allow people to communicate on Telegram without having to give up their phone number. You still need a phone number to authenticate, which is good, because otherwise you'd be having much more spam bots contact you. Telegram doesn't need to become another Skype.

**Comment by ezdev128** [comment]
@sander85 that's bad, because It's impossible to use TDesktop when no cellphone surface available. Just can't log in. I had 2 times when I was in underground (with internet but no cellphone connectivity) and was unable to log in.
That's frustrates...

@kenniki however, when person find me, I have no option to hide my cell phone and use only nickname. That's useless too.

**Comment by 0vermind** [comment]
@sander85 skype bots should be really scary to make design choice like this...

**Comment by Mindstormer619** [comment]
Yes, but you can really close the issue now. It has nothing to do with the code or Telegram Desktop in general. Telegram needs a phone number for your account, you'll have to deal with that.

**Comment by scottie** [comment]
This is such a shitty application, how can you have so many users??? it really is a blatant cia honeypot
