### ISSUE TITLE
[Feature Request] Add the ability to pin a message inside of a private chat

### ISSUE THREAD

**Issue by WaleedAlrashed** [telegramdesktop/tdesktop#8464]
**Context:** Pinning a message inside a group in **Telegram** is available, however, this feature is **not** available inside of personal (private) chats.

This feature is proven to be useful in many scenarios in group chats, and it certainly useful inside private chats as shown in this screenshot below: 
![request](https://user-images.githubusercontent.com/20885525/90744380-a3f86600-e2d8-11ea-8ca0-653bc0baad13.jpg)

Suggestions: 

- Add the ability to **pin** messages inside of personal chats.
- Add the ability to stare messages for each **separate** chat (unlike the Saved Messages chat ).

**Comment by RememberTheAir** [comment]
Pinning messages in private chats is not supported by the API

**Comment by ilya-fedin** [comment]
> Pinning messages in private chats is not supported by the API

I have an item for pinning message in the message context menu in my private chat. I guess that the group should be a supergroup.

**Comment by RememberTheAir** [comment]
As far as I know, the server will accept a message pinning request only in saved messages, normal groups, supergroups/channels

**Comment by ilya-fedin** [comment]
@RememberTheAir modern private chats are supergroups too.

**Comment by RememberTheAir** [comment]
Uhhh...? From when? This is new to me

**Comment by ilya-fedin** [comment]
I don't know, I just know that my private chat is a supergroup: it has recent actions, ability to pin messages, etc, etc.

iirc you can convert a private group to a private supergroup just by changing its type to public and back.

**Comment by RememberTheAir** [comment]
What with private chat you mean private _group_ chat?

**Comment by ilya-fedin** [comment]
> What with private chat you mean private _group_ chat?

Oops, yeah

**Comment by RememberTheAir** [comment]
Ah alright then. I got a bit confused. As far as I know, every group, when it is created from one of the official apps, is created as a normal group. That's probably because Telegram limits the number of supergroups/channels an account can join, so they want people to create normal groups first, and upgrade them to supergroups only when needed (as a side note, as far as I'm aware, the API allows to directly create supergroups - but the official apps don't have an option to do that. And also they could just remove the limit and finally phase out normal groups imo). If the admins perform some specific actions then the group gets upgraded to supergroup. That said - I think the API allows to pin messages in normal groups too. It hasn't always been possible, but they introduced it at some point, so you don't necessarily have to trigger the conversion to supergroup to pin messages in a group chat

Anyway the API will refuse any attempt to pin stuff in private chats (unless it's your saved messages). I think this request belongs to Twitter (or to the in-app support)

**Comment by RememberTheAir** [comment]
Still relevant

**Comment by WaleedAlrashed** [comment]
This feature is now available in Telegram Desktop 2.4.5 ✅
Full changelog can be found [here](https://telegram.org/blog/pinned-messages-locations-playlists)
