### ISSUE TITLE
Session Fixation Bug!

### ISSUE THREAD

**Issue by krugdenis** [telegramdesktop/tdesktop#8496]
### Steps to reproduce
1. Login to Telegram Desktop on Windows PC
2. Copy "AppData\Roaming\Telegram Desktop" folder to another PC to any place
3. Run copied Telegram.exe 

### Expected behaviour
**It MUST ask for authorization on another PC!**

### Actual behaviour
It open saved session, you can run multiple instances on separate PCs and it acts like the same session, even with different IPs

### Configuration
**Operating system:** 
Windows 10
**Version of Telegram Desktop:**
Latest (2.3.1)
**Instalation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**It's been already reported before, more serious bug (you can logout session and use saved tokens again), 5 (!) years ago:**
https://github.com/Rootkitsmm/TelegramSessionFixation-
https://github.com/sinabakh/tgBug

**Comment by Aokromes** [comment]
afaik, not a bug.

**Comment by krugdenis** [comment]
It's a bug. Telegram Desktop for Windows, when installed, must not act like it's a portable version. It should generate something, like HWID, to check where it's installed.
Look at the FreeFileSync program, you can't just copy it to another PC and use it there.
If someone gained access to your PC, he can copy tdata folder and use it everywhere, but you'll never notice that!
Because in Active Sessions you can see only one session.

**Comment by john-preston** [comment]
@krugdenis If someone has access to your computer there is only one way you can prevent them from using your Telegram Desktop session — use a local passcode. That way the auth data will be encrypted with that passcode.

All other approaches essentially give you nothing, because if you have access to the PC, you can launch Telegram Desktop and while it loads the chats you can:

- dump the memory of the process and find the authorization key there, or

- launch a self-built copy of Telegram Desktop that will just save the authorization key to a text file, or

- copy all data together with all the information that was used to bind the auth to the specific machine, like HWID or anything, and then extract the key at your place the same way Telegram Desktop does it (the app is opensource).

So it will give a big headache to the developers and to users who want to move their authorization to another PC, but it won't stop any bad guys from getting your authorization. You can either (a) not let bad guys have access to your PC, or (b) set a strong local passcode.

**Comment by krugdenis** [comment]
@john-preston thanks, local passcode can be solution. But maybe there is a way to prevent multiple instances of Telegram Desktop in the same session? If client is duplicated, then it should show another session in active sessions window. 
For now, you are blind if someone else somewhere is using your Telegram, if you are not using local passcode.

**Comment by john-preston** [comment]
@krugdenis If they use it in the same time that you use it the server should just logout you both, at least in some cases, there is some sort of checks for that, I don’t know the details.

If you use them in turns, not at the same time, there is no way to differentiate this case from a case where you just turned on a vpn and suddenly moved to another country from servers point of view.

**Comment by krugdenis** [comment]
@john-preston 

> If they use it in the same time that you use it the server should just logout you both, at least in some cases, there is some sort of checks for that, I don’t know the details.

Nope, I've just checked it. One instance behind VPN and second without VPN on another PC. I've sent messagess to multiple chats from both at the same time. 
One thing that is sending notification - is when I've tried to export chat from new instance. It warned about 24 hrs timeout. 
And there is still one session opened for both when I check from mobile.

**Comment by krugdenis** [comment]
You don't need to be a hacker to get Telegram Desktop folder from a victim's PC. It's very simple. And the victim will never know that someone got access to their private life. For now, I've got it running almost 3 hours, running two clients on different PCs at the same time, sending messages in different chats from the first instance and the second. One active session for both clients.
Even if it's a portable version, separate sessions must be generated on different machines.
It's a serious privacy threat!

**Comment by john-preston** [comment]
@krugdenis Yes, this is not ideal, but giving access to your computer to someone you don't trust is a serious privacy threat anyway. They can copy your authorization key (anyway). They can launch the app and read your messages, export chats from Settings. They can copy your auth data and install a keylogger on your computer, that way even a local passcode won't help you.
