### ISSUE TITLE
[Question] Switch Camera in Video Call

### ISSUE THREAD

**Issue by Nabav** [telegramdesktop/tdesktop#8534]
I have just tested the video call on my Surface and could not switch to the selfie camera.
Is it possible? How?

**Comment by Aokromes** [comment]
> I have just tested the video call on my Surface and could not switch to the selfie camera.
> Is it possible? How?

you need 2.3.1 and change camera on calls settings.

**Comment by Moldoteck** [comment]
@Nabav 
![image](https://user-images.githubusercontent.com/9899064/92334074-3c416980-f093-11ea-9ba9-c7745a74abb8.png)
![image](https://user-images.githubusercontent.com/9899064/92334077-50856680-f093-11ea-91d8-abf934632233.png)
![image](https://user-images.githubusercontent.com/9899064/92334092-73177f80-f093-11ea-9334-cb61198e409c.png)
@Aokromes call settings should be in general settings so that it will be more intuitive to change them
