### ISSUE TITLE
[Feature Request] Send webm as video

### ISSUE THREAD

**Issue by DarkArc** [telegramdesktop/tdesktop#8591]
### Is your feature request related to a problem?
I have various video files in the webm format, this is also what google's Stadia service saves clips as, so when sharing webm videos with friends on telegram, they have to download the video as a file and then play it, rather than the more pleasant mp4 support where you can send it as a video instead of a file.

### Describe the solution you'd like
Allow webm to be used in addition to mp4 for video sending.

### Alternative solution
Have telegram reencode webm as mp4. (This seems less than ideal for a number of reasons)

**Comment by sebleblanc** [comment]
The alternative solution is what you are describing as a solution. Telegram should convert a video from a format that it can "understand", to a format that is implemented on architectures that Telegram cares about.
Currently Telegram is mostly an application that runs on mobile, with a desktop application as second-class. This means that the video format the most supported across platforms is MPEG4, with H.264 video encoding and AAC audio encoding.

The main issue with supporting transcoding is that you might end up with "supported" platforms that struggle to keep up. An Android device that encodes natively to WEBM and has to transcode to H.264 using only the CPU will not be able to compete with a device (maybe the same device) that can encode directly to H.264. It will be hard to maintain a list of systems with proper support for this workflow, and adding a bunch more options in the client seems like something that goes against the objectives of the project to provide a powerful, yet simple client.

Telegram could extend the protocol by e.g. informing the other party of what formats it supports playing back, that way some agreement can be reached and a sender can pick a format that it can encode to efficiently, if needed, or disallow it for unsupported platforms. An option could be added to allow transcoding inefficiently (battery draining) but this would imply that Telegram provide a general video decoder and encoder library (e.g. ffmpeg) as a dependency, instead of using the system's builtin services.

**Comment by DarkArc** [comment]
@sebleblanc "The alternative solution is what you are describing as a solution" this strikes me as a particularly frustrating comment; why wouldn't you just say something akin to "I think your alternative solution would actually be the better choice?"

Anyways, yes, there's merit to transcoding everything for device support, but there's also merit to allowing devices that support webm and its contained video format to just send and just play said format. Video transcoding especially on a mobile device is going to be potentially quite intense, and perhaps even impossible within a reasonable time frame, not to mention the battery life concerns -- it can take significant resources even for high powered servers to do transcoding depending on the length and quality of the video. Additionally webm especially with VP9 or AV1 can have significant bandwidth advantages over MP4, advantages that benefit both telegram's datacenters, and consumer's data plans. 

I mean the most sane thing to do IMO, is to just add protocol support for webm type videos, and use software playback if no hardware playback is supported; then only the people that lack hardware support pay a cost. This should become less and less significant as more and more phones and GPUs ship hardware decoding support for the various webm formats.

**Comment by sebleblanc** [comment]
Why do you claim that your solution is the sanest approach? Have you demonstrated that other solutions aren't as sane?
—
Your solution will split Telegram users in separate camps and overall be detrimental to the overall experience. People will complain that they can't view attachments that were sent to them from some users, while the other users will keep complaining that they have to convert the files for these users. No gain for them. I believe this includes the whole iPhone platform as it does not have native support for WEBM.
If you make the conversion system transparent, some of these users will then complain that the battery life is horrible when they use Telegram. Plus there's the need to include a general use transcoding library, a huge legal point due to software licenses and patents involved.

I think this is a mess.

Can we get insight from a developer, who can tell us how readily can the Telegram protocol support formats other than what I assume is video/mp4 ?

**Comment by DarkArc** [comment]
> People will complain that they can't view attachments that were sent to them from some users

Not necessarily. Software playback should allow anyone to view the webm video, where as currently that isn't possible without a third party app.

> while the other users will keep complaining that they have to convert the files for these users

Who's complaining about that even _now_? This point seems totally speculative. Most services don't spit out webm video, and as the number of services doing so climbs, I'm sure device support and pressure will follow. 

I'll add that while VP8/9 aren't supported on Apple platforms, without a doubt AV1 will be supported in the future, as Apple is part of the group behind AV1.

> If you make the conversion system transparent, some of these users will then complain that the battery life is horrible when they use Telegram.

Yes, that's an issue especially in the case of transcoding (unless, the transcoding occurs server side, in which case it's a potentially significant expense).

There's a middle ground where you transcode server side, upon request. In other words, if user A sends webm, and user B's device reports it doesn't support webm, the app can then request the server create a mp4 version if one doesn't already exists. This in turn would result in a "lazy" system that only does transcoding when required, and otherwise benefits from the webm video formats.

> Plus there's the need to include a general use transcoding library, a huge legal point due to software licenses and patents involved.

This isn't a huge legal point, all telegram apps are using GPL licenses and are welcome to use FFMPEG as a result.

----

In any case I'd be surprised if any of this discussion is helpful to the devs. I trust them to make the right decision here WRT transcoding, or supporting the format. The more important point is treating webm videos, as videos, conceptually within the app.

**Comment by marcoValkyriweb** [comment]
> With iOS 14 and macOS Big Sur, Safari can also play HDR videos for the first time. The company has enabled the VP9 codec for apps on iOS 14 and tvOS 14, which allows users to watch 4K HDR videos on YouTube for the first time, but Safari 14 is yet to get this codec.
https://9to5mac.com/2020/06/24/apple-adds-webp-hdr-support-and-more-to-safari-with-ios-14-and-macos-big-sur/

So VP9 support might have arrived, Android already supports and desktop battery life it's not really that much of an issue.
![image](https://user-images.githubusercontent.com/34270069/94912619-311e0580-04a8-11eb-951a-6364f8128571.png)
https://developer.android.com/guide/topics/media/media-formats

**Comment by Aokromes** [comment]
such feature belongs to https://bugs.telegram.org/

**Comment by DarkArc** [comment]
Moved to https://bugs.telegram.org/c/2364
