### ISSUE TITLE
Telegram Showing Online and Last seen Even if the Privacy setting are Set to "Nobody"

### ISSUE THREAD

**Issue by soni05** [telegramdesktop/tdesktop#8647]
Telegram Status is showing online and last seen to other users even when the privacy settings are set to "Nobody". How this works?

**Comment by DeltaTimo** [comment]
Please tell us in more detail, what you are expecting to happen and what happens instead as well as how to reproduce your issue (if you know how).

When speaking of "last seen" are you referring to the "last seen recently" mode or actual dates and times?
If you are set to hide your online status and last seen, you will still be appearing as online to the groups and people you are writing to (or for a matter of fact, any action such as uploading an image, etc) and your last seen status will still appear to others although in a very imprecise form such as "recently" or "last week."
This is as far as I know intended behaviour. 

I'm not from this repository, but generally, issues should somewhat be of the form:

### Expected behaviour
text

### Actual behaviour
text

### Steps to reproduce
1. Steps
2. More steps

### Detailed description
text

**Comment by Aokromes** [comment]
not a bug.
