### ISSUE TITLE
Can't leave a comment if writing messages isn't allowed in connected group

### ISSUE THREAD

**Issue by Neurotoxin001** [telegramdesktop/tdesktop#8680]
### Steps to reproduce
1. Go to https://t.me/topor and click "Leave a comment"
2. You will see "No comments here yet" and text field for write the new comment
![image](https://user-images.githubusercontent.com/39812401/94807765-c5309400-03f8-11eb-8aac-d4d06f8e90dd.png)
3. But when you write anything in here and press send – nothing happens, because writing messages isn't allowed in connected chat – https://t.me/topor18
![image](https://user-images.githubusercontent.com/39812401/94808023-222c4a00-03f9-11eb-9fd7-32c85bac3860.png)

### Expected behaviour
Telegram must check if messages in connected chat disabled and don't add "Leave a comment" under posts

### Configuration
**Operating system:** win 10 ltsc 1809

**Version of Telegram Desktop:** 2.4

**Used theme**: Dark default

**Comment by frisbeegrammer** [comment]
+1
I think we should be able to write comment without depending on discussion permissions.
because writing a comment does not require being in a group or joining a channel.
for example, I want to have comment on my channel, but no one in the discussion group can post. but for now this not possible because they have an ugly coupling.

**Comment by Neurotoxin001** [comment]
> we should be able to write comment without depending on discussion permissions. 

I think this is impossible due to api restrictions
