### ISSUE TITLE
Up/down arrows

### ISSUE THREAD

**Issue by Christilut** [telegramdesktop/tdesktop#873]
Like in a terminal, it would be nice to be able to press up and down to get previous sent messages. Especially as a bot developer this would be really great to have...

**Comment by DarkAbsolutE** [comment]
But, this would be a problem, because if navigate in the text, for example 3 lines, this would be limited to the used of the mouse or moved with arrow left. This would be problematic and uncomfortable

**Comment by Christilut** [comment]
Yes that's true. But maybe with a modifier like shift or ctrl? I'm not sure what's in use currently.

**Comment by DarkAbsolutE** [comment]
This would be interesting, with shift would not be bad, I like the idea. "shift + arrow up"

**Comment by hobarrera** [comment]
@Christilut: <kbd>ctrl</kbd>+<kbd>up</kbd> is usually the default for these sort of thing on IM clients.

@DarkAbsolutE: No, <kbd>shift</kbd>+<kbd>up</kbd> is an awful idea, since that's used to select several lines of text on any IM client, or any multiline-textfield in most applications.

**Comment by Mindstormer619** [comment]
Or something like Alt+P and Alt+N as used on the python interpreter. 

+1

**Comment by Walkman100** [comment]
:+1: to <kbd>ctrl</kbd>+<kbd>up</kbd>

**Comment by DarkAbsolutE** [comment]
@hobarrera is true, I had forgotten.
Ctrl + up using it is a bad idea, for example in my mac, this is the default command to display all open applications. But, the idea it's god, you just have to give an easy to use command without making many movements.
For example the terminal used shit + ctrl + c for copy instead of ctrl + c, because that is already booked.

They could use shift + ctrl + up.

**Comment by hobarrera** [comment]
> Ctrl + up using it is a bad idea, for example in my mac, this is the default command to [...]

I assume you mean that this is the default on OS X. Indeed, if OS X normally uses <kbd>ctrl</kbd>+<kbd>up</kbd> for something else, we should use whatever other OS X IM clients use for this. But I'd use <kbd>ctrl</kbd>+<kbd>up</kbd> on other platforms because it's what other IM clients use, and what every user out there would expect.  

Picking a unique keybiding *different* to other clients would only hurt adoption and confuse users (with no upside to it).

We really **should not** discuss what key binding to use, and just do what every other client does on each platform (we wouldn't discuss what to use for copy-paste, would we?).

**Comment by Walkman100** [comment]
<kbd>ctrl</kbd>+<kbd>up</kbd> should be used on every platform except Mac, on a mac the <kbd>Command</kbd> key is used instead of <kbd>Ctrl</kbd>

**Comment by agung-wete** [comment]
:+1:

**Comment by auchri** [comment]
Added to #1060 :)
