### ISSUE TITLE
Buttons from bots in channel messages not work

### ISSUE THREAD

**Issue by On1x** [telegramdesktop/tdesktop#8748]
### Steps to reproduce
1. Join any channel with bot which attach buttons with callback.
2. Wait till admin post any message and see attached buttons and new tg addon for message comment.
3. See that buttons can't be pressed! Only 1 pixel in message shadow work for buttons.

### Expected behaviour
Buttons must be available for clicks!

### Actual behaviour
Buttons not working. Only 1 pixel in shadow works: https://on1x.com/screen/10-2020/7137-386a.gif

### Configuration
**Operating system:**
PC WIN10

**Version of Telegram Desktop:**
LATEST

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package:

**Used theme**:
DEFAULT

**Comment by ilya-fedin** [comment]
#8730

**Comment by On1x** [comment]
There is new problem. Buttons show and clicks well, but now discussion button hidden. And links like https://t.me/VIZ_Ecosystem/141?comment=119062 works ONLY if there is NO inline keyboard. Can we have working discussion link with internal keyboard from bot?

**Comment by john-preston** [comment]
@On1x No :( server doesn’t generate a discussion post for channel posts with inline keyboard.

**Comment by On1x** [comment]
@john-preston why? O_O it's most requested feature from my bot users. They want bot buttons + discussion button. What a reason make awards/dislike buttons and cut off nice discuss feature. Please, fix it or give me a tip, where i need create a new issue.

**Comment by On1x** [comment]
Find some interesting! @john-preston it's not server!
Example: https://t.me/viz_world/119074
Message from channel. Link to discussion didn't work BUT — when right click on message and select "View 2 replies" it's show discussion page! Please, can you make it accessable by public link? Like https://t.me/viz_world/119074?show_replies=true

**Comment by On1x** [comment]
Any comments?

**Comment by RememberTheAir** [comment]
This issue should be brought to https://bugs.telegram.org because as long as the server behaves like that, tdesktop can't do anything about it

**Comment by On1x** [comment]
@RememberTheAir @Aokromes it's not SERVER based. I show you example, when client can open page with replies. Need to internal link for that action (not from popup menu).

Again, example: https://t.me/viz_world/119074
Message from channel. Link to discussion didn't work BUT — when right click on message and select "View 2 replies" it's show discussion page! Please, can you make it accessable by public link? Like https://t.me/viz_world/119074?show_replies=true

**Comment by RememberTheAir** [comment]
> Again, example: https://t.me/viz_world/119074
> Message from channel

No, `@viz_world` is a group. If you are suggesting that tdesktop should offer an option in the right-click context menu to jump to the discussion thread generated in the linked group - that would be inconsistent with what the other apps do. That's why you should suggest that in the platform I linked, tdesktop's not going to behave differently as long as it's consistent with the current mobile apps behavior

**Comment by On1x** [comment]
@RememberTheAir but that menu item didn't show in simple GROUP messages. Only in channel forwarded messages.

Video proof of example:
https://user-images.githubusercontent.com/1928273/116517781-77bdcc00-a8e0-11eb-8fd9-852c09a6f60a.mp4

**Comment by On1x** [comment]
@RememberTheAir Video proof from android app: 
https://viz.world/video_2021-04-29_12-02-58.mp4

**Comment by On1x** [comment]
It's working feature, but hided from developers. Please, add internal link for open message replies.

**Comment by RememberTheAir** [comment]
> Video proof of example: https://user-images.githubusercontent.com/1928273/116517781-77bdcc00-a8e0-11eb-8fd9-852c09a6f60a.mp4

Again that is a group chat, not a channel. This issue is about channels

**Comment by On1x** [comment]
@RememberTheAir ok, created suggestion: https://bugs.telegram.org/c/4681

**Comment by On1x** [comment]
@RememberTheAir i'm not think, that «issue about channels». It's merged issue. Channel posts translated to group. Discussions work in group, but group up by channel message. Why is this issue about channel? It's about BOTH — Channels and Groups.

**Comment by RememberTheAir** [comment]
Comments work by merging together in a thread view all the replies sent to the forwarded channel message in the group. Thread view is available in the group but not in the channel if that post has inline buttons. Everyone here is aware that the post in the group has a thread view available _if you access it from inside the group_.

The issue here is that, as far as I can imagine from @preston's words, the API doesn't let you request the linked replies to a channel post if that channel post has inline buttons. The app would have to load the linked group's chat history until it finds the forwarded channel message, and request the replies chain of that message. Which is a gimmick, you're not supposed to use the API like that - this is why that I initially suggested to bring this to the bugs & suggestions platform.

But **even if that wasn't the case** and the API offered a way to get the thread view for a channel post with inline buttons, tdesktop behavior would be inconsistent with the mobile apps. This is why this issue belongs to the platform I previously linked, as long as the mobile apps don't show the comment button, I doubt tdesktop will

**Comment by On1x** [comment]
@RememberTheAir Thanks for respond. I see the problem now. How we can change behaviour? Many bots use inline buttons but lost discussion feature required by users? Maybe not remove discussion thread while enable inline keyboard?

**Comment by RememberTheAir** [comment]
The only way to change this behavior is to bring this issue on the bugs & suggestion platform. I saw the card you published, but i believe the nature of the request should have a wider scope: [this card](https://bugs.telegram.org/c/1798) requests to add comments to posts with inline keyboards. I think this is the proper solution to the issue. I believe Telegram decided not to show the comments bar when a post shows inline buttons because they haven't figured out a good UI for it
