### ISSUE TITLE
openSUSE telegram-desktop package recommends-related question

### ISSUE THREAD

**Issue by mira-ta** [telegramdesktop/tdesktop#8769]
I am sorry and apologize if that kind of report should have been sent to some openSUSE's bug tracker, but whatever.

### Steps to reproduce
1. Install the latest (at the moment of issue) `telegram-desktop` build using `zypper` without recommends.

```sh
zypper install --no-recommends telegram-desktop # this is how it's been installed
```

2. Try running the `telegram-desktop` executable.

### Expected behaviour
The desktop application shall run.

### Actual behaviour
Assertion error occurres (referring to `strace` output, SIGABRT is raised), and the program fails with:

```
Aborted (core dumped)
```

### Configuration
**Operating system:**
openSUSE Tumbleweed 2020104 (id: 20201004).

**Version of Telegram Desktop:**
`2.3.2-2.1` according to `zypper info telegram-desktop`'s output.

**Installation source (Linux Only)** - the official website / GitHub releases / flatpak / snap / distribution package: ***openSUSE repository***

**Used theme**: none. Well, it did not run, did it?

<details><summary><b>Logs</b>:</summary>
<pre>
[2020.10.07 03:15:11] Launched version: 2003002, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
# much non-related log messages (related to display environment)
[2020.10.07 03:15:11] Assertion Failed! "index < _sprites.size()" emoji_config.cpp:445
</pre>
</details>

**Comment by mira-ta** [comment]
### Note

Installing it using

```sh
zypper install telegram-desktop
# i.e. with installing one more dependency called
# xdg-desktop-portal
# so must it be really a *recommends* package?
```

ends up fine and everything runs.

**Comment by ilya-fedin** [comment]
No one here can help you with your distro package, ask distro maintainer.

**Comment by mira-ta** [comment]
> No one here can help you with your distro package, ask distro maintainer.

Thanks for the reply!

**Comment by ilya-fedin** [comment]
Just looked at [what opensuse maintainers are doing](https://build.opensuse.org/package/view_file/openSUSE:Factory/telegram-desktop/telegram-desktop.spec?expand=1) and I can say that their tdesktop packaging has really low quality.

1. There are a lot of BuildRequires what aren't needed
2. [An useless patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/telegram-desktop/0000-gtk2-default.patch?expand=1) to load gtk2 that won't work with latest versions.
3. [A weird patch](https://build.opensuse.org/package/view_file/openSUSE:Factory/telegram-desktop/0001-use-bundled-ranged-exptected-gsl.patch?expand=1) that doesn't have any sense, since there are automatic fallback to bundled libraries.
4. package should explicitly require libqt5-qtimageformats in runtime, while I see only `BuildRequires:  libqt5-qtimageformats-devel`. This is most likely the cause of your error.
