### ISSUE TITLE
Telegram Signs Out Automatically

### ISSUE THREAD

**Issue by thevalo** [telegramdesktop/tdesktop#8790]
### Steps to reproduce
1. Restart machine
2. Open Telegram

### Expected behaviour
Telegram opens automatically and is signed in.

### Actual behaviour
It displays the "Welcome to Telegram" message thing, asking to sign up or log in, after manually opening Telegram.

### Configuration
**Operating system:** Windows 10 x64

**Version of Telegram Desktop:** 2.4.3

**Used theme**: Default/Night Mode

These are the lines that attracted my attention:
<details><summary><b>Logs</b>:</summary>
[2020.10.09 11:04:08] App Info: reading accounts info...
[2020.10.09 11:04:08] App Info: reading encrypted info...
[2020.10.09 11:04:17] Storage Error: Could not open 'C:/Windows.old/Users/X/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/configs' for writing.
[2020.10.09 11:04:17] Storage Error: Could not open 'C:/Windows.old/Users/X/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/config0' for writing.
[2020.10.09 11:04:20] Storage Error: Could not open 'C:/Windows.old/Users/X/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/configs' for writing.
[2020.10.09 11:04:20] Storage Error: Could not open 'C:/Windows.old/Users/X/AppData/Roaming/Telegram Desktop/tdata/D877F783D5D3EF8C/config0' for writing.
</details>

I thought maybe it's a permission error (?) (highly unlikely) and tried to run as administrator, but it's the same. With signing in again, all custom modifications to the theme I made are lost, however, the session is still active, seeing it from my phone.
It happened yesterday, and now today again, usually after restarting the machine.

**Comment by Mohammed-Laith** [comment]
I had this issue before, but it was due to having too many bad sectors in the disk, I simply moved the folder to another location. 
It can be reproduced by any other method, not just by having bad sectors; by preventing TD from accessing /Telegram Desktop/tdata/. I'm not expert, but I think that the most important files/folders are "working" (a file), and "seesion" (a file), and the folder "userdata/0/".
As I said, try copying the folder that exists in %APPDATA%/Telegram Desktop/ (this one "Telegram Desktop") to another location. And as i see from your log that you have "Windows.old" folder, i assume you recently installed a new version of Windows? Maybe it can be caused by that. Idk.
And the permission thing, i guess it's impossible, not just "highly unlikely".
That what i have here.

**Comment by Mohammed-Laith** [comment]
Another thing, the seesion is active, but I can't access it is something normal.
It also can be reproduced by having two seesions on two phones, cut the Internet connection, end the seesion (by logging out), then remove the battery, and reboot, after that reconnect. The seesion will be there in the seesions list. It's the exact same qs your case. If you didn't do anything, the servers will terminate it after 48h. (This is something by experience, no official things from Telegram. )

**Comment by thevalo** [comment]
Great addition, Mohammed-Laith.
Everything else works fine there. It's just the TD.
However, yes, I have performed a reinstall of Windows a couple of months ago, and presumably, the Windows.old folder is the leftover from the last installation, though, it is now empty, and I don't know why the TD is using this directory and not the current one, Windows.
That folder may be deleted or cleared on the machine being restarted, so that's why perhaps TD "could not open .. for writing" because it doesn't exist?!

**Comment by Aokromes** [comment]
it looks permissions issue, i suggest you to install telegram desktop again renaming old directory.

**Comment by thevalo** [comment]
It has been fixed by itself. If something similar arises again, I'll open up a new issue and try to dig further into that. Thank you.
