### ISSUE TITLE
[Feature Request] Scale Telegram Desktop in Smaller Screens

### ISSUE THREAD

**Issue by antony-jr** [telegramdesktop/tdesktop#8810]
### Is your feature request related to a problem?

In Phosh + Postmarket OS telegram scales well but some content is capped, need to scale smaller to about at least 700 px width.

### Describe the solution you'd like

Scale Telegram Desktop properly as per the screen size. i.e Scale Telegram application to at least a minimum of 700 px width and respective height. 

### Describe alternatives you've considered

None.

### Additional context

The right side of Telegram seems to be cut off only by a bit.

![photo_2020-10-13_02-46-06](https://user-images.githubusercontent.com/33930174/95791131-527bbe80-0cfe-11eb-9d7b-24953d5701ea.jpg)

**Comment by ilya-fedin** [comment]
As already been discussed in #8058, tdesktop is not designed to be used on phones nor on any other touch devices and this is intended.

**Comment by antony-jr** [comment]
Seems like I have to fork or patch this on my own and release it in a different channel for phosh users. Okay Thank you for your time.

**Comment by Aokromes** [comment]
you may want to use kotatogram with sub 100% scaling and larger fonts.

**Comment by allnamesaretakeningithub** [comment]
> As already been discussed in #8058, tdesktop is not designed to be used on phones nor on any other touch devices and this is intended.

@ilya-fedin may I ask:

- Why is this intended?
- Should that information not be in a FAQ?

Also, with the Librem 5 phones and pinephones, we are taking about having the telegram desktop application on a GNU/Linux machine that happens to have a 5 inch touchscreen as main interface.

What both closed requests ask in short is to allow a slightly smaller window so that telegram-desktop for linux fits better on a linux device that has network connection (and that "accidentally" also makes phone calls).

One last question is: 

If you do not intend to provide support for touch devices, will you provide any type of support for example for tdesktop on GNU/Linux tablets? Like the pinetablet?

**Comment by antony-jr** [comment]
@allnamesaretakeningithub 6 and 6.5 inch screen fits Telegram desktop nicely.

**Comment by allnamesaretakeningithub** [comment]
>  6 and 6.5 inch screen fits Telegram desktop nicely.

@antony-jr that does not reply do some of my questions. As the statement made was about no support for: touch devices. 

Nor does it answer to the question of what is the reasoning behind it, nor if it sohuld not be in a FAQ that info
