### ISSUE TITLE
[Feature request] Avoid .desktop file creation

### ISSUE THREAD

**Issue by ItachiSan** [telegramdesktop/tdesktop#933]
I'm actually the [packager of Telegram Desktop for ArchLinux](https://aur4.archlinux.org/packages/telegram-desktop-bin) and I've edited a bit the desktop file generated from the app in order to work the packaging done.
So, I would ask you to prevent the .desktop file creation when */usr/share/applications/telegramdesktop.desktop* is present.

The method that issues that is here: https://github.com/telegramdesktop/tdesktop/blob/master/Telegram/SourceFiles/pspecific_linux.cpp#L1125

I can make a patch, if you wish.

**Comment by Musikolo** [comment]
+1

**Comment by ManuelSchneid3r** [comment]
Same as #680

**Comment by auchri** [comment]
Duplicate #306

**Comment by ManuelSchneid3r** [comment]
The placement of a desktop file is part of the deployment and should never (ever!) be done by the executable. What user experience would this be if a user had to start a the binary form terminal first to see an destop entry...
Actually the (systemwide) placement of a desktop file should be handled by the install skript. If building from source, make install should do this. This will influence all the package based approaches, since most of them use some chrooted buildsystems to build packages with realtive paths. 
The package manager will place and track those files for you.
