### ISSUE TITLE
Searching for specific chat in a folder, searchs from "All chats"

### ISSUE THREAD

**Issue by amir1376irani** [telegramdesktop/tdesktop#9853]
### Steps to reproduce
1. First assume you have some chats with these persons: "A1", "A2" and "A3"
2. Make a folder with name "F1" and include chats of "A1" and "A2"
3. Click on folder "F1" in left panel
4. Click on the search box in top of chats (or simply press Ctrl+f)
5. Type "A"

### Expected behaviour
We must just see chats with "A1" and "A2"

### Actual behaviour
But we will see chats with "A1", "A2" and "A3" !

### Configuration
**Operating system:** Ubuntu 18.04.5

**Version of Telegram Desktop:** 2.4.7

**Installation source (Linux Only)** - the official website

**Used theme**: Night

<details><summary><b>Logs</b>:</summary>
Insert log.txt here (if necessary)
I don't think it's necessary but can provide if you ask for it.
</details>

**Comment by ilya-fedin** [comment]
This is intended behavior AFAIK

**Comment by amir1376irani** [comment]
Any official reaction to this issue?

**Comment by ilya-fedin** [comment]
Search is global AFAIK, so it's intended behavior

**Comment by RememberTheAir** [comment]
Yes, folders-based search is not supported and when you use the search bar it is intended that the search is performed globally. I believe this would be a cool feature, but as long as the mobile apps don't behave like that I doubt tdesktop will add such a thing because the behavior would be too different across clients.

There's already a card on the official suggestions platform: https://bugs.telegram.org/c/889

I also believe that search results should be filtered by the server in first place instead of having the client hiding the irrelevant results from the global search
